### ISSUE TITLE
Tensorflow error during medaka_variant run

### ISSUE THREAD

**Issue by cwbcm** [nanoporetech/medaka#101]
Hi, 
I could not run medaka becasue of a tensorflow error. 
I did the conda installation. And also conda updated tensorflow but still no luck.
Could you help me figure out the problem? Thanks!
Please see the command and the logs below.
$ medaka_variant -f ~/Chen/ref_genome/U00096.3.fasta -i barcode06.merge.sorted.bam -o medaka

Checking program versions
Program    Version    Required   Pass     
bgzip      1.9        1.9        True     
minimap2   2.17       2.11       True     
samtools   1.9        1.9        True     
tabix      1.9        1.9        True     

+ Running initial pass to haplotag reads.

- Running medaka consensus with /home/labuser/Chen/Nanopore/20191029_crispr/debarcodes/barcode06/barcode06.merge.sorted.bam --model r941_min_diploid_snp 
[W::hts_idx_load2] The index file is older than the data file: /home/labuser/Chen/Nanopore/20191029_crispr/debarcodes/barcode06/barcode06.merge.sorted.bam.bai
[W::hts_idx_load2] The index file is older than the data file: /home/labuser/Chen/Nanopore/20191029_crispr/debarcodes/barcode06/barcode06.merge.sorted.bam.bai
[12:44:31 - Predict] Processing region(s): U00096.3:0-4641652
[12:44:31 - Predict] Setting tensorflow threads to 1.
Traceback (most recent call last):
  File "/home/labuser/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/labuser/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 434, in main
    args.func(args)
  File "/home/labuser/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/prediction.py", line 107, in predict
    K.set_session(tf.Session(
AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'
Failed to run medaka consensus.

**Comment by cjw85** [comment]
This looks like the same as #100, if you create a conda environment with the new conda package the issue should be resolved.

**Comment by cwbcm** [comment]
Thanks for the follow up!
I deleted the previous medaka environment and reinstalled it using the command line 
conda create -n medaka -c conda-forge -c bioconda medaka
But the old version was reinstalled.
medaka             bioconda/linux-64::medaka-0.10.0-py36hda2845c_0
How can I install the newer version that you mentioned in #100 ?

**Comment by cjw85** [comment]
I'm afraid I'm not a conda expert and don't know why your environment wasn't created with the `_1` build of medaka. Similarly I've built two environments this afternoon on two different computers, one was built with the older package and one with the newer package.

**Comment by cjw85** [comment]
@druvus Do you know why the package with the highest build number is not consistently pulled by `conda create...`?

**Comment by cjw85** [comment]
@cwbcm This is not something I think we know how to fix. I will leave this issue open in case anyone passing by with more insider knowledge of conda knows how to ensure the correct package build is fetched.

When we create a new medaka version, the issue will be resolved (since conda does at least reliably pull specified versions correctly). In the meantime you might want to raise an issue on bioconda.

**Comment by cwbcm** [comment]
Thanks for the help. I will try to install an older version to bypass this issue for now.

**Comment by cjw85** [comment]
We have just release `v0.10.1` which will appear on bioconda shortly, after which running asking conda to install/update medaka should result in this version being pulled sidestepping the issue of different builds of `v0.10.0`.
