### ISSUE TITLE
Question about variant calling prokaryotic genomes

### ISSUE THREAD

**Issue by nick297** [nanoporetech/medaka#102]
Hello,
Do you have any tips or advice for attempting to variant call SNPs from bacterial genomes? The medaka_variant documentation looks geared towards diploid genomes, do I need to changed anything or should it work OK?
Many thanks,
Nick

**Comment by cjw85** [comment]
You are correct `medaka_variant` is geared toward diploid calling. We do not have models that are specialised toward calling variants for a prokaryotic genome.

I would suggest as a simple alternative running `medaka_consensus` with your reference genome as the "draft assembly". You could then use samtools/bcftools to create a `.vcf` from comparison of the reference to medaka's output. However, this isn't going to tell you much about possible variation within your sample, if that is the question you are trying to asnwer.

**Comment by nick297** [comment]
OK thank you, I will give that a try as well. I am not looking for heterozygous sites or sites with minor variants. 
Do you have any plans for gearing medaka_variant towards non-diplod organisms as well? I have "truth" genomes, both assembled and illumina sequenced for these samples which may useful.

**Comment by cjw85** [comment]
This is something we've had in the back of our minds for a while (we would like to have `medaka_consensus` output an annotated vcf), but not something we are actively working toward. Your setup seems sufficiently similar to what `medaka_consensus` is attempting to achieve that it may give you what you need. If not the next step would be to dig into some of the analysis's intermediate files.

**Comment by cjw85** [comment]
Hi @nick297,

Given that I think I saw you had a paper/preprint out can I close this issue? It seems you found the `medaka snp` command to on the outputs of `medaka consensus`.

**Comment by nick297** [comment]
Yes, thanks for your help
