### ISSUE TITLE
Installation from source fails because `scripts/mini_align` is missing

### ISSUE THREAD

**Issue by caspargross** [nanoporetech/medaka#104]
**Describe the bug**
Installation with both `pip install /medaka/path` and `python setup.py install` fails with error: 
`error: file medaka/scripts/mini_align' does not exist`

This file is not present in the `scripts` folder but referenced in the `setup.py` file: https://github.com/nanoporetech/medaka/blob/295b3278b195df9b8d6372bc7b0ac1c78063f461/setup.py#L154

**Comment by cjw85** [comment]
Hi @caspargross 

Running the `setup.py` file directly (or via pip) is not supported without first running some of the make targets. Please see the README for how to install from source.

**Comment by caspargross** [comment]
thank you,  sorry for not reading correctly ;)
