### ISSUE TITLE
Installation issues with conda and centos7

### ISSUE THREAD

**Issue by ilyavs** [nanoporetech/medaka#109]
**Describe the bug**
I installed medaka using conda and wanted to use it with the model: r941_min_hac_g324. However, the medaka data path only contains hp_compress_model, medaka_model and r941_flip_model.
According to the documentation, the model names should follow the convention {pore}_{device}_{caller variant}_{caller version}. 

**Environment (if you do not have a GPU, write No GPU):**
No GPU

Can someone please give me a detailed guide on how to get the relevant model file? In addition, could you include additional model files in the conda installation or have a process that downloads them when requested by the user?

Thanks,
Ilya.

**Comment by cjw85** [comment]
Hi @ilyavs 

Could you give details of how you have attempted to install medaka? By your final comment it sounds like you are using conda?

I can confirm that all necessary model files to run medaka are included in the [pypi package](https://pypi.org/project/medaka/#files) (and therefore the conda package since this is built via the pacakge on pypi).

**Comment by ilyavs** [comment]
Apparently I had a very old version of medaka installed by a previous user. I now updated to 0.11.
I see many more models in the data folder but neither has the {caller version} in its name, so the model name I use, r941_min_hac_g324, results in an error. The closest I can find in the data path is r941_min_high.
However, I now encounter a different error:
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_assembly/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
How can I fix this?
Thank you,
Ilya.

**Comment by cjw85** [comment]
@ilyavs I would recommend building a conda environment from scratch with:

    conda create -n medaka -c conda-forge -c bioconda medaka

and then using this fresh environment to run medaka:

    conda activate medaka
    medaka tools list_models

and check the models are present with:

    medaka tools resolve_model --model r10_min_high_g303 | xargs ls -lh

**Comment by ilyavs** [comment]
I built a conda environment from scratch as you suggested. I now ran:
medaka tools list_models
And got the following errors:
Traceback (most recent call last):
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 450, in main
    import tensorflow as tf
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/__init__.py", line 34, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /net/mraid08/export/genie/long_read_assembly/miniconda3/envs/medaka/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ilyavs** [comment]
According to our system admin, installing a newer version of glib is not possible for our CentOS 7 system. Is there any way to get medaka to work anyway?
Thanks,
Ilya.

**Comment by cjw85** [comment]
miniconda should come with its own `libstdc++.so.6` (under `miniconda3/lib/libstdc++.so.6`). Are you using a particularly old version of miniconda? Here I have:

    $ conda --version
    conda 4.7.12

As an alternative to conda you can use the precompiled binaries on pypi. These are build on CentOS 6 so will also work on CentOS 7. If you use the pypi package you will have to install things like `samtools` separately. See the README for more information.

**Comment by ilyavs** [comment]
I am also using conda 4.7.12.
I will try the pypi installation. It should still include the models, right?
Thanks,
Ilya.

**Comment by cjw85** [comment]
That is correct, the packages on pypi contain the model files.

**Comment by ilyavs** [comment]
Hi,
I installed medaka 0.11 with pip and the situation is even worse. It now expects an even newer version of gcc. Here is the error I get when I try to run medaka consensus
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_assembly/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so)

Please advise on how to get medaka working with older gcc versions.

Thanks,
Ilya.

**Comment by cjw85** [comment]
The above error looks like you are still running within a conda environment. My guess is that something is awry with your conda setup, or that there is some other peculiarity on your system stopping things from working.

I have confirmed that the the conda package works under centos7 by using the base centos7 docker container.

    ### from the host: `docker run -it centos:centos7 bash`
    curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > Miniconda3-latest-Linux-x86_64.sh
    chmod +x Miniconda3-latest-Linux-x86_64.sh
    ./Miniconda3-latest-Linux-x86_64.sh

    ### in a new shell from the host: `docker exec -it d22552a0701f bash`
    conda create -n medaka -c conda-forge -c bioconda medaka
    conda activate medaka
    medaka tools resolve_model --model r10_min_high_g303 | xargs ls -lh

The output of the final command here is:

    -rw-rw-r-- 2 root root 4.8M Nov 22 20:36 /root/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/data/r10_min_high_g303_model.hdf5

Further, starting python within this conda environment I am able to import both tensorflow and protobuf without error.

**Comment by ilyavs** [comment]
In my previous attempt, I did install medaka using pip but in an existing conda environment. I will try again in a dedicated conda environment.
Thank you for testing this. Could you please tell me the gcc version in the docker environment you used?

**Comment by cjw85** [comment]
Within the centos container running 

    strings /usr/lib64/libc.so.6 | grep ^GLIBC

shows versions up to `GLIBC_2.17`, while running

    strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX

shows versions up to `GLIBCXX_3.4.19`. **_However, note that when using conda we should be using a libstdc++ from the conda installation._** For example taking one of the libraries above for which you are having issues:

    # ldd /root/miniconda3/envs/medaka/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc974da000)
	libprotobuf.so.22 => /root/miniconda3/envs/medaka/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.22 (0x00007f1dec4cf000)
	libstdc++.so.6 => /root/miniconda3/envs/medaka/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libstdc++.so.6 (0x00007f1dec7c6000)
	libgcc_s.so.1 => /root/miniconda3/envs/medaka/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libgcc_s.so.1 (0x00007f1dec7b2000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1dec2b3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1debee5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1dec768000)
	libz.so.1 => /root/miniconda3/envs/medaka/lib/python3.6/site-packages/google/protobuf/pyext/../../../../.././libz.so.1 (0x00007f1dec794000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f1debbe3000)

and inspecting the libstc++ listed here shows versions up to GLIBCXX_3.4.27.

My suggestion would be to create a new conda installation and a medaka environment from that new conda installation.

**Comment by ilyavs** [comment]
For some reason, even though I install in a new conda environment, it still uses the libstdc++ from the system and not from the conda environment.
Any ideas why?
Thanks,
Ilya.

**Comment by cjw85** [comment]
Have you tried reinstalling conda as suggested above (not just creating a new conda environment but completely reinstalling conda).

The following issue details somewhat similar symptoms to what you are seeing: https://github.com/conda/conda-build/issues/3385

**Comment by ilyavs** [comment]
Just tried with a fresh install of conda, same issues.

**Comment by lucyintheskyzzz** [comment]
Hi @cjw85 
I am having trouble downloading the new version of Medaka and my download stalls on centos7 here:

(/lustre/project/taw/share/conda-envs/ONRviral) [kvigil@cypress01-119 conda-envs]$ conda create -n medaka -c conda-forge -c bioconda medaka
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
