### ISSUE TITLE
medaka_consensus: line 16: 31399 Illegal instruction     medaka tools list_models

### ISSUE THREAD

**Issue by damientully** [nanoporetech/medaka#119]
Hi,

I seem to have the following problem when upgrading to the newest version of medaka using pip. Everything seems to install fine but when I go to run I get the following 
`$ medaka_consensus -i Input.fastq -d contigs.fasta -o output -m r941_min_high_g330`
`/home/dct7/medaka/bin/medaka_consensus: line 16: 31399 Illegal instruction     medaka tools list_models
`

**Comment by cjw85** [comment]
Hi @damientully,

Can you confirm the CPU hardware on which you are trying to run medaka? The package on pypi should be compatible with anything later that circa 2011. (The newest CPU instructions contained within the code are AVX instructions).

**Comment by damientully** [comment]
I was running everything fine with version 0.10 so I'm not sure what has changed. It is been run on a computer cluster comprising Intel Xeon CPUs so I don't believe its the hardware as medaka has run fine in the past.

**Comment by cjw85** [comment]
I cannot identify any differences in the instruction sets used by the binaries contained with v0.11.1 and v0.10.0. I've also run the the code (`medaka tools lis_models`) on a processor where the latest instruction set supported is AVX (no AVX2, AVX512, etc). I also cannot identify any differences to our deployment processes that could have caused a difference.

I will continue to investigate. Could you report the output of `cat /proc/cpuinfo/`?

**Comment by damientully** [comment]
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
stepping	: 1
microcode	: 0x3d
cpu MHz		: 2297.339
cache size	: 40960 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc pni ssse3 cx16 hypervisor lahf_lm arat
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
stepping	: 1
microcode	: 0x3d
cpu MHz		: 2297.339
cache size	: 40960 KB
physical id	: 2
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc pni ssse3 cx16 hypervisor lahf_lm arat
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
stepping	: 1
microcode	: 0x3d
cpu MHz		: 2297.339
cache size	: 40960 KB
physical id	: 4
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc pni ssse3 cx16 hypervisor lahf_lm arat
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
stepping	: 1
microcode	: 0x3d
cpu MHz		: 2297.339
cache size	: 40960 KB
physical id	: 6
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc pni ssse3 cx16 hypervisor lahf_lm arat
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
stepping	: 1
microcode	: 0x3d
cpu MHz		: 2297.339
cache size	: 40960 KB
physical id	: 8
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 8
initial apicid	: 8
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc pni ssse3 cx16 hypervisor lahf_lm arat
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
stepping	: 1
microcode	: 0x3d
cpu MHz		: 2297.339
cache size	: 40960 KB
physical id	: 10
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 10
initial apicid	: 10
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc pni ssse3 cx16 hypervisor lahf_lm arat
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
stepping	: 1
microcode	: 0x3d
cpu MHz		: 2297.339
cache size	: 40960 KB
physical id	: 12
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 12
initial apicid	: 12
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc pni ssse3 cx16 hypervisor lahf_lm arat
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
stepping	: 1
microcode	: 0x3d
cpu MHz		: 2297.339
cache size	: 40960 KB
physical id	: 14
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 14
initial apicid	: 14
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc pni ssse3 cx16 hypervisor lahf_lm arat
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by cjw85** [comment]
I note from the above that the CPU you are using should support sse4 and AVX2, but in the flags these are not listed. However you do have `hypervisor` listed. Would I be correct in thinking your cluster is running some sort of virtualisation? My guess would be that the virtualisation does not support newer instruction sets?

**Comment by cjw85** [comment]
@damientully,

Have you resolved this issue?

**Comment by damientully** [comment]
Fixed.

Thanks.
