### ISSUE TITLE
what samples make up of the training dataset for medaka_consensus training?

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/medaka#120]
Hi:
    I am using the medaka for assembly polishing, and very curious about the composition of the training data set of medaka_consensus module. And did you release the dataset?
Thanks

**Comment by cjw85** [comment]
Hi @huangnengCSU,

medaka is trained from a (growing) set of small bacterial and eukaryotic samples. The datasets are not currently all publicly available; though the training methodology is available in our [katuali](https://nanoporetech.github.io/katuali/medaka_train.html) snakemake pipelines.

**Comment by huangnengCSU** [comment]
Got it, thanks for your answer.
