### ISSUE TITLE
Support for python >=3.7

### ISSUE THREAD

**Issue by OscarAspelin** [nanoporetech/medaka#123]
Hi, just a quick question - are you planning on upgrading medaka to have support for python >=3.7 in the near future?

**Comment by cjw85** [comment]
Thanks for the question,

The restriction to python <3.7 is an artefact of the environments under which medaka is developed and that we know there are some issues/bugs under python >=3.7. This is very much one of the reasons we are committed to maintaining a conda package for medaka; there is then at least a lowest common denominator solution.

So whilst there are no immediate plans to implement python 3.7/3.8 support, development time is focussed on new algorithms currently, it is an issue of which we are aware needs addressing as pythons >3.6 become mainstream.

**Comment by boegel** [comment]
@cjw85 Do you have more information available about the problems that pop up when using medaka on top of Python 3.7?

I'm aware that there are some incompatibilities between Python 3.6 & 3.7, but those should be minimal/easy to fix, I think...

**Comment by cjw85** [comment]
@boegel,

We do not have a complete list of issues, we do know from experience with users attempting to use python3.7 that some issues arise. One thing we would be wary of is the status of python3.7 support in all of our dependencies. I'm sure the incompatibilities are not insurmountable, though as noted above we have no immediate plans to support pythons other than 3.5 and 3.6.

**Comment by boegel** [comment]
@cjw85 Any updates on compatibility with more recent Python 3 versions?

**Comment by cjw85** [comment]
We are setting up our build system to build python 3.7 and 3.8 wheels. This will be largely untested.

**Comment by cjw85** [comment]
PyPI now has v1.1.0 wheels for Pythons 3.5-3.8.
