### ISSUE TITLE
medaka/test not included in released source tarball on PyPI

### ISSUE THREAD

**Issue by boegel** [nanoporetech/medaka#125]
To validate the `medaka` installation, I would like to run the tests (using `pytest medaka`, like `make test` does).

I strongly prefer using the latest `medaka` release from PyPI for this (rather than cloning the repository), but this doesn't work because `medaka/test` is not included in the source tarball provided on PyPI.

Is this intentional? Are you willing to consider to change this, so running `pytest medaka` works as expected for a `medaka` installation that was performed using the source tarball downloaded from PyPI?

**Comment by cjw85** [comment]
It is indeed deliberate that the testing code is not included in the source distribution, following the principle that tests are concerned with [development not usage](https://blog.ionelmc.ro/2014/05/25/python-packaging/). Our existing test quite is mainly concerned with unittests of individual components; there are no high-level system level tests.

We do however have a [walkthrough](https://nanoporetech.github.io/medaka/walkthrough.html#walkthrough) of the use of medaka including some example data for download. Note however that this could do with a refresh so you may not now obtain exactly the same results as contained within the example dataset. Its on our TODO list to updates these this page.

**Comment by boegel** [comment]
@cjw85 As suggested in #124, I want to use the tests to validate the installation, mainly w.r.t. the dependencies that are used...
Is using the tests in medaka/test via pytest not the right approach for this after all?

**Comment by cjw85** [comment]
The tests will certainly give you some comfort. The pypi source distributions are built from the release tags available in the git repository (our CI pipeline is included in the repo), you can check out and use these tags as substitutes to the pypi archives.

I will close this issue as including the unit test suite in the pypi source package is not something we are likely to implement.
