### ISSUE TITLE
Info about model choice

### ISSUE THREAD

**Issue by MaestSi** [nanoporetech/medaka#127]
Hi,
I would like to know which is the best model to use if I have basecalled my MinION R9.4.1 data with Guppy v3.4.4 with fast configuration, since there isn't a dedicated model. Would it be better to go for r941_min_high_g344 or r941_min_fast_g303? I guess the lattest may be better, am I correct?
Thanks,
Simone

**Comment by cjw85** [comment]
Hi @MaestSi,

Thank you for you question. In recent times we have not been training of testing medaka with the fast guppy basecaller, so the simple answer is that I cannot give a definitive recommendation. I would suggest possibly trying both and comparing the results (to each other and an appropriate reference sequence if one is available).
