### ISSUE TITLE
Haplotype specific consensus sequences in medaka_variant pipeline ?

### ISSUE THREAD

**Issue by c-oget** [nanoporetech/medaka#128]
Hello,
In the documentation, it is said that in one step of the medaka_variant pipeline, medaka consensus is run independently for each haplotype to calculate haplotype specific consensus sequences.
I would like to know if it would be possible to get these consensus sequences as output files? Because it seems to me that we only have the final vcf files? 
Thanks,
Claire

**Comment by cjw85** [comment]
The `medaka_variant` program does not compute a consensus sequence. It will however produce two files named `round_1_hap_{1/2}_probs.hdf` within its output folder. These files can be given to `medaka stitch` to produce haplotigs.

However, particularly if you wish to first filter the variant calls, it may be better to use [bcftools](https://samtools.github.io/bcftools/howtos/index.html) to apply the variants listed by medaka to back to your reference sequence.

**Comment by c-oget** [comment]
Thank you for your answer and recommendations. 
Claire
