### ISSUE TITLE
Potential problem with locating reference

### ISSUE THREAD

**Issue by ChloeDG** [nanoporetech/medaka#129]
I get the following error, pertaining to the path for the reference, when trying to call for methylation since the latest medaka update (0.11.5). 

(medaka) hh@hh-Latitude-5590:~$ medaka methylation guppy2sam ${FAST5PATH} ${REFERENCE} \
     --workers 16 --io_workers 4 --recursive \
     | samtools sort -@ 8 | samtools view -b -@ 8 > ${OUTBAM}
usage: medaka [-h] [--version]
              {compress_bam,features,train,consensus,smolecule,consensus_from_features,fastrle,stitch,variant,snp,methylation,tools}
              ...
medaka: error: unrecognized arguments: /home/hh/Documents/refs/hg38.fasta

When I specify the reference with --reference the files are extracted but it doesn't align and I get an empty meth.bam

Am I missing something? 
 
 - OS Ubuntu 16.04
 - no GPU 
 - samtools version 1.9
- Medaka version 0.11.5 
- Installation method, conda

**Comment by cjw85** [comment]
Hi @ChloeDG 
If using a reference it must now be specified using the `--reference` argument, otherwise the `guppy2sam` command will output unaligned `.sam` data.

Could you share one of your `.fast5` files that you are trying to process?

**Comment by ChloeDG** [comment]
Hi @cjw85 Thanks for the quick reply!
I can't attach a fast5 here so this is a link to the file
[https://drive.google.com/open?id=1z5GqiGEhE-DX-6KkA5hbJCC1x_AxdddT](url)

**Comment by cjw85** [comment]
Using your file (placed under `fast5path` and running:

```
$ medaka methylation guppy2sam \
    --workers 12 --io_workers 4 --recursive fast5path \
    --reference GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
    > aligned.sam
```

I obtain the desired result. Can you reproduce your original error with this one file?

**Comment by ChloeDG** [comment]
No errors this time thank you so much! But now when I try to extract the meth.tsv I get the following error:

$ medaka methylation call --meth cpg /20191217/b16/meth.bam /refs/hg38.fasta chr20:10000-100000 /meth.tsv
[14:47:27 - Mextract] Processing /home/hh/Documents/20191217/b16/meth.bam.
[W::sam_hdr_parse] Duplicated sequence 'chr4'
[W::sam_hdr_parse] Duplicated sequence 'chr4_GL000008v2_random'
[W::sam_hdr_parse] Duplicated sequence 'chr4'
[W::sam_hdr_parse] Duplicated sequence 'chr4_GL000008v2_random'
[14:47:27 - Mextract] Searching for motif 'CG'.
Traceback (most recent call last):
  File "/home/hh/miniconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/hh/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 532, in main
    args.func(args)
  File "/home/hh/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 325, in call_methylation
    region.ref_name, region.start, region.end):
  File "pysam/libcalignmentfile.pyx", line 1347, in pysam.libcalignmentfile.AlignmentFile.pileup
NotImplementedError: pileup of samfiles not implemented yet

Any ideas for this one?

**Comment by cjw85** [comment]
This looks like you have given `medaka methylation call` a samfile and not a bamfile. The sam output from `guppy2sam` needs to be converted to bam as in the [example](https://nanoporetech.github.io/medaka/methylation.html#methylation-calling).

**Comment by ChloeDG** [comment]
When I try to convert it using samtools index meth.bam I get the following error: 
samtools index: "/home/hh/Documents/20191217/b16/meth.bam" is in a format that cannot be usefully indexed

So I guess I am still having a problem generating the sam

**Comment by cjw85** [comment]
I am guessing that your file `meth.bam` is either unsorted or a sam file not a bam file?

**Comment by ChloeDG** [comment]
unsorted. 
https://drive.google.com/open?id=1z5GqiGEhE-DX-6KkA5hbJCC1x_AxdddT

**Comment by cjw85** [comment]
Can you confirm all the commands that you are now running?

**Comment by ChloeDG** [comment]
medaka methylation guppy2sam \
    --workers 12 --io_workers 4 --recursive FAST5PATH \
    --reference REFERENCEPATH \
    > OUTBAMPATH/meth.bam

samtools index OUTBAMPATH/meth.bam

medaka methylation call --meth cpg OUTBAMPATH REFERENCEPATH REGION OUTPUT/meth.tsv

**Comment by cjw85** [comment]
The output `medaka methylation guppy2sam` is a sam formatted alignment data, not its bam equivalent. This is why `samtools index` is failing. Also the file that `meth.bam` file you linked above is empty.

Can you check your other inputs are valid? As above, when I process the single fast5 file you linked above with [this](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz) reference file, I obtained the desired result.

**Comment by ChloeDG** [comment]
Oh ok. So what commands am I missing? When I run the following using your above reference, samtools index works but still an empty meth.bam: 

medaka methylation guppy2sam ${FAST5PATH} \
        --reference ${REFERENCE} \
        --workers 16 --io_workers 4 --recursive \
        | samtools sort -@ 8 | samtools view -b -@ 8 > ${OUTBAM}
samtools index /meth.bam

https://drive.google.com/drive/folders/1z5GqiGEhE-DX-6KkA5hbJCC1x_AxdddT

**Comment by cjw85** [comment]
I believe I have found the issue. A change to the `ont_fast5_api` in version 3.0.0 of that packaged release last week has broken the ability of `guppy2sam` to read the input files. My testing environment did not have this new version on `ont_fast5_api` so still works fine. 

We will amend `guppy2sam` to use the new version on `ont_fast5_api`. In the meantime it may be possible for you to have it work in your environment by downgrading `ont_fast5_api` to version `2.0.1` with:

    pip install ont_fast5_api==2.0.1
    # or
    conda install -c bioconda ont-fast5-api==2.0.1

**Comment by ChloeDG** [comment]
Ok. I downgraded `ont_fast5_api` and it works! I'll keep an eye out for the new version as well. 
Thank you.
