### ISSUE TITLE
medaka polishing and flappie data

### ISSUE THREAD

**Issue by SorenKarst** [nanoporetech/medaka#13]
I would like to test flappie basecalled data with medaka, but I guess I need a new model for medaka since the error profile has changed. Would it be possible for you to train and provide such a model?

**Comment by SorenKarst** [comment]
Fantastic! Looking forward to it.

**Comment by cjw85** [comment]
Version 0.4.3 now includes a model for the flip-flop algorithm as implemented in guppy. It can be enabled with the `-m` option:

    medaka_consensus -i <reads.fasta> -d <draft> -m r94_flip
