### ISSUE TITLE
Is there an medaka option to not break contigs

### ISSUE THREAD

**Issue by tpshea2** [nanoporetech/medaka#131]
Greetings-

I am polishing a fungal genome canu assembly and medaka takes this contig (showing length in bases)

> tig00000097	823947

and appears to split it into 3 pieces (I suppose due to local mis-assembly)

> tig00000097:16.0-70144.0	70427
> tig00000097:70453.0-73183.0	2749
> tig00000097:73476.0-823947.0	752022

This is in the region of the very repetitive rDNA and we know that we may not have the consensus exactly correct but wish to proceed with the contig structure as-is anyway.

Is there an option to force medaka to leave the contig intact and not break it into pieces?

Thank you.

**Comment by cjw85** [comment]
Hi @tpshea2,

Apologies for the late response here (I appear to have not finished my previous attempt at replying!). You are correct that when medaka is breaking contigs it might be evidence of mis-assembly; more precisely its simply when no reads span a region of the draft sequence in the input `.bam` file.

You request is related to similar issues in the past, and we have a long standing internal issue for medaka to write out a `.vcf` of edits rather than a consensus sequence directly. Unfortunately we have never had the time to implement these things.

In the meantime, and if you haven't figured out already, the numbers in the above sequence identifiers from medaka's output relate to (zero-based) co-ordinates in from the input sequence. You could use there (or rather the implied gaps) to fill in the missing sequence from your input assembly.

**Comment by mwykes** [comment]
Hi @tpshea2, you could create a .vcf using `medaka variant` using the consensus hdf file created by `medaka consensus`. You could then apply the vcf to the draft using e.g. `bcftools consensus` to obtain the polished draft without breaking contigs.

**Comment by tpshea2** [comment]
Thank you for all of the replies thus far.

Related to the issue of Medaka finding no read spanning a region, how does
Medaka deal with a region (say a very large region, longer than the typical
ONT read length) where all ONT reads have mapping quality of zero.  For
example the calls_to_draft.bam may look like the following (showing only
fields 1-5):

4917fb81-a97a-4340-83eb-971cc570df2a    16
>  tig00000009_tig00000507_tig00000262     5181129 0
> 424c9964-234d-4d34-ac42-6ff03ff10177    0
> tig00000009_tig00000507_tig00000262     5183519 0
> 2ad754dc-e36e-4ac1-a8f8-f1bf672023ce    16
>  tig00000009_tig00000507_tig00000262     5183634 0
> 71a0da6d-794a-4477-97ef-580c436ab784    16
>  tig00000009_tig00000507_tig00000262     5183882 0
> 25bd8d03-c427-40c0-8a01-c414256b042f    16
>  tig00000009_tig00000507_tig00000262     5183962 0
> 82a36201-2694-4bfa-b614-43d135427ea4    16
>  tig00000009_tig00000507_tig00000262     5184237 0
> 203030fe-f4d2-4bd8-b0ee-eeb4eec1b751    0
> tig00000009_tig00000507_tig00000262     5184589 0



Will Medaka be unable to polishing have difficulting polishing such regions
because reads map equally well to two places?  I see from log file message
like:

[20:24:13 - PileUp] Splitting discontiguous pileup region.
> [20:24:13 - PileUp] Splitting discontiguous pileup region.
> [20:24:13 - PileUp] Splitting discontiguous pileup region.
> [20:24:13 - PileUp] Splitting discontiguous pileup region.
> [20:24:13 - Feature] Pileup counts do not span requested region, requested
> tig00000009_tig00000507_tig00000262:4999000-6000000, received
> 4999000-5182135.
> [20:24:13 - Feature] Processed
> tig00000009_tig00000507_tig00000262:4999000.0-5182135.0 (median depth 416.0)
> [20:24:13 - Feature] Pileup counts do not span requested region, requested
> tig00000009_tig00000507_tig00000262:4999000-6000000, received
> 5183697-5186777.
> [20:24:13 - Feature] Processed
> tig00000009_tig00000507_tig00000262:5183697.0-5186777.0 (median depth 1.0)
> [20:24:13 - Feature] Pileup counts do not span requested region, requested
> tig00000009_tig00000507_tig00000262:4999000-6000000, received
> 5190532-5190780.
> [20:24:13 - Feature] Processed
> tig00000009_tig00000507_tig00000262:5190532.0-5190780.0 (median depth 1.0)


and where depth drastically drops to 1x (from 416x) suggesting that MQ=0
reads may not count as spanning and thus used to polish the consensus here?

In this specific example the reason for many readsss having MQ=0 is because
a large duplication originally collapsed by the assembler was manually
built out and inserted into the consensus.  So there are basically two
copies of a ~250 Kb region.  Based on read alignment (both ONT and
Illumina) to medaka consensus output that Medaka not only failed to polish
this large duplicated region but maybe even made the consensus sequence
worse.

Thank you for any insight you may have in this particular example.

Terrance

**Comment by SAMtoBAM** [comment]
I have this same problem, where a assembly becomes fragmented after a run with medaka consensus, which I would rather avoid..Is there any development on inhibiting this?
I can see how I might use the coordinates within the new fragmented contig names, however this seems like a laborious task

@mwykes, 
How can you perform this trick of yours to convert the hdf file to a vcf using medaka variant (prior to bcftools consensus)?

Thank you

**Comment by cjw85** [comment]
The `-v` option was added to `medaka_consensus` in version 0.12.0, this will output a `.vcf` file of changes from the input sequence, and use bcftools to create a new consensus. The process is however a little slow compared to the normal consensus generation.

**Comment by cjw85** [comment]
@tpshea2,

Medaka will ignore alignments with a mapping quality of 0, though to be honest I cannot remember if this was a deliberate choice or an oversight in the minimum possibly mapping score (see [here](https://github.com/nanoporetech/medaka/blob/master/src/medaka_bamiter.c#L21) and [here](https://github.com/nanoporetech/medaka/blob/master/src/medaka_counts.c#L319) in the code).
