### ISSUE TITLE
Guppy (research_rle_0.0.0) compatability

### ISSUE THREAD

**Issue by damientully** [nanoporetech/medaka#134]
Hi,
Is the latest Guppy (research_rle_0.0.0) version compatible with current medaka models? 

Thanks,
Damien

**Comment by cjw85** [comment]
Apologies for the lack of response here. Current research has moved away from RLE basecallers. The RLE functionality in medaka was developed against models trained previous to that include in the research_rle_0.0.0 version of guppy.
