### ISSUE TITLE
Add option to disable version check

### ISSUE THREAD

**Issue by valsenlis** [nanoporetech/medaka#135]
**Is your feature request related to a problem? Please describe.**
I have to do thousands of runs of medaka on many small batches of reads to call as many consensus sequences. But each time medaka starts, it seems that there is a quite long initialization step to check the versions of the dependencies before running. This constitutes a significant share of the full runtime when using medaka thousands of times in a row, and is unnecessary once I know that I have the right versions installed.

**Describe the solution you'd like**
A nice solution to this issue could be to add an option when running medaka that disables version check, and therefore shortens the initialization step. If this is possible, that would save quite some time in instances for which medaka is called many times in a row.

**Comment by cjw85** [comment]
Hi @valsenlis,

For your use case I would recommend eschewing the `medaka_consensus` script and running the steps of the workflow yourself. The steps of the script are detailed here: https://nanoporetech.github.io/medaka/installation.html#improving-parallelism

**Comment by valsenlis** [comment]
Thank you for this suggestion, indeed it should address my needs.
