### ISSUE TITLE
Question: Aggregating methylation tables for whole genome

### ISSUE THREAD

**Issue by ChloeDG** [nanoporetech/medaka#136]
I have a naive question. Is there a way to extract methylation tables (meth.tsv) for the whole genome instead of a specific region? 
That is, in this step, I am making a meth.tsv for each chromosome and then merging them afterwards, but there has to be an easier way: 

The second step is to aggregate the reference-aligned information to produce a simple tabular summary of read methylation counts:

```
BAM=meth.bam
REFERENCE=grch38.fasta
REGION=chr20:500000-1000000
OUTPUT=meth.tsv
```
```medaka methylation call --meth cpg ${BAM} ${REFERENCE} ${REGION} ${OUTPUT}```

**Comment by cjw85** [comment]
Hi @ChloeDG,

The program does currently require a region to be given. There's no good reason for this, so we will look to get it changed. One thing I will say is that for performance it is likely desirable to run the program across chromosomes separately and merge the results afterward.
