### ISSUE TITLE
How to use medaka to call variant for haploid genome

### ISSUE THREAD

**Issue by zhanxw** [nanoporetech/medaka#140]
**Is your feature request related to a problem? Please describe.**
For many organism, their genomes are haploid. How to use medaka to call their variants?

**Describe the solution you'd like**
I am seeking a way to use medaka to get haploid variant, e.g., not get heterozygous variant.

**Describe alternatives you've considered**
I googled "haploid medaka nanopore", but did not find solution.

**Additional context**
N/A

**Comment by mwykes** [comment]
Hi @zhanxw, 
After running medaka_consensus, you can obtain haploid variant calls by running `medaka variant` on the consensus_probs.hdf file. If you just want SNPs rather than SNPs and indels, you could use `medaka snp` instead of `medaka variant`.

**Comment by mbhall88** [comment]
The [documentation on variant calling](https://nanoporetech.github.io/medaka/snp.html#variant-calling) states

> The pipeline leverages a diploid-aware neural network, read haplotype tagging via WhatsHap, and haplotype consensus using medaka’s usual consensus network.

This would indicate the models have been fine-tuned for diploid genomes though? Have you done any testing or benchmarking on haploid genomes?
