### ISSUE TITLE
Provide small test case

### ISSUE THREAD

**Issue by SHuang-Broad** [nanoporetech/medaka#141]
We'd like small tests that we can use to verify installation is successful, preferably also testing GPU capabilities.

Thanks!

**Comment by mwykes** [comment]
Hi @SHuang-Broad, have you had problems installing medaka? How did you install it? We do have tests aimed at developers, which can be run with `make test` if you install medaka from source. 

If you want a small dataset to test medaka on, we have a small [bam](https://github.com/nanoporetech/medaka/blob/master/medaka/test/data/test_reads.bam) that you could use:
```
# download bam and index
wget https://github.com/nanoporetech/medaka/raw/master/medaka/test/data/test_reads.bam
wget https://github.com/nanoporetech/medaka/raw/master/medaka/test/data/test_reads.bam.bai
# test medaka consensus without GPU
CUDA_VISIBLE_DEVICES="" medaka consensus test_reads.bam test_reads_cpu.hdf &> test_cpu.log
medaka stitch test_reads_cpu.hdf test_reads_cpu.fasta
# test medaka consensus with GPU
CUDA_VISIBLE_DEVICES=0 medaka consensus test_reads.bam test_reads_gpu.hdf &> test_gpu.log
medaka stitch test_reads_gpu.hdf test_reads_gpu.fasta
# check cudnn flag to see if GPU was used
grep "Building model with cudnn optimization" *.log
# you should see something like
# test_cpu.log:[ModelLoad] Building model with cudnn optimization: False
# test_gpu.log:[ModelLoad] Building model with cudnn optimization: True
# test fasta contig lengths
awk '{if(/^>/){name=$1}else{print FILENAME " "name" " length}}' test_reads_cpu.fasta test_reads_gpu.fasta
# you should see something like
# test_reads_cpu.fasta >utg000001l_segment0 258702
# test_reads_gpu.fasta >utg000001l_segment0 258702
```

Note that the exact contig length will depend on the default medaka model used, which can change from time to time as we release new models.

**Comment by SHuang-Broad** [comment]
Thanks @mwykes !

I have installed Medaka successfully.

The intention was simply that after installation, a test run is a peace of mind that nothing is obviously wrong with the installation.

So to make sure I understand correctly, `make test` will test installation, and GPU capability if such device is available. Is that right?

**Comment by mwykes** [comment]
So make test will only test the installation if you installed from source, i.e. you ran `make install` to install. However, it does not specifically check that medaka is using the GPU. To do this, you need to check the `Building model with cudnn optimization` flag as mentioned above.
