### ISSUE TITLE
Medaka problem with trimmed consensus - amplicon sequencing

### ISSUE THREAD

**Issue by jacqgg** [nanoporetech/medaka#142]
Hi,
I have a nanopore read alignment (minimap2) to circular reference and I want to create Medaka consensus. It was a amplicon sequencing, so coverage in some regions is higher becouse of amplicons overlap. As you can see in the picture below (IGV), the problem is that I got a consensus shorter than reference (c).

This problem is caused by BAM supplementary flag in part of the amplicon (a) - the rest (longer part) of the amplicon is aligned at the end of the reference and marked as primary alignment. Medaka consensus does not take into account supplementary alignments and trims consensus where the amplicons (a,b) overlap ends.

If I mark supplementary alignments from the first amplicon (a) as primary I will get a whole length consensus (d).

![image](https://user-images.githubusercontent.com/15021501/75870224-fb7a4680-5e0a-11ea-9602-885268d5e1fb.png)

**Comment by mwykes** [comment]
Hi @jacqgg, 
Medaka does not currently have any special handling for circular genomes, but as you have discovered, you can achieve what you want by modifying your bam before running medaka. We have chosen to exclude supplementary alignments as minimap2 can generate many such alignments, and we wish to polish with the single best alignment. In the case of a circular genome, one may wish to polish with the two best alignments - but only for reads whose alignments abut the start and end of the reference. For a read which aligns to the middle (well away from the ends) of a linear representation of a circular genome, one simply wants to pick the single best alignment.

**Comment by macieksk** [comment]
Hi @mwykes. I'm trying to understand your decision to exclude supplementary reads completely. You wrote "we wish to polish with the single best alignment. ". However, a supplementary read is exactly this: the single best alignment for this part of a read (another longer part of this read alignment of will be primary, other alignments of the same part of the read are marked "secondary", and are usually not included in bam). 

Is your concern spurious alignments of reads to repetitive elements? Then maybe you should exclude very short suplementary, or those of poor mapping quality. 
Is your concern structural variants in diploid genomes? In any case I suppose Medaka could always take into account *the aligned part* of a supplementary and primary reads. If aligned reads indicate a structural variant with many (eg. half) of the reads being split over a breakpoint (hence ~half of these suplementary), Medaka could make the consensus of the aligned parts, possibly issue a warning in logs, and not deal with this in any other way - this is a job for an assembler, or a variant caller later.

**Comment by cjw85** [comment]
@macieksk 

It is for the sorts of reasons you have indicated that medaka makes no attempt at handling subtleties of this nature (it takes only primary alignments, we could be more stringent still and take reads with only a primary alignment). Our development of medaka is focussed on calculating the consensus of sequences for which it it meaningful to perform such a task; the related ancillary tasks of determining which sequences to calculate a consensus from is beyond the scope of the research, though naturally something still of interest ultimately.

**Comment by macieksk** [comment]
What is slightly relevant to this discussion: minimap2 by default adds secondary alignments to bam.
https://lh3.github.io/minimap2/minimap2.html
```
--secondary=yes\|no
   Whether to output secondary alignments [yes]
```
In contrast to `bwa mem` where `-a` flag needs to be used to enable that.
