### ISSUE TITLE
Mac Conda OpenMP error KMP_DUPLICATE_LIB_OK

### ISSUE THREAD

**Issue by nickloman** [nanoporetech/medaka#143]
**Describe the bug**
Bioconda install of medaka on Mac fails on medaka consensus, setting KMP_DUPLICATE_LIB_OK permits it to run

**Logging**
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Environment (if you do not have a GPU, write No GPU):**
- Conda
- OS: Catalina 10.15.3
- No GPU

**Comment by cjw85** [comment]
C
