### ISSUE TITLE
tabix

### ISSUE THREAD

**Issue by woodoo46** [nanoporetech/medaka#145]
I am not sure if this is a bug, I tried to run medaka_variant, and I got this information:

++ Preparing data
- Checking program versions
tabix: invalid option -- '-'
tabix: invalid option -- 'v'

Program: tabix (TAB-delimited file InderXer)
Version: 0.2.5 (r1005)

Usage:   tabix <in.tab.bgz> [region1 [region2 [...]]]

Options: -p STR     preset: gff, bed, sam, vcf, psltbl [gff]
         -s INT     sequence name column [1]
         -b INT     start column [4]
         -e INT     end column; can be identical to '-b' [5]
         -S INT     skip first INT lines [0]
         -c CHAR    symbol for comment/meta lines [#]
         -r FILE    replace the header with the content of FILE [null]
         -B         region1 is a BED file (entire file will be read)
         -0         zero-based coordinate
         -h         print also the header lines
         -H         print only the header lines
         -l         list chromosome names
         -f         force to overwrite the index

[main] unrecognized command '--version'
bgzip: invalid option -- '-'
bgzip: invalid option -- 'v'
bgzip: invalid option -- 'e'
bgzip: invalid option -- 'r'

**Comment by cjw85** [comment]
This looks like you have an old version of tabix on your system. When installed medaka from the git repository (or conda), tabix 1.9 will be installed.

**Comment by cjw85** [comment]
@woodoo46 Have you resolved this issue?

**Comment by lichihengDG** [comment]
I am also getting this error when running medaka_variant. medaka is installed through pip, and I tried to build the tabix and bgzip from source. The version is 1.9, but the `-v` is an invalid option:

```
$ ./tabix -v
./tabix: invalid option -- 'v'

Version: 1.9
Usage:   tabix [OPTIONS] [FILE] [REGION [...]]

Indexing Options:
   -0, --zero-based           coordinates are zero-based
   -b, --begin INT            column number for region start [4]
   -c, --comment CHAR         skip comment lines starting with CHAR [null]
   -C, --csi                  generate CSI index for VCF (default is TBI)
   -e, --end INT              column number for region end (if no end, set INT to -b) [5]
   -f, --force                overwrite existing index without asking
   -m, --min-shift INT        set minimal interval size for CSI indices to 2^INT [14]
   -p, --preset STR           gff, bed, sam, vcf
   -s, --sequence INT         column number for sequence names (suppressed by -p) [1]
   -S, --skip-lines INT       skip first INT lines [0]

Querying and other options:
   -h, --print-header         print also the header lines
   -H, --only-header          print only the header lines
   -l, --list-chroms          list chromosome names
   -r, --reheader FILE        replace the header with the content of FILE
   -R, --regions FILE         restrict to regions listed in the file
   -T, --targets FILE         similar to -R but streams rather than index-jumps

```

But `--version` is a valid option:
```
$ ./tabix --version
tabix (htslib) 1.9
```

**Comment by DustinSokolowski** [comment]
Hey! As a quick follow-up, does this end up leading to downstream issues or does it just mess with the line that checks the version?? I'm getting the same error
