### ISSUE TITLE
medaka train never finish

### ISSUE THREAD

**Issue by lfaino** [nanoporetech/medaka#15]
Dear developper,
i`m using medaka train with the option ephoc set to 10 but I noticed that the software never finish. It is one day that it is doing nothing. Additionally, the software medaka fix does not exists.

Cheers
Luigi

**Comment by cjw85** [comment]
Hi @lfaino

It's no longer necessary to run medaka fix after training; we need to update the walkthrough in that respect.

The issue of training not exiting correctly is known, it is something we intend to fix in the next release. It should be safe to kill the process and use any of the checkpoint models written to the workspace.

**Comment by lfaino** [comment]
Hi @cjw85 
you were right. the file was good. however after the training, the number of insertions increased compared to the flip-flop standard model while the number of deletions reduced.

Can i use a bam file of short reads to train the model?

Cheers
Luigi

**Comment by cjw85** [comment]
The models should be trained with the type of data with which they are to be used, both the draft assembly and reads. Read length is not an issue per-se, though you should have reference contigs. of a decent size, 10s of kilo bases.

Your results with the trained model are in line with expectations if you were following the process in the [walkthrough](https://nanoporetech.github.io/medaka/walkthrough.html#training-a-consensus-network). The supplied models were trained from rather more data using a few more tricks. We hope to release our complete training workflow in the new year.

**Comment by cjw85** [comment]
This is resolved in v0.5.0, along with many other improvements to training.
