### ISSUE TITLE
methylation stop iterating after first motif

### ISSUE THREAD

**Issue by ginolhac** [nanoporetech/medaka#150]
**Describe the bug**
Hello, 
i am interested in calling methylation from all context. For this, I used `guppy` v3.5.2 with `rerio` the all context config. The `guppy2sam` went fine, but the calling stop after the first iteration of motifs.
I tried `--meth dam` and `--meth all` and got the same issue as below

**Logging**
```
medaka methylation call --debug  --meth all barcode12_meth.
bam references/sc_R64-2-1_20150113.fasta chrI:1-230200 barcode12_chrI_call_all.tsv                                               
[16:16:32 - Mextract] Processing barcode12_meth.bam.
[16:16:32 - Mextract] Searching for motif 'C'.
[16:16:33 - Mextract] Processed 0 ref positions (0%)
Traceback (most recent call last):
  File "~/install/miniconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "~/install/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 601, in main
    args.func(args)
  File "~/install/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 458, in call_methylation
    next(tracker)
  File "~/install/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 386, in __next__
    self.index = next(self.loci)
StopIteration
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method conda in an isolated py3.6 env
 - OS: [CentOS Linux release 7.7.1908 (Core)
 - GPU model, no CPU version

**Additional context**
the output are written and look fine, here is the last lines of both my attemps
```
==> barcode12_chrI_call_all.tsv <==
chrI    230072  C       0       0       143     0
chrI    230091  C       0       0       157     0

==> barcode12_chrI_call_dam.tsv <==
chrI    229120  GATC    0       0       134     89
chrI    229328  GATC    0       0       160     94
```

many thanks in advance

**Comment by cjw85** [comment]
Hi @ginolhac,

A fix for this issue has been identified and will appear in the next medaka release.

**Comment by cjw85** [comment]
This should now be fixed in v1.0.0 available on GitHub, PyPI and shortly bioconda.

**Comment by ginolhac** [comment]
thanks! I will test it tomorrow, I was using `guppy` 3.5.2, it is recommended to re-basecall everything with **3.6**?

**Comment by ginolhac** [comment]
thanks, I can confirm the program did it to the end, if you know for 3.6 guppy I will glad to know your advice. Thanks again for fixing the issue!
