### ISSUE TITLE
Racon loss of unpolished contigs

### ISSUE THREAD

**Issue by cabbagesofdoom** [nanoporetech/medaka#154]
Hi,

I just discovered that the default behaviour of Racon to exclude unpolished contigs unless the `-u` flag is used. Is there a particular reason that you do not include this flag for the recommended Racon runs prior to Medaka polishing (`racon -m 8 -x -6 -g -8 -w 500 ...`)? I find the default behaviour to silently drop contigs to be rather surprising and wondered what the rationale was for this decision.

Many thanks,

Rich

**Comment by cjw85** [comment]
Hi @cabbagesofdoom,

Until recently medaka had the same behaviour (and still does be default). The usual reason for unpolished sequence occurring is that reads haven't aligned to the assembly at this point. If that's occurring in the alignments pre-racon its quite likely to happy post-racon too.

By all means experiment with adding the `-u` option to racon, note that if you want to get out all the sequence after medaka there's a good chance you will need to use the `-v` option of `medaka_consensus`

**Comment by cabbagesofdoom** [comment]
Hi @cjw85, thanks for the quick response. I got some clarification about Racon behaviour ([here](https://github.com/lbcb-sci/racon/issues/21#issuecomment-623534141)) and I think part of my concern stemmed from my assumptions about the meaning of "polished". I interpreted this to mean "corrected" (i.e. altered), rather than "considered for correction" (i.e. supported by sufficient reads). As an ideal behaviour for polishing would be to converge on the point where the sequence is perfect and there is no need for additional polishing, it is obviously a concern if unaltered contigs get dropped. However, if it always the case that dropped sequences have  insufficient read support to be considered for polishing, this is a "feature" rather than an issue. 

Nevertheless, I would argue this is assembly "filtering" not assembly "polishing" and the behaviour should be made more explicit in the introduction and basic use examples of the tool, e.g. 

> When `medaka_consensus` has finished running, the consensus will be saved to `${OUTDIR}/consensus.fasta`. **NOTE:** This consensus will not include input sequences with insufficient read support for polishing. By default, sequences will also be split ... this can be switched off using ...

In some ways this is even more important for Medaka than Racon, as the contig-splitting of Medaka often makes the total number of sequences go *up*, masking any losses. Is there a way of pulling out the list of input sequences that have been excluded entirely from Medaka output?

**Comment by cjw85** [comment]
Thanks for the suggestion to amend the documentation. We should do that as you are not the first to be caught out by the behaviour.

Medaka does not provide a list of the excluded sequences; it does however provide lists of the included sequences. these can be found in one of two ways:

1. When using the `-v` option a BED file is output of the included regions
2. Without the `-v` option the headers of the output FASTA contain coordinates it terms of the input sequence to which they correspond (these will have decimal places which you can ignore, they relate to insertion columns in the read pileup but will invariably be zero).

**Comment by cabbagesofdoom** [comment]
Thanks. And rather than re-running anything, I will change the subheading to "Initial Polishing and Filtering" 😛

**Comment by colindaven** [comment]
Thats @cabbagesofdoom for picking this up. I would estimate >95 % of users have been (and are still being) caught out by this when using both Racon and Medaka. Despite using Racon for years (infrequently), I hadn't picked up on this despite seeing the changes in pre and post "polishing".

Note to devs - users **desperately** want to keep all contigs in their assemblies, whether they can be improved by the polisher or not, it should absolutely be a user level decision to exclude contigs based on further criteria (adapters, contamination, blast hits, fragmentation, annotation troubles etc). 

Otherwise, thanks for the nice tools.

**Comment by cjw85** [comment]
Medaka v1.1.2 now has the option to fill in uncorrected regions (using sequence from the input sequence). This will happen automatically when using `medaka_consensus`, or is enabled with the `--draft` option to `medaka stitch`.
