### ISSUE TITLE
Model for Guppy 3.6

### ISSUE THREAD

**Issue by dominik-handler** [nanoporetech/medaka#155]
Hi, 

will you provide a model for Guppy 3.6? Looking at the accuracy improvements it would be quite interesting to run Medaka with the correct model for this guppy release. 
If you plan to release a model, do you have an estimate when this will happen?
Also, do you know which model was used for the Medaka benchmark shown in the Guppy 3.6 release?

Thank you,
Dominik

**Comment by cjw85** [comment]
Medaka v1.0.0 is now on GitHub and pypi and includes models for Guppy 3.6.
