### ISSUE TITLE
model for guppy 3.2.10

### ISSUE THREAD

**Issue by tolot27** [nanoporetech/medaka#156]
On the GridION guppy 3.2.10 is installed for a long time and still the most recent version beside 3.6 was released yet. Please can you provide a model for this guppy version 3.2.10? For this version and the PromethION, models are available (r103_prom_snp_g3210, r103_prom_variant_g3210).

**Comment by cjw85** [comment]
Hi @tolot27,

Guppy 3.2.10 is a bit of an oddball in terms of model versioning.

Guppy 3.2.10 includes back ported models from Guppy 3.4.4 for R9.4.1 and Guppy 3.4.5 for R10.3. This means that for the purposes of choosing a medaka model for R9.4.1, Guppy 3.2.10 should be treated as if it were Guppy 3.4.4 (3.4.5 for R10).

For the GridION data you therefore should use the medaka model: `r941_min_high_g344`.

**Comment by MehmetGoktay** [comment]
Hi,

Same issue but different version of guppy.
I have reads from GridION Mk1 platform with R9.4.1 RevD Flow Cells, Guppy 4.2.3 and high accuracy. Can someone please tell me which medaka model I am supposed to use? (Guppy 4.2.3 is not available in madeka models list)  r941_min_high_???

Best,
Mehmet

**Comment by cjw85** [comment]
Hi @MehmetGoktay,

As per the [README](https://github.com/nanoporetech/medaka/blob/master/README.md#models):

> where a version of Guppy has been used without an exactly corresponding medaka model, the medaka model with the highest version equal to or less than the guppy version should be selected.

**Comment by MehmetGoktay** [comment]
Ah I see. Thank you very much!
