### ISSUE TITLE
Medaka error 

### ISSUE THREAD

**Issue by danielperez96** [nanoporetech/medaka#157]
Hello,
I downloaded the new version of Medaka (1.0.0) using conda (NO GPU). When I ran a command, I got the following error:

**_Traceback (most recent call last):
  File "./.conda/envs/medaka-1.0.0-dani/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "./.conda/envs/medaka-1.0.0-dani/lib/python3.6/site-packages/medaka/medaka.py", line 640, in main
    args.func(args)
  File "./.conda/envs/medaka-1.0.0-dani/lib/python3.6/site-packages/medaka/medaka.py", line 205, in get_alignment_params
    align_params = alignment_params['non-rle']
NameError: name 'alignment_params' is not defined_**

The script related to line 205 (I understood that this is the main bug) in get_alignment_params is:

**def get_alignment_params(args):
    if is_rle_encoder(args.model):
        align_params = alignment_params['rle']
    else:
        align_params = alignment_params['non-rle']
   print(align_params)**

I would be very grateful if you tell me a way to fix it.

Thank you very much, 

Dani.

**Comment by JWDebler** [comment]
Same exact story / problem here.

**Comment by mwykes** [comment]
Hi @danielperez96, @JWDebler, 
We've just released v1.0.1, with a fix. 
Could you possibly try it out?
Thanks,
Mike

**Comment by danielperez96** [comment]
> Hi @danielperez96, @JWDebler,
> We've just released v1.0.1, with a fix.
> Could you possibly try it out?
> Thanks,
> Mike

**Comment by danielperez96** [comment]
> > Hi @danielperez96, @JWDebler,
> > We've just released v1.0.1, with a fix.
> > Could you possibly try it out?
> > Thanks,
> > Mike


Now it works! Thank you very much!
