### ISSUE TITLE
medaka_consensus: Invalid option: -M

### ISSUE THREAD

**Issue by stephanflemming** [nanoporetech/medaka#158]
When running

`medaka_consensus -d 'assembly.fasta' -i 'basecalls.fastq'`

the program stops with the following error message.

```
Checking program versions
This is medaka 1.0.1
Program    Version    Required   Pass     
bcftools   1.9        1.9        True     
bgzip      1.9        1.9        True     
minimap2   2.17       2.11       True     
samtools   1.9        1.9        True     
tabix      1.9        1.9        True     
Aligning basecalls to draft
Invalid option: -M.
Failed to run alignment of reads to draft.
```

An option -M is not specified in `-h`. What am I doing wrong? Testdata can be found [here](https://github.com/nanoporetech/medaka/files/4641142/testdata.zip).

Thanks,
Stephan

**Comment by mwykes** [comment]
Hi @stephanflemming,
How did you install medaka? Could you try a fresh install, removing whatever previous env you might have had? I've just tried installing medaka into a new conda env and virtualenv (via pip) and did not have this problem. The invalid option -M is occuring when medaka runs a pomoxis script mini_align, which is bundled with the medaka wheel. Do you by any chance have an older installation of pomoxis in your PATH? If so, can you try upgrading to the latest pomoxis release, or removing it from your PATH?

**Comment by stephanflemming** [comment]
Hi,

that worked. I created a conda env with medaka 1.0.0 and updated it later to 1.0.1 ... maybe that caused the trouble.

I realised that the conda version is outdated.

0.3.2: https://bioconda.github.io/recipes/pomoxis/README.html
0.3.3: https://github.com/nanoporetech/pomoxis/releases

Thanks for the quick response,
Stephan
