### ISSUE TITLE
Test data for variant and medaka_variant

### ISSUE THREAD

**Issue by stephanflemming** [nanoporetech/medaka#159]
Hi,

I am implementing Galaxy wrappers for `medaka variant` and `medaka_variant`. You can find the PR [here](https://github.com/galaxyproject/tools-iuc/pull/3026). Can you provide a small (<< 1MB) test dataset that can be used for the internal tests of the wrappers?

- medaka variant: ref_fasta, multiple inputs
- medaka_variant: -i, -f

Test data provied [here](https://github.com/nanoporetech/medaka/tree/master/medaka/test/data) here cause errors.

Thank you.

**Comment by cjw85** [comment]
The above linked issues appear close, so I'm going to assume you solved this problem yourself.
