### ISSUE TITLE
Galaxy wrappers are ready to test.

### ISSUE THREAD

**Issue by stephanflemming** [nanoporetech/medaka#163]
Hi,

we just added wrappers for

[medaka consensus ](https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fmedaka_consensus%2Fmedaka_consensus%2F1.0.1%2Bgalaxy0)
[medaka_consensus](https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fmedaka_consensus_pipeline%2Fmedaka_consensus_pipeline%2F1.0.1%2Bgalaxy0)
[medaka variant ](https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fmedaka_variant%2Fmedaka_variant%2F1.0.1%2Bgalaxy0)
[medaka_variant](https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fmedaka_variant_pipeline%2Fmedaka_variant_pipeline%2F1.0.1%2Bgalaxy0)

Feel free to test it :-) Your comments and suggestions are highly appreciated.

Thank you,
Stephan

**Comment by cjw85** [comment]
Thank you for this. Unfortunately this is not something we will not ourselves be able to give a this a thorough test.
