### ISSUE TITLE
medaka v0.10 predict - unable to open file: name = 'consensus_probs.hdf' - failed to run medaka consensus

### ISSUE THREAD

**Issue by KatharinaFrey** [nanoporetech/medaka#166]
Hi,

I tried to run medaka v0.10 after installation in its own environment using conda-forge. (I work on a compute cluster and have no sudo privileges.) However, it fails with the following error:

`Traceback (most recent call last):`
`File "/homes/.conda/envs/medaka/lib/python3.6/site-packages/h5py/_hl/files.py", line 111, in make_fid`
`fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)`
`File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper`
`File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper`
`File "h5py/h5f.pyx", line 78, in h5py.h5f.open`
`OSError: Unable to open file (unable to open file: name = 'consensus_probs.hdf', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2)`

Prior to this error message the contig names and positions are printed:

[...] `[M::main] Real time: 21049.016 sec; CPU: 256944.031 sec; Peak RSS: 15.272 GB`
`[bam_sort_core] merging from 126 files and 14 in-memory blocks...`
`Running medaka consensus`
`OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.`
`OMP: Info #213: KMP_AFFINITY: cpuid leaf 11 not supported - decoding legacy APIC ids.`
`OMP: Info #149: KMP_AFFINITY: Affinity capable, using global cpuid info`
`OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-31`
`OMP: Info #156: KMP_AFFINITY: 32 available OS procs`
`OMP: Info #157: KMP_AFFINITY: Uniform topology`
`OMP: Info #159: KMP_AFFINITY: 8 packages x 1 cores/pkg x 4 threads/core (8 total cores)`
`OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:`
`OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 thread 0 `
`OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 thread 1 `
`OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 thread 2 `
`OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 thread 3 `
`OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 1 thread 0 `
`OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 1 thread 1 `
`OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 1 thread 2 `
`OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 1 thread 3 `
`OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to package 2 thread 0`
`OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to package 2 thread 1 `
`OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to package 2 thread 2 `
`OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to package 2 thread 3 `
`OMP: Info #171: KMP_AFFINITY: OS proc 12 maps to package 3 thread 0 `
`OMP: Info #171: KMP_AFFINITY: OS proc 13 maps to package 3 thread 1 `
`OMP: Info #171: KMP_AFFINITY: OS proc 14 maps to package 3 thread 2 `
`OMP: Info #171: KMP_AFFINITY: OS proc 15 maps to package 3 thread 3 `
`OMP: Info #171: KMP_AFFINITY: OS proc 16 maps to package 4 thread 0 `
`OMP: Info #171: KMP_AFFINITY: OS proc 17 maps to package 4 thread 1 `
`OMP: Info #171: KMP_AFFINITY: OS proc 18 maps to package 4 thread 2 `
`OMP: Info #171: KMP_AFFINITY: OS proc 19 maps to package 4 thread 3 `
`OMP: Info #171: KMP_AFFINITY: OS proc 20 maps to package 5 thread 0 `
`OMP: Info #171: KMP_AFFINITY: OS proc 21 maps to package 5 thread 1 `
`OMP: Info #171: KMP_AFFINITY: OS proc 22 maps to package 5 thread 2 `
`OMP: Info #171: KMP_AFFINITY: OS proc 23 maps to package 5 thread 3 `
`OMP: Info #171: KMP_AFFINITY: OS proc 24 maps to package 6 thread 0 `
`OMP: Info #171: KMP_AFFINITY: OS proc 25 maps to package 6 thread 1 `
`OMP: Info #171: KMP_AFFINITY: OS proc 26 maps to package 6 thread 2 `
`OMP: Info #171: KMP_AFFINITY: OS proc 27 maps to package 6 thread 3 `
`OMP: Info #171: KMP_AFFINITY: OS proc 28 maps to package 7 thread 0`
`OMP: Info #171: KMP_AFFINITY: OS proc 29 maps to package 7 thread 1 `
`OMP: Info #171: KMP_AFFINITY: OS proc 30 maps to package 7 thread 2 `
`OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to package 7 thread 3 `
`OMP: Info #250: KMP_AFFINITY: pid 17730 tid 17730 thread 0 bound to OS proc set 0`
`[19:21:32 - Predict] Processing region(s): tig00000007_pilon_pilon_pilon:0-13157589 tig00000009_pilon_pilon_pilon:0-9335297 tig00000012_pilon_pilon_pilon:0-109504 tig00000013_pilon_pilon_pilon:0-164587 tig00000019_pilon_pilon_pilon:0-306288 tig00000021_pilon_pilon_pilon:0-30157116 tig00000029_pilon_pilon_pilon:0-18080349 tig00000035_pilon_pilon_pilon:0-113335 tig00000038_pilon_pilon_pilon:0-13747995 tig00000043_pilon_pilon_pilon:0-230015 tig00000044_pilon_pilon_pilon:0-136101 tig00000045_pilon_pilon_pilon:0-1470187 tig00000046_pilon_pilon_pilon:0-119824 tig00000048_pilon_pilon_pilon:0-105343 tig00000050_pilon_pilon_pilon:0-634538 tig00000055_pilon_pilon_pilon:0-23503980 tig00000060_pilon_pilon_pilon:0-2581942 tig00000064_pilon_pilon_pilon:0-11653826 tig00000066_pilon_pilon_pilon:0-3046615` [...]

Command used:
`medaka_consensus -i ./reads_ont.fastq.gz -d ./racon.fasta -o ./medaka/ -t 14 -m r941_min_high`

Do you have any suggestions to solve this problem?

Thanks!
Kathi

**Comment by mwykes** [comment]
Hi @KatharinaFrey, sorry for the slow reply. Have you managed to solve this? 
If not, I see you are using quite an old version of medaka - could you possibly try installing the [latest version](https://github.com/nanoporetech/medaka/releases/tag/v1.0.3) and see if the problem persists?

**Comment by KatharinaFrey** [comment]
Hi @mwykes, I managed to run medaka on a virtual machine of a cloud service we use in addition to our system. We wanted to use this version of medaka to allow comparison between different studies. Further, I tried to install the latest version of medaka and now the dependencies seem to make problems on our system. However, I am happy to now have the results I needed.
