### ISSUE TITLE
medaka_consensus splits contig into multiple contigs

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/medaka#167]
Hi

I have experienced that running medaka_consensus (Medaka v. 1.0.1) splits some of the contigs in my assembly. 
I expected that the output of polishing a contig with medaka would be a single contig. However, it is not always the case. 

1. What triggers medaka to split contigs? 
2. Can I turn it off?

Best regards
Rasmus

**Comment by mwykes** [comment]
Hi @Kirk3gaard, 

Medaka will split contigs where there are gaps in coverage; the logic is to only output polished sequence. 

Yes you can avoid the splitting of contigs; use the -v option to medaka_consensus, which decodes changes medaka has made to vcf, and applies those changes to the input draft to create the consensus. It also outputs a bed indicating which regions (in draft coordinates) were polished, as well as a chain file for converting draft coordinates to polished consensus coordinates if you so wish.

Hope that helps,

Mike

**Comment by Kirk3gaard** [comment]
Hi Mike

Thanks for the reply. I will try the -v option then.

Best regards 
Rasmus
