### ISSUE TITLE
How to pick the right model if no exact match from Guppy version to Medaka model

### ISSUE THREAD

**Issue by ms-gx** [nanoporetech/medaka#169]
I have FastQ data which was basecalled with Guppy 3.2.10 (PromethION Release 19.12.9).

There is no exact match regarding Medaka model and Guppy 3.2.10 as I can see (at least according to Medaka model names).

1) Is Medaka model `r941_prom_high_g303_model.hdf5` the correct/best one if basecalling was performed with high accuracy model of Guppy 3.2.10 (Flowcell was 9.4.1 and Platform was PromethION)?

2) Is there no Medaka model for 3.2.10 since there were no changes in the guppy model from 3.0.3 to 3.2.10 regarding my configuration? Or what is the reason?

**Comment by cjw85** [comment]
See the discussion here: https://github.com/nanoporetech/medaka/issues/156
