### ISSUE TITLE
Medaka Consensus - ModuleNotFoundError: No module named 'tensorflow.keras'

### ISSUE THREAD

**Issue by DDavila10** [nanoporetech/medaka#170]
Hi all,

I am trying to run medaka but I failed run medaka consensus. This is what was displayed.

Checking program versions
This is medaka 1.0.1
Program    Version    Required   Pass     
bcftools   1.10.2     1.9        True     
bgzip      1.10.2     1.9        True     
minimap2   2.17       2.11       True     
samtools   1.10       1.9        True     
tabix      1.10.2     1.9        True     
Aligning basecalls to draft
Removing previous index file /beegfs/group_dv/home/DDavila/genome2_0/long_reads_assembly/Merge_genomes/BC02_SEQ3/raconx2_merged_BC02_SEQ3.fasta.mmi
Removing previous index file /beegfs/group_dv/home/DDavila/genome2_0/long_reads_assembly/Merge_genomes/BC02_SEQ3/raconx2_merged_BC02_SEQ3.fasta.fai
Constructing minimap index.
[M::mm_idx_gen::0.260*1.05] collected minimizers
[M::mm_idx_gen::0.343*1.51] sorted minimizers
[M::main::0.432*1.37] loaded/built the index for 3 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 3
[M::mm_idx_stat::0.453*1.35] distinct minimizers: 726918 (60.82% are singletons); average occurrences: 1.452; average spacing: 5.345; total length: 5641212
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /beegfs/group_dv/home/DDavila/genome2_0/long_reads_assembly/Merge_genomes/BC02_SEQ3/raconx2_merged_BC02_SEQ3.fasta.mmi /beegfs/group_dv/home/DDavila/genome2_0/long_reads_assembly/Merge_genomes/BC02_SEQ3/raconx2_merged_BC02_SEQ3.fasta
[M::main] Real time: 0.469 sec; CPU: 0.625 sec; Peak RSS: 0.054 GB
[M::main::0.105*1.14] loaded/built the index for 3 target sequence(s)
[M::mm_mapopt_update::0.131*1.11] mid_occ = 25
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 3
[M::mm_idx_stat::0.147*1.10] distinct minimizers: 726918 (60.82% are singletons); average occurrences: 1.452; average spacing: 5.345; total length: 5641212
[M::worker_pipeline::347.168*0.76] mapped 65102 sequences
[M::worker_pipeline::404.630*0.76] mapped 10694 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 -x map-ont --MD -t 1 -a -A 2 -B 4 -O 4,24 -E 2,1 /beegfs/group_dv/home/DDavila/genome2_0/long_reads_assembly/Merge_genomes/BC02_SEQ3/raconx2_merged_BC02_SEQ3.fasta.mmi /beegfs/group_dv/home/DDavila/genome2_0/Nanopore_seq3/demultiplex_porechop/BC02.fastq.gz
[M::main] Real time: 404.734 sec; CPU: 309.385 sec; Peak RSS: 1.492 GB
[bam_sort_core] merging from 1 files and 1 in-memory blocks...
Running medaka consensus
Traceback (most recent call last):
  File "/beegfs/group_dv/home/DDavila/.python/3.6.0/bin/medaka", line 8, in <module>
    sys.exit(main())
  File "/beegfs/group_dv/home/DDavila/.python/3.6.0/lib/python3.6/site-packages/medaka/medaka.py", line 643, in main
    args.func(args)
  File "/beegfs/group_dv/home/DDavila/.python/3.6.0/lib/python3.6/site-packages/medaka/prediction.py", line 88, in predict
    from tensorflow.keras import backend as K
ModuleNotFoundError: No module named 'tensorflow.keras'
Failed to run medaka consensus.

thanks a lot for the help

**Comment by cjw85** [comment]
Hi @DDavila10,

Can you give background on how you installed medaka?

**Comment by DDavila10** [comment]
Hi, thanks a lot for the help. 
 I installed medaka using **pip install medaka**

**Comment by cjw85** [comment]
Did you observe any errors when running `pip install medaka`?

As outlined in the README I would suggest installing medaka into a virtual environment when using pip to perform the installation.

**Comment by DDavila10** [comment]
No, issue during the installation.
Thanks for the suggestion. I installed medaka into a virtual environment and now is working!. Thanks a lot for the help :) 👍
