### ISSUE TITLE
Clarify: -v option of medaka consensus will apply vcf variants to input?

### ISSUE THREAD

**Issue by ms-gx** [nanoporetech/medaka#171]
Just to be sure: the `-v` option of `medaka consensus` will already apply the detected variants to the input draft assembly? So I do not have to run any `bcftools consensus` afterwards?

**Comment by cjw85** [comment]
The variants will have already been applied, see here:
https://github.com/nanoporetech/medaka/issues/171

**Comment by ms-gx** [comment]
Awesome, thanks for fast reply and pointing to the actual code! That is convincing ;)
