### ISSUE TITLE
Analyzing available Sars-CoV-2 Nanopore data using Medaka. 

### ISSUE THREAD

**Issue by MauricioMoldes** [nanoporetech/medaka#173]
Dear Nanoporetech Team
Dear Medaka team, 

In the context of the sars-cov-2 viral beacon, https://covid19beacon.crg.eu/ , we are analyzing the available sars-cov-2 Nanopore data, using medaka. 

Issue 1 

In the variant calling results, we are observing large SNP's, such as for example :

REF : CTAGTTGTAATGGCCTACATTACAGGTGGTGTTGTTCAGTTGACTTCGCAGTGGCTAACTAAC
ALT :  GCAGTTGTAATGGCCTACATTACAGGTGGTGTTGTTCAGTTGACTTCGCAGTGGCTAACTAAC

There seems to be an SNP in position 1,2 (CT GC), however, instead of SNP, we obtain a larger sequence.
Could you elaborate on this issue?

Issue 2 

For Nanopore data, in position 28881, we are have obtained a high-frequency variant.  : 

REF : GGG
ALT :  AAC

We have confirmed this high-frequency variant using other datasets and we obtain 
28881 | G | A
28882 | G | A
28883 | G | C

Why are we obtaining an MNP from medaka, while we were expecting three SNP?

We are enthusiastic about knowing more and working with the medaka team, 
Mauricio Moldes

**Comment by cjw85** [comment]
Hi @MauricioMoldes,

To address your second issue first, medaka reporting 28881 | GGG | AAC is simply an alternative representation to the three SNPs. If I recall correctly the independent representation wouldn't be considered as valid VCF records (at least we had trouble with other tools consuming VCF files that were written like that).

You first issues looks like it may be a bug in medaka. Given the nature of your data I suspect you cannot share it, but it would be useful for us if you could.

**Comment by cjw85** [comment]
Can you confirm how you are performing variant calling with medaka? Are you using `medaka_variant`? this is set up for diploid variant calling. In your issue 1, is there another ALT which specifies a long INDEL?

**Comment by lucacozzuto** [comment]
Dear @cjw85, thanks for your reply. I'm a collaborator of @MauricioMoldes on this project, we are using medaka_variant with the default model.

**Comment by cjw85** [comment]
Using `medaka_variant` is not entirely appropriate. You will want to run something more like:

```
minimap2 ... > alignments.bam
medaka consensus alignments.bam outputs.hdf
medaka variant reference.fasta outputs.hdf variants.vcf
medaka tools annotate variants.vcf reference.fasta alignments.bam variants.annot.vcf
```
This is a sketch of what the ARTIC bioinformatics workflow performs. The last step is optional, it adds statistics on read support for each ALT.

**Comment by lucacozzuto** [comment]
Hi @cjw85, thanks for your kind advice! I found that medaka tools annotate gives me an error:

```
medaka tools: error: argument tool_command: invalid choice: 'annotate' (choose from 'haploid2diploid', 'diploid2haploid', 'clas
sify_variants', 'vcf2tsv', 'homozygous_regions', 'resolve_model', 'is_rle_model', 'rlebam', 'list_models', 'hdf_to_bed')
```
Can you help me on this, please?

**Comment by cjw85** [comment]
That looks like you possibly have an older version. The `annotate` subcommand was added in version 1.0.0 (https://github.com/nanoporetech/medaka/releases).

**Comment by cjw85** [comment]
@lucacozzuto @MauricioMoldes 

Have we reached a resolution here? Is it OK for me to close the issue?

**Comment by leocaserta** [comment]
Hi @cjw85 , you mentioned above that the ideal workflow would be: 
minimap2 ... > alignments.bam
medaka consensus alignments.bam outputs.hdf
medaka variant reference.fasta outputs.hdf variants.vcf
medaka tools annotate variants.vcf reference.fasta alignments.bam variants.annot.vcf 

What if I use medaka_haploid_variant instead of medaka variant? Will I have more accurate results for calling variants on virus genome assemble? 

Thank you

**Comment by lucacozzuto** [comment]
For me, it can be closed. We embed this code in our pipeline and are grateful to the authors :)
