### ISSUE TITLE
Error with v1.4.3.

### ISSUE THREAD

**Issue by damientully** [nanoporetech/medaka#18]
Hi,

I am getting the following error with v1.4.3. Also to use use the flip-flop basecaller from Guppy the model should be called using -m r941_flip not -m r94_flip as suggested. 

> `medaka_consensus -i Run12_all_guppy_v2.2.2.fastq -d Run12_guppy_contigs.fasta -o Run12
> Aligning basecalls to draft
> Found minimap files.
> open: No such file or directory
> [bam_sort_core] fail to open file calls_to_draft.bam
> [M::main::0.003*1.04] loaded/built the index for 1 target sequence(s)
> [M::mm_mapopt_update::0.003*1.02] mid_occ = 3
> [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
> [M::mm_idx_stat::0.003*1.15] distinct minimizers: 1620 (99.94% are singletons); average occurrences: 1.001; average spacing: 5.290
> [samopen] SAM header is present: 1 sequences.
> open: No such file or directory
> [bam_index_build2] fail to open the BAM file.
> Running medaka consensus
> Using TensorFlow backend.
> [E::hts_open_format] Failed to open file calls_to_draft.bam
> Traceback (most recent call last):
>   File "/home/dct7/medaka/bin/medaka", line 11, in <module>
>     sys.exit(main())
>   File "/home/dct7/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 170, in main
>     args.func(args)
>   File "/home/dct7/medaka/lib/python3.6/site-packages/medaka/inference.py", line 381, in predict
>     args.regions = get_regions(args.bam, region_strs=args.regions)
>   File "/home/dct7/medaka/lib/python3.6/site-packages/medaka/common.py", line 218, in get_regions
>     with pysam.AlignmentFile(bam) as bam_fh:
>   File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>   File "pysam/libcalignmentfile.pyx", line 935, in pysam.libcalignmentfile.AlignmentFile._open
> FileNotFoundError: [Errno 2] could not open alignment file `calls_to_draft.bam`: No such file or directory`

Any suggestions?

Thanks,
Damien

**Comment by cjw85** [comment]
Hi,

It appears that alignment of the input reads to the draft sequence is failing. The error:

    [bam_sort_core] fail to open file calls_to_draft.bam

may indicate that the output folder is not writeable. Can you check that the output folder has been created and that it is writeable?

**Comment by damientully** [comment]
Hi @cjw85 Yes the output folder is created but is empty.

**Comment by damientully** [comment]
Ah ha @cjw85 I figured that it was due to the version of samtools that was being used. When I updated to samtools 1.9. it worked fine.

Thanks
Damien
