### ISSUE TITLE
Medaka train without any reference genome

### ISSUE THREAD

**Issue by luqrei82** [nanoporetech/medaka#180]
Hello,
I'm trying to make a consensus of a 3 kb amplicon of the HIV-1 PRRT gene.
Considering the reference might be outdated due to the fast mutation rate, de novo assembly seems to be the most logical way.
Using Canu+Medaka, I was able to get 0.08%-0.55% discordant rate compared with Sanger sequencing.
However, I'm trying to lower this discordant rate by training Medaka.
The walkthrough seems to suggest using a reference genome to obtain the training features. But because I did not use any reference genome, Medaka train failed with this output: 

[12:16:44 - root] The path keras_train exists. Results will be overwritten.
[12:16:44 - DataIndex] Loaded 1/1 (100.00%) sample files.
Traceback (most recent call last):
  File "/home/luqrei/miniconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/luqrei/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 643, in main
    args.func(args)
  File "/home/luqrei/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/training.py", line 66, in train
    args.seed, args.batch_size, threads=args.threads_io)
  File "/home/luqrei/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/training.py", line 225, in __init__
    self.label_scheme = di.metadata['label_scheme']
KeyError: 'label_scheme'

I assume this is because the absence of reference genome.
Is there any way for Medaka train to finish for a completely de novo assembly?

Thanks.

**Comment by mwykes** [comment]
Hi @luqrei82,
A reference genome is needed to train a medaka model. Reads should be aligned to a de novo assembly (the draft) and the reference genome should be aligned to the draft to create training labels. See the [docs ](https://nanoporetech.github.io/medaka/walkthrough.html#training-a-consensus-network)for more information. 
However, I would not train a medaka model using only just 3kb of sequence; there is a risk of overfitting to such a small amount of training data. 
Hope this helps,
Mike

**Comment by luqrei82** [comment]
@mwykes,

Thanks for your answer.
What do you mean with overfitting? What kind of phenomenon can happen if I keep on forcing to train with a short sequence?

**Comment by cjw85** [comment]
@luqrei82 

If you were to train medaka with simply a 3000 bases of unique sequence content within the training data, it is very likely that the algorithm will learn to simply regurgitate the reference sequence which you give it to train from. This is unlikely to be useful.

I'm not sure that we can be of anymore help here, certainly training medaka without a reference is not possible and training from so little data is unlikely to produce meaningful results.
