### ISSUE TITLE
Header contig has no length

### ISSUE THREAD

**Issue by neobernad** [nanoporetech/medaka#182]
**Describe the bug**
When using `medaka_variant` the header item `contig` from the output VCF (round_1.vcf) has no attribute length. We have used the following command:

```bash
medaka_variant -f reference.fa -i alignment.bam -r "chr14:22544787-22549756" -s r941_min_high_g344 -m r941_min_high_g344 -t 16 -d -o "output_folder"
```
That is to say, the header of round_1.vcf has the following contig:
```bash
##contig=<ID=chr14>
```
However, other tools (like some GATK) expect that this contig preserves the `lenght` attribute  (like `sniffles`, `gatk` or `bcftools` do), as in:

```bash
##contig=<ID=chr14,length=107043718>
```

**Logging**
Not applicable.

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: conda
 - OS: Ubuntu 14.04
 - GPU model: No GPU
 - Nvidia driver version: No GPU
 - CUDA version: No GPU
 - cuDNN version: No GPU

**Comment by cjw85** [comment]
Hi @neobernad,

I have created an issue internally to have this fixed.

**Comment by cjw85** [comment]
This has been amended in version 1.1.2, the length attribute should now be present.
