### ISSUE TITLE
Assertion error on medaka tools annotate

### ISSUE THREAD

**Issue by leoisl** [nanoporetech/medaka#183]
Hello,

**Describe the bug**
I followed these commands: https://github.com/nanoporetech/medaka/issues/173#issuecomment-642566213 to perform bacterial WGS variant calling. Everything works fine except the last step, `medaka tools annotate`, where I get an assertion error.

**Logging**
```
medaka tools annotate medaka_variants.vcf ${reference_assembly} nanopore.sorted.bam medaka_variants.annotated.vcf
Traceback (most recent call last):
  File "/usr/local/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/medaka/medaka.py", line 643, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/medaka/vcf.py", line 1093, in annotate_vcf_n_reads
    read_group=args.RG)
  File "/usr/local/lib/python3.6/dist-packages/medaka/vcf.py", line 1150, in get_trimmed_reads
    assert region == region_got
AssertionError
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: `pip3` inside a container (the Singularity recipe can be found here: https://github.com/leoisl/Singularity_recipes/blob/master/Singularity.medaka . You can pull this image with `singularity pull shub://leoisl/Singularity_recipes:medaka` )
 - OS: Ubuntu 18.04 LTS
 - GPU model: No GPU
 - Nvidia driver version: No GPU
 - CUDA version: No GPU
 - cuDNN version: No GPU

**Additional context**
It should be totally reproducible if I could give you the reference and the reads (which I am not sure I can, I can check this). The environment is the singularity image, and these are the exact command lines:
```
    minimap2 -ax map-ont ${reference_assembly} ${nanopore_reads} | samtools view -b - > nanopore.bam
    samtools sort nanopore.bam > nanopore.sorted.bam
    samtools index nanopore.sorted.bam
    medaka consensus --model r941_min_high_g344 nanopore.sorted.bam medaka_consensus_out.hdf
    medaka variant --verbose ${reference_assembly} medaka_consensus_out.hdf medaka_variants.vcf
    medaka tools annotate medaka_variants.vcf ${reference_assembly} nanopore.sorted.bam medaka_variants.annotated.vcf
```

Please tell me if this is a known issue or if it would be better for you to have the reference and reads for reproducibility and debug. I will then check with collaborators.

Thanks a lot for your help

**Comment by cjw85** [comment]
Hi @leoisl, I don't believe this is a known issue. If we could have your data to debug the issue that would be useful. I can provide a private sharing mechanism if required.

@mwykes why is there the assertion in the code? I'm not sure is warranted.

**Comment by mwykes** [comment]
Hi @leoisl,
Could you possible see if installing v1.0.4rc1 resolves the issue? It is availble on pypi so you should be able to install by running `pip install medaka==1.0.4rc1`.

**Comment by leoisl** [comment]
Hello,

sorry for the delay. The assertion error is now gone with version `1.0.4rc1`, but now I get another error:
```
medaka tools annotate medaka_variants.vcf ${reference_assembly} nanopore.sorted.bam medaka_variants.annotated.vcf
Traceback (most recent call last):
  File "/usr/local/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/medaka/medaka.py", line 644, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/medaka/vcf.py", line 1083, in annotate_vcf_n_reads
    read_group=args.RG)
  File "/usr/local/lib/python3.6/dist-packages/medaka/vcf.py", line 1150, in get_trimmed_reads
    region_split=2*region.size))
StopIteration
```

Could you please provide me a way to share you the input files in a private channel?

Cheers

**Comment by mwykes** [comment]
Hi @leoisl, you should receive an email with instructions on how to share input files in a private channel.

**Comment by leoisl** [comment]
Hello,
thanks, I have been running into issues to share the files... and then thought about retrying later... but still having issues:
![image](https://user-images.githubusercontent.com/8397967/89942460-8100ee80-dc14-11ea-8036-4797dea71eff.png)

I could provide you a link to the data if it is easier. Then I'd just need a mail address.

Thanks for the help.
Cheers

**Comment by cjw85** [comment]
@leoisl

I believe this bug has been fixed with the latest released, so I will close the issue. Please repoen if this is not the case.
