### ISSUE TITLE
Ubuntu Conda Run Error

### ISSUE THREAD

**Issue by mpaxhia** [nanoporetech/medaka#184]
I recently installed Medaka using Conda, and when I run the program I receive this error asking for the input -r:

![Ubuntu18 04 Medaka Error](https://user-images.githubusercontent.com/60884899/88689876-08087f80-d0c9-11ea-9ddb-7881f9c1a408.png)

Is there a way to fix this?

Thanks,

mpaxhia

 - Installation method: conda
 - OS: Ubuntu 18.04
 - GPU model: No GPU

**Comment by cjw85** [comment]
Hi @mpaxhia,

Can you please provide the command you have used to run the program?

**Comment by mpaxhia** [comment]
Yep, this is the command I used:

`medaka_consensus -i parentRawReads.fq -d racon2parentFlyeContigs.fasta -o consensus -m r103_min_high_g345`

**Comment by lmarmin** [comment]
Hi, I also encounter a similar issue (`-r must be specified`  message).

The command I used is:

`medaka_consensus -i clstrs_ITS2/reads_to_consensus_250.fastq -d clstrs_ITS2/racon_cl_id_250/consensus.fasta -o clstrs_ITS2/medaka_cl_id_250/consensus.fasta -m r941_min_high_g360`

and got this output:

```
Checking program versions

This is medaka 1.0.3
Program    Version    Required   Pass     
bcftools   1.10.2     1.9        True     
bgzip      1.10.2     1.9        True     
minimap2   2.17       2.11       True     
samtools   1.10       1.9        True     
tabix      1.10.2     1.9        True     
Warning: Output clstrs_ITS2/medaka_cl_id_250/consensus.fasta already exists, may use old results.
Aligning basecalls to draft

mini_align [-h] -r <reference> -i <fastq>

Align fastq/a formatted reads to a genome using minimap2.
    -h  show this help text.
    -r  reference, should be a fasta file. If correspondng minimap indices
        do not exist they will be created. (required).
    -i  fastq/a input reads (required).
    -I  split index every ~NUM input bases (default: 16G, this is larger
        than the usual minimap2 default).
    -f  force recreation of index file.
    -a  aggressively extend gaps (sets -A1 -B2 -O2 -E1 for minimap2).
    -P  filter to only primary alignments (i.e. run samtools view -F 2308).
        Deprecated: this filter is now default and can be disabled with -A.
    -A  do not filter alignments to primary alignments, output all.
    -n  sort bam by read name.
    -c  chunk size. Input reads/contigs will be broken into chunks
        prior to alignment.
    -t  alignment threads (default: 1).
    -p  output file prefix (default: reads).
    -m  fill MD tag.
    -s  fill cs(=long) tag.
    -X  only create reference index files.
    -x  log all commands before running.
    -M  match score 
    -S  mismatch score
    -O  open gat penalty
    -E  extend gap penalty.
-r must be specified.
Failed to run alignment of reads to draft.
````

Running directly the command `mini_align [-h] -r <reference> -i <fastq>` works fine for me.

I also installed with conda on Ubuntu 18.04. Here is the conf file of my environment, in case it is package related: [Env_medaka.txt](https://github.com/nanoporetech/medaka/files/5057617/Env_medaka.txt)

I downgraded to minimap2 v2.11 too (medaka v0.8.1), but I now have a `-i and -r must be specified` when I use the same commandline as above.

I can't find any logfile or way to add details to what is prompted on the screen.

**Comment by cjw85** [comment]
We have not been able to reproduce this issue. As a user on the linked issue has reported that a reinstall has resolved the problem I will close this issue. Please open a new issue if the problem persists with the latest conda package.
