### ISSUE TITLE
Medaka model training question

### ISSUE THREAD

**Issue by gwl2** [nanoporetech/medaka#185]
Dear Medaka-Team,

Thanks a lot for your great work!
I am using Medaka for polishing my bacterial assemblies. From my understanding, it might be a good idea to train the algorithms for my specific needs (->organism), instead of using standard parameters.

However, the whole process is not completely clear to me. I tried to get some input from the ONT forums, but didn't get any comments yet. I hope it's fine to post this question here (otherwise please just delete my post). Are there any best practice recommendations?

I guess, I’d have to re-sequence and analyze a reference strain of the same bacterial species using the MinION, with the same protocol, flow cell, basecaller etc. I plan to use.

1. What coverage do you need? From what I’ve heard, neural networks need huge amounts of data.

2. Do you want to do this for more than a single strain to pick up subtle differences between strains and be less prone against “reference bias”? How many do you suggest?

3. One point in the Walk-through on the Medaka documentation is a bit confusing for me. It seems that the training involves a draft assembly. From my understanding, you optimize the sequences by mapping the reads and the "true sequence (reference)" to the assembly. In this case I'd optimize the polishing for a certain assembler (because assemblies and errors might differ)/pipeline? 

4. Using racon seems to make Medaka less sensitive to the kind of assembler and mapper? (at least that's how I understand the paragraph "origin of the draft sequence" in the Medaka documentation). Ideally with the following parameters:

> Medaka has been trained to correct draft sequences processed through racon, specifically racon run four times iteratively with: racon -m 8 -x -6 -g -8 -w 500 ...

Is this still the case?

5. To sum up, while Medaka might not be overly sensitive to the origin of the draft assembly, nevertheless it might be beneficial to run the exact same pipeline as will be run for the samples in mind (to keep the setting and the training of the algorithm as close as possible?
So in my case will assemble with canu and polish with racon 4 times (with the mentioned parameters), use minimap2 and use this as a training set. (Is that’s what Katuali is gonna do?)

Thanks a lot. These infos might be very useful for a lot biologists like me who are not into these topics.
I could even write a tutorial based on my data to help others with these first steps. 

Thanks a lot for your help!

Best,
Gabriel

**Comment by cjw85** [comment]
Hi,

I will start with your final question first: "is that what katuali is gonna do?" In short yes, katuali is what we use ourselves for training medaka models, it fully automated the training process, a user needs to provide simply basecaller reads and genome reference sequences. Katuali will perform all the necessary alignments, depth filterings, assemblies, medaka training data creation, and validation graphs. This should answer also your first question about best practices.

However, we would not recommend training medaka from a single bacterial strain. This is likely to lead to overtraining such that the generated model is not useful outside of the training set. The models included with medaka are trained from >60 million reference bases (at sequencing depths ranging from 30X to 150X). We have observed over training with around 15 million bases.

**Comment by gwl2** [comment]
Thanks for your answer! 
This means for bacteria with 4 megabases, one would have to resequence roughly 15 strains?!
From your experience, is it worth doing such a training or will your model be already pretty good (as it includes E.coli).
What would be the best training set to cover a large range of bacteria?
Including species with huge differences in G/C content or huge differences in codon bias respectively?
Or would you suggest using Nanopolish for bacteria where no trained model is available.

**Comment by Silverfoxcome** [comment]
> The models provided with medaka are trained from a variety of bacterial genomes and other small model organisms. They encompass a range of GC content. We continue to add more organisms when we can. Selecting a training dataset is a bit of an art form and there are various, sometimes competing, philosophies about how to do so.

Hi!

Following the post, then, it is not so recommended to do the training? 
I'm assembling 2 little chloroplast genomes (I suppose there are similar to bacterial genomes) and I was wondering if I should train medaka for my data to get a better polishing result or use an adecuate model from the list. 

Also, it is mandatory to run racon 4 times before using medaka (1 time), right? 

Thank you so much in advance for the help. I'm pretty new so I'm very grateful for any pointer you could give me.
