### ISSUE TITLE
Best model for MinION data with Guppy 3.6.0

### ISSUE THREAD

**Issue by MaestSi** [nanoporetech/medaka#188]
Hi,
I have MinION data basecalled with Guppy v3.6.0 high-accuracy, and I want to perform diploid variant calling with `medaka_variant`.
I saw that default models for Medaka v1.0.3 are the following:
```
Default consensus:  r941_min_high_g360
Default snp:  r941_prom_snp_g360
Default variant:  r941_prom_variant_g360

```

Would you advise to use r941_min_high_g360 model, due to the device I used to generate my data?
Thanks in advance,
Simone

**Comment by cjw85** [comment]
Variant calling uses different models than consensus calling. The only models we have for diploid variant calling have been trained on data from PromethION flowcells. You will have to use the defaults.

**Comment by MaestSi** [comment]
Thank you,
I also did a quick test and I confirm you were definitely right.
Best,
Simone
