### ISSUE TITLE
Clarification on "consensus_probs.hdf5" Format

### ISSUE THREAD

**Issue by TimD1** [nanoporetech/medaka#189]
I'm trying to use the output HDF5 file `consensus_probs.hdf5` to determine Medaka's confidence about the results of each polished reference position, but I'm a little lost as to how to interpret the data contained within it, and I can't find any documentation online.

The outer organization levels of the HDF5 file make sense: it contains metadata about the consensus caller and model, and the `data` subfolder contains information about each polished 10kbp RaCon chunk. But the `positions` matrix contains two columns: `major` and `minor`, which I don't understand. `major` appears to refer to a specific genome position, and `minor` counts how many times that position appears in the matrix (does that mean any position where `minor>0` contains an insertion? The corresponding `label_probs` matrix obviously contains probabilities for each position, but the encoding is unclear since there are 5 columns. Are they A, C, G, T, DEL, or something else?

Additionally, does medaka attempt to polish each reference position, or does it choose only a few based on certain pileup-based statistics?

Thanks in advance for the clarification!

**Comment by cjw85** [comment]
Your description is correct. The `minor` column counts insertions in the pileup of reads against a reference. The row of the table with `minor=0` is the reference column, `minor=1` is the first insertion after the reference position. The length 5 dimension of the matrix is ordered as [DEL, A, C, G, T], see [labels.py](https://github.com/nanoporetech/medaka/blob/master/medaka/labels.py#L328).

The consensus sequence output of medaka is simply the argmax decoding of the `label_probs` matrix; there is no post processing, masking of the outputs, or consideration of the input sequence.

**Comment by TimD1** [comment]
Wow, sounds like my guesses were pretty spot-on. Thanks!

**Comment by TimD1** [comment]
I have one more question @cjw85 : There appears to be an (approximately 500bp) overlap in the chunks that medaka outputs (for example `chromosome:0.0-5978.1, chromosome:5418.4-10851.1, chromosome:10314.0-15859.1'`). You mention that the consensus sequence is simply the argmax decoding of the `label_probs` matrix, but what is done in these overlapping positions?

Since medaka is a uni-directional RNN, I suspect I should trust the calls from the first (lower bp number) region. Since medaka can use multiple threads, I would guess that it calls the genome in chunks (and starts with an overlap to "prime" the RNN hidden state)? So equivalence is not guaranteed, and the early calls in the second region are discarded? Thanks again, I just want to make sure I'm processing this data correctly!

**Comment by cjw85** [comment]
So medaka is in fact a stacked bi-directional GRU RNN. We don't carry over the hidden state from one chunk to the next: partly because of the bidirectional nature and partly because of the complexity it requires in the code.

The overlap is as you guess to mitigate against the possibility of edge effects in the network outputs. In the standard case medaka stitches the chunks together simply by splitting the overlap in half and then processing the outputs as if they had been produced continuously.

The code also has the ability to fall back to using a heuristic to stitch together chunks in the case that (for whatever reason) the feature generation step produces incongruent position arrays. This more complex method isn't triggered for the simple pileup based feature generation, only in some experimental branches where we use different feature (derived from graphs).

**Comment by TimD1** [comment]
Thanks for the clarification, I didn't realize medaka was bi-directional! I'll just split the overlap in half, do my own stitching, and verify that it's equivalent to medaka's output.

**Comment by cjw85** [comment]
By the way, most of what is mentioned above is outlined in this notebook:
https://colab.research.google.com/github/epi2me-labs/tutorials/blob/master/Introduction_to_how_ONT's_medaka_works.ipynb

which runs through the key steps of what medaka is doing, with some parts reimplemented for simplicity of exposition.

**Comment by TimD1** [comment]
That NB is a great reference, pretty much exactly what I was looking for. Thanks!

Is there a link to it from either this repo or the `medaka` documentation? If not, it might be helpful to add.

**Comment by TimD1** [comment]
@cjw85 Could you think of any reason why the simple "split the overlap in half" method adds a 3-400bp insertion every approximately 1,000,000bp? Other than these short regions of disagreement every 1Mbp (I've verified that medaka is correct in these cases), the output of medaka and the basic stitching is identical.

Here's the CIGAR of "split the overlap in half" stitching aligned to "medaka stitching": **997109S** 5045= 418I **995143=** 368I 4117= 472I **999563=** 1D 2= 1D 3= 2X 2= 1X 5= 1X 1= 1X 2= 1X 1= 1I 5= 3D 6= 2150545S

Here's the code I'm using:
```
def get_consensus(hdf5_filename):                                                                                 
                                                                                                                  
    # sort regions in HDF5 file by chromosomal position                                                           
    hdf5_file = h5py.File(hdf5_filename, 'r')                                                                     
    regions = [ r for r in hdf5_file['samples']['data'] ]                                                         
    starts = []                                                                                                   
    for r in regions:                                                                                             
        pos = re.search('chromosome:(.*)-(.*)', r).group(1)                                                       
        starts.append(float(pos))                                                                                 
    regions = [r for p,r in sorted(zip(starts,regions))]                                                          
    print(regions)                                                                                                
                                                                                                                  
    # stitch together consensus                                                                                   
    consensus = ""                                                                                                
    for idx, region in enumerate(regions):                                                                        
        probs = hdf5_file['samples']['data'][region]['label_probs'][:]                                            
        start = 0 if idx == 0 else args.chunk_overlap // 2                                                        
        end = args.chunk_size if idx == len(regions)-1 else args.chunk_size - args.chunk_overlap // 2             
        probs = probs[start:end, :]                                                                               
        for chunk_idx in range(probs.shape[0]):                                                                   
            consensus += code[np.argmax(probs[chunk_idx,:])]                                                      
                                                                                                                  
    return consensus 
```

I'm trying to get medaka's confidence for each genomic position in the called consensus, and parsing this file is the only way to do so since medaka outputs in FASTA format.

**Comment by cjw85** [comment]
The chunks stored in the HDF5 file are not guaranteed to be of equal length, hence your algorithm isn't guaranteed to be splitting the overlaps in half. Take a look at [stitch.py#23](https://github.com/nanoporetech/medaka/blob/master/medaka/stitch.py#L23), which calls some of medaka's API for fetching the chunks in order and determining how they overlap.
