### ISSUE TITLE
medaka model for promethION data

### ISSUE THREAD

**Issue by MichelMoser** [nanoporetech/medaka#19]
Hi, i would like to do polishing of genome assemblies with promethION data but am unsure if r94 model is suitable for the data since a different ligation kit and flowcell is used than for minION and gridION. 

Do you have other models or would r94 just work fine? 

Thank you, 
Michel

**Comment by cjw85** [comment]
Hi @MichelMoser 

We do not have models specific to PromethION data. The included models will likely work reasonably well but they have not been tested under such circumstances.

**Comment by MichelMoser** [comment]
ok, thank you for the info
