### ISSUE TITLE
False negative InDel vs DeepVariant

### ISSUE THREAD

**Issue by husamia** [nanoporetech/medaka#191]
Medaka(1.0.3)_variant does not call real indel for the CYP2D6 *9 c.2615_2617delAAG. For comparison, I used deepvariant with default settings and it calls it. (snapshot) 

![igv_snapshot](https://user-images.githubusercontent.com/13439952/89926140-6f96f280-dbd2-11ea-9f51-b515ae840808.png)

**Comment by cjw85** [comment]
Calling variants from ONT data is an evolving space. At this time we are aware of several classes of INDEL that the medaka variant caller tends to get wrong; we are continually looking to improve the algorithms.

**Comment by cjw85** [comment]
@husamia One thin I noticed in your screenshot is that your read coverage seems really very high: The top-left of the coverage track is indicating up to 126,354.

**Comment by husamia** [comment]
@cjw85 thank you. I used the guide https://davemcg.github.io/post/easy-bam-downsampling/ to downsample to exactly 100X. The indel is still not called. Here is the new screenshot. 
![igv_snapshot](https://user-images.githubusercontent.com/13439952/90048170-206bc300-dca1-11ea-913a-80d9a769d915.png)
