### ISSUE TITLE
Model for Albacore 

### ISSUE THREAD

**Issue by reel-cmd** [nanoporetech/medaka#194]
We would like to use medaka on nanopore data that was sequenced a while ago and basecalled with Albacore. Is there a model compatible with older basecallers? Unfortunately re-basecalling is not an option. 

Thanks!

**Comment by cjw85** [comment]
There are no plans to release a medaka model for Albacore basecallers. I cannot remember precisely but I have a suspicion that the oldest R9.4 medaka model might be compatible with the final Albacore version.
