### ISSUE TITLE
variant vcf files not compatible with IGV

### ISSUE THREAD

**Issue by seanrj-conagen** [nanoporetech/medaka#197]
I'm not sure if this an issue with medaka or with IGV, but I'm not able to use IGV visualize the .vcf files produced by medaka.
Is there some option I can set to make it work?
Is there a different viewer that works better?

I used medaka 1.0.3

Here's the code:
```bash
    minimap2 --MD -a -x map-ont -t 16 contigs.fasta reads.fastq  > minimap.sam
    
    # Convert to bam file
    samtools view -bS minimap.sam > mapped.bam

    # Sort the bam file
    samtools sort -o mapped.sorted.bam mapped.bam

    # create an index file
    samtools index mapped.sorted.bam

    # run medaka
    medaka_variant -m r103_min_high_g360 -s r103_min_high_g360 -t 16 -f contigs.fasta -S -i mapped.sorted.bam -o medaka_variant
```

**Comment by cjw85** [comment]
Hi @seanrj-conagen,

Apologies for the lack of response here. Can I ask what version of IGV you are using. This is not something we have noticed.

**Comment by seanrj-conagen** [comment]
Hi,

I just double checked, and it seems like it's still an issue.

IGV version 2.8.9

Relevant part of the error message is:
`The provided VCF file is malformed at approximately line number 26: The VCF specification requires a valid (non-zero length) info field, for input source:medaka_variant/round_1.vcf`

**Comment by cjw85** [comment]
Medaka version 1.1.2 now include a length attribute in the contig headers.

Contrary to the error message from IGV these are not mandated by the specification:
_"It is recommended for VCF, and required for BCF, that the header includes tags describing the contigs referred to
in the file. The structured contig field must include the ID attribute and typically includes also sequence length,
MD5 checksum, URL tag to indicate where the sequence can be found, etc."_
