### ISSUE TITLE
Correct model to polish my assembly with Oxford Nanopore PromethION data

### ISSUE THREAD

**Issue by Silverfoxcome** [nanoporetech/medaka#200]
Good day :)

I'm using data from the accession SRX5632308 from the SRA database. It comes from Oxford Nanopore PromethION that was uploaded in 2019. That's is all I know about it. I assembled 2 little chloroplast genomes from it and I want to polish my assemblies. 

The SRA database doesn't say anything about the version of guppy that was used. Due to this being from 2019, I was thinking of using r941_prom_hac_g303 or r941_prom_high_g303. But I'm not sure. Perhaps r941_prom_high_g360 should be better? 

Please, can you give me some pointers?

Thanks a lot in advance.

**Comment by cjw85** [comment]
Without knowing the basecaller that was used it is impossible to advise you any better than your quite reasonable guesses. All I can see from the SRX is that the data was generated on a PromethION.

Apologies.
