### ISSUE TITLE
Medaka model training for chloroplast genomes and run racon before running medaka?

### ISSUE THREAD

**Issue by Silverfoxcome** [nanoporetech/medaka#201]
Good day!

Following the post #185, I was wondering if it is not recommended to do the Medaka model training?

I'm assembling 2 little chloroplast genomes from maize (I suppose there are similar to bacterial genomes) and I was wondering if I should train medaka for my data to get a better polishing result or use an adecuate model from the list.

Also, is it necessary to run racon 4 times before using medaka (1 time or how many)?
I have seen a few people doing this in some posts and also read that racon was used 1 time before medaka in https://nanoporetech.github.io/medaka. 

Thank you so much in advance for the help. I'm pretty new to working with nanopore data so I'm very grateful for any pointer you could give me.

**Comment by cjw85** [comment]
Training new models is a fairly large undertaking, and requires careful consideration. It is not something that can be undertaken lightly, or is generally necessary to undertake.

Running racon once should be sufficient.

**Comment by cjw85** [comment]
@Silverfoxcome 

I trust that the above has answered your questions, since you have not replied I will close this issue.
