### ISSUE TITLE
medaka tools list_models and tools medaka tools resolve_model take up significant run time

### ISSUE THREAD

**Issue by christopher-vollmers** [nanoporetech/medaka#203]
Hi,

We are running ~200,000 small jobs (1-5kb of sequence each) of medaka and it looks like simply getting the list of available models and checking the one you enter take up a significant chunk of the runtime for each job. We can't install this from source (unsurmountable dependency issues with libssl-dev) otherwise I would have disabled those checks and simply hardcoded the model. Is there a reason the medaka tools take so much time? They take about 2 second on the command line which seems long and really adds up.

Any suggestions to get around that?

Best,
Chris

**Comment by cjw85** [comment]
I believe this startup is simply python being slow, specifically the `argparse` module seems tardy (checkout how long `medaka --help` takes.

I'm going to take a guess that your use case is related to R2C2? There's a somewhat hidden program in medaka: `medaka smolecule` that might be appropriate for your needs. This takes either multiple .fasta files with the subreads, or a single file with judiciously named subreads and creates consensus sequences by:

1. orientating reads
2. POA consensus 
3. medaka consensus.

The code is [here](https://github.com/nanoporetech/medaka/blob/dev/medaka/smolecule.py), I think its changed a bit on that branch from the release version (though the [prerelease packages](https://pypi.org/project/medaka/1.1.0a3/#files) on PyPI are built from it).

Note, if you want to build your own program from the medaka API that's easily done. The `smolecule` program should give you a sketch of how to do this. If you want to resort to hacking the main code you can use the `build-wheels.sh` program in combination with docker to build packages (from memory, something like):

    docker run --rm -v `pwd`:/io quay.io/pypa/manylinux2010_x86_64 /io/travis/build-wheels.sh

**Comment by christopher-vollmers** [comment]
Thank you so much for that information. Yes, we are analyzing R2C2 reads in our Mandalorion tool. It turns out the medaka_consensus isn't compiled so I could edit it in the pip installed version. I managed to hard code the model, get rid of the model check, rle check and align parameter check. That shaved of a bunch of time. Not a universal solution but was good practice to get to know medaka.

Good to know you implemented that function. I'm going through the code right now. We tried using Medaka in C3POa for raw reads to consensus read processing but it was just too slow. Especially considering we are dealing with >10 million reads in a data set these days. 
Have you timed this out against or compared it to C3POa at any point?

**Comment by cjw85** [comment]
We have not compared to C3POa. I haven't benchmarked the `medaka smolecule` command, I suspect the bottleneck would be in the POA-based consensus rather than the medaka's RNN consensus. For your chemistry `smolecule` could be made faster by shortcutting the orientation step, and just assume the subreads are aligned parallel to each other.

**Comment by christopher-vollmers** [comment]
To speed up the poa step, I recommend looking at abpoa which I believe has a python library. It's much faster than any other poa implementation we have tried and produces very similar results.

**Comment by cjw85** [comment]
Thanks, we'll give it a go.

**Comment by cjw85** [comment]
We've released v1.1.0 which includes the code I linked above (and is now available in the master branch). I will close this issue since you use case is outside of the scope of the `medaka_consensus` script.
