### ISSUE TITLE
Using medaka_variant for calling small regions of interest

### ISSUE THREAD

**Issue by teem123-byte** [nanoporetech/medaka#204]
Hi, 

We are running a pipeline that currently maps small regions (<2000 bp) to illumina shortread data and are subsequently passing that onto bcftools for variant calling. We wanted to switch to ONT reads because of its many known advantages, but we wanted to know if it is possible to use medaka's variant caller on these small "consensus" regions of interest  and conduct a long-read pile up to determine if there is variance as opposed to its use as an error correction tool.

Thanks

**Comment by cjw85** [comment]
Medaka contains two workflows for variant calling: `medaka_variant` and `medaka_haploid_variant`. The first is specialized for calling variants in human samples, whereas the latter is more appropriate for ploidy-1 samples.

**Comment by cjw85** [comment]
@teem123-byte 

I trust that the above answers your question, since you have not responded I will close this issue.
