### ISSUE TITLE
Generating a model for the Flongle

### ISSUE THREAD

**Issue by DewBudd** [nanoporetech/medaka#206]
We are switching to using the Flonglefor smaller runs and I have noticed that there are more differences (indels mostly) between the consensus sequence medaka produces and the reference for the Flongledata than the MinION data on the same samples. 

Is this a problem with the medaka model being for a MinION and not a Flongle? Should I train a new model? I know it is a big undertaking so I was hoping you could suggest a better model that is already available. 

I have been using r941_min_high_g360 for data generated from pore type: 9.4.1, device: Flongle to the MinION via and adaptor, basecaller variant: high, version: 4.0.9.

**Comment by cjw85** [comment]
The MinION is the best model I can suggest. I will raise an internal issue to train a model for Flongle.

**Comment by Marcio-Co** [comment]
Hi,
I was wondering if this issue has been addressed/solved? I am currently trying to polish a bacterial genome assembly for which the DNA was sequenced on a MinION MK1C using a FLONGLE (FLO-FLG001). Basecalling was performed using the High-accuracy model with Guppy 6.2.7.

Thanks in advance
