### ISSUE TITLE
Failed to stitch consensus chunks. medaka: error: unrecognized arguments: --jobs

### ISSUE THREAD

**Issue by igorantoshechkin** [nanoporetech/medaka#210]
I am using medaka 1.1.1 to polish racon-polished flye assembly, but getting the following error at the stitch stage:
...
[15:32:28 - Sampler] Took 0.00s to make features.
[15:32:36 - PWorker] All done, 0 remainder regions.
[15:32:36 - Predict] Finished processing all regions.
Using medaka stitch to create consensus.
usage: medaka [-h] [--version]
              {compress_bam,features,train,consensus,smolecule,consensus_from_features,fastrle,stitch,variant,snp,tools}
              ...
medaka: error: unrecognized arguments: --jobs
Failed to stitch consensus chunks.

It looks like stitch command uses --threads option, while medaka_consensus batch script, which is what I'm using, uses --jobs instead. I was able to run stitch manually to generate consensus, but I thought I'd let you know.

medaka was installed using conda:
conda create -n medaka -c conda-forge -c bioconda medaka

It's running on Debian Linux.

**Comment by cjw85** [comment]
Thanks for notifying us, we will correct this shortly.

**Comment by cjw85** [comment]
This is fixed in version 1.1.2/

**Comment by igorantoshechkin** [comment]
Thanks!
