### ISSUE TITLE
Information about the workings of Medaka

### ISSUE THREAD

**Issue by DeanH10** [nanoporetech/medaka#211]
Hello, I am currently trying to create my own Medaka models. I would like to have a deeper understanding of the workings of Medaka, specifically the neural network. Would you be able to direct me to the papers which you used to come up with Medaka? Or some other information sources which could help me understand the workings of Medaka?
I have read your documentations but it remains quite unclear to me what you specifically use and how it works in general
I would greatly appreciate your help!

Cheers,
Dean

**Comment by cjw85** [comment]
This notebook may be of use to you:
https://colab.research.google.com/github/epi2me-labs/tutorials/blob/master/Introduction_to_how_ONT's_medaka_works.ipynb

There are no papers describing medaka; the methodology used was conceived without reference to any previous work.

**Comment by DeanH10** [comment]
This looks like a good  starting point thanks!
