### ISSUE TITLE
VCF Formatting Error

### ISSUE THREAD

**Issue by phspo** [nanoporetech/medaka#213]
hi,

we are using medaka in the context of the artic pipeline and noticed that using the latest iteration of the pipeline which uses the conda package of medaka in version 1.0.3 we get vcf files that cause issues with other tools, specifically vcfpy.

the vcfs contain the header line:

`##INFO=<ID=PH,Number=G,Type=Integer,Description="PHRED-scaled Probabilities of Phased Genotypes">`

specifying the phred scores as integer, however the values are represented as floats

`NAME	8802	.	C	T	500.0	PASS	DP=400;AC=6,358;AM=36;MC=0;MF=0.0;MB=0.0;AQ=13.08;GM=1;PH=6.02,6.02,6.02,6.02;SC=None;	GT:GQ:PS:UG:UQ	1/1:500.0:.:1/1:500.0`

which causes exceptions in vcf parsing.

our call to run medaka is:

`artic minion --medaka --normalise 200 --threads 4 --scheme-directory ~/artic-ncov2019/primer_schemes --read-file run_name_barcode01.fastq nCoV-2019/V1 samplename`

thank you for your suggestions

**Comment by cjw85** [comment]
I believe this is an issue with [longshot](https://github.com/pjedge/longshot), that is used within the artic pipeline not medaka:

See the file `src/print_output.rs` listed here:
https://github.com/pjedge/longshot/search?q=PHRED
