### ISSUE TITLE
medaka_haploid_variant for large genome

### ISSUE THREAD

**Issue by dcopetti** [nanoporetech/medaka#215]
Hello,
I polished twice my 2.3 Gb assembly of a haploid plant with medaka (1.1.1, PromethION data called with Guppy 4.0.14) and now I see that the newest medaka has an option for haploid genomes. In the documentation it is recommended for bacteria. I wonder if I can apply it to my plant (and maybe to all diploid but highly inbred organisms by extension?) and how I can call the haploid function when doing the `mini_align`, `consensus`, and `stitch` steps separately to improve parallelism. I guess I may need to specify something at the consensus step, but I don't see it.
If it is worth using it, how do I invoke the haploid genome option?
Thanks,

Dario

**Comment by cjw85** [comment]
Hi @dcopetti,

The haploid genome option is for variant calling, if you are doing denovo assemblies then what you have done already is optimal. If you want to call variants with respect to a reference sequence you will want to take a look at this code:
[wrappers.py:84](https://github.com/nanoporetech/medaka/blob/8ce8135edc8c2960d93e0f4b68981a3cd2d88545/medaka/wrappers.py#L84)
which is exposed as the program `medaka_haploid_variant`.

Essentially the process is:
1. Run `racon` with your reads aligned to the reference genome (we affectionately call this scuffing, as opposed to polishing)
2. Run `medaka consensus` using the reads aligned to the consensus sequence from step 1.
3. Run `medaka tools consensus2vcf` to calculate a VCF.

**Comment by dcopetti** [comment]
Oh, that's right! it is even written it is for variants [facepalm]

But this introduces me to a related problem I have:
I would like to know if this haploid (or maybe double haploid? still, no heterozygosity) plant genome assembly is accurate enough, and I have no Illumina reads or another assembly to compare it to.

The assembly was generated with Flye, with two rounds of the built-in polishing. Then I did twice medaka (1.1.1) and now a third round (1.1.2) is ongoing - just in case. The BUSCO score improved from the Flye polishing rounds (90.4 complete) to 93.8 after the first medaka. BUSCO on medaka2 is ongoing. My questions:
- how much should I keep polishing with long reads? Will the plateauing of the BUSCO score be enough?
- is there a way to estimate QV of the assembly basecalls without any external sequencing source? (not that I know of)
- I have ONT reads (Promethion, Guppy 4.0.14) of the parent plant (diploid, heterozygous): would it make sense to compare the SNP calls from the reads of father and son and use the non-50:50 variants of the father as a metric to estimate nt accuracy of the assembly? I wonder if that would make sense at all.
Looking forward for you inputs, thanks!

**Comment by cjw85** [comment]
I would expect multiple iterations of medaka to not produce consistently an improvement. We don't recommend it as being necessary.

Naturally one cannot estimate a quality with respect to an external truth without said truth. However one might think to produce a confidence measure on the consensus call. Unfortunately this is somewhat difficult with the methodology that medaka employs; we have not yet found a way to produce confidence scores (similar to basecall qualities) in usefully robost manner. You may however want to look at simple things like depth of sequencing at different loci to understand better any discrepancies with expectation that you uncover.

Certainly comparing variant calls between the individuals may help to form confidence estimates.
