### ISSUE TITLE
Medaka taking 100s of CPUs

### ISSUE THREAD

**Issue by dcopetti** [nanoporetech/medaka#217]
Hello,
I am running medaka 1.1.2 as three separate steps and the consensus step makes the load mf my machine go up to 1000 or more CPUs. The command I run is
`medaka consensus --model r941_prom_high_g4011 --threads 10 Kyuss_OF1p2_m3.bam single_cons.hdf `
and I get the same behavior also if I use `--regions` with 1/10 of the contigs in each bed file. I was not getting this behavior with 1.1.1, and I am running it on a virtual machine (no GPU). It was installed from conda
```
conda create -n medaka1.1.2 -c conda-forge -c bioconda medaka
conda activate medaka1.1.2
```
the mini align step went fine after I changed the path to a SAMtools version 1.9 (the one in the package is 1.10 and gives an error), but that is not the issue.

This behavior does not happen (in the first 2 or so minutes the load stays at 5-7 instead of shooting up to 100s in seconds) when I run the same command with medaka 1.1.1, installed with pip in a separate environment.

**Comment by cjw85** [comment]
This is a difference between the conda package and the pip package not v1.1.1 and v1.1.2 of medaka.

Can you try setting the environment variable `OMP_NUM_THREADS=1` before running medaka in your conda installation.

**Comment by dcopetti** [comment]
Thanks,
I did this
```
$ OMP_NUM_THREADS=1
$ echo $OMP_NUM_THREADS
1
$ medaka consensus --model r941_prom_high_g4011 --threads 10 Kyuss_OF1p2_m3.bam single_cons_test.hdf
```
and it still goes up to 100s of CPUs within 10 seconds.
I went back to the 1.1.1 installation and I was still able to complete the polishing - besides the haploid_variant pipeline, what were other changes in this 1.1.2 version?

**Comment by cjw85** [comment]
@dcopetti 

I've done a bit of digging, can you try:

    export TF_NUM_INTEROP_THREADS=2
    export TF_NUM_INTRAOP_THREADS=1

On my test machine these make medaka run near optimally without consuming CPU resource needlessly.

**Comment by dcopetti** [comment]
it definitely works!
```
$ export TF_NUM_INTEROP_THREADS=2
$ export TF_NUM_INTRAOP_THREADS=1
$ echo $TF_NUM_INTRAOP_THREADS
1
$medaka consensus --model r941_prom_high_g4011 --threads 10 Kyuss_OF1p2_m3.bam single_cons_test2.hdf
```
it did not shoot to 100s of threads right away like it was doing before. 
Thanks for digging around!

**Comment by lbal-biomat** [comment]
Hi,
I'm having the same problem with medaka 1.2.1, installed from conda. If I run the command with the `-t` flag, it takes every thread on my machine. If I run the command without the flag, it takes 16 full threads instead of 1 as it should by default. I tried with
```
export TF_NUM_INTEROP_THREADS=2
export TF_NUM_INTRAOP_THREADS=1
OMP_NUM_THREADS=1
```
as mentioned above but it was the same.
