### ISSUE TITLE
Medaka model for guppy 2.3.7

### ISSUE THREAD

**Issue by utrivedi** [nanoporetech/medaka#218]
Hi,
I am analysing some old data which was basecalled with guppy 2.3.7. I have asembled the data and now trying to polish it with Racon and medaka (version 1.1.2). However, I wonder which model should I use with while running medaka_consensus? I will be grateful if you could provide any advise regarding this matter? 
Many thanks.

**Comment by cjw85** [comment]
Medaka removed models for older versions of Guppy in version 0.9.0. If you install version 0.8.2 of medaka there will be a model for Guppy 2.3.5.

However we would strongly advise that you find the original .fast5 files from your experiment and perform basecalling with the latest version of Guppy, you will obtain more accurate results.

**Comment by utrivedi** [comment]
Thank you for your prompt response. Unfortunately, I haven't got any fast5 files.  I will check out medaka 0.8.2.
