### ISSUE TITLE
ModelStore exception <class 'AttributeError'> on running medaka consensus

### ISSUE THREAD

**Issue by Koeng101** [nanoporetech/medaka#222]
**Describe the bug**
When attempting to run the consensus on a sequence, I get a `ModelStore exception`. When I checked the location of the model, it looked like it was there, so it isn't missing from the system. Overall, the medaka consensus 

**Logging**
Command:
`medaka_consensus  -d n.fa -o consensus -t 2 -m r941_min_high_g360 -i sequencing_data/20201017_2208_MN33517_AEI192_8c5ab6e7/fastq_pass/*`

Exception:
```
[09:27:20 - ModelStore] filepath /usr/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5
[09:27:21 - ModelStore] ModelStore exception <class 'AttributeError'>
Traceback (most recent call last):
  File "/usr/bin/medaka", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/medaka/medaka.py", line 669, in main
    args.func(args)
  File "/usr/lib/python3.8/site-packages/medaka/prediction.py", line 147, in predict
    model = model_store.load_model(time_steps=args.chunk_len)
  File "/usr/lib/python3.8/site-packages/medaka/datastore.py", line 78, in load_model
    model.load_weights(self.filepath)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 1266, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 659, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
Failed to run medaka consensus.
```

```
This is medaka 1.1.3
Program    Version    Required   Pass
bcftools   1.11       1.9        True
bgzip      1.11       1.9        True
minimap2   2.17       2.11       True
samtools   1.10       1.9        True
tabix      1.11       1.9        True
```

**Environment (if you do not have a GPU, write No GPU):**
 - pip installed 
 - OS: Arch Linux
 - No GPU

**Additional context**

**Comment by cjw85** [comment]
Hi @Koeng101,

It looks to me like you have installed medaka in your root environment? We would not recommend doing this, and instead use a virtual environment to allow better dependency management. The issue above appears to be with Tensorflow and not medaka per se; further I suspect you have installed version 3.0.0 of h5py installed. Can you report the output of:

    pip freeze

Further can I ask how you have installed medaka? Medaka depends on tensorflow 2.2.0 which itself depends on h5py <2.11.0, so what I have described above should not happen if you have followed the installation instructions of the README.

**Comment by aawgit** [comment]
I believe this is caused by the release 3.0.0 of h5py. There is a pull is a pull request for that [here](https://github.com/h5py/h5py/pull/1734). Also, the same issue is posted [here.](https://github.com/h5py/h5py/issues/1732).

**Comment by cjw85** [comment]
@aawgit An installation of medaka according to the instructions in the README would not result in h5py 3.0.0 being installed. So although I agree this is likely the cause of the @Koeng101's issue, I don't quite understand how they have arrived at the situation that they are in.

**Comment by aawgit** [comment]
Apparently Tensorflow installs h5py latest version as one of its dependencies. I faced the same issue in one of my projects which uses Tensorflow.

**Comment by Koeng101** [comment]
@aawgit is correct, that seems to be the issue. h5py 3.0.0 is installed, even if I directly followed the pip install instructions on the README. I get the following error when I run "pip install medaka" in a fresh virtual environment. 

```
tensorflow 2.2.0 requires h5py<2.11.0,>=2.10.0, but you'll have h5py 3.0.0 which is incompatible.
```

However, if I just downgrade h5py manually with `sudo pip3 install -Iv h5py==2.10.0`, this fixes the problem!
