### ISSUE TITLE
SNP calling in regions and phase blocks

### ISSUE THREAD

**Issue by dcopetti** [nanoporetech/medaka#224]
In the meanwhile I did some testing with the `g360` models:
`medaka_variant -f scf1-10.fa -o r12-1 -s r941_prom_snp_g360 -m r941_prom_variant_g360 -t 10 -p -r 'OF1p3c_SSc_Bd_SSc_all_1:320000-520000' -i file.bam`
but I am having a problem specifying more than one region. with the example above it works (single region), with two specified as 
`-r 'OF1p3c_SSc_Bd_SSc_all_1:320000-520000' -r 'OF1p3c_SSc_Bd_SSc_all_1:770000-970000'`
it gives finds SNPs only in the region listed first (I tested both orders), and with 
`-r 'OF1p3c_SSc_Bd_SSc_all_1:320000-520000 OF1p3c_SSc_Bd_SSc_all_1:770000-970000'`
it says
`whatshap.vcf.VcfNotSortedError: VCF not ordered: OF1p3c_SSc_Bd_SSc_all_1:465338 appears before OF1p3c_SSc_Bd_SSc_all_1:399998`
What is the correct way to specify more than one region? is there an advantage in having more than one in a command, or rather better having a separate `medaka_variant` run for each region?

Looking at the result of the first region, I see that there are many more SNPs than with the 10x data (top vcf)
<img width="736" alt="Capture" src="https://user-images.githubusercontent.com/13842014/98171526-29f77680-1ef0-11eb-91da-6161d9a5ad60.PNG">

[black: scf gap; 1-x vcf; pink: 10x haplotype block; green: region of interest; medaka vcf; pale blue: medaka haplotype block; file.bam]
I am surprised by the much higher amount of SNPs that I get with the ONT data, I wonder if the phased haplotypes will be accurate then. I thought `round_1_hap_*.vcf` files could be of any help, but I can't figure out the encoding for e.g. to create a pseudoreference from them.
Looking forward for your thoughts

**Comment by cjw85** [comment]
I believe I have answered your preliminary questions on the other issue.

With regard to the SNP calling your alignments look very noisey judging by the colours in the coverage track, more so than might expect. The coverage looks fairly patchy which isn't going to help matters: we would recommend doing variant calling with at least 40x, if not 60x.

**Comment by dcopetti** [comment]
Thank you for your comments,
I noticed the patchiness as well, but I can't explain it. The reference was produced with PromethION reads (Guppy 3.0.3) assembled with Flye (3 internal polishing rounds) and 2 rounds of medaka. The reads I aligned here are the same used for the assembly but in the meanwhile they were re-basecalled with Guppy 4.0.14, they have mean accuracy (BLASTN ID) of 88.2%, median 91%. The bam file in this image above was just for one of the four files I have, the regions I am working on have >50x coverage. 

After the alignment with minimap2 I did:
`medaka_variant -f scf1-10.fa -o r1-1 -s r941_prom_snp_g360 -m r941_prom_variant_g360 -t 10 -p -r 'OF1p3c_SSc_Bd_SSc_all_1:320000-520000' -i alignment.bam`
then assigned a phase tag to each read based on medaka's phase blocks
`whatshap haplotag -o Sscf1_haplotagged.bam --reference genome.fa --ignore-read-groups Ssc_1_1_round_1_phaseds.vcf.gz alignment.bam`
visualized on IGV (color by tag: HP) and I see the two groups of reads. 
![region1](https://user-images.githubusercontent.com/13842014/98465940-aa59f800-21cc-11eb-8b79-7a7a421d535d.jpg)
<img width="639" alt="Capture2" src="https://user-images.githubusercontent.com/13842014/98465960-ce1d3e00-21cc-11eb-876f-fed683563d41.PNG">
<img width="641" alt="Capture3" src="https://user-images.githubusercontent.com/13842014/98465963-d1b0c500-21cc-11eb-9772-d0747f3d678d.PNG">

however, I see that not all 10x SNPs are found with the raw ONT reads (OK, acceptable), but especially that the phasing (sorting by base at the leftmost SNP above) is not consistent along the read. 

Do you have any explanation on why I see so many mismatches that do not resemble SNPs from the medaka_variant part? I will ask to the whatshap developers too, regarding the phasing of course.

**Comment by cjw85** [comment]
@mwykes Can you pick this up please?

**Comment by mwykes** [comment]
Hi @dcopetti,

<Do you have any explanation on why I see so many mismatches that do not resemble SNPs from the medaka_variant part?>

The final SNP calls in medaka are calculated separately on each haplotype. Any problems with phasing could mean that reads supporting a heterozygous SNP might not be well partitioned by haplotype. If medaka sees a mix of reads on each haplotype it may not call the SNP. It might be worth taking a look at the SNPs in round_0_hap_mixed_unphased.vcf as these to not rely on phasing. 

If you are primarily interested in obtaining long phase blocks, it migh be worth trying [Longshot](https://github.com/pjedge/longshot), which also outputs a bam with haplotype tags.

**Comment by dcopetti** [comment]
thank you @mwykes, I will check it out!

**Comment by lssb** [comment]
Have you found the correct way to specify more than one region? Please.

**Comment by lssb** [comment]
> Have you found the correct way to specify more than one region? Please.

I checked the source code. They just transfer the region argvs to `samtools view` program.  So it will work with `-r "region1 region2"`
