### ISSUE TITLE
medaka smolecule method versus consensus?

### ISSUE THREAD

**Issue by nextgenusfs** [nanoporetech/medaka#226]
I'm working on a problem where I've "binned" amplicon reads together and then generating error-corrected output from the binned reads. My first approach was to use `pyspoa` to generate consensus sequence and then use the binned FASTQ ONT reads to error correct the spoa consensus with the `medaka_consensus` wrapper.  

I see there is a mostly undocumented `medaka smolecule` script that likely seems to be doing something similar. Is there any difference in these two approaches?  

The help menu isn't quite clear on what the input is, is it a directory containing FASTA files?  Is FASTQ not supported?
```
$ medaka smolecule -h
usage: medaka smolecule [-h] [--debug | --quiet] [--batch_size BATCH_SIZE] [--chunk_len CHUNK_LEN] [--chunk_ovlp CHUNK_OVLP] [--model MODEL] [--method {racon,spoa}]
                        [--depth DEPTH] [--length LENGTH] [--threads THREADS] [--check_output] [--save_features]
                        fasta [fasta ...] output

positional arguments:
  fasta                 Single-molecule reads, one file per read.
  output                Output directory.

optional arguments:
  -h, --help            show this help message and exit
  --debug               Verbose logging of debug information. (default: 20)
  --quiet               Minimal logging; warnings only). (default: 20)
  --batch_size BATCH_SIZE
                        Inference batch size. (default: 100)
  --chunk_len CHUNK_LEN
                        Chunk length of samples. (default: 1000)
  --chunk_ovlp CHUNK_OVLP
                        Overlap of chunks. (default: 500)
  --model MODEL         Model to use. {r103_min_high_g345, r103_min_high_g360, r103_prom_high_g360, r103_prom_snp_g3210, r103_prom_variant_g3210, r10_min_high_g303,
                        r10_min_high_g340, r941_min_fast_g303, r941_min_high_g303, r941_min_high_g330, r941_min_high_g340_rle, r941_min_high_g344, r941_min_high_g351,
                        r941_min_high_g360, r941_prom_fast_g303, r941_prom_high_g303, r941_prom_high_g330, r941_prom_high_g344, r941_prom_high_g360, r941_prom_high_g4011,
                        r941_prom_snp_g303, r941_prom_snp_g322, r941_prom_snp_g360, r941_prom_variant_g303, r941_prom_variant_g322, r941_prom_variant_g360} (default:
                        r941_min_high_g360)
  --method {racon,spoa}
                        Pre-medaka consensus generation method. (default: spoa)
  --depth DEPTH         Minimum subread count. (default: 3)
  --length LENGTH       Minimum median subread length. (default: 400)
  --threads THREADS     Number of threads used by inference. (default: 1)
  --check_output        Verify integrity of output file after inference. (default: False)
  --save_features       Save features with consensus probabilities. (default: False)
```

Update:  Sorry I clicked the 'bug' report on this issue -- its not really a bug.

**Comment by cjw85** [comment]
Yes, the `smolecule` command runs pyspoa and then the medaka consensus algorithm (it takes care of reverse complementing those reads which need to be when running spoa). The input should be all reads from each amplicon in individual files (alternatively it can be all in one file but you need augment the record headers for this to work). There shouldn't be an issue in providing fastq rather than fasta.

**Comment by nextgenusfs** [comment]
Thanks @cjw85, so the method I implemented is essentially the same I guess? (reads are already oriented and trimmed).

**Comment by gordonrix** [comment]
> The input should be all reads from each amplicon in individual files (alternatively it can be all in one file but you need augment the record headers for this to work).

Could you provide some more info on how this would work / what exactly needs to be changed in the headers? To be clear, I'd like to be able to provide a single file containing all subreads for an amplicon and have the output be the consensus sequence for all the reads in that file. If I have to split everything up into individual files I can but that will take a bit longer and seems unnecessary. Any guidance you can provide will be greatly appreciated

**Comment by cjw85** [comment]
It is assumed that subreads are grouped by read and named with `<read_id>_<subread_id>`. More precisely the per-amplicon ID is take to be anything up to the first `_` in the fastq header.
________________________________

**Comment by gordonrix** [comment]
Thanks! Having some issues with this, I'll open a new thread
