### ISSUE TITLE
medaka consensus generate FASTQ output instead of only FASTA?

### ISSUE THREAD

**Issue by nextgenusfs** [nanoporetech/medaka#227]
Is it possible to generate a FASTQ consensus sequence instead of the default `consensus.fasta` from the `medaka consensus/stitch` method?  I see an option to `--save_features` which seems to suggest it would save the consensus probabilities, so is there a tool to convert those probabilities into FASTQ format?

**Comment by cjw85** [comment]
Outputting a fastq has been contemplated in the past but never implemented as the scores that are output by medaka's neural network tend to be over-confident (this is a common issue with neural networks) and we have not found an adequate manner in which to rejig them to be more informative.

If you want to play with the scores and have time to dig into the code I would suggest starting with: https://colab.research.google.com/gist/cjw85/814605ec4bbfe40c0c5b7e41ef3794fa/introduction-to-how-ont-s-medaka-works.ipynb which explains the output of the network and how it relates to the sequence which is ultimately formed as the consensus.

**Comment by nextgenusfs** [comment]
Thanks @cjw85, I tend to agree the consensus quality scores aren't really super informative (although collaborators requested FASTQ output). Thanks for the link I'll take a look.
