### ISSUE TITLE
medaka is running extremely slowly

### ISSUE THREAD

**Issue by PeterEmmrich** [nanoporetech/medaka#229]
Hello, 
I am running medaka for the first time on my large-ish plant genome and it seems to just be taking forever... I am 17 days in now, and don't know whether to kill it. It still seems to be writing to the HDF file, but extremely slowly. That file is now up to 1.3 Gb, starting with a 19.5 Gb bam-file and a 223 Mb bam.bai.

What is going on here? The SLURM log file only says that medaka_consensus is running, but my error file has now reached 1.1 Gb, filling up with lines like:

Constructing minimap index.
[M::mm_idx_gen::368.750*1.65] collected minimizers
[M::mm_idx_gen::451.233*1.89] sorted minimizers
[M::main::485.892*1.83] loaded/built the index for 2526399 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2526399
[M::mm_idx_stat::488.143*1.82] distinct minimizers: 203115707 (21.33% are singletons); average occurrences: 14.860; average spacing: 5.302
[M::mm_idx_gen::877.996*1.76] collected minimizers
[M::mm_idx_gen::958.464*1.86] sorted minimizers
[M::main::1003.114*1.82] loaded/built the index for 2538963 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2538963
[M::mm_idx_stat::1004.822*1.82] distinct minimizers: 203062764 (21.34% are singletons); average occurrences: 14.863; average spacing: 5.302

Is this related to the chunk size issue other people have reported? What is the expected final size of the .hdf file? That would at least help me estimate how far it has got.

I am running on 16 CPUs, 512Gb memory, no GPU, conda install, medaka 0.11.5

Many thanks,
Peter

**Comment by cjw85** [comment]
The output above is produced while `minimap2` is being run to align reads to the draft genome, this occurs before the any HDF intermediate output files have been opened. If the output looks like the above, it would indicate reads are still being aligned; I would not expect this to take 17 days even for a large genome.

For large genomes with a GPU you should take a look at the [Improving Parallelism](https://nanoporetech.github.io/medaka/installation.html#improving-parallelism) section of the documentation.
