### ISSUE TITLE
GPU not being detected v1.2.1

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/medaka#232]
**Describe the bug**
Hello,
Using medaka v1.2.1 with conda, we are running into a bug where medaka_variant is not detecting our GPUs on our CentoOS 7 cluster.

**Logging**
[17:24:36 - Predict] Reducing threads to 2, anymore is a waste.
[17:24:36 - Predict] It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.
[17:24:36 - Predict] Setting tensorflow inter/intra-op threads to 2/1.
[17:24:36 - Predict] Processing region(s): chr22:1-50818468
[17:24:36 - Predict] Using model: /share/ClusterShare/software/contrib/jamfer/medaka-1.2.1/miniconda-medaka/envs/medaka-1.2.1/lib/python3.8/site-packages/medaka/data/r941_prom_high_g4011_model.hdf5.
[17:24:36 - Predict] Processing 51 long region(s) with batching.
[17:24:36 - ModelStore] filepath /share/ClusterShare/software/contrib/jamfer/medaka-1.2.1/miniconda-medaka/envs/medaka-1.2.1/lib/python3.8/site-packages/medaka/data/r941_prom_high_g4011_model.hdf5

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: conda
 - OS: Cent OS 7
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   32C    P0    51W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1C:00.0 Off |                    0 |
| N/A   29C    P0    54W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:1D:00.0 Off |                    0 |
| N/A   29C    P0    53W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:1E:00.0 Off |                    0 |
| N/A   36C    P0    53W / 300W |      0MiB / 16160MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Additional context**

We have 4 Tesla V100s but when I run
`tf.config.list_physical_devices('GPU')` in python

I get an empty lis [] 

I have a sneaking suspicion that it's our Cuda version.

Any ideas?

Thanks

**Comment by cjw85** [comment]
Although we maintain the conda package we never use it, I would start by looking here: I believe @philres has sucessfully used GPUs with the medaka conda package.

**Comment by Psy-Fer** [comment]
I must say, i went with conda because usually it is meant to be "easier". But so far, it has been anything but easy.

Happy to work with Philipp to get it working, but I might give a regular python venv method a go. It's my usual go to anyway.

Thanks

**Comment by hasindu2008** [comment]
I installed medaka 1.2.1 using the regular pip method inside a venv and it has the same problem.

**Comment by cjw85** [comment]
Using the PyPI package I am more confident in saying that something is up with your GPU libraries. If I recall correctly, the tensorflow PyPI packages require the CUDA 10.1 runtime and cuDNN 7.6.

I've confirmed medaka runs successfully on a system meeting these requirements so will close this issue.

**Comment by Psy-Fer** [comment]
ah..so I guess CUDA 11.0 doesn't work with tf 2.20 which just seems ridiculous. sigh.

I also can't test it with out RTX 3090 setup, as that doesn't work with CUDA 10 at all. lol!

I'll have a think and see if I can come up with a solution with Hasindu

**Comment by asantat** [comment]
I am looking for a solution at the similar situation. Have you any success?
Now I am working around different tf installations.
My workstation setup is CUDA 11, cuDNN 8, RTX 2070.

TF 2.2 compiled for CUDA 11, cuDNN 8 and RT support - without succes
in separate conda env medaka compiled with tf 2.3 - without success
in separate conda env medaka compiled with tf-nightly - without success
with tf 2.4 and with docker images I have not tried yet.

**Comment by davidryderuk2** [comment]
Hi,

I think whoever is responsible for maintaining the tensorflow package in conda is compiling a range of different builds to support different versions of python and different maths libraries. I have managed to install medaka with conda, which appears to be using my graphics card, based on messages in the log, so I thought I would post some instructions here, in case they help anyone else.

**Use conda to install medaka and a version of tensorflow which supports GPUs:**
1. Check the different builds of tensorflow 2.2.0 available through conda:
`conda search tensorflow`

2. Look at the different versions of tensorflow available:

```
tensorflow                     2.2.0 eigen_py36h84d285f_0  pkgs/main
tensorflow                     2.2.0 eigen_py37h1b16bb3_0  pkgs/main
tensorflow                     2.2.0 eigen_py38hfc6e53c_0  pkgs/main
tensorflow                     2.2.0 gpu_py36hf933387_0  pkgs/main
tensorflow                     2.2.0 gpu_py37h1a511ff_0  pkgs/main
tensorflow                     2.2.0 gpu_py38hb782248_0  pkgs/main
tensorflow                     2.2.0 mkl_py36h5a57954_0  pkgs/main
tensorflow                     2.2.0 mkl_py37h6e9ce2d_0  pkgs/main
tensorflow                     2.2.0 mkl_py38h6d3daf0_0  pkgs/main
```

3. Identify a build of tensorflow 2.2.0 which is compiled with support for python 3.6 (or 'py36' for short) and CUDA (or 'gpu' for short). 

4. Create a new environment for medaka making sure to specify the correct build and version of tensorflow to install:

`conda create -n medaka medaka=1.2.3 tensorflow=2.2.0=gpu_py36hf933387_0`

**Comment by cjw85** [comment]
Thanks @davidryderuk2,

What you have above is what I would recommend. We've noticed recently that medaka and Tensorflow 2.3 is and unhappy combination and Tensorflow 2.4 is not available on conda when I last checked. Yesterday we pinned the python version required by the conda medaka package to Python 3.6 as our Tensorflow issues appear compounded by the Python 3.7 and Python 3.8 builds of Tensorflow.
