### ISSUE TITLE
module 'tensorflow.keras.backend' has no attribute 'set_session'

### ISSUE THREAD

**Issue by qingyyyy** [nanoporetech/medaka#233]
**Describe the bug**
Hi I came across this issue when running medaka:

AttributeError: module 'tensorflow.keras.backend' has no attribute 'set_session'
My tensorflow is 2.3.0 version, and I tried to use .compat.v1 to solve the issue, but it seems it didn't work.
**Logging**
Please attach any relevant logging messages.
![image](https://user-images.githubusercontent.com/75665815/101459157-d9ea5480-3972-11eb-80c2-4f5ffa21a379.png)

**Environment (if you do not have a GPU, write No GPU):**
 - conda install
 - Ubuntu 16.04
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by cjw85** [comment]
Medaka is developed with tensorflow 2.2, can you try downgrading your tensorflow to tensorflow>=2.2.0,<2.3.0.

**Comment by qingyyyy** [comment]
> Medaka is developed with tensorflow 2.2, can you try downgrading your tensorflow to tensorflow>=2.2.0,<2.3.0.

Hi thanks for your reply. I installed tensorflow 2.2 in the virtual environment, but it still showed the same error.

**Comment by cjw85** [comment]
Reviewing your screenshot above, the error would indicate you are using an old version of medaka (the more recent versions do not use `K.setsession`. Can you please upgrade medaka to the most recent version (v1.2.1).

**Comment by cjw85** [comment]
Hi @qingyyyy 

I'm going to assume from your other issues that you have resolved this one now?
