### ISSUE TITLE
GPU variant calling - recommeded setup

### ISSUE THREAD

**Issue by RichardCorbett** [nanoporetech/medaka#235]
Hi there,

I am running **medaka_variant** on a GPU server.    I don't see it registering much if any load on the GPUs themselves, but when I run on a server without a GPU I get the message 

> It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.

So perhaps the GPU was being used after all.    Is it recommended to use a GPU for running medaka_variant?        

Also, my estimates are that it will take about 24 hours to run on my GPU server (again - I don't see much if any GPU resource being used).   Is it recommended to split up the genome into chunks and then merge after, or is there parameter estimation that should be done with the whole genome available ?

**Comment by RichardCorbett** [comment]
Runinng the same commands on one machine with a GPU and another without seems to give the same rate of analysis.
My command:
```
/opt/medaka-1.2.0/bin/medaka_variant -f hg38_no_alt_phage_lambda.fa -i PAD78137.sorted.bam -o output.vcf -t 8
```

**Comment by cjw85** [comment]
Hi @RichardCorbett,

The `medaka_variant` script contains a variety of steps using third-party tools. The bottleneck when using a GPU for the medaka steps is typically the running of whatshap. If you are trying to process a whole genome we'd recommend breaking the computation up into sub-regions of the genome and running the script independently on the regions.

We're looking at creating a more productionized version of the workflow implemented by the `medaka_variant` demonstration script.

**Comment by cjw85** [comment]
The `medaka_variant` script at the heart of this issue will soon be deprecated in favour of [Clair3](https://github.com/HKU-BAL/Clair).
