### ISSUE TITLE
Empty VCF not written by medaka_variant when there are no records.

### ISSUE THREAD

**Issue by mike-molnar** [nanoporetech/medaka#237]
Hi,

I am trying to run medaka_variant on whole human genome samples using a snakemake workflow.  I'm breaking it up into regions to make it finish quicker.  If I call variants one chromosome at a time it works, but it takes about 10-12 hours for the larger chromosomes.  For most other parts of the workflow I split the jobs into 10Mb regions, but there are some large regions in the human reference that are all N's, such as the first 10Mb of chr22.  When I run medaka_variant in these regions it reports that there are no records, and that it is writing an empty VCF:
```
[11:51:43 - PWorker] All done, 0 remainder regions.
[11:51:43 - Predict] Finished processing all regions.
+ Running snp calling
- Running medaka snp
[11:51:47 - DataIndex] Loaded 1/1 (100.00%) sample files.
[11:51:47 - SNPs] Processing chr22:1-10000000.
  VCF written to temp_files/phase_split/chr22:1-10000000/round_0_hap_mixed_unphased.vcf.
- First pass vcf has no records, writing empty vcf and finishing.

++ All done.
ls: cannot access '*.gz': No such file or directory
ls: cannot access '*.tbi': No such file or directory
```
Unfortunately, there is no VCF actually written.  There are only three files in the directory: a BAM file, it's associated BAI file, and round_0_hap_mixed_probs.hdf.  The snakmake workflow stops because the expected VCF file is not there.  I at least need an empty VCF file for the workflow to continue.  I would also need the empty VCF to be named the same as what it would be if it worked, which called 'round_1_phased.vcf'.

I could use larger regions to get around the issue, but I want the user to be able to select the size of the regions and I can't guarantee that they will make it large enough to get around this problem.  I'm also making the workflow adaptable to any species, not just the human genome, so adding layers of requirements or blacklist regions so that medaka_variant can work is not really what I would like to do.  Any help would be greatly appreciated.

Thanks,

Mike

**Environment**
 - Installation method: conda
 - Version: medaka 1.0.3
 - OS: Ubuntu 18.04.5 LTS
 - Univa Grid Engine

**Comment by mwykes** [comment]
Hi @mike-molnar,
If I recall correctly, at some point medaka did write an empty vcf, but a user asked that to be changed for reasons related to yours (it's hard to spot real issues if the pipeline fail silently). If you have already chunked up the reference, it would be relatively straight forward to check if a given chunk is completely contained within a stretch of Ns and hence skip such chunks. There are a [number of tools](https://bioinformatics.stackexchange.com/questions/3526/bed-file-with-n-regions-of-grch38-reference/3528) which can generate a bed file of stretches of Ns from a reference, and you could use [bedtools subtract](https://bedtools.readthedocs.io/en/latest/content/example-usage.html#bedtools-subtract) to remove any of your chunks fully contained within a stretch of Ns. This could be generated on the fly just before you run medaka, so need not create any overhead for your users.

**Comment by cjw85** [comment]
Closing this as `medaka_variant` is now deprecated.
