### ISSUE TITLE
medaka run freezes

### ISSUE THREAD

**Issue by PfeiferLab** [nanoporetech/medaka#243]
Hello,

Similar to other users, I encountered the previously reported issue (https://github.com/nanoporetech/medaka/issues/186) when installing Medaka via the bioconda channel. I followed the suggestion to use the PyPI distribution with samtools version 1.9, bcftools version 1.10.2, and minimap2 version 2.17. However, I now encounter a different problem: my job runs for a day or so and then it suddenly stops writing any output. It still shows as "running" on our cluster but i) the logfiles haven't been touched in 5 days (the last stderr was "[Predict] Finished processing all regions."), ii) all allocated cores appear to be idle, and iii) the resulting consensus.fasta is empty (calls_to_draft.bam, calls_to_draft.bam.bai, and consensus_probs.hdf contain data). Any idea what might be causing this issue?

Thank you in advance for your help!
Susanne

**Comment by RaverJay** [comment]
The conda recipe for medaka 1.2.1 is fixed and can use samtools 1.11 now (https://github.com/nanoporetech/medaka/issues/245)

Updating or recreating your environment might fix your problem

**Comment by cjw85** [comment]
@PfeiferLab 

I'm at a loss as to what could be happening here. It sounds like the `medaka consensus` process as finished correctly but that the `medaka stitch` process has not begun at all.

You might like to take the `consensus_probs.hdf` file and run `medaka stitch` on it "manually".

**Comment by PfeiferLab** [comment]
@cjw85: Thank you for your reply! 
I followed @RaverJay's advice and used the newest conda recipe for medaka 1.2.1 with samtools 1.11 which fixed the issue!
