### ISSUE TITLE
Multi-sample variant calling

### ISSUE THREAD

**Issue by Irsan88** [nanoporetech/medaka#248]
It would be very useful for our research if the medaka snp/indel caller allows multiple bam files as input and can do multiple-sample variant calling just like illumina based variant callers can do that (e.g. FreeBayes, BCFtools, GATK). This way we can do comparative mutation analysis, for example determining acquired mutations, present in sample A while not in B or even reconstructing a phylogentic tree (if >2 samples). My current workaround is to do single-sample variant calling, merge the vcf-files and use all positions in the merged VCF file to get a pileup of reference and alternate reads counts for each position.

**Comment by cjw85** [comment]
Hi Irsan,

Thank you for the suggestion. Multi-sample calling is something that we have thought about, but have not yet had the time to investigate. Beyond the independence assumption that you're making in your workaround, there are lots of avenues of research for implementing multi-sample calling within medaka. The current focus with medaka however is to make single sample calling as effective as possible.

**Comment by Irsan88** [comment]
As an intermediate step, maybe doing "naive "multi-sample calling is a
first step. With "naive" I mean just re-applying single sample calling to
multiple samples without leveraging the dependence information. That way
you at least get the pileup information for each sample for each (putative)
variant

**Comment by cjw85** [comment]
As I say, the current focus is on making single sample calling as accurate as possible. We have limited resource to provide tooling for downstream analysis of medaka's calls. What you describe is I believe all possible using samtools and bcftools.

Medaka is supported as a "Research Release" only.

Research releases are provided as technology demonstrators to provide early access to features or stimulate Community development of tools. Support for this software will be minimal and is only provided directly by the developers. Feature requests, improvements, and discussions are welcome and can be implemented by forking and pull requests. However much as we would like to rectify every issue and piece of feedback users may have, the developers may have limited resource for support of this software. Research releases may be unstable and subject to rapid iteration by Oxford Nanopore Technologies.
