### ISSUE TITLE
Guppy 4.x models

### ISSUE THREAD

**Issue by noncodo** [nanoporetech/medaka#249]
Hi Chris! 

I was wondering if guppy 4.4 plays nicely with the r941_min_high_g360_model.hdf5 model? 
Any plans for an update or a model compatibility table? 

Cheers

**Comment by cjw85** [comment]
The default MinION basecalling model in Guppy hasn't been updated since Guppy 3.6, as such `r941_min_high_g360` is still the model to use.

If you are referring however to the bonito-style model support in Guppy 4.4, @iiSeymour can likely provide a different model.

**Comment by cjw85** [comment]
Information on medaka models for bonito-style basecallers can be found here:
https://github.com/nanoporetech/bonito#medaka
