### ISSUE TITLE
medaka_variant is not available

### ISSUE THREAD

**Issue by sharon558** [nanoporetech/medaka#25]
Hi, I installed medaka into /python/Python-3.6.3/bin using:
pip install medaka

I wanted to use medaka _variant to call variants, but I didn't find it in the installed directory:

ls medaka*
medaka  medaka_consensus  medaka_counts  medaka_data_path  medaka_version_report

Did I miss something? 
Thanks in advance!

**Comment by cjw85** [comment]
Hi @sharon558,

`pip` will not by default install pre-release versions. To install the current pre-release you will need to run:

    pip install medaka==0.6.0a2

**Comment by sharon558** [comment]
Thank you that solved the problem.

However I got an error when running:
medaka_variant -r GRCh38_full_analysis_set_plus_decoy_hla.fa -b rel5-guppy-0.3.0-chunk10k.sorted.bam  -m r94 -R chr22 

The reference file and bam file are downloaded from 
https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-genome/rel5.md

[15:11:34 - Feature] Processed chr22:43999000.0-45000000.0 (median depth 34.0)
[15:11:34 - Sampler] Took 3.93s to make features.
[15:11:53 - PWorker] 46.8% Done (23.8/50.9 Mbases) in 532.3s
[15:11:54 - Sampler] Initializing sampler for consensus or region chr22:44999000-46000000.
python3.6: sam.c:1550: **resolve_cigar2: Assertion `k < c->n_cigar' failed.**
python/Python-3.6.3/bin/medaka_variant: line 75: 24999 Aborted                 (core dumped) medaka consensus ${BAM} ${PROBS} --model ${MODEL} --batch_size ${BATCH_SIZE} ${REGIONS} --threads ${THREADS} ${EXTRAOPTS}

From the error message above, it seems there are some bad cigar in the aligned bam? This problem happened to other chromosomes as well. Please let me know if I shall open a separate ticket on this. Thank you!
