### ISSUE TITLE
encountering "samtools index " error when running medaka_haploid_variant

### ISSUE THREAD

**Issue by chunlinxiao** [nanoporetech/medaka#251]
The error message is as below. 

**Describe the bug**
A clear and concise description of what the bug is including the command that you have run.

**Logging**
Please attach any relevant logging messages.

[17:26:55 - ALIGN] Indexing bam
[17:26:55 - ALIGN] samtools index medaka_haploid_variant/calls_to_draft.bam -@ 1
index: invalid option -- '@'
Usage: samtools index [-bc] [-m INT] <in.bam> [out.index]
Options:
  -b       Generate BAI-format index for BAM files [default]
  -c       Generate CSI-format index for BAM files
  -m INT   Set minimum interval size for CSI indices to 2^INT [14]
[17:26:55 - ALIGN] BAM written to medaka_haploid_variant/calls_to_draft.bam

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method :   pypi (pip install)
 - OS: [  CentOS Linux 7 (Core) ]
 

**Additional context**

When I manually created bam index file, saved the index file, and copied back to the working directory, the whole process finished with vcf file being generated  (though mentioning bam.bai index file was created earlier than the bam)

**Comment by cjw85** [comment]
Hi @chunlinxiao,

You appear to have an old version of samtools installed. I would recommend updating.

**Comment by chunlinxiao** [comment]
yes updating samtools cleared that error.  thanks.

But from the log, I noticed "failed call to cuInit: UNKNOWN ERROR " - any idea? 

[17:56:30 - Predict] Using model:  ..../medaka/lib/python3.7/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
2021-02-03 17:56:30.052257: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
[17:56:30 - Predict] Processing 1 long region(s) with batching.

**Comment by cjw85** [comment]
If you are running on a computer without a GPU, this error is expected and can be ignored. You might like to install the `medaka-cpu` package from PyPI which won't display these errors.

**Comment by chunlinxiao** [comment]
I see - yes the computer I'm running is without GPU.

Thank you very much for your quick response and useful help.

**Comment by chunlinxiao** [comment]
just wanted to make sure:

1. the coordinates of the vcf file (consensus_to_ref.vcf) generated by the program "medaka_haploid_varian" are the draft-reference based ;
2. the consensus assembly (consensus.fasta) is really a draft-reference guided assembly, not de novo assembly;
3. If I understand correctly, were you mapping the consensus.fasta to the draft-reference, then using "medaka_variant" to call variants?  I'm trying to check from the log, it seemed not showing the actual command  - can you share?   The reason I'm asking, I may want to try further polishing the consensus assembly using short reads, then using your same program/command to call variants, and see how much the consensus assembly is improved.   Many thanks.

**Comment by cjw85** [comment]
The workflow `medaka_haploid_variant` performs the following:

1) mapping of reads to the reference sequence
2) construction of a reference-scaffolded consensus sequence
3) correction of the consensus sequence via medaka's usual consensus methods
4) alignment of consensus from 3) to reference sequence to calculate variants

The output VCF has coordinates with respect to the reference sequence provided by the user.

From your question 3, it sounds like your primary goal is not infact to calculate variants with respect to an external reference but construct the most accurate de-novo consensus from the read data. For this I would recommend assembly with the Flye assembler followed by correction with the `medaka_consensus` workflow. If you still want to use your short reads at that point I would recommend hypo: https://github.com/kensung-lab/hypo

Please start a new issue to ask new question as it helps other users find questions releated to those that they might have.
