### ISSUE TITLE
wrong chr formatting in vcf files with medaka variant

### ISSUE THREAD

**Issue by PaolaArzuffi** [nanoporetech/medaka#253]
Hello, 

I am running the` artic minion --medaka` command on a Debian machine within the artic-ncov2019 enviroment. 

```
run artic minion --medaka --normalise 200 --threads 8 \
    --scheme-directory ../primer_schemes \
    --read-file $read_file $scheme \
    $prefix >>$log_file 2>&1 \
```

I have noticed that this command fails because of a different format between the vcf and the bam files: 

```
2021-02-05 14:29:54 Reading potential variants from input VCF...
WARNING: Potential variant VCF contains contig b'MN908947.3' not found in BAM contigs.
error: Error reading potential variants VCF file.
caused by: Error accessing tid from chrom2tid data structure
```

All the vcfs generated by medaka_varianta have the b'MN908947.3' formatting: 

```
##fileformat=VCFv4.1
##medaka_version=1.0.3
##contig=<ID=MN908947.3>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Medaka genotype.">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Medaka genotype quality score">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
b'MN908947.3'	55	.	AGATC	CTTTAAAA	0.131	PASS		GT:GQ	1:0
b'MN908947.3'	62	.	TTCTCT	AAAAAAAAAAAACCCAAAAAAA	0.302	PASS		GT:GQ	1:0
b'MN908947.3'	69	.	AA	CTTT	0.076	PASS		GT:GQ	1:0
b'MN908947.3'	72	.	GAACTTT	CCCTTAAAAAAAAAAAA	0.272	PASS		GT:GQ	1:0
```

I was wondering if you noticed this behaviour before or if it's due to something I am not doing correctly. 

Many thanks
Paola

**Comment by cjw85** [comment]
Hi @PaolaArzuffi,

You are better off asking the Artic project about this. We have never seen this behaviour in medaka when it is used outside of Artic.

**Comment by PaolaArzuffi** [comment]
Hello @cjw85, 

cheers, will ask over there. 

Thanks
Paola
