### ISSUE TITLE
Can I use Medaka to determine gene copy number?

### ISSUE THREAD

**Issue by mlosilla** [nanoporetech/medaka#254]
Hi,

Thank you for providing and supporting Medaka.

I am studying one gene duplication and I was wondering if I could use medaka to determine how many copies of the gene are present in each of my samples. This gene is ~2000bp, and I amplicon-sequenced it with ONT, so all reads completely span the gene. My samples were barcoded so there are reads from only one individual in each analysis.

Although all the species I am looking into have diploid genomes, my target gene may be present in one, two, three (more?) copies in each species. Hence, for the purposes of this gene, they could be considered as of unknown ploidy.

My goals are 1) to figure out how many copies of my target gene are there in each sample, and 2) to get a consensus sequence for each copy.

Do you think medaka could be applicable here? Potentially useful options I have thought about are:

medaka smolecule to generate a consensus sequence
medaka_haploid_variant: Is there a limit on how many haplotypes it can find?
medaka_variant: If this can use whatshap polyphase, I could do several runs with different ploidy values (I plan to explore using whatshap directly as well)

Any thoughts or suggestions are appreciated

Thank you
Mau

**Comment by cjw85** [comment]
@mlosilla Thank you for the great question. Medaka might be useful to help solve your questions, but I think it will only be part of the solution.

Medaka is great at finding consensus sequences from groups of reads, once those groups have been estabilished. It doesn't really try to solve the problem of defining which reads it is meaningful to create a consensus sequence from.

Its not clear how to me immediately the best way to do this without knowing more about the repeats you are expecting and how homologous they may be. I'm going to assume that your reads contain only a single copy (i.e. reads don't contain the multiple copies, which would help simplify things); such that you have up to up to N * M distinct copies of the gene, the ploidy multiplied by the copy number per haplotype. For this the polyphase and read tagging functions of whatshap are going to be useful to separate the copies (if they are not strictly identical).

However you would first need to generate candidate variants (differences) between the copies for the phasing to work. The workflow in `medaka_variant` is specialised to the diploid case, so perhaps not applicable to your situation. I think you are going to have to get a bit green-fingered to derive these putative variants to give to whatshap.
