### ISSUE TITLE
GT is not defined in the header

### ISSUE THREAD

**Issue by Sudosundu** [nanoporetech/medaka#257]
bcftools complaining about GT not defined in the annotated vcf

`bcftools filter -Ob -e 'DP<1000' -o filtered.vcf annotated.vcf`

I got the following error

`    FORMAT 'GT' at NC_xxxxx:33 is not defined in the header, assuming Type=String`

There is GT is not defined in the header. What could be the reason? Is it because medaka_haploid_variant already filtered for homozygous variants? Then how can I make bcftools filter to ignore GT? 
medaka version1.2.1

**Comment by cjw85** [comment]
The workflow in `medaka_haploid_variant` is specialised to haploid samples, it will not make heterozygous calls. 

The fact that a reference to `GT` does not appear in the VCF header but does occur in the records is a bug in medaka. This will be fixed in the next release.

**Comment by Sudosundu** [comment]
Is it possible to use bcftools by ignoring this bug? Sorry for the off-topic question.

**Comment by cjw85** [comment]
I believe this issue has been resolved.
