### ISSUE TITLE
DP is not in the header from medaka_variant output

### ISSUE THREAD

**Issue by Sudosundu** [nanoporetech/medaka#258]
After running medaka variant 
`bcftools filter -Ob -e 'QUAL<40 || DP<1000 || GT!="1/1"' -o bc07.filtered.vcf round_1.vcf`

Output:
`[filter.c:2914 filters_init1] Error: the tag "DP" is not defined in the VCF header`

**Comment by cjw85** [comment]
@mwykes

**Comment by mwykes** [comment]
Hi @Sudosund,

medaka does not put a DP field into the vcf by default.

If you want to add this, you can use `medaka tools annotate` to postprocess your vcf to add a DP field.

**Comment by Sudosundu** [comment]
> Hi @Sudosund,
> 
> medaka does not put a DP field into the vcf by default.
> 
> If you want to add this, you can use `medaka tools annotate` to postprocess your vcf to add a DP field.

Can I annotate using` medaka tools annotate` after calling `medaka_haploid_variant`?

**Comment by cjw85** [comment]
You most certainly can! 😄
