### ISSUE TITLE
medaka annotate region_chunks returns list instead of array

### ISSUE THREAD

**Issue by alvinwt** [nanoporetech/medaka#259]
Hi, 

I was trying to annotate medaka called variants and had an error when it was trying to generate the region chunks for annotation. I believe something was happening with the numpy array and it returned region_chunks as a list instead.

medaka tools annotate --dpsp round1.vcf $ref $bam $annotated.vcf

File "/home/ng02/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/vcf.py", line 1143, in annotate_vcf_n_reads
    if region_chunks.size else chunks
AttributeError: 'list' object has no attribute 'size'

I saved the variables as an object and it seems like region_chunks was concat into a flat list instead of having the Region() objects. The chrom_regions variable look intact with Region() objects split by chunksize. 

## region_chunks variable
['chr1', '10107', '510107', ..., 'hs37d5', '34973112', '35473112']

## chrom_regions 
[Region(ref_name='chr1', start=10107, end=249240539),...]

Could you kindly take a look at error and let me know if you need more information? 

Medaka was installed using conda and the versions are listed below:
medaka                    1.2.3            py36hbcc4abb_0    bioconda
numpy                     1.19.5           py36h2aa4a07_1    conda-forge
parasail-python           1.2.4            py36hd181a71_0    bioconda

**Comment by cjw85** [comment]
Hi @alvinwt,

Thanks for reporting this. Looking at the code, I'm not sure why a numpy array is used here and not a plain list. We'll change this. I'm trying to understand why this wasn't picked up in outr testing. 😕

**Comment by cjw85** [comment]
I've just tagged version v1.2.5, this should make its way to PyPI shortly. I believe the issue arises when the input VCF has more than two CHROMs referenced in the header (else the bug isn't triggered). I have fixed the code for this case and amending our testing.

(Note the bioconda build is currently broken (), once v1.2.5 is available on PyPI you should be able to `conda remove medaka`, and `pip install medaka==1.2.4` in your conda environment to test the changes.

**Comment by alvinwt** [comment]
Thanks for taking a look at this @cjw85, it seemed like quite a simple fix to change it to a list. 

It is likely that my reference for alignment might have triggered the bug and it was hg19 with alternative contigs. I'll check again and reinstall the new version of medaka on PyPI.

**Comment by cjw85** [comment]
@alvinwt Please reopen if you continue to have issues.
