### ISSUE TITLE
resolve_cigar2: Assertion `k < c->n_cigar' failed.

### ISSUE THREAD

**Issue by cjw85** [nanoporetech/medaka#26]
However I got an error when running:
medaka_variant -r GRCh38_full_analysis_set_plus_decoy_hla.fa -b rel5-guppy-0.3.0-chunk10k.sorted.bam  -m r94 -R chr22 

The reference file and bam file are downloaded from 
https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-genome/rel5.md

[15:11:34 - Feature] Processed chr22:43999000.0-45000000.0 (median depth 34.0)
[15:11:34 - Sampler] Took 3.93s to make features.
[15:11:53 - PWorker] 46.8% Done (23.8/50.9 Mbases) in 532.3s
[15:11:54 - Sampler] Initializing sampler for consensus or region chr22:44999000-46000000.
python3.6: sam.c:1550: **resolve_cigar2: Assertion `k < c->n_cigar' failed.**
python/Python-3.6.3/bin/medaka_variant: line 75: 24999 Aborted                 (core dumped) medaka consensus ${BAM} ${PROBS} --model ${MODEL} --batch_size ${BATCH_SIZE} ${REGIONS} --threads ${THREADS} ${EXTRAOPTS}

From the error message above, it seems there are some bad cigar in the aligned bam? This problem happened to other chromosomes as well. Please let me know if I shall open a separate ticket on this. Thank you!

_Originally posted by @sharon558 in https://github.com/nanoporetech/medaka/issues/25#issuecomment-464920351_

**Comment by cjw85** [comment]
@sharon558, I've moved this to a new issue.

I do not know for sure, but this might be due to overly longer cigar strings in the BAM (https://github.com/samtools/hts-specs/issues/40). I'm going to download the dataset now and investigate.

**Comment by cjw85** [comment]
Updating medaka to use a newer version of htslib resolves this issue. A new prerelease is available: https://pypi.org/project/medaka/0.6.0a3/.

**Comment by sharon558** [comment]
Thank you @cjw85 ! I'll try the new release!

**Comment by sharon558** [comment]
It works now, but found another error. Will create a new ticket. Thanks!
