### ISSUE TITLE
medaka_consensus errors

### ISSUE THREAD

**Issue by rkimoakbioinformatics** [nanoporetech/medaka#261]
**Describe the bug**

medaka_consensus errors.

**Logging**

>medaka_consensus -i sample_unk/reads_to_consensus_20.fastq -d sample_unk/consensus_reference_20.fasta -o sample_unk/medaka_cl_id_20 -t 1
(...)/miniconda3/envs/py36/bin/medaka_consensus: line 16: 15766 Illegal instruction: 4  medaka tools list_models
Checking program versions
This is medaka 1.0.3
Program    Version    Required   Pass     
bcftools   1.10.2     1.9        True     
bgzip      1.10.2     1.9        True     
minimap2   2.17       2.11       True     
samtools   1.10       1.9        True     
tabix      1.10.2     1.9        True     
Warning: Output sample_unk/medaka_cl_id_20 already exists, may use old results.
usage: medaka tools is_rle_model [-h] [--model MODEL] [--disable_cudnn]
medaka tools is_rle_model: error: argument --model: expected 1 argument

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: conda
 - OS: macOS Big Sur
 - GPU model: Apple Silicon M1
 - Nvidia driver version: NA
 - CUDA version: NA
 - cuDNN version: NA

**Additional context**
NA

**Comment by cjw85** [comment]
Can you describe how you have installed medaka? You have listed conda above but also Apple M1: there should not be a conda package for medaka for macOS Arm (up to v1.0.3 there was a macOS x64 package on conda).

**Comment by rkimoakbioinformatics** [comment]
@cjw85 I did the following.
>conda create -n ngspeciesid python=3.6
>pip install NGSpeciesID
>conda install --yes -c conda-forge -c bioconda medaka==0.11.5 openblas==0.3.3 spoa racon minimap2

Then, followed the example at https://github.com/ksahlin/NGSpeciesID#b6--read-filtering-clustering-consensus-generation-and-polishing-with-ngspeciesid
>NGSpeciesID --ont --consensus --sample_size 500 --m 800 --s 100 --medaka --primer_file Supplementary_File4_primer.txt --fastq sample_unk.fastq --outfolder sample_unk_consensus

Meanwhile, I followed the same process on Ubuntu 20.04 and got the following errer:
> medaka_consensus -i sample_unk_consensus/reads_to_consensus_46.fastq -d sample_unk_consensus/consensus_reference_46.fasta -o sample_unk_consensus/medaka_cl_id_46 -t 1             
Checking program versions
This is medaka 0.11.5
Program    Version    Required   Pass     
bgzip      1.9        1.9        True     
minimap2   2.17       2.11       True     
samtools   1.9        1.9        True     
tabix      1.9        1.9        True     
Warning: Output will be overwritten (-f flag)
Not aligning basecalls to draft, calls_to_draft.bam exists.
Running medaka consensus
[E::idx_find_and_load] Could not retrieve index file for 'calls_to_draft.bam'
[E::idx_find_and_load] Could not retrieve index file for 'calls_to_draft.bam'
[10:26:24 - Predict] Processing region(s): consensus_cl_id_46_total_supporting_reads_238:0-839
[10:26:24 - Predict] Setting tensorflow threads to 1.
[10:26:24 - Predict] Processing 1 long region(s) with batching.
[10:26:24 - Predict] Using model: /home/rick/miniconda3/envs/ngspeciesid/lib/python3.6/site-packages/medaka/data/r941_min_high_g344_model.hdf5.
[10:26:24 - ModelLoad] Building model with cudnn optimization: False
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
OMP: Info #156: KMP_AFFINITY: 8 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 4 cores/pkg x 2 threads/core (4 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 0 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 1 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 2 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 3 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 3 thread 1 
OMP: Info #250: KMP_AFFINITY: pid 966185 tid 966222 thread 0 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 966185 tid 966222 thread 1 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 966185 tid 966227 thread 2 bound to OS proc set 2
OMP: Info #250: KMP_AFFINITY: pid 966185 tid 966228 thread 3 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 966185 tid 966229 thread 4 bound to OS proc set 4
[10:26:25 - DLoader] Initializing data loader
[10:26:25 - PWorker] Running inference for 0.0M draft bases.
[10:26:25 - Sampler] Initializing sampler for consensus of region consensus_cl_id_46_total_supporting_reads_238:0-839.
Failed to read .bam file 'calls_to_draft.bam'.Failed to run medaka consensus.

**Comment by cjw85** [comment]
As far as diagnosing things for macOS ARM goes I can't really help, since we don't have any hardware to test this configuration. The code in medaka itself should compile fairly straightforwardly if medaka is installed from pip, but I would be worried about some of medaka's dependencies not being available for macOS ARM.

Your errors on Ubuntu indicate an alignment BAM file has been produced but the index file is missing:
```[E::idx_find_and_load] Could not retrieve index file for 'calls_to_draft.bam'```
Why that would be the case is not clear to me. I should say `medaka==0.11.5` is fairly old at this point, If you can upgrade to the latest 1.2.3 (on bioconda) or 1.2.4 (on pypi) we will be able to prvide further assistance.

**Comment by rkimoakbioinformatics** [comment]
@cjw85 Thanks for your reply. I'll try with pip installation and update the status.

**Comment by rkimoakbioinformatics** [comment]
@cjw85 I re-installed mostly with pip (and used a different test at https://github.com/ksahlin/NGSpeciesID/tree/master/test) and the medaka step went without an error. Thanks.
