### ISSUE TITLE
Has Medaka's run ended?

### ISSUE THREAD

**Issue by JQVazquez** [nanoporetech/medaka#262]
Hi, I was runnig for two days: 
medaka_variant -f /media/BRA20.contigs.fasta -i /media/BRA01reads_to_canuBRA20ref.mmpa2_1.sorted.bam -o /media/j/vc/ -m r941_min_fast_g303 -t 24 

in a Ryzen 9 3900x CPU, 32GB with Ubuntu 16

Now the screen output stop from 12 hours, after repetitive items Feature/Sampler/Pworker/DLoader and:
[01:16:48 - Predict] Finished processing all regions

and displaying very low CPU activity but with a complete use of physical memory (100%)  and a high exchange memory usage  (77,5%).

Has Medaka's run ended with a fail? or still working?
Thank you
Regards

**Comment by cjw85** [comment]
Can you please open a new issue providing the information requested in the issue template?

**Comment by wt2015-github** [comment]
Hi, I have the same problem. How to fix it? Thanks

**Comment by cjw85** [comment]
@wt2015-github,

Please open a new issue providing the details requested.
