### ISSUE TITLE
which model

### ISSUE THREAD

**Issue by jpn2021** [nanoporetech/medaka#264]
There does not appear to be a model for r941_min_fast_g360. I understand that for guppy 4.0 or later g360 is acceptable but I wonder how much difference min_fast would make instead of min_high.

**Comment by cjw85** [comment]
We stopped producing models explicitely paired for use with fast basecallers some time ago. The most appropriate model for fast basecallers is likely the equivalent high accuracy medaka model, but we have not validated this combination.
