### ISSUE TITLE
Installation in WSL 2

### ISSUE THREAD

**Issue by jpn2021** [nanoporetech/medaka#265]
**Describe the bug**
With a goal of using GPU acceleration I updated to WSL 2 but now the medaka installation seems to fail. I am running `pip install medaka` and get the below error. I have started clean a few times from a fresh Ubuntu installation (on WSL 2) and installing anaconda3 (Anaconda3-2020.11-Linux-x86_64.sh). Conda install seems to work better but also fails and doesn't have the latest version of medaka and has the bugs related to annotations which are important to me.

**Logging**

```
   Building wheel for mappy (setup.py) ... error
   ERROR: Command errored out with exit status 1:
    command: /anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-td7dnmy3/mappy_a21f6069115645e4b3cddb6ca1b07d23/setup.py'"'"'; __file__='"'"'/tmp/pip-install-td7dnmy3/mappy_a21f6069115645e4b3cddb6ca1b07d23/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ysghqs29
        cwd: /tmp/pip-install-td7dnmy3/mappy_a21f6069115645e4b3cddb6ca1b07d23/
   Complete output (15 lines):
   running bdist_wheel
   running build
   running build_ext
   skipping 'python/mappy.c' Cython extension (up-to-date)
   building 'mappy' extension
   creating build
   creating build/temp.linux-x86_64-3.8
   creating build/temp.linux-x86_64-3.8/python
   gcc -pthread -B /anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -I/anaconda3/include/python3.8 -c python/mappy.c -o build/temp.linux-x86_64-3.8/python/mappy.o -DHAVE_KALLOC -msse4.1
   In file included from python/mappy.c:612:
   python/cmappy.h:6:10: fatal error: zlib.h: No such file or directory
       6 | #include <zlib.h>
         |          ^~~~~~~~
   compilation terminated.
   error: command 'gcc' failed with exit status 1
   ----------------------------------------
   ERROR: Failed building wheel for mappy
   Running setup.py clean for mappy
 Failed to build mappy

```

Trying to run the `conda install -c bioconda medaka` install give the following

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: -
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method from pip install
 - OS: WSL 2 Ubuntu 20.04

**Comment by cjw85** [comment]
It looks like pip has decided it wants to compile the mappy package rather than use a precompiled version. You will need to install the Ubuntu package zlib1g-dev to obtain the zlib.h file.
