### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by jpn2021** [nanoporetech/medaka#267]
**Describe the bug**
I have followed the steps to install the cudnn following the Ubuntu instruction 2.3.4.1 for ubuntu 2004 cuda 11.2 at https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html. For some reason it had a hard time with the cudnn 8.1.1.33 but I was able to get the cudnn and cudnn-dev for 8.1.0.77 using cuda 11.2.

To insall cuda I followed the steps at https://docs.nvidia.com/cuda/wsl-user-guide/index.html for "Setting up CUDA Toolkit" but changed the ubuntu to 2004 from 1804 and the cuda to 11-2 from 11-0

Unfortunately it seems like medaka still doesn't use the GPU (GeForce RTX 2060).

**Logging**

> [16:48:26 - HAPLOID_VARIANT] Running medaka consensus.
> [16:48:28 - Predict] Reducing threads to 2, anymore is a waste.
> 2021-03-08 16:48:28.493961: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
> [16:48:28 - Predict] It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: WSL2 Ubuntu 2004
 - GPU GeForce RTX 2060
 - Nvidia driver version = 465.42
 - CUDA version = 11.2
 - cuDNN version = 8.0.7

**Comment by cjw85** [comment]
Medaka uses tensorflow 2.2, the table here:
https://www.tensorflow.org/install/source#gpu
details which versions of CUDA and cuDNN you will need.
