### ISSUE TITLE
Document output files

### ISSUE THREAD

**Issue by jakobnissen** [nanoporetech/medaka#269]
Apologies if this is already documented elsewhere, but I couldn't find it on this README, on the CLI help, or in the documentation.

Would it be possible to document the exact format of the outputs? For example, I am using `medaka_consensus`, which creates new headers for the consensus FASTA file - but the new format of the headers is not specified anywhere. Similarly, it creates a HDF5 file `consensus_probs.hdf`, which I cannot find any documentation for.

**Comment by cjw85** [comment]
The `consensus_probs.hdf` file is not intended to be a useful output to end-users, hence it is not documented (it contains the outputs of the neural network calculations).

The fasta headers are simply the input contig names possibly decorated with coordinates tracing to which part of the input sequence the output sequence corresponds.
