### ISSUE TITLE
Error in stitch.py?

### ISSUE THREAD

**Issue by sharon558** [nanoporetech/medaka#27]
- Tested medaka (v0.6.0a3) on chr3 of the NA12878 sample downloaded from the following link:
https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-genome

- cmd: 
medaka_variant -r GRCh38_full_analysis_set_plus_decoy_hla.fa -b rel5-guppy-0.3.0-chunk10k.sorted.bam  -m r94 -R chr3

- Errors:
[13:59:00 - PWorker] 100.0% Done (198.5/198.5 Mbases) in 4397.1s
[13:59:06 - PWorker] All done
[13:59:06 - Predict] Finished processing all regions.
[13:59:21 - DataIndex] Loaded sample-index from 1/1 (100.00%) of feature files.
[13:59:25 - SNPs] Processing chr3.
Traceback (most recent call last):
  File "python/Python-3.6.3/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "python/Python-3.6.3/lib/python3.6/site-packages/medaka/medaka.py", line 257, in main
    args.func(args)
  File "python/Python-3.6.3/lib/python3.6/site-packages/medaka/stitch.py", line 347, in snps
    find_snps(args.inputs, args.ref_fasta, args.output, regions=args.regions, threshold=args.threshold, ref_vcf=args.ref_vcf)
  File "python/Python-3.6.3/lib/python3.6/site-packages/medaka/stitch.py", line 178, in find_snps
    ref_seq_encoded = np.fromiter((label_encoding[ref_seq[i]] for i in major_pos), int, count=len(major_pos))
  **File "python/Python-3.6.3/lib/python3.6/site-packages/medaka/stitch.py", line 178, in <genexpr>
    ref_seq_encoded = np.fromiter((label_encoding[ref_seq[i]] for i in major_pos), int, count=len(major_pos))
KeyError: 'B'**

- The output and error files can be found in the attached zip folder.

[chr3.zip](https://github.com/nanoporetech/medaka/files/2882173/chr3.zip)

Thank you!

**Comment by cjw85** [comment]
Hi again,

Thanks for this. Medaka neglects to handle the full set of IUPAC base ambiguity codes. This should be easy to fix.

**Comment by cjw85** [comment]
Please try the https://pypi.org/project/medaka/0.6.0a4/ pre-release.

For reference `medaka variant` is untested on guppy 0.3.0 basecalls.

**Comment by sharon558** [comment]
Thanks @cjw85! So far it's working. 

Just curious, are there any downsides to use medaka on guppy basecalls? Is the tested flip-flop basecaller better suited for medaka?

**Comment by cjw85** [comment]
The [benchmarks](https://nanoporetech.github.io/medaka/benchmarks.html) page compares results for consensus accuracy of the current flip-flop and older transducer basecalling algorithm. The former is a marked improvement.

Variant calling is being developed with basecalls from the flip-flop algorithm; results would be expected to be worse with the transducer algorithm.

**Comment by sharon558** [comment]
Hi @cjw85 

Thanks for helping troubleshooting! I saw two tables on the SNP calling page (https://nanoporetech.github.io/medaka/snp.html) showing medaka's performance for "a region of Chr20". Do you happen to know the region size or bed coordinates? Just wanted to get an idea and maybe check how the performance is for guppy called data on the same region.

Thanks!
