### ISSUE TITLE
VCF file issues

### ISSUE THREAD

**Issue by jpn2021** [nanoporetech/medaka#270]
**Describe the bug**
The new version 1.2.5 seems to have fixed `medaka tools annotate` - thank you! Would it make sense to run the medaka tools annotate program using _consensus_to_ref.vcf_ and calls_to_draft.bam? Is there a different bam file that would be better? Is there a way to use _consensus_probs.hdf_? Also is there a way to have a bam file that is usable in IGV or Ugene to see the alignments? _call_to_draft.bam_ isn't aligned to the ref and doesn't seem to be called the same as the consensus. On the other side _consensus_to_ref.bam_ doesn't have multiple alignments.

After running `medaka tools annotate` after running `medaka_haploid_variant` it seems to annotate only DP and DPS (no QUAL or any other annotations). Also in the vcf file (and the _consensus_to_ref.vcf_ file) seems like many of the variants have the same same REF and ALT base - why would it consider that a variant? Is this because of some haploid/diploid issue?

**Comment by cjw85** [comment]
To annotate the variants within `consensus_to_ref.vcf` you will need to align the reads to the reference sequence outside of medaka -- the `calls_to_draft.bam` is not suitable for this purpose. This is the bam that you would load into IGV.

Outputting a QUAL field is not implemented currently.

**Comment by jpn2021** [comment]
Is there any way to get QUAL fields from `medaka_haploid_variant`? Otherwise it is quite difficult to sort.

**Comment by cjw85** [comment]
The new implementation of `medaka_haploid_variant` in medaka version 1.3.0 provides information in the QUAL field.
