### ISSUE TITLE
Enable the creation of gvcf files

### ISSUE THREAD

**Issue by larahurban** [nanoporetech/medaka#273]
I would like to ask if it is already possible to create a gvcf file using medaka, i.e. a vcf file that also contains the reference alleles that are supported by the aligned reads? If not, I think this would be a very valuable feature. Thank you!

**Comment by cjw85** [comment]
Hi @larahurban,

Currently medaka cannot output records for non-variant loci when using the convenience programs `medaka_variant` and `medaka_haploid` variant. We are looking to implement this feature for the next release within the next few weeks.

**Comment by gchevignon** [comment]
Hello, 
Apparently this option is available since v1.3.1  "Option to output VCF record for all reference positions from
medaka variant." 
But what is the option exactly ? This is not clear from the -h ...
Also is this option available with medaka_haploid_variant ?

Thanks a lot!

**Comment by cjw85** [comment]
Hi @gchevignon

The option is not currently enabled in `medaka_haploid_variant`. It is however available in the command `medaka variant`, which is used by `medaka_haploid_variant` to process the neural network output into a VCF. You can run this command "manually" after running `medaka_haploid_variant` as:

    medaka variant reference.fasta medaka_ouput/consensus_probs.hdf my_variants.gvcf

**Comment by swiddison** [comment]
Hello, 
Can you please clarify how to output all reference positions with medaka variant (not haploid variant). Can it only be run once hdf files have been generated rather than as a command line option to the basic medaka variant command? 
If the latter then how to deal with the fact there are two hdf files (round_1_hap_1.vcf and round_1_hap_2.vcf) with the aim of ultimately producing a single vcf? 
Thanks!

**Comment by cjw85** [comment]
The `medaka_variant` pipeline is unable to produce a GVCF on its own.

It may be possible, but completely untested, to run the pipeline steps independently to produce a GVCF for the two haplotypes and then run the merging step (`medaka tools haploid2diploid`) on the two haplotype VCFs.

We are not actively developing the medaka diploid variant calling pipeline as [Clair3](https://github.com/HKU-BAL/Clair3) gives superior results.
