### ISSUE TITLE
ETA for Q20EA medaka model?

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/medaka#275]
Hi

What is the ETA on the Q20EA medaka model?

Best regards
Rasmus

**Comment by stureid** [comment]
Hi @Kirk3gaard,

We can't provide an ETA at the moment, although we are actively working on it. Our interim recommendation is to use the polisher built into flye with the `--nano-corr` option. We've seen great results with that, setting a high bar for Medaka to beat.

**Comment by Kirk3gaard** [comment]
Hi @stureid 

Great to hear that flye is already producing good results with the --nano-corr option. However, as far as I remember flye does not accept multiple input types. For this metagenome I have some additional R9 data that I want to include to increase the coverage so I am using the raw option with the combined data. I am eagerly waiting for the medaka model for polishing the assembly when you are able to beat the flye output.

Best regards
Rasmus

**Comment by Sam-Tuna** [comment]
@Kirk3gaard, a relatively new feature of Flye is a [metagenome assembly tool](https://doi.org/10.1038/s41592-020-00971-x), that runs if you use the `--meta` option.
But, I'm pretty sure the `--nano-corr` option is to input already corrected reads, and it assumes a low error rate for them. If you're inputing raw reads you'll want the `--nano-raw` option.

**Comment by Kirk3gaard** [comment]
Hi @Sam-Tuna 

Yep I know.

Best regards
Rasmus

**Comment by stureid** [comment]
Hi @Sam-Tuna ,

We don't have a lot of experience with metagenome assembly, but the Q20 data is < 1 % error (modal). The [manual](https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md) states that the `corr` options are optimised for < 3 % error.

I believe these settings don't have much (if any) impact on results from the polishing stage itself. There's plenty of room for experimentation with these more accurate nanopore data types.

**Comment by cjw85** [comment]
Closing this as models have been included for a while now in v1.4.4.
