### ISSUE TITLE
medaka not finding expected deletions

### ISSUE THREAD

**Issue by pcantalupo** [nanoporetech/medaka#276]
Hello, I ran the following `medaka_haploid_variant` commands using the 3 different mode arguments to look for variants in SARS2 genome using nanopore reads that were basedcalled with Guppy 4.0.14.

```
medaka_haploid_variant -t 2 -o haploid_variant_HWT --debug --model r941_min_high_g360 --mode HWT reads.fastq.gz ../refs/GCA_009937905.1_ASM993790v1_genomic.fna
medaka_haploid_variant -t 2 -o haploid_variant_NW --debug --model r941_min_high_g360 --mode NW reads.fastq.gz ../refs/GCA_009937905.1_ASM993790v1_genomic.fna
medaka_haploid_variant -t 2 -o haploid_variant_HW --debug --model r941_min_high_g360 --mode HW reads.fastq.gz ../refs/GCA_009937905.1_ASM993790v1_genomic.fna
```

The resulting VCF files were exactly the same:

```
##fileformat=VCFv4.1
##medaka_version=1.2.3
##contig=<ID=MN985325.1,length=29882>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
MN985325.1      23608   .       GC      G       .       .               GT      1
MN985325.1      23612   .       GCAC    G       .       .               GT      1
MN985325.1      23624   .       GCT     G       .       .               GT      1
MN985325.1      27740   .       T       C       .       .               GT      1
MN985325.1      29862   .       G       A       .       .               GT      1
```

I expected it to find two abundant deletions, 21nt and 36nt, in the region ~23,590 to 23,630. These deletions are clearly seen in my minimap2 map-ont alignment using IGV:

![](https://i.imgur.com/rY11dbX.jpg)

I was wondering why Medaka could not find these deletions. Am I using the wrong `--model` parameter? What else should I try to find these deletions?

**Comment by cjw85** [comment]
Hi @pcantalupo,

Firstly, I apologise that someone has not responded sooner. I agree that medaka doesn't appear to be doing the best job in this region.

`medaka_haploid_variant` calls variants by constructing a consensus sequence scaffolded from the given reference. This consensus is then aligned back to the reference. It could be that our detection of "errors" in this alignment is sub-optimal and hence this long variant is not picked up.

There is an alternative (older) approach to calling variants in medaka which is a combination of the `medaka consensus` and `medaka variant` commands. To use this approach, provide the `medaka consensus` program with a BAM of youre reads aligned to the reference sequence to produce an HDF file, this file can then be given to `medaka variant` to produce a VCF.

**Comment by pcantalupo** [comment]
Thank you.

I had already tried the "older" approach and got similar results (see below; I removed the INFO field for clarity). I had thought I was doing it wrong and that is why I switched to the haploid caller since I'm working with a viral genome.

```
##fileformat=VCFv4.1
##medaka_version=1.2.3
##contig=<ID=MN985325.1,length=29882>
##INFO=<ID=ref_seq,Number=1,Type=String,Description="Medaka reference sequence">
##INFO=<ID=pred_seq,Number=1,Type=String,Description="Medaka predicted sequence">
##INFO=<ID=ref_qs,Number=.,Type=Float,Description="Medaka quality score for reference">
##INFO=<ID=pred_qs,Number=.,Type=Float,Description="Medaka quality score for prediction">
##INFO=<ID=ref_q,Number=1,Type=Float,Description="Medaka per position quality score for reference">
##INFO=<ID=pred_q,Number=1,Type=Float,Description="Medaka per position quality score for prediction">
##INFO=<ID=n_cols,Number=1,Type=Integer,Description="Number of medaka pileup columns in variant call">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Medaka genotype.">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Medaka genotype quality score">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	FORMAT	SAMPLE
MN985325.1	23608	.	GC	G	0.377	PASS	GT:GQ	1:0
MN985325.1	23612	.	GCAC	G	11.136	PASS	GT:GQ	1:11
MN985325.1	23624	.	GCT	G	1.815	PASS	GT:GQ	1:2
MN985325.1	29862	.	G	A	27.555	PASS	GT:GQ	1:28
```

**Comment by cjw85** [comment]
That's unfortunate. A couple of points:

1. Its not clear from your IGV screenshot that your reads cleanly support a single allele: many reads seem to span the gap implied by the other reads. Is there a possibility of contamination here? Or some otherway in which your reads might reflect a population with variation? medaka's variant calling implicitely assumes a single allele (in otherwords the idea that a single consensus sequence can explain the observed reads is correct).
2. medaka is designed as a small variant caller and while it may pick out some longer indel variants it is by no means guranteed to do so. There is some power to create joint predictions across reference positions provided by the recurrent neural network, but its not something we explicitely attempt.

**Comment by pcantalupo** [comment]
The reads reflect a population of variants. I don't expect there to be one single haplotype in the sample. I'm just looking for a "variant" caller to tabulate the different variants. Do you know if there is any software to do this or will I have to resort to manually tabulating the indels? Thank you

**Comment by cjw85** [comment]
I am not aware of any software that is able to tabulate accurately multitple alternative plausible alleles with low false positive rate. There's definitley scope for creating one!
