### ISSUE TITLE
Samtools error query name too long

### ISSUE THREAD

**Issue by lixiaopi1985** [nanoporetech/medaka#284]
Hi

I encountered an error when running `medaka_consensus -i reads_to_consensus_0.fastq -d consensus_reference_0.fasta -o medakaout -t 10 -m r941_min_high_g303`. It seems the error came from the samtools, but I am not sure how to fix it.

system: ubuntu 18.04
medaka: 1.2.3

medaka was installed through conda:

`conda install --yes -c conda-forge -c bioconda "parasail-python>=1.1.10" "edlib>=1.1.2" python-edlib "medaka>=1.0.2" spoa racon minimap2 mmseqs2`

output message:

Checking program versions
This is medaka 1.2.3
Program    Version    Required   Pass     
bcftools   1.11       1.9        True     
bgzip      1.11       1.9        True     
minimap2   2.17       2.11       True     
samtools   1.11       1.9        True     
tabix      1.11       1.9        True     
Aligning basecalls to draft
Removing previous index file /media/swaggyp1985/HDD6T/VT_Projects_2020/Mock_community/mock_community_rerun_3302021/Analysis/preprocess_with_consensus/test/barcode5/consensus_reference_0.fasta.mmi
Removing previous index file /media/swaggyp1985/HDD6T/VT_Projects_2020/Mock_community/mock_community_rerun_3302021/Analysis/preprocess_with_consensus/test/barcode5/consensus_reference_0.fasta.fai
Constructing minimap index.
[M::mm_idx_gen::0.002*2.05] collected minimizers
[M::mm_idx_gen::0.004*2.44] sorted minimizers
[M::main::0.006*1.82] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*1.80] distinct minimizers: 326 (90.49% are singletons); average occurrences: 1.120; average spacing: 5.405
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /media/swaggyp1985/HDD6T/VT_Projects_2020/Mock_community/mock_community_rerun_3302021/Analysis/preprocess_with_consensus/test/barcode5/consensus_reference_0.fasta.mmi /media/swaggyp1985/HDD6T/VT_Projects_2020/Mock_community/mock_community_rerun_3302021/Analysis/preprocess_with_consensus/test/barcode5/consensus_reference_0.fasta
[M::main] Real time: 0.007 sec; CPU: 0.012 sec; Peak RSS: 0.003 GB
[M::main::0.004*1.42] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.004*1.40] mid_occ = 4
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.004*1.39] distinct minimizers: 326 (90.49% are singletons); average occurrences: 1.120; average spacing: 5.405
[E::sam_parse1] query name too long
samtools view: error reading file "-"
[E::sam_parse1] query name too long
samtools view: error closing "-": -5
Alignment pipeline failed.
Failed to run alignment of reads to draft.

Thank you

**Comment by cjw85** [comment]
Hi @lixiaopi1985,

Judging by the error message

```
[E::sam_parse1] query name too long
```

above it looks like something is malformed in your input reads file. Or that your reads have genuinely long names. The length of the sequence names from Oxford Nanopore Technologies' sequencing devices should be handled correctly by samtools so I suspect the files have been currupted somehow.

**Comment by lixiaopi1985** [comment]
@cjw85 Thank you, shorten the name resolved the issue.

**Comment by lixiaopi1985** [comment]
> Hi @lixiaopi1985! I ran into the same issue. How did you shorten the name?

I removed the default nanopore run-id and replaced with barcode and read id (i.e. @barcode05|read-id) using inhouse python functions I wrote.
