### ISSUE TITLE
medaka_consensus stops at [**:**:** - Predict] Finished processing all regions.

### ISSUE THREAD

**Issue by wt2015-github** [nanoporetech/medaka#285]
**Describe the bug**
Hi, I have been running medaka_consensus for two days, but it has stopped changing at "Finished processing all regions." But htop command shows it is still running. What is happening and how to fix it?
/// medaka_consensus -i sampleName.fastq.gz -d asm_final.fa -o sampleName -t 2 -m r103_min_high_g360 ///

**Logging**
Checking program versions
This is medaka 1.2.5
Program    Version    Required   Pass
bcftools   1.11       1.9        True
bgzip      1.11       1.9        True
minimap2   2.17       2.11       True
samtools   1.11       1.9        True
tabix      1.11       1.9        True
Aligning basecalls to draft
...
Running medaka consensus
...
[00:40:27 - DLoader] Initializing data loader
[00:40:27 - Sampler] Initializing sampler for consensus of region utg000053l:0-5016.
[00:40:27 - PWorker] Running inference for 0.0M draft bases.
[00:40:27 - Feature] Processed utg000053l:0.0-5015.0 (median depth 26.0)
[00:40:27 - Sampler] Took 0.14s to make features.
[00:40:29 - PWorker] All done, 0 remainder regions.
[00:40:29 - Predict] Finished processing all regions.

**Environment:**
 - Installation method [conda]
 - OS: [Ubuntu 14.04 server with 48 CPUs Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz and 130 GB memory]
 - medaka version [1.2.5]
 - GPU [No GPU]

Thank you!

**Comment by wt2015-github** [comment]
BTW, my Nanopore data was generated by MinION R10.3 flowcells using the fast Guppy basecaller version 4.4.1. Each sample has about 20k reads after filtering and trimming.

**Comment by cjw85** [comment]
Hi @wt2015-github,

We have some perenial issues with HDF5 libraries on older Ubuntus. I suspect this to be the case here since you are using Ubuntu 14.04.

You can likely kill the medaka process. You should have a file `consensus_probs.hdf` in the output directory. I would make a copy of this file outside the output directory before proceeding.

If you run `medaka_consensus` just as you did initially it will pick up after the step where `consensus_probs.hdf` is generated to produce the final consensus sequences in FASTA format. If it does not, please report back what did happen.

I should say, I would recommend that you update your system if possible since Ubuntu 14.04 was reached its end of life in April 2019, so unless you have an [ESM](https://ubuntu.com/security/esm) subscription your system will not be receiving security updates.

**Comment by wt2015-github** [comment]
Hi,

Thanks! I just tried as you suggested. It stopped again with error some messages.

///medaka_consensus -i barcode01_01.E7140.fastq.gz -d barcode01_01.E7140_asm_final.fa -o ./ -t 2 -m r103_min_high_g360 ///

***Logging
Checking program versions
This is medaka 1.2.5
Program    Version    Required   Pass
bcftools   1.11       1.9        True
bgzip      1.11       1.9        True
minimap2   2.17       2.11       True
samtools   1.11       1.9        True
tabix      1.11       1.9        True
Warning: Output ./ already exists, may use old results.
Not aligning basecalls to draft, calls_to_draft.bam exists.
Not running medaka consensus, consensus_probs.hdf exists.
*** Error in `~/miniconda3/envs/medaka/bin/python': free(): invalid pointer: 0x00007f837933f770 ***
*** Error in `~/miniconda3/envs/medaka/bin/python': free(): invalid pointer: 0x00007f837933f770 ***

**Comment by wt2015-github** [comment]
@cjw85
Sorry, I forgot to @ you in the last comment.

**Comment by cjw85** [comment]
That looks unfortunately like the consensus_probs.hdf file is currupt. Can you try running the [h5check](https://support.hdfgroup.org/products/hdf5_tools/h5check.html) command on the file. You should be able to install this from the apt package manager as part of hfd5-tools pacakge.

Short of rerunning medaka from scratch I do not know what else to suggest.

**Comment by MehmetGoktay** [comment]
Had the same issue yesterday and today but I guess I know what is the problem. 

If you install medaka directly via conda, it also installs the most recent version of minimap2 (2.20) and samtools (1.12).

Which leads the same problem as it was explained in the first and second entries.

Solution is simple, just as it was suggested;

virtualenv medaka --python=python3 --prompt "(medaka) "
. medaka/bin/activate
pip install medaka

Just make sure you have minimap2 (2.11 or 2.17), samtools (1.11), tabix (1.11) and bgzip (1.11)

Probably there is some kind of incompatibility either with minimap (2.20) or samtools (1.12).

Hope it helps
