### ISSUE TITLE
Blank space in INFO column of vcf file--medaka_haploid_variant

### ISSUE THREAD

**Issue by rln0005** [nanoporetech/medaka#286]
The vcf file generated from `medaka_haploid_variant` (consensus_to_ref.vcf) is blank in the 'INFO' column for each variant (contains white space). As such, it cannot be imported into IGV. 
IGV gives the following error: "The provided VCF file is malformed at approximately line number 6: The VCF specification requires a valid (non-zero length) info field". Line 6 marks the end of the header and beginning of my list of variants....with whitespace in the column for "Info". I believe IGV requires that there be _something_ in this column, but the vcf file was generated this way. 

command typed: `medaka_haploid_variant -t 2 trim.fastq reference.fasta `

installed medaka using: pip
medaka version: 1.2.6
OS: ubuntu 20.04.1
gpu model: intel(r) HD graphics 4000

> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> Please ensure that you are using the most recent version of medaka before filing
> a bug report. The most recent version can be found on the [release page](https://github.com/nanoporetech/medaka/releases).
> If you are not using the most recent release, and file a issue regardless the
> most likely response from our developers will be to ask you to first upgrade.
>
> Please ensure also to provide the information below, not doing so will likely
> result in a request for the information.

**Describe the bug**
A clear and concise description of what the bug is including the command that you have run.

**Logging**
Please attach any relevant logging messages. (Use \`\`\` before and after code blocks).

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: [e.g. Ubuntu 16.04]
 - medaka version (can be found by running `medaka --version`)
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by cjw85** [comment]
Hi @rln0005,

Thank you for reminded us of this; we'd had it on an internal list of bugs for a while. We will fix it today.

**Comment by cjw85** [comment]
This is fixed in v1.3.0 available now on PyPI, and shortly from conda.
