### ISSUE TITLE
Questions - medaka_haploid_variant

### ISSUE THREAD

**Issue by jpn2021** [nanoporetech/medaka#289]
In running `medaka_haploid_variant` there seem to be many messages along the lines of the below at various stages. Could you please provide some guidance as to whether these are things that I should fix (perhaps by adjusting some settings like chunk length). If so it would be great to incorporate the possibility of having flags for these options in `medaka_haploid_variant`:

**1 - During aligning**
[_TIME_ - Sampler] Region _XXXX_ (_XXXX_ positions) is smaller than inference chunk length 10000, quarantining

and

[_TIME_ - Feature] Pileup counts do not span requested region, requested _XXXX_, received _XXXX_.

**2 - During variant calling**
/home/unix/miniconda3/lib/python3.8/site-packages/medaka/labels.py:381: RuntimeWarning: divide by zero encountered in log10
  q = -10 * np.log10(err)

and

[_TIME_ - TrimOlap] _XXXX_ and _XXXX_ cannot be concatenated as there is no overlap and they do not abut.

**Comment by cjw85** [comment]
This messages are for information only and can be ignored in normal use.
