### ISSUE TITLE
medaka_variant model for flipflop data

### ISSUE THREAD

**Issue by MichelMoser** [nanoporetech/medaka#29]
Hi, 

I would like to test the medaka_variant pipeline to do SNP detection and haplotyping. 
We did basecalling of nanopore data using ```guppy version 2.2.3``` and the model `dna_r9.4.1_450bps_flipflop_prom.cfg` (json file: template_r9.4.1_450bps_large_flipflop_prom.jsn). 

There are three possible options to choose for base-call models in medaka_variant (`r941_trans', 'r941_flip213', 'r941_flip235'`) and i am unsure which one (`r941_flip213` or `r941_flip235`) supports best our data. 
Could you tell me which is preferentially used for the data described?

 
Thank you, 
Michel

**Comment by cjw85** [comment]
Hi @MichelMoser 

There's some details on this in the [README](https://github.com/nanoporetech/medaka#usage) under usage, though admittedly they could be clearer.

Roughly speaking, the medaka models are numbered according to the guppy version where there were updates to guppy's basecalling model. As per the README then you should use the `r941_flip213` model for your data. If you had used the very latest guppy `2.3.5` without flip-flop basecalling, the medaka model `r941_flip235` would be more appropriate.
