### ISSUE TITLE
medaka model for guppy4.2.2?

### ISSUE THREAD

**Issue by gf777** [nanoporetech/medaka#290]
Hello,

I could not find in the latest medaka the model for guppy4.2.2. Is the model to be loaded separately or it's not available? In which case what would you recommend to use?

Thanks

Giulio

**Comment by cjw85** [comment]
As per the README and [documentation](https://nanoporetech.github.io/medaka/installation.html#sequence-correction):

> Where a version of Guppy has been used without an exactly corresponding medaka model, the medaka model with the highest version equal to or less than the guppy version should be selected.
