### ISSUE TITLE
Wrong description in README.md file section "Human variant calling"

### ISSUE THREAD

**Issue by Oleg-Mozhei** [nanoporetech/medaka#291]
Dear ONT support,

As stated in "Human variant calling" section of README.md file you need to execute 
`medaka_variant -f <REFERENCE.fasta> -b <reads.bam>` to perform calling. Please note that there isn't an "-b" option in the script.

According to `medaka_variant -help` you need to use -i option to specify path to aligned reads,

Please consider updating your manual.

Thank you very much =)

**Comment by cjw85** [comment]
Hi @Oleg-Mozhei,

We have corrected this, the changes will be reflected in the README the next time we make a formal release.
