### ISSUE TITLE
M1 Mac running issue

### ISSUE THREAD

**Issue by joshquick** [nanoporetech/medaka#293]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> Please ensure that you are using the most recent version of medaka before filing
> a bug report. The most recent version can be found on the [release page](https://github.com/nanoporetech/medaka/releases).
> If you are not using the most recent release, and file a issue regardless the
> most likely response from our developers will be to ask you to first upgrade.
>
> Please ensure also to provide the information below, not doing so will likely
> result in a request for the information.

**Describe the bug**
A clear and concise description of what the bug is including the command that you have run.

**Logging**
Please attach any relevant logging messages. (Use \`\`\` before and after code blocks).

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: [e.g. Ubuntu 16.04]
 - medaka version (can be found by running `medaka --version`)
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by joshquick** [comment]
Get 'zsh: illegal hardware instruction' when running medaka consensus on an M1 Mac. I believe this is a known issue importing tensorflow in python so feel free to close this issue but wanted to let you know about it.

**Comment by cjw85** [comment]
Hi Josh!

You might have some joy if you trawl the internet for how to install tensorflow on M1 devices. We've made medaka packages in the past for aarch64, but never for Apple's flavour. I think you might face an uphill battle.

**Comment by cjw85** [comment]
We're hoping to begin testing this in the new year

**Comment by joshquick** [comment]
Just ordered your new laptop have you ;)
