### ISSUE TITLE
bonito model

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/medaka#298]
Hi,
I was wondering if you are planning to include bonito models in future releases. I am aware that there used to be a model file in the [bonito repository](https://nanoporetech.box.com/shared/static/ve8445ceb2bnwod1zaj0z2ptuwsvxd64.hdf5) but it is not listed in the current README anymore, which makes me wonder if it is still save to use that model file on calls made by the latest bonito basecall model.
Cheers

**Comment by cjw85** [comment]
Bonito has been iterating rapidly in recent months, there's a somewhat involved process to validate consensus calling models so its not something we have had the time to undertake for all bonito iterations.

With the upcoming transfer of models from bonito to Guppy, there will be a parallel release of accompanying medaka models.

**Comment by cjw85** [comment]
There are now models for Guppy 5 available in medaka 1.4.
