### ISSUE TITLE
NotImplementedError(Cannot convert a symbolic Tensor ({}) to a numpy)

### ISSUE THREAD

**Issue by mao-sheng** [nanoporetech/medaka#299]
I am running the command line
“
medaka_consensus -i input.fa -d draft.fa -o output_dir -t 8
”
Error:  NotImplementedError(Cannot convert a symbolic Tensor ({}) to a numpy)

What could be the cause of such a problem?

**Comment by cjw85** [comment]
Hi @mao-sheng,

Please open a new issue provided the information requested in the Issue template.
