### ISSUE TITLE
Custom guppy model

### ISSUE THREAD

**Issue by fbemm** [nanoporetech/medaka#30]
Hi,

I have a sort of unrelated question. Is there a chance to (re-)train guppy and also tailor medals towards the restrained guppy model?

Cheers,
F

**Comment by cjw85** [comment]
There is a forthcoming release of software used to train neural networks for guppy.

We have a [walkthrough](https://nanoporetech.github.io/medaka/walkthrough.html#walkthrough) for a basic process to train medaka models. A more involved process can be found in a branch of our pipelining project [katuali](https://github.com/nanoporetech/katuali/tree/medaka_training).

**Comment by fbemm** [comment]
Great. How forthcoming is the release ;) ?

**Comment by cjw85** [comment]
The basecaller training is now available:
https://github.com/nanoporetech/taiyaki
