### ISSUE TITLE
Medaka running on gpu server for many days and Still going on 

### ISSUE THREAD

**Issue by ckhithesh** [nanoporetech/medaka#305]
Dear Team Medaka, 
We are working on human exome analysis on nanopore data. Our issue with the tool is the variant calling with medaka, It's taking too long time and still not completed the analysis, is we have to wait till is completes.
Our sample is Human exome. May I know the TAT for human sample (exome sample) variant calling on medaka. Do any issues with the version. I have installed using conda.

Thanks in advance,
Regards,
Hithesh

**Comment by ckhithesh** [comment]
Dear Team,
Our analysis has stopped in the middlle showing the below error

ModelStore exception <class 'OSError'>
Traceback (most recent call last):
  File "/home/acgt01/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())

Please tell us to resolve this issue

**Comment by fidibidi** [comment]
@ckhithesh Heyo, it seems like support for issues like these isn't a priority. I've switched over to https://github.com/HKU-BAL/Clair3 and had excellent results. Hope this helps

**Comment by cjw85** [comment]
Hi @ckhithesh,

Your example above appears to be using an older version of medaka than is current; older versions were egregiously slow processing many short discontiguous/non-overlapping alignments.

Having said we would currently that advise that for diploid variant calling using [Clair3](https://github.com/HKU-BAL/Clair3) over medaka.
