### ISSUE TITLE
Support for 30xx Nvidia cards

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/medaka#306]
**Is your feature request related to a problem? Please describe.**
Hey everyone, recently attained a workstation with a 3080 Nvidia card. However, much to my disdain, it appears that the tensorflow package medaka uses relies on CUDA 10.1 being installed... which turns out isn't compatible with said card. 

**Describe the solution you'd like**
Has anyone had experience resolving this issue with a workaround?
Is this something that is in the near future as an update? Changing the tensorflow package to 2.4.0? 

Thanks!

**Comment by cjw85** [comment]
Hi @fidibidi, if you install medaka from source you should be able to change the requirements file to specify use of tensorflow 2.4. We have only done a little testing with this version of tensorflow.

**Comment by fidibidi** [comment]
Awesome! 
Well I'll give it a shot and see how it goes.
