### ISSUE TITLE
medaka_variant fails at haploid2diploid step

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/medaka#307]
**Describe the bug**

Hello! 
Running medaka_variant, I'm having issues getting past the haploid2diploid step. 

From what I can tell it seems to be a memory issue, as the ram steadily fills up, until the process is killed. 

I've successfully run medaka on some smaller flongle datasets, but this is a minION one. 

**Logging**
- Running medaka haploid2diploid
/medaka/venv/bin/medaka_variant: line 199: 21613 Killed (lots of spaces) medaka tools haploid2diploid "${VCF1}" "${VCF2}"  "${REF}" "${MERGED}" ${OPTS}
* Failed to run medaka haploid2diploid

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: Github source
 - OS: Ubuntu 18.04
 - medaka version 1.3.4
 - GPU model: 3080
 - Nvidia driver version: 460.73.01
 - CUDA version: 11.2
 - cuDNN version: 8

**Additional context**
The command its crashing on is:
medaka tools haploid2diploid round_1_hap_1.vcf round_1_hap_2.vcf GCA_000001405.15_GRCh38_no_alt_analysis_set.fna round_1_unfiltered.vcf 

the sizes of these vcf files are both 2.3gb. 

Appreciate any and all direction!

**Comment by fidibidi** [comment]
...

**Comment by cjw85** [comment]
Hi @fidibidi,

Apologies for the lack of response here. Medaka is untested with CUDA 11.2 and cuDNN so I wouldn't like to guess what the issue is here.

I would however advise that for diploid variant calling we would currently recommend using [Clair3](https://github.com/HKU-BAL/Clair3) over medaka.

**Comment by fidibidi** [comment]
Does this step even have anything to do with GPU Drivers? 

Merging two VCF files and encountered memory issue.
