### ISSUE TITLE
Can I use Medaka for RNA data?

### ISSUE THREAD

**Issue by VikArz02** [nanoporetech/medaka#309]
Can I use Medaka for RNA data?

**Comment by cjw85** [comment]
We do not provide support for RNA data or basecallers.

This has been on the TODO likst for a long time. I would recommend https://github.com/nanoporetech/isONclust2 as a more RNA specific tool that can perform consensus calculations whilst also handling the subtleties that come with handling RNA molecules of DNA.

**Comment by VikArz02** [comment]
Thanks for your answer, but I need to find SNPs and Indels. Maybe I was looking bad, but I don't understand why you recommend me isONclust2.

**Comment by cjw85** [comment]
I'm not aware of any program that will directly calculate variants from RNA read data. isONClust2 and the tools built around it (linked in the README) might be applicable to get you started in analysing your data.

For further support on analysing your reads I would suggest posting in the Nanopore Community pages. I will close this issue.
