### ISSUE TITLE
Processing Short Regions Apparent Error

### ISSUE THREAD

**Issue by nhartwic** [nanoporetech/medaka#31]
I'm attempting to run medaka on an unpolished assembly and I seem to have encountered an error. I don't recieve any error message and the tool is currently "running" but doesn't seem to be doing anything. I've posted the last message medaka created below. The time stamp is from over 12 hours ago.

[06:29:02 - Predict] Processing short regions
[06:29:02 - ModelLoad] Building model (steps, features, classes): (None, 10, 5)
[06:29:04 - ModelLoad] Loading weights from /local/ifs2_projdata/9043/projects/MGX/localenv/anaconda/envs/medaka/lib/python3.6/site-packages/medaka-0.6.0a2-py3.6-linux-x86_64.egg/medaka/data/medaka_model.hdf5
[06:29:05 - PWorker] Running inference for 0.0M draft bases.
[06:29:05 - Sampler] Initializing sampler for consensus or region Consensus_Consensus_Consensus_ctg865:0-7228.
[06:29:05 - Feature] Pileup-feature is zero-length for Consensus_Consensus_Consensus_ctg865:0-7228 indicating no reads in this region.
[06:29:05 - Sampler] Took 0.13s to make features.

**Comment by cjw85** [comment]
It looks like you are using the 0.6.0 pre-release. Could you please upgrade to either 0.6.0 or 0.6.1? Several issues along the lines of which you are experiencing were discovered in the pre-release and were resolved in the release version.

**Comment by nhartwic** [comment]
Thanks. I'll do that and get back to you.

Slightly off topic note; medaka 0.6.1 doesn't seem to be available on the bioconda channel.

**Comment by Ivanbh214** [comment]
Hello,
In my case, I'm trying to run mekada for short read, (300 to 600 bp), I have the version 0.6.0, I'll tried to download from github repository and It's the same version, so I used 0.6.0 and the pipeline worked but I could n't obtain result(I have the fasta but it's empty). 

> mini_assemble -i ${BASECALLS} -o /home/ivan/Escritorio/medaka -p assm -t ${NPROC}
Copying FASTX input to workspace: /home/ivan/medaka/C26_carb_f.fasta > /home/ivan/Escritorio/medaka/assm.fa.gz

Skipped adapter trimming.
Skipped pre-assembly correction.
Overlapping reads...
[M::mm_idx_gen::0.024*1.07] collected minimizers
[M::mm_idx_gen::0.030*1.94] sorted minimizers
[M::main::0.030*1.94] loaded/built the index for 1428 target sequence(s)
[M::mm_mapopt_update::0.031*1.92] mid_occ = 487
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1428
[M::mm_idx_stat::0.032*1.90] distinct minimizers: 20842 (0.00% are singletons); average occurrences: 6.932; average spacing: 3.071
[M::worker_pipeline::0.757*5.43] mapped 1428 sequences
[M::main] Version: 2.14-r883
[M::main] CMD: minimap2 -x ava-ont -K 500M -t 8 assm.fa.gz assm.fa.gz
[M::main] Real time: 0.762 sec; CPU: 4.120 sec; Peak RSS: 0.035 GB
Assembling graph...
[M::main] ===> Step 1: reading read mappings <===
[M::ma_hit_read::0.208*1.00] read 243144 hits; stored 486288 hits and 680 sequences (210170 bp)
[M::main] ===> Step 2: 1-pass (crude) read selection <===
[M::ma_hit_sub::0.260*1.00] 680 query sequences remain after sub
[M::ma_hit_cut::0.267*1.00] 486288 hits remain after cut
[M::ma_hit_flt::0.275*1.00] 484120 hits remain after filtering; crude coverage after filtering: 525.25
[M::main] ===> Step 3: 2-pass (fine) read selection <===
[M::ma_hit_sub::0.295*1.00] 680 query sequences remain after sub
[M::ma_hit_cut::0.303*1.00] 484120 hits remain after cut
[M::ma_hit_contained::0.311*1.00] 10 sequences and 32 hits remain after containment removal
[M::main] ===> Step 4: graph cleaning <===
[M::ma_sg_gen] read 16 arcs
[M::main] ===> Step 4.1: transitive reduction <===
[M::asg_arc_del_trans] transitively reduced 0 arcs
[M::main] ===> Step 4.2: initial tip cutting and bubble popping <===
[M::asg_cut_tip] cut 10 tips
[M::asg_arc_del_multi] removed 0 multi-arcs
[M::asg_arc_del_asymm] removed 0 asymmetric arcs
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.3: cutting short overlaps (3 rounds in total) <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::asg_arc_del_short] removed 0 short overlaps
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 4.4: removing short internal sequences and bi-loops <===
[M::asg_cut_internal] cut 0 internal sequences
[M::asg_cut_biloop] cut 0 small bi-loops
[M::asg_cut_tip] cut 0 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.5: aggressively cutting short overlaps <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 5: generating unitigs <===
[M::main] Version: 0.3-r179
[M::main] CMD: miniasm -s 100 -e 3 -f assm.fa.gz assm.paf.gz
[M::main] Real time: 0.315 sec; CPU: 0.316 sec
Running racon read shuffle 1...
Running round 1 consensus...
[M::mm_idx_gen::0.000*2.72] collected minimizers
[M::mm_idx_gen::0.001*3.95] sorted minimizers
[M::main::0.001*3.91] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.001*3.81] mid_occ = 1
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.001*3.73] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
[M::worker_pipeline::0.007*3.27] mapped 1428 sequences
[M::main] Version: 2.14-r883
[M::main] CMD: minimap2 -K 500M -t 8 assm.gfa.fa.gz assm.fa.gz
[M::main] Real time: 0.008 sec; CPU: 0.024 sec; Peak RSS: 0.003 GB
[racon::Polisher::initialize] error: empty target sequences set!
Running round 2 consensus...
[M::mm_idx_gen::0.000*4.02] collected minimizers
[M::mm_idx_gen::0.001*4.91] sorted minimizers
[M::main::0.001*4.87] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.001*4.74] mid_occ = 1
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.001*4.61] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
[M::worker_pipeline::0.007*3.37] mapped 1428 sequences
[M::main] Version: 2.14-r883
[M::main] CMD: minimap2 -K 500M -t 8 racon_1_1.fa.gz assm.fa.gz
[M::main] Real time: 0.008 sec; CPU: 0.025 sec; Peak RSS: 0.003 GB
[racon::Polisher::initialize] error: empty target sequences set!
Running round 3 consensus...
[M::mm_idx_gen::0.000*3.61] collected minimizers
[M::mm_idx_gen::0.001*4.48] sorted minimizers
[M::main::0.001*4.44] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.001*4.34] mid_occ = 1
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.001*4.25] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
[M::worker_pipeline::0.008*3.07] mapped 1428 sequences
[M::main] Version: 2.14-r883
[M::main] CMD: minimap2 -K 500M -t 8 racon_1_2.fa.gz assm.fa.gz
[M::main] Real time: 0.008 sec; CPU: 0.024 sec; Peak RSS: 0.003 GB
[racon::Polisher::initialize] error: empty target sequences set!
Running round 4 consensus...
[M::mm_idx_gen::0.000*3.84] collected minimizers
[M::mm_idx_gen::0.001*4.45] sorted minimizers
[M::main::0.001*4.42] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.001*4.29] mid_occ = 1
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.001*4.18] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
[M::worker_pipeline::0.008*3.18] mapped 1428 sequences
[M::main] Version: 2.14-r883
[M::main] CMD: minimap2 -K 500M -t 8 racon_1_3.fa.gz assm.fa.gz
[M::main] Real time: 0.008 sec; CPU: 0.026 sec; Peak RSS: 0.003 GB
[racon::Polisher::initialize] error: empty target sequences set!
Waiting for cleanup.
rm: can not delete 'shuffled *': the file or directory does not exist
rm: can not delete '* paf *': the file or directory does not exist
Final assembly written in /home/ivan/medaka_2/assm_final.fa. You have a good day.

I checked the pipeline with the tutorial data and work perfectly. Could be in this case that I have to adjust something from minimap2, every time  apperearing in the message minimap2 -K 500M -t 8 racon_1_3.fa.gz assm.fa.gz. I checked the final length of consensus.fasta from data tutorial is 47018010(4700M). Could be de reason for don't get consensus with my data?Do you know how to modificate minimap requeriments or another requeriments for get data with this small size? 

Thank you very much

**Comment by cjw85** [comment]
@nhartwic

Did the newer versions work for you? There is now a v0.6.2 in bioconda.

**Comment by Ivanbh214** [comment]
Thank your very much,

I'll try it.

Cheers

**Comment by nhartwic** [comment]
@cjw85

After I posted, I updated to 0.6.1 and restarted the run. It is still running and hasn't yet hit the "processing short regions" part of the execution. I'll update when I have more information.

**Comment by nhartwic** [comment]
Well, Medaka is still running but seems to be functioning. It hit the processing short regions step a couple days ago, spent about 12 hours on it, and is now stitching everything up.
