### ISSUE TITLE
r103_507 models no specific models for minION vs promethION?

### ISSUE THREAD

**Issue by nextgenusfs** [nanoporetech/medaka#312]
I got tripped up when using R10.3 flow cell that there doesn't seem to be multiple models for minION vs promethION for r103 but there is for r941?

So I should just be using `r103_hac_g507` for `medaka consensus` from minION data using10.3 flow cells called with guppy 5.0.11?

Thanks!

```
$ medaka tools list_models
Available: r103_fast_g507, r103_fast_snp_g507, r103_fast_variant_g507, r103_hac_g507, r103_hac_snp_g507, r103_hac_variant_g507, r103_min_high_g345, r103_min_high_g360, r103_prom_high_g360, r103_prom_snp_g3210, r103_prom_variant_g3210, r103_sup_g507, r103_sup_snp_g507, r103_sup_variant_g507, r10_min_high_g303, r10_min_high_g340, r941_min_fast_g303, r941_min_fast_g507, r941_min_fast_snp_g507, r941_min_fast_variant_g507, r941_min_hac_g507, r941_min_hac_snp_g507, r941_min_hac_variant_g507, r941_min_high_g303, r941_min_high_g330, r941_min_high_g340_rle, r941_min_high_g344, r941_min_high_g351, r941_min_high_g360, r941_min_sup_g507, r941_min_sup_snp_g507, r941_min_sup_variant_g507, r941_prom_fast_g303, r941_prom_fast_g507, r941_prom_fast_snp_g507, r941_prom_fast_variant_g507, r941_prom_hac_g507, r941_prom_hac_snp_g507, r941_prom_hac_variant_g507, r941_prom_high_g303, r941_prom_high_g330, r941_prom_high_g344, r941_prom_high_g360, r941_prom_high_g4011, r941_prom_snp_g303, r941_prom_snp_g322, r941_prom_snp_g360, r941_prom_sup_g507, r941_prom_sup_snp_g507, r941_prom_sup_variant_g507, r941_prom_variant_g303, r941_prom_variant_g322, r941_prom_variant_g360
Default consensus:  r941_min_hac_g507
Default snp:  r941_prom_hac_snp_g507
Default variant:  r941_prom_hac_variant_g507
```

**Comment by cjw85** [comment]
Hi Jon,

I'll need to check with the team that is responsible for producing the models (the research team doesn't do this anymore), but I think the answer here is that they found a single shared model for MinION/GridION and PromethION sufficient.

**Comment by nextgenusfs** [comment]
Thanks for checking. I had assumed that was the case but wanted to make sure I was using the proper model for 10.3 flow cells.

**Comment by cjw85** [comment]
My statement above is correct. Aplogies that this makes things a little obtuse, we will think how to put back the systematic naming even if the models are ultimately resolved to be the same.
