### ISSUE TITLE
minimap2 index for parallel jobs on same reference

### ISSUE THREAD

**Issue by W-L** [nanoporetech/medaka#315]
Hi!
I am running `medaka_haploid_variant` for several samples against the same reference in parallel and while all samples complete successfully, I noticed that the output files of one sample were very small. Looking into the logfiles it seems to me that there was a problem with minimap2's index of the reference for the sample with an issue. Assuming that minimap2 creates an index of the same reference for each of the jobs, it might have caused one job to read the index while it was written to by another job. Does that make sense? 

My command:
 `medaka_haploid_variant -i br.fq -r listeria_SLCC2378_roi.ref.fa -m r941_prom_variant_g360 -t 24 -o br-listeria_SLCC2378`

minimap2 portion of the logfile of a successful sample:
```
Constructing minimap index.
[M::mm_idx_gen::0.104*0.98] collected minimizers
[M::mm_idx_gen::0.131*1.18] sorted minimizers
[M::main::0.171*1.14] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.184*1.13] distinct minimizers: 460345 (98.62% are singletons); average occurrences: 1.022; average spacing: 5.339; total length: 2512844
[M::main] Version: 2.21-r1071
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d ../listeria_SLCC2378_roi.ref.fa.mmi ../listeria_SLCC2378_roi.ref.fa
[M::main] Real time: 0.223 sec; CPU: 0.210 sec; Peak RSS: 0.026 GB
[M::main::0.062*0.64] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.072*0.69] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.079*0.72] distinct minimizers: 460345 (98.62% are singletons); average occurrences: 1.022; average spacing: 5.339; total length: 2512844
[M::worker_pipeline::52.489*8.66] mapped 203403 sequences
[M::worker_pipeline::65.265*10.77] mapped 205543 sequences
[M::worker_pipeline::77.752*12.68] mapped 207332 sequences
[M::worker_pipeline::89.569*13.91] mapped 206903 sequences
[M::worker_pipeline::101.393*13.76] mapped 212615 sequences
[M::worker_pipeline::103.268*13.52] mapped 51204 sequences
[M::main] Version: 2.21-r1071
[M::main] CMD: minimap2 -x map-ont --MD -t 24 -a -A 2 -B 4 -O 4,24 -E 2,1 ../listeria_SLCC2378_roi.ref.fa.mmi ../rfc.fq
[M::main] Real time: 103.343 sec; CPU: 1396.542 sec; Peak RSS: 4.106 GB
```

minimap2 portion of the logfile of the "silently failing" sample:
```
Constructing minimap index.
[M::mm_idx_gen::0.153*1.00] collected minimizers
[M::mm_idx_gen::0.199*1.07] sorted minimizers
[M::main::0.243*1.06] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.254*1.06] distinct minimizers: 460345 (98.62% are singletons); average occurrences: 1.022; average spacing: 5.339; total length: 2512844
[M::main] Version: 2.21-r1071
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d ../listeria_SLCC2378_roi.ref.fa.mmi ../listeria_SLCC2378_roi.ref.fa
[M::main] Real time: 0.275 sec; CPU: 0.271 sec; Peak RSS: 0.028 GB
[M::mm_idx_gen::0.004*0.88] collected minimizers
[M::mm_idx_gen::0.014*1.69] sorted minimizers
[M::main::0.014*1.69] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.014*1.68] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.014*1.68] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan; total length: 0
[M::worker_pipeline::10.705*2.51] mapped 892554 sequences
[M::worker_pipeline::14.814*4.17] mapped 1096005 sequences
[M::worker_pipeline::15.269*4.07] mapped 539441 sequences
[M::main] Version: 2.21-r1071
[M::main] CMD: minimap2 -x map-ont --MD -t 24 -a -A 2 -B 4 -O 4,24 -E 2,1 ../listeria_SLCC2378_roi.ref.fa.mmi ../br.fq
[M::main] Real time: 15.314 sec; CPU: 62.262 sec; Peak RSS: 1.160 GB

```

Rerunning the same sample by itself worked without an issue. I appreciate that this is probably really tricky to reproduce, but are there any checks in place to see if a minimap2 index of the reference already exists and is valid?

Thanks very much!

Environment:
 - Installation method: conda
 - OS: CentOS 8.3
 - medaka version: 1.4.3
 - no GPU

**Comment by cjw85** [comment]
Hi,

Yes there is a bit of a race condition if you run multiple instances of the script in performing the indexing, as there would be if you tried running minimap2 directly. I would suggest either running an initial instance and letting it be solely responsible for creating the index, or index the reference upfront before running the medaka script. Subsequent processes will find that the indexing has taken place already and simply use the previously created files.

**Comment by W-L** [comment]
Ok, thanks very much! I'll keep in mind to index the reference before running multiple instances of medaka.

**Comment by W-L** [comment]
I noticed that index files of a reference are re-created even if they already exist. So unfortunately making sure that an index is present does not prevent this race condition from causing issues. I think the problem is with the call to `mini_align` in `medaka_haploid_variant`, which includes the `-f` flag to force the re-creation of the index (https://github.com/nanoporetech/medaka/blob/77e8e33cd3ef1a6a2d42554f1d5d7b3a0a1ca3a1/scripts/medaka_haploid_variant#L114). Would it cause any problems to remove that flag?
Thank you!

**Comment by cjw85** [comment]
Good spot, I don't know why that line is using the force option and suspect if should not be.

**Comment by cjw85** [comment]
This should be fixed in our next release; the forced recreation of the minimap2 index will not occur.
