### ISSUE TITLE
Medaka on multiple reference files

### ISSUE THREAD

**Issue by rleenay** [nanoporetech/medaka#317]
I'm trying to use a few tools to collapse Nanopore reads onto a relatively small (50x) sequence library of synthetic DNA that's 2kb long. My question using `medaka` is: if I were to supply a fasta reference sequence with multiple components, would every fastq be aligned to *each* fasta consensus? Or would it query the fully fasta sequence and then collapse to the highest scoring consensus?

**Comment by cjw85** [comment]
The `medaka_consensus` wrapper script will align reads to all references collectively such that the single best alignment of a read to a single reference is used to calculate a consensus for each reference sequence. If you want to obtain something different you will need to perform the alignments yourself and use the medaka subcommands for the consensus calculation.
