### ISSUE TITLE
"assert len(haps) == 1" when running medaka tools haploid2diploid

### ISSUE THREAD

**Issue by charliechen912ilovbash** [nanoporetech/medaka#318]
Hi,
I am using `medaka tools haploid2diploid` and it showed the following error message.
I have run it successfully on other chromosomes,
so maybe it is due to there are some data not acceptable by medaka in this chromosome?
My command is:
`medaka tools haploid2diploid round_1_hap_1.vcf round_1_hap_2.vcf chr15.fa round_1_unfiltered.vcf
`

```
[20:54:18 - VCFMERGE] Merging variants in chrom chr15
Traceback (most recent call last):
File "/home/charlie/miniconda3/envs/medaka/bin/medaka", line 11, in <module>
sys.exit(main())
File "/home/charlie/miniconda3/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 707, in main
args.func(args)
File "/home/charlie/miniconda3/envs/medaka/lib/python3.8/site-packages/medaka/vcf.py", line 942, in haploid2diploid
for v in variants:
File "/home/charlie/miniconda3/envs/medaka/lib/python3.8/site-packages/medaka/vcf.py", line 884, in variants
merged.append(_merge_variants(
File "/home/charlie/miniconda3/envs/medaka/lib/python3.8/site-packages/medaka/vcf.py", line 772, in _merge_variants
assert len(haps) == 1
AssertionError
Country: Japan
Phone number: 0354525406
I would like to receive news and information about nanopore products and events by email: Yes
Contact Type: Customer
Lead Source: HubSpot
SFDC Hubspot Actions: Contact Us
Marketing lead source Add to: Contact us form

ref:_00D20N1PA._5004LA4kGQ:ref
```

**Comment by cjw85** [comment]
Hi @charliechen912ilovbash,

Where did your input files come from? They seem to be named like the files produced by the `medaka_variant`. Did that program fail to produce a final diploid vcf?

**Comment by charliechen912ilovbash** [comment]
Yes, I first run the `medaka_variant`, it showed this error, then I run `medaka tools haploid2diploid` manually, trying to complete `medaka_variant` workflow.

The output folder of `medaka_variant` contains the following files:
```
round_0_hap_mixed_phased.bam
round_0_hap_mixed_phased.bam.bai
round_0_hap_mixed_phased.vcf
round_0_hap_mixed_phased.vcf.gz
round_0_hap_mixed_phased.vcf.gz.tbi
round_0_hap_mixed_probs.hdf
round_1_hap_1_probs.hdf
round_1_hap_1.vcf
round_1_hap_2_probs.hdf
round_1_hap_2.vcf
```

My `medaka_variant` command is:
`medaka_variant  -t 1 -b 100 -f GDC-GRCh38-chr15.fa -i chr15.bam   -o chr15`
the error message is the same as I mentioned in this issue.

The end of the stdout of `medaka_variant` is:
```
+ Running consensus calling
- Running medaka consensus with round_0_hap_mixed_phased.bam --model r941_prom_hac_variant_g507 --tag_name HP --tag_value 2 --tag_keep_missing
+ Running variant calling
- Running medaka variant
  VCF written to round_1_hap_2.vcf.
+ Merging vcfs to diploid vcf
- Running medaka haploid2diploid
* Failed to run medaka haploid2diploid.
```

This happened at both `chr20` and `chr15` in my data.

By the way, in some other chromosomes, the `round_1_hap_1.vcf` and `round_1_hap_2.vcf` were not sorted. I sorted it manually with `bcftools sort` then run the `medaka tools haploid2diploid` and `bcftools filter` as the source bash script to complete the `medaka_variant`  workflow.

**Comment by charliechen912ilovbash** [comment]
Hi, just want to know the current status of this question, thanks.

**Comment by cjw85** [comment]
We have not yet had time to look at this issue, and in all honesty with our current priorities I do not think that we will do soon.

Our current recommendation for diploid calling is to use [clair3](https://github.com/HKU-BAL/Clair3) which typically produces better results than the workflow implemented within medaka.

**Comment by charliechen912ilovbash** [comment]
I see, I will try to use clair3, thanks!
