### ISSUE TITLE
Medaka very slow

### ISSUE THREAD

**Issue by stefandiederich** [nanoporetech/medaka#319]
Hi,
we are new to Oxford Nanopore Sequencing and tried to establish a workflow to detect variants. We sequenced genomic DNA of NA12878. Basecalling was performed with GUPPY version 5.0.11 and the super acurate basecalling model. Alignement against HG19 is done with minimap2 version 2.21. 
I extracted alignemnt data of chr22 to have a small testset and perform variant calling with medaka with the following command:

```medaka_variant -i /media/Data/ONTTest/Test_chr22.bam -f /media/Data/Referenzgenome/HG19/HG19.karyo.fasta -s r941_min_sup_g507 -m r941_min_sup_g507 -t 60 -o /media/Data/Nanopore/medaka/```

Unfortunately it uses only 1 CPU instead of 60 like I put with the `-t 60` option and also only one of our four A100 GPUs was used at some short time during analysis. At the end the 150 MB BAM file took 2h and 45 min to finish. Is that behaviour normal? Shouldn't it be faster to call variants? 

Maybe someone else saw this behaviour too and can give me some advices how to solve this problem.

Bests Stefan

**Comment by cjw85** [comment]
Hi @stefandiederich 

Medaka will only use a single GPU. The bottleneck of the `medaka_variant` analysis is the running of the read haplotyping step which utilises whatshap and is single threaded. For additional performance you can provide the `-r` regions option to `medaka_variant` to limit processing to a sub-region of the chromosome. Such jobs can be run independently in parallel.

I should say that we currently recommend using [clair3](https://github.com/HKU-BAL/Clair3) for diploid variant calling, which has been found to produce superior results in most circumstances.

**Comment by stefandiederich** [comment]
Hi @cjw85 

thanks for your explanation! I will test clair3 as you mentioned and the option of parallelisation of medaka with different sub-regions. 
Bests 
Stefan

**Comment by cjw85** [comment]
Closing as `medaka_variant` is now deprecated.
