### ISSUE TITLE
Problem trying to train a model for consensus polishing

### ISSUE THREAD

**Issue by ddiazdom** [nanoporetech/medaka#320]
Hi, 

I am using the command `medaka train` to build a model for the consensus polishing of a bacterial assembly. However, I am not able to obtain the hdf5 file with the model. 

The exact command I am running is this:

`medaka train train_features.hdf --train_name barcode01 --epochs 10 --debug`

**train_features.hdf** is a file I previously created as described in [this](https://nanoporetech.github.io/medaka/walkthrough.html) tutorial,  but using my own data. On the other hand, **barcode01** is the folder where the output model is supposed to be stored. After running medaka train, the folder **barcode01** is left with the following content:

`model-02.tar.gz model-06.tar.gz model-10 model-03.tar.gz  model-07.tar.gz  model.best.cat_acc.tar.gz
model-04.tar.gz model-08.tar.gz training.log model-01.tar.gz model-05.tar.gz model-09.tar.gz`

The execution of medaka throws some warnings but nothing fatal (as far as I understand). 

`WARNING:tensorflow:Can save best model only with val_cat_acc available, skipping.`
`WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.`

`2021-08-18 19:58:16.071915: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`

`2021-08-18 19:58:16.071954: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-27-214): /proc/driver/nvidia/version does not exist`

`2021-08-18 19:58:16.072272: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`

My environment settings:
- I do not have GPU. 
- Installation method : pip install
- OS: Ubuntu 18.04.5 LTS
- medaka 1.4.3

Please let me know if you need some extra information. I would really appreciate the help :)

**Comment by cjw85** [comment]
Hi @ddiazdom,

It looks like we need to update the tutorial, the file name `model.best.cat_acc.tar.gz` is the final trained model file. This can be used with the other medaka programs for performing inference.

I should say we wouldn't typically advise training your own model and simply use the ones provided with medaka.

**Comment by ddiazdom** [comment]
Hi @cjw85 ,

Thanks for helping me out. I read the medaka train documentation (-h flag), and there are several models to choose from. In my case, I need to polish a consensus from a bacterial draft assembly. Which criteria should I use to select a model ? The tutorial says the default model was trained using E.coli, S.cerevisaie, and H.sapiens samples, but I am working with Mycobacterium.

**Comment by cjw85** [comment]
The models are paired to particular versions of the Guppy basecaller, they should be applicable to all samples. For choosing a model see the [Models](https://github.com/nanoporetech/medaka#models) section of the README. If you have used the most recent version of Guppy to call your data the default medaka model will be appropriate.
