### ISSUE TITLE
Error during Medaka installation

### ISSUE THREAD

**Issue by ramnageena11** [nanoporetech/medaka#321]
base) singhram@CH-CB-RS-T15GL:~$ conda install medaka
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - medaka -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0|3.4.*|3.7.10|3.7.10|3.6.12|3.7.9|3.6.12|3.6.9|3.6.9|3.6.9|3.6.9|>=3|3.8.*|>=3.6|3.7.*|3.9.*|<3.0.0|>=3.5',build='1_73_pypy|2_73_pypy|4_73_pypy|5_73_pypy|1_73_pypy|0_73_pypy|5_73_pypy|3_73_pypy|0_73_pypy']
  - medaka -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - medaka -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

**Comment by cjw85** [comment]
Hi @ramnageena11,

You output above shows that you have attempted to install medaka into your base conda environment. As indicated in the [Installation](https://github.com/nanoporetech/medaka#installation) section of the README we would advise installing medaka into a dedicated conda environment.

**Comment by ramnageena11** [comment]
but it seems that medaka is installed?

**Comment by ramnageena11** [comment]
Okay, thanks.
But it seems it is installed.

pls suggest.

rgds
Ram

Ram Nageena Singh, Ph.D (Microbiology)
Lab No. 3 Molecular Microbiology Lab
Division of Microbiology
ICAR-Indian Agricultural Research Institute
Pusa, New Delhi-110012, Delhi, India

**Comment by cjw85** [comment]
As above please follow the directions in the README to install medaka into an independent conda environment, not your base conda environment.
