### ISSUE TITLE
Variant calling fails on contigs with low (but not zero) coverage

### ISSUE THREAD

**Issue by swiddison** [nanoporetech/medaka#325]
Hi, I am running medaka_variant on a genome where there are contigs that represent chromosomes and some that represent additional scaffolds.
I am getting an error e.g. :
ERROR: whatshap error: invalid contig `DS231680`
Failed to partition reads in round 0.

When I look at the coverage in my BAM file it looks like the contigs that give an error are those with low coverage (less than 8 reads). Where a contig has zero coverage no error occurs.

**Comment by cjw85** [comment]
Hi @swiddison,

Thanks for reporting this. Our current recommendation for diploid calling is to use [clair3](https://github.com/HKU-BAL/Clair3) which typically produces better results than the workflow implemented within medaka.
