### ISSUE TITLE
Docker Medaka_consensus can not find python

### ISSUE THREAD

**Issue by ChristophBoerlin** [nanoporetech/medaka#326]
**Describe the bug**
When I call the medaka_consensus function through the ONT docker image it fails because it does not find python. See error below.
If I call `docker run --rm ontresearch/medaka:latest medaka_consensus -h` it shows the help, so that part is working.

The main reason i am trying to get the Docker image working is that I am having trouble with getting medaka to use the GPU I have.

**Logging**
`docker run --rm ontresearch/medaka:latest medaka_consensus -i input.fastq -d draft_assembly.fq -o medaka -t 10 -m r941_min_hac_g507`
leads to 
/usr/local/bin/medaka_consensus: line 5: python: command not found

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: Pulled from Docker
 - OS: Ubuntu 20.10
 - medaka version 1.4.3
 - GPU model: GeForce RTX 3060

**Comment by cjw85** [comment]
Hi @ChristophBoerlin,

This does look like an oversight, I'm curious how this passed our internal tests! We'll take a look.

**Comment by cjw85** [comment]
@ChristophBoerlin I've updated the tags on dockerhub, things should now work more smoothly.

The command you were using above is mostly correct, though don't forget to add a bind mount for your working directory.

**Comment by ChristophBoerlin** [comment]
Thank you @cjw85 for the fast response and fixing it.
And thanks for the bind mount reminder, I didn't put it in there to keep the command producing the error short.
