### ISSUE TITLE
medaka requires pomoxis in order to run :: mini_align name conflict

### ISSUE THREAD

**Issue by EricDeveaud** [nanoporetech/medaka#331]
Hello 

after installing medak-1.4.4 from tag archive (https://github.com/nanoporetech/medaka/releases/download/v1.4.4/medaka-1.4.4.tar.gz) 

I ran the walktrough instructions https://nanoporetech.github.io/medaka/walkthrough.html

NOTE I din not installed pomoxis, but ran the medak steps from provided data.

problem is that medak requires pomoxis. 
while Training a Consensus Network, command 
`mini_align -c ${CHUNKSIZE} -P -m -r ${DRAFT} -i ${TRUTH} -t ${NPROC} -p ${TRUTH2DRAFT}` 

failed with following error:

```
rpm_maker:medaka/1.4.4 > mini_align -c 100000  -m -r draft_assm.fa -i ../../datas/medaka/truth.fasta -t `nproc` -p truth2draft
Found minimap files.
Splitting input into 100000 chunks.
/opt/gensoft/exe/medaka/1.4.4/bin/mini_align: line 150: split_fastx: command not found
Failed to split input into chunks.
```

`splitx_fasta` is one of the scripts from pomoxis.

installing pomoxis solved the problem, of course. BUT  **both pomoxis and medaka provides a mini_align script**

currently they are in sync (no diffs) 

may I suggest that either one of the distribution drops the min_align script, or mini_align name will be adapted in order to avoid name_conflicts

regards

Eric

**Comment by cjw85** [comment]
Hi @EricDeveaud,

We used to have text on the Github pages stating that the release archives should not be used as they do not contain all necessary code. This test doesn't appear to be present anymore. The Github release archives should not be used, and there is no way (to my knowledge) for us to stop Github automatically adding them to the release pages.

The PyPI and bioconda release builds of medaka copy the `mini_align` file from pomoxis for use in the `medaka_consensus` convenience program. No other functionality from pomoxis is strictly required by medaka. The use of `mini_align` in the example training process is an oversight; although the example does suggest installing pomoxis into distinct virtual environments so if you follow the example verbatim it should be the case that everything works.

If you seriously want to train medaka models you should consider using the [katuali](github.com/nanoporetech/katuali), which is what we use to train the bundled models. @mwykes and @ftostevin-ont can help you with this.

**Comment by EricDeveaud** [comment]
Hello, 

indeed mekad mini_align opeied from pomonix (if I understand correctly)  requires split_fastx which is not part of mekada 
```
rpm_maker:medaka/medaka-1.4.4 > grep -R -n split_fastx
scripts/mini_align:150:  split_fastx "${INPUT}" "${INPUT}.chunks" "${CHUNK}" \
```

maybee this oone should also be copied or just pomonix set as a dependency of mekada as minmap, samtools etc ;-)

regards

Eric

**Comment by cjw85** [comment]
The way mini_align is used in medaka does not require the split_fastx functionality. Ideally both medaka and pomoxis would depend on a third package containing the shared functionality. However the developers have limited time for this sort of activity and so this is unlikely to happen.

As above we are not aware of any issues here for normal (consensus calling) uses cases.

**Comment by EricDeveaud** [comment]
OK thanks for the clarification and extensive answer.

best regards

Eric
