### ISSUE TITLE
installation with conda into an environment

### ISSUE THREAD

**Issue by mtva0001** [nanoporetech/medaka#332]
Hi,
I try to install medaka but it is not an easy task apparently. I try to install it into an already existing conda environment using:
conda install -c conda-forge -c bioconda medaka

But I got this error: 
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - medaka -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0|3.4.*|3.7.10|3.7.10|3.6.12|3.7.9|3.6.12|3.6.9|3.6.9|3.6.9|3.6.9|>=3|>=3.6|3.7.*|<3.0.0|>=3.5',build='0_73_pypy|1_73_pypy|3_73_pypy|1_73_pypy|0_73_pypy|5_73_pypy|5_73_pypy|4_73_pypy|2_73_pypy']
  - medaka -> python[version='>=3.6,<3.7.0a0']

Your python: python=3.9

Can you make medaka compatible with any version of python?

**Comment by mtva0001** [comment]
Well, I don't have other options if Nanopore doesn't provide a complete pipeline for clustering, consensus creation and making an OTU table finally. Anyway, then I'm forced to use Racon instead.

**Comment by cjw85** [comment]
Closing this issue. The recommendation remains that medaka should be installed in to an isolated conda or virtual environment, this is easily specified in workflow managers commonly used in bioinformatics.
