### ISSUE TITLE
Build from Dockerfile fails

### ISSUE THREAD

**Issue by veghp** [nanoporetech/medaka#339]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> Please ensure that you are using the most recent version of medaka before filing
> a bug report. The most recent version can be found on the [release page](https://github.com/nanoporetech/medaka/releases).
> If you are not using the most recent release, and file a issue regardless the
> most likely response from our developers will be to ask you to first upgrade.
>
> Please ensure also to provide the information below, not doing so will likely
> result in a request for the information.

**Describe the bug**
Build from Dockerfile fails at last step -- see output below

`docker build .`

**Logging**
Please attach any relevant logging messages. (Use \`\`\` before and after code blocks).
```
Step 7/7 : RUN     cd /tmp/medaka     && make install_root     && cd /     && rm -rf /tmp/medaka     && medaka --help     && samtools --help
 ---> Running in f6c27b99e29b
test -d venv || python3 -m venv venv --prompt "medaka"
. ./venv/bin/activate && pip install pip --upgrade
Collecting pip
  Downloading https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl (1.7MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-21.3.1
# setuptools 53.0.0 trips up on whatshap deps
. ./venv/bin/activate && pip install setuptools==52.0.0
Collecting setuptools==52.0.0
  Downloading setuptools-52.0.0-py3-none-any.whl (784 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
Successfully installed setuptools-52.0.0
. ./venv/bin/activate && python -c "from setup import check_model_lfs; check_model_lfs()"
Bundling models: ['r103_fast_g507', 'r103_fast_snp_g507', 'r103_fast_variant_g507', 'r103_hac_g507', 'r103_hac_snp_g507', 'r103_hac_variant_g507', 'r103_min_high_g345', 'r103_min_high_g360', 'r103_prom_high_g360', 'r103_prom_snp_g3210', 'r103_prom_variant_g3210', 'r103_sup_g507', 'r103_sup_snp_g507', 'r103_sup_variant_g507', 'r104_e81_fast_g5015', 'r104_e81_hac_g5015', 'r104_e81_sup_g5015', 'r10_min_high_g303', 'r10_min_high_g340', 'r941_min_fast_g303', 'r941_min_fast_g507', 'r941_min_fast_snp_g507', 'r941_min_fast_variant_g507', 'r941_min_hac_g507', 'r941_min_hac_snp_g507', 'r941_min_hac_variant_g507', 'r941_min_high_g303', 'r941_min_high_g330', 'r941_min_high_g340_rle', 'r941_min_high_g344', 'r941_min_high_g351', 'r941_min_high_g360', 'r941_min_sup_g507', 'r941_min_sup_snp_g507', 'r941_min_sup_variant_g507', 'r941_prom_fast_g303', 'r941_prom_fast_g507', 'r941_prom_fast_snp_g507', 'r941_prom_fast_variant_g507', 'r941_prom_hac_g507', 'r941_prom_hac_snp_g507', 'r941_prom_hac_variant_g507', 'r941_prom_high_g303', 'r941_prom_high_g330', 'r941_prom_high_g344', 'r941_prom_high_g360', 'r941_prom_high_g4011', 'r941_prom_snp_g303', 'r941_prom_snp_g322', 'r941_prom_snp_g360', 'r941_prom_sup_g507', 'r941_prom_sup_snp_g507', 'r941_prom_sup_variant_g507', 'r941_prom_variant_g303', 'r941_prom_variant_g322', 'r941_prom_variant_g360']

Model files appear to be git lfs stubs. Please refer to README.md
for instructions regarding git lfs. If you obtained medaka through
a method other than cloning the repository from github, please raise
an issue on github.com/nanoporetech/medaka.
Makefile:125: recipe for target 'check_lfs' failed
make: *** [check_lfs] Error 1
The command '/bin/bash -o pipefail -c cd /tmp/medaka     && make install_root     && cd /     && rm -rf /tmp/medaka     && medaka --help     && samtools --help' returned a non-zero code: 2
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: clone github source, run `docker build .`
 - OS: Ubuntu 18.04
 - medaka version: latest source
 - GPU model: No GPU

**Additional context**

**Comment by cjw85** [comment]
Hi @veghp,

As remarked in the error above, the README file details that git lfs is required for succesffuly cloning the repository.

Incidently a docker image can be retrieve from dockerhub as ontresearch/medaka:v1.4.4

**Comment by veghp** [comment]
Thank you, yes the provided docker image is very handy - it was not obvious from the readme that we can use that as it talks about building the image.

Also another note, this command in the readme seems to require parameter flags:
```
medaka_haploid_variant <reads.fastq> <ref.fasta>
```
Thanks again

**Comment by cjw85** [comment]
The README has been updated to indicate that a prebuilt image is available on dockerhub.
