### ISSUE TITLE
Unable to use the specified model

### ISSUE THREAD

**Issue by twolinin** [nanoporetech/medaka#34]
Hi,

I am trying to use the specified model by follow the commands on [Walkthrough.](https://nanoporetech.github.io/medaka/walkthrough.html) In the last step, medaka_consensus command went wrong. And get the following error message.

> RuntimeError: Filepath for '--model' argument does not exist and is not a known model ID (training/model.best.val.hdf5)
Failed to run medaka consensus.

To use a model run medaka_consensus for the default model (specifying the model using the -m option):

> cd ${WALKTHROUGH}
source ${MEDAKA}
CONSENSUS=consensus_trained
MODEL=${TRAINNAME}/model.best.val.hdf5
medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${CONSENSUS} -t ${NPROC} -m ${MODEL}

full message below.

> (medaka) [JH@bip7 medaka_walkthrough]$ cd ${WALKTHROUGH}
(medaka) [JH@bip7 medaka_walkthrough]$ source ${MEDAKA}
(medaka) [JH@bip7 medaka_walkthrough]$ CONSENSUS=consensus_trained
(medaka) [JH@bip7 medaka_walkthrough]$ MODEL=${TRAINNAME}/model.best.val.hdf5
(medaka) [JH@bip7 medaka_walkthrough]$ medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${CONSENSUS} -t ${NPROC} -m ${MODEL}
Checking program versions
Program    Version    Required   Pass
bgzip      1.9        1.9        True
minimap2   2.11       2.11       True
samtools   1.9        1.9        True
tabix      1.9        1.9        True
Warning: Output consensus_trained already exists, may use old results.
Not aligning basecalls to draft, calls_to_draft.bam exists.
Running medaka consensus
Traceback (most recent call last):
  File "/b_disk/JH/medaka_walkthrough/medaka/venv/lib/python3.6/site-packages/medaka-0.6.2-py3.6-linux-x86_64.egg/medaka/medaka.py", line 37, in __call__
    val = model_dict[val]
KeyError: 'training/model.best.val.hdf5'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/b_disk/JH/medaka_walkthrough/medaka/venv/bin/medaka", line 11, in <module>
    load_entry_point('medaka==0.6.2', 'console_scripts', 'medaka')()
  File "/b_disk/JH/medaka_walkthrough/medaka/venv/lib/python3.6/site-packages/medaka-0.6.2-py3.6-linux-x86_64.egg/medaka/medaka.py", line 249, in main
    args = parser.parse_args()
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/home/JH/miniconda3/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/b_disk/JH/medaka_walkthrough/medaka/venv/lib/python3.6/site-packages/medaka-0.6.2-py3.6-linux-x86_64.egg/medaka/medaka.py", line 41, in __call__
    self.dest, val)
RuntimeError: Filepath for '--model' argument does not exist and is not a known model ID (training/model.best.val.hdf5)
Failed to run medaka consensus.

So I changed the other files under the medaka/medaka/data/ to test.

I changed to r941_flip235_model.hdf5 and r941_trans_model.hdf5 and I will finish running successfully.

> medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${CONSENSUS} -t ${NPROC} -m medaka/medaka/data/r941_flip235_model.hdf5

> medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${CONSENSUS} -t ${NPROC} -m medaka/medaka/data/r941_trans_model.hdf5

I change to r941_213_model.hdf5 and the same error message will appear.

> medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o training_213 -t ${NPROC} -m medaka/medaka/data/r941_213_model.hdf5

error message

> RuntimeError: Filepath for '--model' argument does not exist and is not a known model ID (/b_disk/JH/medaka_walkthrough/medaka/medaka/data/r941_213_model.hdf5)
Failed to run medaka consensus.

I want to use my own data to train the model, but I will get an error message according to the instructions on the Walkthrough. I want to know how to solve this problem.

While following the instructions, I found a small problem. There is no --max_label_len parameter in features, but it is used in [train.](https://github.com/nanoporetech/medaka/blob/master/medaka/medaka.py#L154) Removing the --max_label_len parameter in the command should not affect the final result.

> cd ${WALKTHROUGH}
source ${MEDAKA}
REFNAME=utg000001c
TRAINEND=3762624
TRAINFEATURES=train_features.hdf
FRACTION="0.1 1"
BATCHSIZE=200
MODEL_FEAT_OPT=medaka/medaka/data/medaka_model.hdf5
medaka features ${CALLS2DRAFT}.bam ${TRAINFEATURES} --truth ${TRUTH2DRAFT}.bam --threads ${NPROC} --region ${REFNAME}:-${TRAINEND} --batch_size ${BATCHSIZE} --read_fraction ${FRACTION} --chunk_len 1000 --chunk_ovlp 0 --model ${MODEL_FEAT_OPT} --max_label_len 1

Thank you.

**Comment by cjw85** [comment]
If giving the model as a filename, this needs to be an absolute (full) path. To use the built in models you can use the names as described int he commandline help text (e.g. `-m r941_213`).

We will fix this so that relative paths are accepted.

**Comment by twolinin** [comment]
Successfully changed to absolute path.

The default model was trained using data obtained from E.coli, S.cerevisaie, and H.sapiens samples. The instructions on Walkthrough also demonstrate only one example. How to combine multiple samples, such as the default model?

**Comment by cjw85** [comment]
Glad to here that using an absolute path worked.

We have just refreshed the pipeline which we use to train the set of default models. This automates the process of the walkthrough at a large scale for many runs, samples, coverage depths.

The pipeline is available in our [katuali](https://github.com/nanoporetech/katuali) software and is detailed [here](https://nanoporetech.github.io/katuali/medaka_train.html).
