### ISSUE TITLE
Install with conda fails

### ISSUE THREAD

**Issue by veghp** [nanoporetech/medaka#340]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> Please ensure that you are using the most recent version of medaka before filing
> a bug report. The most recent version can be found on the [release page](https://github.com/nanoporetech/medaka/releases).
> If you are not using the most recent release, and file a issue regardless the
> most likely response from our developers will be to ask you to first upgrade.
>
> Please ensure also to provide the information below, not doing so will likely
> result in a request for the information.

**Describe the bug**
Running this command in the readme starts the install but then hangs (see output below):
```
conda create -n medaka -c conda-forge -c bioconda medaka
```
I also tried creating an environment (with Python 3.8) and install medaka there, but has the same error as in this report: https://github.com/nanoporetech/medaka/issues/332

Even though the env has the correct Python version, it still finds it incompatible. There are two conflicting medaka requirements listed in the error output in https://github.com/nanoporetech/medaka/issues/332 and I had the same -- could that be the issue?

**Logging**
Please attach any relevant logging messages. (Use \`\`\` before and after code blocks).
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: conda
 - OS: Ubuntu 18.04
 - medaka version (can be found by running `medaka --version`): N/A
 - GPU model: no GPU

**Comment by cjw85** [comment]
Hi again @veghp,

Conda can often often be glacially slow at the `Solving environment` step. I just ran the faster alternative [`mamba`](https://github.com/mamba-org/mamba) and saw no errors:

```
mamba create -n medaka -c conda-forge -c bioconda medaka
```

**Comment by veghp** [comment]
Okay, thanks. I tried on another machine and it seems to have installed the environment and the package.

**Comment by asan-emirsaleh** [comment]
Also conda stayed at this checkpoint for hours
```
$ conda create -n medaka-env -c conda-forge -c bioconda medaka
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment:  \
```
