### ISSUE TITLE
medaka_variant command not found

### ISSUE THREAD

**Issue by ogrecio** [nanoporetech/medaka#343]
I am interested on calling variants from a bam file and a reference genome in a diploid organism.

I installed medaka using miniconda (`conda create -n medaka -c conda-forge -c bioconda medaka`)

Then, I tried using medaka_variant, but it is returning command not found.

Any help?

`medaka --version`
medaka 1.5.0

Linux version: Linux version 3.10.0-862.14.4.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Sep 21 09:07:21 UTC 2018

**Comment by ogrecio** [comment]
solved

**Comment by tahashmi** [comment]
How did you solve it?

**Comment by cjw85** [comment]
The `medaka_variant` workflow for diploid variant calling is deprecated and no longer supported. Instead we recommend using https://github.com/HKU-BAL/Clair3

**Comment by tahashmi** [comment]
Okay. thanks.
