### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by svedwards** [nanoporetech/medaka#347]
You've misspelled an important, confidence-instilling word on your Medaka landing page:

"Improved accurary over graph-based methods"

Scott

> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> We provide no guarantees that feature requests will be implemented. They may
> be implemented if sufficient interest is generated or if the request aligns
> with research objectives.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cjw85** [comment]
@svedwards Thanks for this, I've fixed the typo in our development branch.
