### ISSUE TITLE
Add option to fill gaps in consensus sequence with 'N'

### ISSUE THREAD

**Issue by dhoconno** [nanoporetech/medaka#348]
**Is your feature request related to a problem? Please describe.**
The two options for a consensus file are to split areas with gaps into separate FASTQ entries (with `-g` or replacing gaps with reference sequence.

**Describe the solution you'd like**
Addition of a new flag that replaces gaps with `N` or another user-defined character, or passing a parameter to `-g` that does the same thing (e.g., `-g "N"`)

**Describe alternatives you've considered**
This could be implemented by re-mapping the consensus to the reference and parsing the output manually, but since these coordinates already exist to fill gaps in the consensus sequence with reference, it seems like it would be easy to implement in Medaka.

**Additional context**
This would be useful when using Medaka to generate quick-and-dirty SARS-CoV-2 consensus sequences by running ONT reads against a SARS-CoV-2 reference (e.g., NC_045512).

**Comment by cjw85** [comment]
For the specific context of using medaka for SARS-CoV-2 sequencing, this is already handled by the ARTIC field-bioinformatics analysis and derived pipelines such as our [wf-artic](https://www.github.com/epi2me-labs/wf-artic).

I'm unsure of a timeline to implement this into medaka, though its a relatively minor change. The heart of the filling is performed here: https://github.com/nanoporetech/medaka/blob/master/medaka/stitch.py#L113. That function would want to be modified with an option to not use the reference but instead `"N" * gap_length`, and the option plumbed into the command-line interface.

**Comment by cjw85** [comment]
This shoudl appear in the next release.
