### ISSUE TITLE
Medaka calls a 5 nt deletion instead of a 6 nt deletion with high accuracy basecaller

### ISSUE THREAD

**Issue by MarieLataretu** [nanoporetech/medaka#351]
**Describe the bug**
`medaka` calls a 5 nt deletion instead of a 6 nt deletion while reads support 6 nt deletion, see also https://github.com/artic-network/fieldbioinformatics/issues/100:

![igv_snapshot_run382_del](https://user-images.githubusercontent.com/52002068/151808283-eeacd4c7-33b3-49a8-9e2b-61eda43085dd.png)
(barcode20 -> 6 nt deletion; barcode16,18 -> 5 nt deletion)

`medaka` call (within ARTIC):
```
medaka consensus --model r941_min_hac_g507 --threads 16 --chunk_len 800 --chunk_ovlp 400 --RG 2 barcode16.trimmed.rg.sorted.bam barcode16.2.hdf
medaka variant external_primer_schemes/nCoV-2019/V4.1/nCoV-2019.reference.fasta barcode16.2.hdf barcode16.2.vcf
```
results in (`barcode16.2.vcf`)
`MN908947.3	21765	.	TACATG	T	164.271	PASS	DP=606.0;DPS=318.0,288.0	GT:GQ	1:164`

Expected variant:
`MN908947.3	21764	.	ATACATG	A	152.788	PASS	DP=1000;DPS=500,500;Pool=2	GT:GQ	1:153`

We see the 5 nt deletion in only a few samples.

**Environment:**
 - in Singularity container via pip
 - OS: Linux
 - medaka 1.5.0 and medaka 1.4.3 (inside ARTIC)

(Let me know if other environment setting are of interest - I'll try to find them out.)

**Additional context**
solved with sup (super-acc) basecalling and respective `medaka` model

**Comment by cjw85** [comment]
I don't think there's much to say here other than the algorithms in medaka aren't perfect. Your IGV screenshot does show that there is a population of bases present in reads within the deletion and its reasonable to rationalise this as being why medaka has suggested only a five base deletion. It looks like you have lower coverage on the following bases also; I wonder if this is confusing things.

As you've noted a 6-bp deletion is called with the sup-basecalling model, which we'd recommend using in any case.

**Comment by MarieLataretu** [comment]
Thanks, @cjw85 , for your answer!

So you see no way to optimize the parameter or something, other than using sup-basecalled data?

Yes, I also noticed the slight coverage drop at the two following bases, but we see this also in the 6 nt samples.
(I updated the IGV screenshot which is less crowded. )

**Comment by cjw85** [comment]
Correct. With your updated screenshot it looks like theres such ambiguity in the basecalls and alignments that there's not much consistent that medaka can interpret. The most obvious statement is that it appears some Ts could be shuffled from the left-handside of the deletion to the neighbouring T.
