### ISSUE TITLE
-d must be specified Error

### ISSUE THREAD

**Issue by lucyintheskyzzz** [nanoporetech/medaka#355]
Hi ,
I was wondering why I am getting this error at the end? It is weird, because this code worked on my 2 other barcodes. Thanks!

```
(/lustre/project/taw/share/conda-envs/medaka-env) [kvigil@cypress1 FASTQ_concat]$ BASECALLS=/lustre/project/taw/ONR01202
1/FASTQ_concat/barcode02.fastq DRAFT=/lustre/project/taw/ONR012021/canu/barcode02/barcode02canu.contigs.fasta OUTDIR=/lu
stre/project/taw/ONR012021/canu/medaka/barcode02 NPROC=20 medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t $
{NPROC} -m r941_min_high_g330

medaka 1.4.4
------------

Assembly polishing via neural networks. The input assembly should be
preprocessed with racon.

medaka_consensus [-h] -i <fastx>

    -h  show this help text.
    -i  fastx input basecalls (required).
    -d  fasta input assembly (required).
    -o  output folder (default: medaka).
    -g  don't fill gaps in consensus with draft sequence.
    -m  medaka model, (default: r941_min_hac_g507).
        Available: r103_fast_g507, r103_fast_snp_g507, r103_fast_variant_g507, r103_hac_g507, r103_hac_snp_g507, r103_hac_variant_g507, r103_min_high_g345, r103_min_high_g360, r103_prom_high_g360, r103_prom_snp_g3210, r103_prom_variant_g3210, r103_sup_g507, r103_sup_snp_g507, r103_sup_variant_g507, r104_e81_fast_g5015, r104_e81_hac_g5015, r104_e81_sup_g5015, r10_min_high_g303, r10_min_high_g340, r941_min_fast_g303, r941_min_fast_g507, r941_min_fast_snp_g507, r941_min_fast_variant_g507, r941_min_hac_g507, r941_min_hac_snp_g507, r941_min_hac_variant_g507, r941_min_high_g303, r941_min_high_g330, r941_min_high_g340_rle, r941_min_high_g344, r941_min_high_g351, r941_min_high_g360, r941_min_sup_g507, r941_min_sup_snp_g507, r941_min_sup_variant_g507, r941_prom_fast_g303, r941_prom_fast_g507, r941_prom_fast_snp_g507, r941_prom_fast_variant_g507, r941_prom_hac_g507, r941_prom_hac_snp_g507, r941_prom_hac_variant_g507, r941_prom_high_g303, r941_prom_high_g330, r941_prom_high_g344, r941_prom_high_g360, r941_prom_high_g4011, r941_prom_snp_g303, r941_prom_snp_g322, r941_prom_snp_g360, r941_prom_sup_g507, r941_prom_sup_snp_g507, r941_prom_sup_variant_g507, r941_prom_variant_g303, r941_prom_variant_g322, r941_prom_variant_g360.
        Alternatively a .hdf file from 'medaka train'.
    -f  Force overwrite of outputs (default will reuse existing outputs).
    -t  number of threads with which to create features (default: 1).
    -b  batchsize, controls memory use (default: 100).

-d must be specified.
(/lustre/project/taw/share/conda-envs/medaka-env) [kvigil@cypress1 FASTQ_concat]$
```

**Comment by cjw85** [comment]
Hi @lucyintheskyzzz,

I cannot immediate see a problem here. The error suggests that the options are not being interpreted correctly from the command.

```
BASECALLS=/lustre/project/taw/ONR012021/FASTQ_concat/barcode02.fastq
DRAFT=/lustre/project/taw/ONR012021/canu/barcode02/barcode02canu.contigs.fasta
OUTDIR=/lustre/project/taw/ONR012021/canu/medaka/barcode02
NPROC=20
medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t ${NPROC} -m r941_min_high_g330
```

**Comment by lucyintheskyzzz** [comment]
What do you recommend? reinstall medaka?

**Comment by lucyintheskyzzz** [comment]
Do I have to use Racon for pre-polishing first? I only used canu for assembly and went straight into Medaka after with that fasta file.

**Comment by cjw85** [comment]
Racon need not be used prior to use of medaka, the message above is erroneous and will be fixed in our next release.

For your continued issues with the `-d` parameter; I would suggest not setting shell variables before giving the parameters to the program and simply run (copy and paste the below):

```
medaka_consensus -i /lustre/project/taw/ONR012021/FASTQ_concat/barcode02.fastq -d /lustre/project/taw/ONR012021/canu/barcode02/barcode02canu.contigs.fasta -o /lustre/project/taw/ONR012021/canu/medaka/barcode02 -t 20 -m r941_min_high_g330
```

I'm afraid I cannot really provide more assistance because the above command as written should work.

**Comment by lucyintheskyzzz** [comment]
like this?- it now says medaka_consensus not found

 BASECALLS=/lustre/project/taw/ONR012021/FASTQ_concat
/barcode02.fastq DRAFT=/lustre/project/taw/ONR012021/canu/barcode02/barcode02canu.contigs.fasta OUTDIR=/lustre/project/taw/ONR012021/canu/medaka/barcode02 NPROC=20 medaka_consensus -i /lustre/project/taw/ONR012021/FASTQ_concat/barcode02.fas
tq -d /lustre/project/taw/ONR012021/canu/barcode02/barcode02canu.contigs.fasta -o /lustre/project/taw/ONR012021/canu/med
aka/barcode02 -t 20 -m r941_min_high_g330
-bash: medaka_consensus: command not found

**Comment by lucyintheskyzzz** [comment]
medaka_consensus -i /lustre/project/taw/ONR012021/FASTQ_concat/barcode02.fastq -d /lustre/project/taw/ONR012021/canu/barcode02/barcode02canu.contigs.fasta -o /lustre/project/taw/ONR012021/canu/medaka/barcode02 -t 20 -m r941_min_high_g330
-bash: medaka_consensus: command not found

**Comment by cjw85** [comment]
The error

```medaka_consensus: command not found```

would suggest that your environment does not have medaka installed. Are you using a virtual or conda environment, you will need to ensure you have always activated such an environment before running `medaka_consensus`.
