### ISSUE TITLE
numpy version error 

### ISSUE THREAD

**Issue by lfurn** [nanoporetech/medaka#356]
Hi I am attempting run medaka on a HPC. I installed with conda and I am getting this error:

/scipy/__init__.py:146: UserWarning: A NumPy ver$
  warnings.warn/mnt/nfs/home/b6046230/.conda/envs/medaka/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarni$
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/mnt/nfs/home/b6046230/.conda/envs/medaka/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy ver$
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
mkdir: cannot create directory ‘consensus’: Permission denied

The numpy version in the conda medaka environment is 1.19.5, scipy is 1.8.0, medaka is 1.5.0

I've messed around with versions a bit but can't get anything to work. I am also not sure why permission is denied for making directory - that has not been an issue for other programmes I run on the HPC.

**Comment by cjw85** [comment]
Hi @lfurn 

Can you confirm that you are getting this error when you install medaka or when you try to use it? The above doesn't look like a complete error log, can you share all errors that are shown.

**Comment by cjw85** [comment]
Closing, assuming this is a permissions error in the users environment.
