### ISSUE TITLE
medaka to output unpolished sequences

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/medaka#36]
After polishing with medaka it appears that I have fewer sequences than I put in. I assume that medaka gets rid of some of them for some reason e.g. they do not get polished. 

Any chance that you can include an option to keep all sequences similarly to the "--include-unpolished" option in racon?

**Comment by cjw85** [comment]
Hi Rasmus,

You are correct that medaka can occasionally drop sequences that it is unable to process (for a variety of reasons). See the discussion in #35 for a somewhat related issue.

We plan to rewrite how medaka writes its output, as part of this we will include an option to write the dropped sequences.
