### ISSUE TITLE
Medaka documentation at https://nanoporetech.github.io/

### ISSUE THREAD

**Issue by waltergallegog** [nanoporetech/medaka#362]
Hello,
I'm following the epi2meLabs tutorials on SNP using Medaka
The following link is mentioned:
>The workflow used within Medaka to call variants in human whole genome sequencing is outlined in the [documentation](https://nanoporetech.github.io/medaka/snp.html)

But the link does not exists.
Where can i find the Medaka documentation? I tried searching in https://nanoporetech.github.io/ but could not find anything.
Thanks.

**Comment by cjw85** [comment]
The `medaka_variant` small variant workflow is no longer supported. Instead we recommend [clair3 ](https://github.com/HKU-BAL/Clair3)for small variant calling in diploid samples. The tutorial requires updating.

https://github.com/epi2me-labs/tutorials/issues/27
