### ISSUE TITLE
ontresearch/epi2melabs-notebook medaka and bcftools dependency issue

### ISSUE THREAD

**Issue by rjwswenson** [nanoporetech/medaka#363]
Currently I am experiencing an issue running medaka provided in either ontresearch/epi2melabs-notebook v1.1.11 or v1.1.14 jupyterlab notebook docker images that we heavily utilize for our interactive pipelines we are running for secondary-to-tertiary analysis.  Medaka fails to run, due to a bcftools dependency, and in general bcftools fails to run when we run **bcftools -v**. The following error is returned:

``` bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory```

We prefer to use medaka_consensus for our polishing strategy.  I would rather employ this then use the combination of racon, canu, and pilon. 

I have tried setting LD_LIBRARY_PATH, but I do not know in which lib location is the libgsl.so.25.  Can somebody recommend the path and/or how do we resolve this error since medaka and bcftools are already built or provided in the docker image itself?  Sorry, also, this may be the wrong repo or channel to open this issue. I could not find a repo for the main ontresearch/epi2melabs-notebook in which its original dockerfile is maintained, to open the issue there.

**Comment by cjw85** [comment]
Hi @rjwswenson 

If helps us tremendously if you can use the issue templates as provided.

That being said I cannot reproduce this error using the epi2melabs-notebook v1.1.14 server container started with the EPI2ME Labs Launcher.

![image](https://user-images.githubusercontent.com/3592009/159894553-2491abd0-7dd0-44cf-93c4-0e3486bdd799.png)

**Comment by rjwswenson** [comment]
Understood.

The launcher appears to be a bit quirky too, as I have clicked Update in one of my envs, and on itslauncher, it is not updating to v1.1.14.  In the other env, which has the latest, I do not know why it has the same error. In your environment with v1.1.14, can you verify what path location the libgsl.so.25 is located?

Thanks,
Ryan







From: cjw85 ***@***.***>
Reply-To: nanoporetech/medaka ***@***.***>
Date: Thursday, March 24, 2022 at 6:16 AM
To: nanoporetech/medaka ***@***.***>
Cc: Ryan Swenson ***@***.***>, Mention ***@***.***>
Subject: Re: [nanoporetech/medaka] ontresearch/epi2melabs-notebook medaka and bcftools dependency issue (Issue #363)


Hi @rjwswenson<https://github.com/rjwswenson>

If helps us tremendously if you can use the issue templates as provided.

That being said I cannot reproduce this error using the epi2melabs-notebook v1.1.14 server container started with the EPI2ME Labs Launcher.

[Image removed by sender. image]<https://user-images.githubusercontent.com/3592009/159894553-2491abd0-7dd0-44cf-93c4-0e3486bdd799.png>

**Comment by rjwswenson** [comment]
Resolved upon manually pulling v1.1.14 and restarting the launcher. The utility now works properly.

From: Ryan Swenson ***@***.***>
Date: Thursday, March 24, 2022 at 6:25 AM
To: nanoporetech/medaka ***@***.***>, nanoporetech/medaka ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [nanoporetech/medaka] ontresearch/epi2melabs-notebook medaka and bcftools dependency issue (Issue #363)

Understood.

The launcher appears to be a bit quirky too, as I have clicked Update in one of my envs, and on itslauncher, it is not updating to v1.1.14.  In the other env, which has the latest, I do not know why it has the same error. In your environment with v1.1.14, can you verify what path location the libgsl.so.25 is located?

Thanks,
Ryan







From: cjw85 ***@***.***>
Reply-To: nanoporetech/medaka ***@***.***>
Date: Thursday, March 24, 2022 at 6:16 AM
To: nanoporetech/medaka ***@***.***>
Cc: Ryan Swenson ***@***.***>, Mention ***@***.***>
Subject: Re: [nanoporetech/medaka] ontresearch/epi2melabs-notebook medaka and bcftools dependency issue (Issue #363)


Hi @rjwswenson<https://github.com/rjwswenson>

If helps us tremendously if you can use the issue templates as provided.

That being said I cannot reproduce this error using the epi2melabs-notebook v1.1.14 server container started with the EPI2ME Labs Launcher.

[Image removed by sender. image]<https://user-images.githubusercontent.com/3592009/159894553-2491abd0-7dd0-44cf-93c4-0e3486bdd799.png>

**Comment by cjw85** [comment]
The library is located in a standard location for things installed via conda:

![image](https://user-images.githubusercontent.com/3592009/159896664-a050ccc9-47e8-46f4-b7db-4bc30bdc034d.png)

**Comment by rjwswenson** [comment]
Ok, well this is strange.  In my environment with v1.1.11, I manually docker pulled the v1.1.14 image, and restarted the epi2me launcher, and verified that bcftools was runnable.  I went back to finish writing logic to run medaka and was excited to then go give it a try in the actual HPC environment connected to the sequencers that we have, and where it was having the same issue, I found it was running v1.1.6 and v1.1.14, but that the launcher and instance running was bound to v1.1.6. I removed this image, and restarted and now with v1.1.14, bcftools was runnable.  I had a few more edits to make in my dev env, and then it threw the same error as before, I returned to this env, and the same error is occurring.   I suspect it is in a standard location, now I just need to figure out what that is, because apparently something is happening that is not being controlled by us.  E.g. I haven’t restarted docker or Jupyter kernels  and sessions, etc while actively working on coding.




From: cjw85 ***@***.***>
Reply-To: nanoporetech/medaka ***@***.***>
Date: Thursday, March 24, 2022 at 7:28 AM
To: nanoporetech/medaka ***@***.***>
Cc: Ryan Swenson ***@***.***>, Mention ***@***.***>
Subject: Re: [nanoporetech/medaka] ontresearch/epi2melabs-notebook medaka and bcftools dependency issue (Issue #363)


The library is located in a standard location for things installed via conda:

[Image removed by sender. image]<https://user-images.githubusercontent.com/3592009/159896664-a050ccc9-47e8-46f4-b7db-4bc30bdc034d.png>
