### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by abeliavskaia** [nanoporetech/medaka#367]
Hi! 
I am getting the Segmentation fault error at the end of the Medaka pipeline. 
I tried to run 'medaka_consensus' or three steps separately (mini_align, medaka consensus, medaka stitch), but it doesn't make a difference. In the case of running separate steps, the error appears at the 'stitch' step. 

Any ideas on what might cause it? I found a similar [issue](https://github.com/nanoporetech/medaka/issues/212#issue-715972264), although couldn't find an answer there. I installed medaka with conda.

**Comment by cjw85** [comment]
Hi @abeliavskaia 

It helps us greatly if you can use the issue template provided. Please open a new issue supplying the requested information.
