### ISSUE TITLE
using hdf from medaka_variant for polishing

### ISSUE THREAD

**Issue by MichelMoser** [nanoporetech/medaka#37]
Hello, 

I would like to call variants on realigned reads to an assembly and at the same time polish the assembly. I see that medaka_variant produces a hdf file (`round_0_hap_mixed_probs.hdf`) similar to the one used in medaka_consensus. Is it advisable to use the same hdf, so one could go directly for stitching with `round_0_hap_mixed_probs.hdf`? 
Or are different mapping parameters used to produce `consensus_probs.hdf`?

Thanks, 
Michel

**Comment by cjw85** [comment]
Currently the file `round_0_hap_mixed_probs.hdf` produced by `medaka_variant` is indeed the same as would be produced by `medaka_consensus` and could be used with `medaka stitch` to create a consensus sequence.

Note that `medaka_variant` is specialised to diploid variant calling.
