### ISSUE TITLE
Cannot find documentation for Medaka

### ISSUE THREAD

**Issue by zztin** [nanoporetech/medaka#371]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> Please ensure that you are using the most recent version of medaka before filing
> a bug report. The most recent version can be found on the [release page](https://github.com/nanoporetech/medaka/releases).
> If you are not using the most recent release, and file a issue regardless the
> most likely response from our developers will be to ask you to first upgrade.
>
> Please ensure also to provide the information below, not doing so will likely
> result in a request for the information.

**Describe the bug**
Hi, 
I remembered Medaka used to have a documentation that describe the performance and step-by-step usage. Can anyone point me to it? I cannot find it anymore.

**Logging**
Please attach any relevant logging messages. (Use \`\`\` before and after code blocks).

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: [e.g. Ubuntu 16.04]
 - medaka version (can be found by running `medaka --version`)
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by cjw85** [comment]
Hi @zztin,

I think you're possibly referring to this:
https://github.com/nanoporetech/medaka#improving-parallelism

We removed the standalone documentation site as it was becoming out of date. All the still relevant parts have been moved into the README file.

**Comment by zztin** [comment]
Hi @cjw85,

Thank you for the explanation!

Best,
Liting
