### ISSUE TITLE
r941_e81 model?

### ISSUE THREAD

**Issue by gallardo-seq** [nanoporetech/medaka#372]
Hi Medaka team, I realize this might not be the highest priority (particularly with LC22 around the corner), but was wondering if you have any r941_e81 models lying around? We have a project where we used R9.4.1 in combination with the the LSK112 kit, and even though guppy has a model for basecalling, I was not able to find a corresponding model for medaka. Any help/insights would be much appreciated.

**Comment by cjw85** [comment]
Let me see if I can dig one out. R9.4.1 with LSK112 isn't an entirely supported combination: we toyed with it for a while but efforts are all now on LSK114.

**Comment by caonetto** [comment]
Any updates on this? We are facing the same situation.

**Comment by gallardo-seq** [comment]
Looks like this was addressed in v1.6.1. released a couple of days ago (https://github.com/nanoporetech/medaka/blob/master/medaka/data/r941_e81_sup_g514_model.tar.gz). Already seeing improvements in accuracy metrics. Thanks @cjw85 and team for your help with this.
