### ISSUE TITLE
medaka versions Mac vs Linux

### ISSUE THREAD

**Issue by antoine4ucsd** [nanoporetech/medaka#373]
hello
I am trying to run medaka on my mac 
installed successful with conda BUT latest version is 
```
This is medaka 1.0.3
Program    Version    Required   Pass     
bcftools   1.10.2     1.9        True     
bgzip      1.10.2     1.9        True     
minimap2   2.24       2.11       True     
samtools   1.10       1.9        True     
tabix      1.10.2     1.9        True 
```
when running medaka_consensus , I got no output...
```
 medaka_consensus -i 0_alignment.sam -d 0_haplotype.fasta  -o 0_polished_haplotype
```
if I try on a linux machine with pip. 
```
This is medaka 1.6.0
Program    Version    Required   Pass     
bcftools   1.15       1.11       True     
bgzip      1.15       1.11       True     
minimap2   2.24       2.11       True     
samtools   1.15       1.11       True     
tabix      1.15       1.11       True   
```
then the command above give me the expected output
```
 medaka_consensus -i 0_alignment.sam -d 0_haplotype.fasta  -o 0_polished_haplotype
```
is there a way to install the latest medaka on my Mac (pip not working )??

thank you!

**Comment by cjw85** [comment]
You'll have to take up the issue with the conda package with the people at @bioconda I'm afraid; I've given up on that front, see my comments [here](https://github.com/bioconda/bioconda-recipes/pull/33669#issuecomment-1069285343).

Installation with pip on macOS will required compilation from the source distribution as we've never added macOS wheels unfortunately. If you paste what errors you get trying to do a `pip install medaka==1.6.0` I can guide you through what might be going wrong.

**Comment by srnarum** [comment]
I am also trying to install medaka on macOS with pip. After the command:
```
pip install medaka
``` 
I get the error:
  clang-16: error: unsupported argument 'haswell' to option '-mtune='

**Comment by cjw85** [comment]
Closing due to lack of response.
