### ISSUE TITLE
R10.4.1 model?

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/medaka#374]
Hi 

Do you have an estimate of when a model for R10.4.1 data will be available?

Best regards
Rasmus

**Comment by cjw85** [comment]
I believe we have them, I'm not sure why they haven't been released. I'll pick this up after the weekend.

**Comment by Kirk3gaard** [comment]
Wednesday is perfectly fine. No need to get into trouble with product management ;).

**Comment by Kirk3gaard** [comment]
Which Wednesday did you refer to?

**Comment by cjw85** [comment]
I did mean last Wednesday :(

We have a version ready to go, it's working its way through our build and deployment system at the moment.

**Comment by cjw85** [comment]
v1.6.1 is now available on GitHub and PyPI.

**Comment by Kirk3gaard** [comment]
Great. Thanks a lot :D
