### ISSUE TITLE
CPU usage to high

### ISSUE THREAD

**Issue by VadimRakitin** [nanoporetech/medaka#375]
Hi! I run Medaka on an institutional server. But the CPU usage goes up to 100% which is not desirable. I use -b 50function but it has no effect on reducing CPU usage. Any advice? Am I using wrong function?

![afbeelding](https://user-images.githubusercontent.com/83976249/174278313-3360d983-87cc-4485-81e0-dd6252fc4c09.png)

**Comment by cjw85** [comment]
Hi @VadimRakitin,

Could you please reopen an issue and use the issue template to provide all the requested information.
