### ISSUE TITLE
test suite generates untracked files

### ISSUE THREAD

**Issue by tkonopka** [nanoporetech/medaka#378]
**Describe the bug**

Running `make test` creates untracked files in the repository root, which is unexpected.

```
.coverage
data.pickle
test_hap1.vcf
test_hap2.vcf
test_ref.fasta
```

**Logging**

NA

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: from github source
 - OS: Ubuntu 20.04
 - medaka version: 1.6.1
 - GPU model: No GPU
 - Nvidia driver version: 10.1

**Additional context**

Would it be alright to include `.coverage` in `.gitignore`?

As far as I can tell, the other files are not needed to run the test suite, and it would be strange if they were needed elsewhere. Would it be alright to remove these?

I can prepare a PR with these changes if you agree.

**Comment by cjw85** [comment]
@mwykes Would be good to track from which tests these are coming and make sure they are being written to a proper tempdir.

**Comment by cjw85** [comment]
I have fixed this on our development branch.
