### ISSUE TITLE
Choosing the right model

### ISSUE THREAD

**Issue by pbelmann** [nanoporetech/medaka#380]
Hi,

thank you for developing this tool!
I would like to use medaka for polishing a dataset where I only have information about the device.
Would it still make sense to use medeka with a model randomly chosen just based on the device used?

**Comment by pbelmann** [comment]
Hi @cjw85,

thank you for your fast reply!

> From where has your data come? 

The idea is actually to process datasets that are available on SRA. So my question is not bound to a specific dataset but is a more general question regarding datasets where I do not have the information needed to run medaka. In most cases I really just get the used "instrument" from the SRA metadata. 
Example Dataset: http://ftp.era.ebi.ac.uk/vol1/fastq/ERR499/008/ERR4994318/ERR4994318.fastq.gz

> It might be the case that the fastq headers contain useful information that can help us advise you.

Do you mean that the device or the basecaller version is encoded in the header?

> Failing that, if you know an approximate time perioid when sequencing/basecalling was performed we can take a best guess assuming the most recent Guppy version was used at the time.

Based on the SRA  'release date' attribute I could indeed get the rough time period. So you would suggest to check which guppy version was the most recent one? Where would I get this information?

**Comment by cjw85** [comment]
The basecaller version and model is encoded in the fastq headers for more recent data, older datasets will not have this.

The guppy CHANGELOG contains release dates. I don't know if this is bundled in the Guppy distribution. Its available in the Nanopore Community (sorry, needs a sign in) https://community.nanoporetech.com/downloads/guppy/release_notes

**Comment by Lobna-H** [comment]
Could you please advise on which model should be used for medaka for polishing a long read sequenced genome recovered by using flow cell FLO-MIN114, Guppy version 6.3.8, and super accurate basecalling? Is it r103_min_high_g360?
