### ISSUE TITLE
parameters for minimap2

### ISSUE THREAD

**Issue by inemp** [nanoporetech/medaka#382]
Hello,

I am running 
medaka_consensus -i toMount/alsoGoodDataDiv16.fastq -d toMount/small.fa -o experimentFolder -m r1041_e82_400bps_sup_g615

The first step in the pipeline I notice is 
minimap2 -I 16G -x map-ont -d /toMount/small.fa.map-ont.mmi /toMount/small.fa

Did you experiment with other parameters of minimap2? If yes, did it have big impact on the result, or regardless of minimap parameters , the pipeline performs always similarly? 

I know this is mainly a minimap question, but it is an important step of the pipeline

**Comment by cjw85** [comment]
We have not performed a systematic study of the effect of varying the minimap2 parameters recently. However the consensus model in medaka is trained against alignments using the parameters as stated in the helper script.
