### ISSUE TITLE
possibility to call mixed bases ?

### ISSUE THREAD

**Issue by alantsangmb** [nanoporetech/medaka#383]
Hello, I am trying medaka implemented in wf-artic to do CoV WGS.
Just wondering whether medaka could call mixed bases when a minor variant exceed a certain frequency threshold?
For example, a 'Y' can be called in the consensus sequences when both C and T are detected.
Thank you

**Comment by cjw85** [comment]
Hi @alantsangmb,

I don't think it likely that this feature be implemented. At its heard medaka is a consensus caller, not a variant caller -- it is not setup to provide indications of mixed populations of bases at a locus.
