### ISSUE TITLE
Medaka fails to complete.

### ISSUE THREAD

**Issue by tnn111** [nanoporetech/medaka#385]
Medaka version 1.7.1 fails with the attached message. It's a CentOS system with an A100, Driver Version: 460.32.03    CUDA Version: 11.2.

Any suggestions? The command line is:

/usr/bin/time medaka_consensus -i Ashby0005_nano.fastq -d results_flye/assembly.fasta -o medaka -t 24 -m r941_min_sup_g507 &> medaka.log &

> [21:51:27 - TrimOlap] contig_14166:0.0-5179.0 and contig_14166:5210.0-5855.0 cannot be concatenated as there is no overlap and they do not abut.
> [21:51:27 - TrimOlap] contig_14166:5210.0-5855.0 and contig_14166:6204.0-7699.0 cannot be concatenated as there is no overlap and they do not abut.
> [21:51:27 - DataIndx] Loaded 1/1 (100.00%) sample files.
> [21:51:27 - TrimOlap] contig_8404:0.0-1108.0 and contig_8404:1416.0-4745.0 cannot be concatenated as there is no overlap and they do not abut.
> [E::fai_retrieve] Failed to retrieve block: unexpected end of file
> Traceback (most recent call last):
>   File "/home/torben/opt/mambaforge/envs/medaka/bin/medaka", line 11, in <module>
>     sys.exit(main())
>   File "/home/torben/opt/mambaforge/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 724, in main
>     args.func(args)
>   File "/home/torben/opt/mambaforge/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 229, in stitch
>     contigs, gt = fill_gaps(contigs, args.draft, args.fill_char)
>   File "/home/torben/opt/mambaforge/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 128, in fill_gaps
>     draft_seq = draft.fetch(ref_name)
>   File "pysam/libcfaidx.pyx", line 317, in pysam.libcfaidx.FastaFile.fetch
> BlockingIOError: [Errno 11] b'Resource temporarily unavailable'
> Failed to stitch consensus chunks.
> Command exited with non-zero status 1
> 42173.47user 5962.48system 1:25:21elapsed 939%CPU (0avgtext+0avgdata 19757920maxresident)k
> 5763728inputs+88325544outputs (381major+1071758484minor)pagefaults 0swaps

**Describe the bug**
A clear and concise description of what the bug is including the command that you have run.

**Logging**
Please attach any relevant logging messages. (Use \`\`\` before and after code blocks).

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: [e.g. Ubuntu 16.04]
 - medaka version (can be found by running `medaka --version`)
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by tnn111** [comment]
I redid my conda setup and the problem went away. It looks like a Python issue.

**Comment by DanaBlu** [comment]
Hi @tnn111! 
I have exactly the same problem with the latest version of Medaka (1.11.3). I also tried it with an older version of Medaka (1.7.2) in combination with an old version of Python (3.8). Do you remember what exactly you did with your conda setup to solve the problem?
Best, Dana!

**Comment by michoug** [comment]
Hi @DanaBlu 
Use the `-x` option to regenerate the indexes at the start, it was the issue for me
Best
Greg
