### ISSUE TITLE
Anaconda install fails silently

### ISSUE THREAD

**Issue by eoli3n** [nanoporetech/medaka#387]
**Describe the bug**
When I install medaka in a conda env (anaconda fresh install, up to date), it fails after trying to solve environment, without any error.

**Logging**
```
root@jammy:/net/apps/anaconda3/bin# ./conda create -n bioinfo -c conda-forge -c bioconda medaka busco
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - Processus arrêté
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method : conda
 - OS: Ubuntu 22.04

**Comment by cjw85** [comment]
Please raise this on bioconda, the issue is not with medaka per se.

**Comment by eoli3n** [comment]
Ok, thanks
