### ISSUE TITLE
variant calling for gbk files?

### ISSUE THREAD

**Issue by katefgit** [nanoporetech/medaka#388]
I just started using me `medaka_haploid_variant` to find SNP between ONT reads and HA. I can see that it doesn't work with gbk file (as for e.g. when working with breseq software and Illumina reads). Is this right? and is there an alternative?

**Comment by cjw85** [comment]
Medaka does not support gbk files as input, only fasta. If you wish to annotate the output VCF file you will need to use a standalone program dedicated to that task.
