### ISSUE TITLE
Tensorflow and Python version upgrade request: Tensorflow >=2.8.0 for Python 3.10 support

### ISSUE THREAD

**Issue by StephDC** [nanoporetech/medaka#396]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> We provide no guarantees that feature requests will be implemented. They may
> be implemented if sufficient interest is generated or if the request aligns
> with research objectives.

**Is your feature request related to a problem? Please describe.**
medaka does not support python version >=3.10

With some investigation it seems that the root cause of such is that the specified version of tensorflow (v.2.7.0) do not support python version >=3.10

**Describe the solution you'd like**
- Upgrade the tensorflow version to at least 2.8.0 so python 3.10 is supported.
- Run the python test on python 3.10, and if no issue is found
- Make a new release to PyPI with Requires-Python that is higher.

**Describe alternatives you've considered**
State the required python version on README so we know which version of medaka require which version of python.

**Additional context**
I am attempting to run this software on Gentoo, and Gentoo has upgraded python to python3.10 a little while ago. When I try to install it with pip, I was greeted with the error message of all versions of medaka requires a different python version.

When attempting to compile medaka from scratch against python 3.10, I figured out that the tensorflow 2.7.0 is not available on python 3.10. After changing tensorflow to 2.8.0 and allowing python 3.10, it seems that `make install` can complete successfully, although further testing is not done yet.

**Comment by asan-emirsaleh** [comment]
Was the upgrade successful? Did medaka proceed with both python and TF being upgraded?

**Comment by cjw85** [comment]
The Tensorflow dependency has been upgraded to to 2.8 in v1.7.3 of medaka.
