### ISSUE TITLE
medaka command and medaka_consensus errors

### ISSUE THREAD

**Issue by eprileson** [nanoporetech/medaka#397]
Hi, I am having issues running the basic ```medaka_consensus``` command on Linux environment (no GPU)

I installed the latest version of ```medaka``` v1.7.2 following the GitHub source instructions:
```git clone https://github.com/nanoporetech/medaka.git```
```cd medaka```
```make install```
```. ./venv/bin/activate ```

which installed successfully I believe as all directories installed in my directories match those from the GitHub directories. However, when I try to run the ```medaka_consensus``` program:
```medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t ${NPROC} -m r941_min_high_g303```
 it gives the same error each time:
```/home/egp43/medaka/scripts/medaka_consensus: line 12:  medaka: command not found```
On the ```medaka_consensus``` script at line 12, the command throwing the error is the ```(medaka --version)``` command.

It seems like there is a general issue with either installation or missing  packages that I'm not aware of as the same error is thrown trying to run any medaka command on the command line, eg. ```medaka -h```
This is despite the medaka environment being activated.

Any help towards this would be appreciated!
Thanks,

**Comment by cjw85** [comment]
Hi @eprileson,

Is there a particular reason you want to compile and use the code from source. The preferred method is to use simply the packages from PyPI.

**Comment by eprileson** [comment]
Hi @cjw85, thanks for your reply;
The reason we want to use the code from source is that we're using a MacOS system and receive the error:
```
error: subprocess-exited-with-error
```
and so we decided to use the GitHub source

**Comment by eprileson** [comment]
Following up on this, the same error occurred with the packages installed from PyPI:
```
medaka_consensus: line 12: medaka: command not found
```

**Comment by cjw85** [comment]
Can you provide detailed of you OS and environment setup and describe precisely what you have done to install medaka to lead to this error?

**Comment by eprileson** [comment]
I am running a Markov interactive desktop (Xfce) through our University's HPC ondemand portal with a Linux system.
I installed the latest version of medaka v1.7.2 following the pip install instructions:

```
virtualenv medaka --python=python3 --prompt "(medaka) "
. medaka/bin/activate
pip install medaka
```
which installed the software successfully I believe. However, when I try to run the medaka_consensus program:
```
medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t ${NPROC} -m r941_min_high_g303
```
it gives the same error from before:
```/home/egp43/medaka/scripts/medaka_consensus: line 12: medaka: command not found ```
On the medaka_consensus script at line 12, the command throwing the error is the (```medaka --version```) command.

**Comment by cjw85** [comment]
I apologise for the lack of reply here.

However I don't know that I have much more to add. It strange that `medaka_consensus` is on your PATH but not `medaka`. They are both installed into the virtual environment together. Can you run `medaka` directly?
