### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by nadakubikova** [nanoporetech/medaka#40]
Hello,
I am having trouble with the installation of Medaka. I tried conda and pip, pip, as recommended and build from the source but the following error occur: 

**Nadas-MBP:~ nadakubikova$ conda install -c bioconda medaka**
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - medaka
  - intervaltree[version='>=3.0.0']
  - medaka
  - whatshap==0.18

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Nadas-MBP:~ nadakubikova$ pip install medaka**
Collecting medaka
  Could not find a version that satisfies the requirement medaka (from versions: )
No matching distribution found for medaka
**Nadas-MBP:~ nadakubikova$ virtualenv medaka --python=python3 --prompt "(medaka) "**
Running virtualenv with interpreter /Users/nadakubikova/anaconda3/bin/python3
Using base prefix '/Users/nadakubikova/anaconda3'
/Library/Python/2.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Overwriting /Users/nadakubikova/medaka/lib/python3.7/orig-prefix.txt with new content
New python executable in /Users/nadakubikova/medaka/bin/python3
Not overwriting existing python script /Users/nadakubikova/medaka/bin/python (you must use /Users/nadakubikova/medaka/bin/python3)
Installing setuptools, pip, wheel...done.
**Nadas-MBP:~ nadakubikova$ . medaka/bin/activate**
**(medaka) Nadas-MBP:~ nadakubikova$ pip install medaka**
Collecting medaka
  Could not find a version that satisfies the requirement medaka (from versions: )
No matching distribution found for medaka

Both conda and pip are up to date. Any thoughts? 

Thanks, 
Nada

**Comment by cjw85** [comment]
Hi @nadakubikova,

with conda, you must also use the `conda-forge` channel, e.g.:

    conda create -n medaka -c bioconda medaka
    conda activate medaka

See http://bioconda.github.io/#set-up-channels.

**Comment by nadakubikova** [comment]
Thanks @cjw85<mailto:notifications@github.com>, that worked. Apologies, I am new to this but I also wondered about the basic usage. I only want to use Medaka for error correction of my called reads. I have both fastq files and aligned bam files but they look crap. In order to get rid of some of these errors, should I use fatsq files as an input to medaka and of so what are the required arguments and their corresponding data file formats when using medaka consensus on MacOS? And what is the output fileʔ

**Comment by cjw85** [comment]
It would be useful to know more about your experiment, the data you have and what you are ultimately trying to achieve. Medaka has been designed as an assembly polisher; so ordinarily the intended workflow would be to assemble the reads (with e.g. canu, wtdbg2, flye, etc.) and then run medaka as:

    medaka_consensus -i reads.fasta -d assembly_contigs.fasta

to obtain a higher quality assembly. This is not to say it cannot be used as a more generic consensus tool with a little creativity.

I will close this issue; please feel free to open a new one if you need more help in using medaka for other use cases.
