### ISSUE TITLE
Model for Dorado

### ISSUE THREAD

**Issue by shaqpl** [nanoporetech/medaka#405]
Dear Developers!
I would like to use Medaka with Dorado. Any ideas on which model(s) should I choose?
Regards
Lukasz

**Comment by cjw85** [comment]
@mwykes @ftostevin-ont

Do you know the answer to this?

**Comment by ftostevin-ont** [comment]
For the R9.4.1 and R10.4.1 v3.5.2 models in dorado you should use the latest medaka models for the corresponding chemistry and basecaller, ie one of `r941_*_g507` or `r1041_e82_*_g632`.
Medaka models paired with the R10.4.1 v4 dorado basecallers have not yet been released but these should be coming soon.

**Comment by mmcguffi** [comment]
@ftostevin-ont With the pending MinKNOW update to dorado as the default basecaller, is there a dorado-specific model we should be using?
