### ISSUE TITLE
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory #408

### ISSUE THREAD

**Issue by marianajeeb** [nanoporetech/medaka#409]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> Please ensure that you are using the most recent version of medaka before filing
> a bug report. The most recent version can be found on the [release page](https://github.com/nanoporetech/medaka/releases).
> If you are not using the most recent release, and file a issue regardless the
> most likely response from our developers will be to ask you to first upgrade.
>
> Please ensure also to provide the information below, not doing so will likely
> result in a request for the information.

**Describe the bug**
Hi, 

I am running medaka v1.7.2 under conda environment and getting the import error. 

**Logging*
`Running medaka consensus
Traceback (most recent call last):
  File "/home/phdstudent4/.conda/envs/maria2/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/medaka.py", line 10, in <module>
    from medaka.inference import train, predict
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/inference.py", line 22, in <module>
    from medaka.features import SampleGenerator
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/features.py", line 23, in <module>
    import libmedaka
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Failed to run medaka consensus.`

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from conda]
 - OS: [Pop!_OS 22.04 LTS]
 - medaka version (medaka v1.7.2)
 - No GPU
 
Thanks

**Comment by cjw85** [comment]
Hi @marianajeeb,

Can you confirm that your are using a conda environment bespoke to medaka? The libcrypto dependency should have been installed by conda.

If you are using a clean conda environment and installing only medaka and still having difficulties I would suggest raising and issue in the bioconda space on github

**Comment by marianajeeb** [comment]
Hi @cjw85

Thanks for your reply. I created a new conda environment and installed medaka through bioconda channel
`conda create -n medaka -c conda-forge -c bioconda medaka`

**Comment by cjw85** [comment]
Hi @marianajeeb,

I'm not sure how you could have ended up in this situation having installed from conda. The `libcrypto` dependency is a indirect dependency coming from the conda package's dependency on the htslib conda package.

I think you are better off asking on the bioconda space.

**Comment by marianajeeb** [comment]
Hi @cjw85 

Thanks for your reply.

I managed to solve the import error. But now I am getting another issue

`RuntimeError: Filepath for '--model' argument does not exist and is not a known model ID (r941_min_fast_g383)
Failed to run medaka consensus.`

Could you please tell what is the issue?

Thanks

**Comment by cjw85** [comment]
The error message is correct, there is no model named `r941_min_fast_g383`. You can view a list of valid model names with:

```
medaka tools list_models
```
