### ISSUE TITLE
Download a model behing a corporative proxy

### ISSUE THREAD

**Issue by enekomatute** [nanoporetech/medaka#414]
Hello, 

My name is Eneko and maybe i can get some help to solve this problem with medaka. I don't know if it's the right place to post this but I don't know where else to do it.

I'm new to this, starting with Epi2me on Ubuntu and trying to test the epi2me-labs/wf-bacterial-genomes v0.2.11 workflow. I keep having the same error.

[c4/92af38] Submitted process > calling_pipeline:medakaNetwork (1)
Error executing process > 'calling_pipeline:medakaNetwork (1)'
Caused by:
  Process `calling_pipeline:medakaNetwork (1)` terminated with an error exit status (1)
Command executed:
  medaka --version
      echo r1041_e82_400bps_hac_g615
  
      echo r1041_e82_400bps_hac_g615
  ..............
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 38, in __call__
      raise RuntimeError(msg.format(self.dest, str(e)))
  RuntimeError: Error validating model from '--model' argument: The model file for r1041_e82_400bps_hac_g615 is not already installed **and could not be downloaded.** Check you are connected to the internet and try again..
Work dir:

I have configured  then proxy like enviroment  variables for docker; Lowercase and UPppercase, but  i still get the same error. I think the problem is that I can`t configure medaka for download the model request thorugh the coportative proxy. Any ideas to solve it?

Thank you.

**Comment by cjw85** [comment]
Hi @enekomatute,

Thank you for reporting this. It was intended that the docker images used in wf-bacterial-genomes should contain all the medaka models, negating the need for them to be downloaded on the fly. It seems this wasnt implemented. We will rectify that.

**Comment by hkaspersen** [comment]
Hello! I am having similar difficulties, as I am running it on an HPC cluster with no internet connection. Making the models available in the image sounds like an excellent fix, when can we expect this to be available?

**Comment by cjw85** [comment]
I believe the images have now been updated with a more complete set of models.

**Comment by ElderMedic** [comment]
> I believe the images have now been updated with a more complete set of models.

Hey, I am also trying to pack all medaka models in my docker container for offline server but it seems medaka can not recognize the right path for pre-installed models (I used medaka tools download_models cmd inside container) when running the container in k8s. Can you share how you put models into the image?

**Comment by hkaspersen** [comment]
Hello again, 
I am still having troubles understanding "where" in the image the models are stored. 
Medaka cannot seem to find the models when I run it. Is there a specific path I have to use?
