### ISSUE TITLE
SR and SC info missing in medaka variants output

### ISSUE THREAD

**Issue by yul96** [nanoporetech/medaka#416]
The ref and alt allele info for the variants are not in the annotated VCF file. Below is an example output 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
VEC1	6810	.	AT	A	1.649	PASS	DP=1460;DPS=731,729	GT:GQ	1:2
VEC1	7041	.	GAG	TT	6.674	PASS	DP=1266;DPS=636,630	GT:GQ	1:7

Command used:
medaka_haploid_variant -i in.fastq.gz -r ref.fasta -o medaka-variant -m r1041_e82_260bps_sup_g632
 
This information is important to do customized filtering. Is there a way to turn it on?
Thanks

SR and SC are described in the header as below
##INFO=<ID=DP,Number=1,Type=Integer,Description="Depth of reads at pos">
##INFO=<ID=DPS,Number=2,Type=Integer,Description="Depth of reads at pos by strand (fwd, rev)">
##INFO=<ID=DPSP,Number=1,Type=Integer,Description="Depth of reads spanning pos +-25">
##INFO=<ID=SR,Number=.,Type=Integer,Description="Depth of spanning reads by strand which best align to each allele (ref fwd, ref rev, alt1 fwd, alt1 rev, etc.)">
##INFO=<ID=AR,Number=2,Type=Integer,Description="Depth of ambiguous spanning reads by strand which align equally well to all alleles (fwd, rev)">
##INFO=<ID=SC,Number=.,Type=Integer,Description="Total alignment score to each allele of spanning reads by strand (ref fwd, ref rev, alt1 fwd, alt1 rev, etc.) aligned with parasail: match 5, mismatch -4, open 5, extend 3">

**Comment by cjw85** [comment]
Please see the command-line help information for the annotate command, specifically the `--dpsp` option.

It is not recommended to filtered based on these metrics as to do so largely negates the use of medaka as a variant caller.

**Comment by yul96** [comment]
Thank you so much! this is helpful. The info is also useful for diagnosis.
