### ISSUE TITLE
Medaka variant error: OSError: .vcf is unsorted at index #8.

### ISSUE THREAD

**Issue by yul96** [nanoporetech/medaka#417]
Got this error when using Medaka variant on a sample like:
medaka_haploid_variant -i input.fastq.gz -r reference.fasta -o medaka-variant -m r1041_e82_260bps_sup_g632

Below is the vcf generated by medaka:
##fileformat=VCFv4.1
##medaka_version=1.7.2
##contig=<ID=VEC-1,length=3173>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Medaka genotype.">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Medaka genotype quality score">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
VEC-1	2005	.	CAAAAAAA	C	21.977	PASS	.	GT:GQ	1:22
VEC-1	2006	.	AAAAAAAAAA	C	25.521	PASS	.	GT:GQ	1:26
VEC-1	2005	.	CA	C	0.827	PASS	.	GT:GQ	1:1
VEC-1	2005	.	CAAAAAA	C	25.662	PASS	.	GT:GQ	1:26
VEC-1	2005	.	CA	C	5.859	PASS	.	GT:GQ	1:6
VEC-1	2005	.	CAAA	C	3.881	PASS	.	GT:GQ	1:4
VEC-1	2025	.	AAAAA	C	32.895	PASS	.	GT:GQ	1:33
VEC-1	2031	.	A	C	9.731	PASS	.	GT:GQ	1:10
VEC-1	2033	.	A	C	0.882	PASS	.	GT:GQ	1:1
VEC-1	2046	.	A	C	6.942	PASS	.	GT:GQ	1:7

I found if I move the line of 2006 to before 2025, then the error goes away.

**Comment by cjw85** [comment]
Hi @yul96 @edgraham

There is a corner case in how medaka outputs and ["normalizes"](https://academic.oup.com/bioinformatics/article/31/13/2202/196142) variant records which can lead to the output being unsorted. We will fix this.

**Comment by cjw85** [comment]
This was fixed in [v1.10.0](https://github.com/nanoporetech/medaka/releases/tag/v1.10.0).
