### ISSUE TITLE
samtools/minimap2 version conda install

### ISSUE THREAD

**Issue by aistBMRG** [nanoporetech/medaka#418]
Small question.

I am installing medaka v1.7.2 using conda -- it completes but I found that it installs samtools (and related tools) v1.16 and minimap2 v2.24. I am able to downgrade minimap2 to version 2.17 but seem to run into issues with getting samtools V1.14 installed in the same conda environment. It is mentioned that samtools v1.14 is recommended but would any issues be expected using v1.16?

Thanks.

Dieter

**Comment by cjw85** [comment]
The newer versions are fine to use.
