### ISSUE TITLE
Auto detecting polishing model based on fastq header information

### ISSUE THREAD

**Issue by replikation** [nanoporetech/medaka#419]
Hi there,

It's usually a bit "annoying" to choose the correct medaka model for genome polishing based on the provided guppy model. However, the newest MinKnow software prints the basecalling model into the fastq header.
I wanted to ask if Medaka will be (or is) able to autodetect the correct model for polishing a fasta.

**Describe the solution you'd like**
It would be great if Medaka could auto-detect the polishing model based on the provided fastq files or state if it can't find a suitable model.

**Comment by cjw85** [comment]
We are looking into how this might be accomplished.

**Comment by cjw85** [comment]
This is done in v1.11.0, see [this section](https://github.com/nanoporetech/medaka#models) of the README.
