### ISSUE TITLE
"SyntaxError" reported by medaka_consensus and installing.

### ISSUE THREAD

**Issue by jyw-atgithub** [nanoporetech/medaka#423]
To whom it may concern, 
There are two issues.
1. I could not install the Medaka 1.7.2 from Bioconda, even everything was up-to-date and a new environment was created.
2. After days of trails, I used pip to installed the latest version of Medaka on a server with Ubuntu. In the test run, the following command was given.

`medaka_consensus -i ....../raw/PRJNA929424/SRR23269563_ONT.fastq -d ....../assemble/SRR23269563_ONT_Flye/assembly.fasta 
-o ....../SRR23269563-medaka-1/ -t 8 -m r941_min_hac_g507`

Then the messages were shown:
`2023-03-08 17:28:23.289950: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-08 17:28:23.289989: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
  File "<string>", line 1
    import sys; import itertools; mods=[f'{x[:-1]}' for x in sys.stdin.readline().split() if ('variant' not in x and 'snp' not in x)]; print(' '.join(mods))
                                                  ^
SyntaxError: invalid syntax`

May I know how to resolve the problems? Thank you!

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method:  pypi (pip install)
 - OS: Ubuntu 22.04.2 LTS
 - medaka version: medaka 1.7.3
 - GPU model: NVIDIA GV100 [TITAN V]
 - NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4
 - Python 2.7.18
 - Python 3.10.6
 - pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`

**Comment by cjw85** [comment]
Closing through lack of response.
