### ISSUE TITLE
Questions about consensus polishing models for Version 4 basecallers introduced in medaka v1.7.3

### ISSUE THREAD

**Issue by ilnamkang** [nanoporetech/medaka#424]
Hi, 

First note that this issue is for asking questions, not for feature request. I couldn't find how to leave questions in this repository.

I have two questions.

1\. What are the names of consensus polishing models for version 4 basecallers? 
Are the models having names ending with v4.0.0 for version 4 basecallers?

2\. What do "Version 4 basecallers" indicate?

Thanks.

**Comment by cjw85** [comment]
The names are:

```
r1041_e82_400bps_hac_v4.0.0
r1041_e82_400bps_sup_v4.0.0
```

I must admit, what makes the basecaller models version 4 and not version 1, 2, 3, 5, 6, or anything else, I am unsure.

**Comment by iiSeymour** [comment]
The major version represents the basecaller model neural network architecture and minor is a data/training improvement.

 - v1.x CNN-CTC QuartzNet 5x5
 - v2.x CNN-CTC QuartzNet variant.
 - v3.x LSTM-CRF-CTC
 - v4.x LSTM-CRF-CTC variant.

**Comment by ilnamkang** [comment]
If my nanopore data was obtained from R10.4.1 flow cell and was basecalled using "dna_r10.4.1_e8.2_400bps_sup.cfg" model by Guppy v6.4.6, then is it okay to use "r1041_e82_400bps_sup_g615" model for medaka-cpu v1.7.3?

Or, would "r1041_e82_400bps_sup_v4.0.0" model be better for me?

**Comment by Kirk3gaard** [comment]
> The names are:
> 
> ```
> r1041_e82_400bps_hac_v4.0.0
> r1041_e82_400bps_sup_v4.0.0
> ```
> 
> I must admit, what makes the basecaller models version 4 and not version 1, 2, 3, 5, 6, or anything else, I am unsure.

No "fast" model coming for this release? 

The new extended names are not making things a lot easier yet (#77) I guess  most people will be aware about the pore number, possibly also the sequencing speed but the "e82" part is already a bit tricky. I can imagine that the introduction of 5 khz vs 4 khz is going to add another layer of complexity/confusion?

**Comment by ls47** [comment]
> If my nanopore data was obtained from R10.4.1 flow cell and was basecalled using "dna_r10.4.1_e8.2_400bps_sup.cfg" model by Guppy v6.4.6, then is it okay to use "r1041_e82_400bps_sup_g615" model for medaka-cpu v1.7.3?
> 
> Or, would "r1041_e82_400bps_sup_v4.0.0" model be better for me?

I have the exact same setup and question. 
Also will there be a manual for the different models? The description in the readme is wrong since you need to use e82 (motorprotein) instead of min (MinION).
