### ISSUE TITLE
conda install version error

### ISSUE THREAD

**Issue by junkim83** [nanoporetech/medaka#426]
Dear All,

I've installed medaka (1.7.2) using anaconda but I got problem to execute medaka.
When I typed medaka -h it gave me an error message below.

Traceback (most recent call last):
  File "/usr/anaconda3/envs/nanopore_assemble/bin/medaka", line 7, in <module>
    from medaka.medaka import main
ModuleNotFoundError: No module named 'medaka'

How can I solve this?

**Comment by lidi4** [comment]
does medaka --version give you the same output?

**Comment by cjw85** [comment]
This seems like a problem with your conda setup and environment, not an issue with medaka per se.
