### ISSUE TITLE
KeyError: r94

### ISSUE THREAD

**Issue by GracelinTina** [nanoporetech/medaka#43]
i am using Conda Env. 

Traceback (most recent call last):
  File "medaka.py", line 38, in __call__
    val = model_dict[val]
KeyError: 'r94'

**Comment by mwykes** [comment]
Thanks for your query. 

Unless you are providing a model file path, the valid options for the model are presently `941_flip235`, `r941_flip213` or `r941_trans`. 
If the model is not a file, nor a model name, Medaka will raise an exception and the last line of the traceback should read:

`RuntimeError: Filepath for '--model' argument does not exist and is not a known model ID (r94)`

If you try again with one of the above options, it should work.
