### ISSUE TITLE
polish with ONT reads from different model 

### ISSUE THREAD

**Issue by cjchen5** [nanoporetech/medaka#435]
Hi,

My draft genome is assembled with ONT reads generated from Min and Prom. 
I would like to use all ONT reads for polish but as ONT reads contain different models, I can't do this.

Any suggestion for how to deal with this situation? Can the model be set for each ONT reads file?

Thanks!

**Comment by cjw85** [comment]
I cannot provide any clear advice here as it is not something we typically do. All I can suggest is trying a few experiments using each medaka model with the different facets of your data and all your data combined.

**Comment by cjchen5** [comment]
Hi,
Is there any update on this question now?
I have two fq files with models r1041_e82_400bps_hac and r1041_e82_400bps_sup. Is that possible to select different models for different fq? Or do I have to generate it with the same basecaling model and then medaka?

In addition, if I have to generate it with the same basecaling model, should I restart assembly or I only need to new generate fasta reads for polishing?
Thanks!

**Comment by cjw85** [comment]
All the medaka models are intended for use with a single basecalling model, with assemblies generated from from the same reads.

**Comment by cjchen5** [comment]
> All the medaka models are intended for use with a single basecalling model, with assemblies generated from from the same reads.

Thanks for your quick response! Just double checking, the suggestion is to restart the assembling with reads used with a single basecalling model?

**Comment by cjw85** [comment]
Correct
