### ISSUE TITLE
medaka_haploid_variant model for guppy v 6.4.8

### ISSUE THREAD

**Issue by katefgit** [nanoporetech/medaka#438]
which model from the following options should I select, when I have basecalled using the newest guppy version for R10.4.1 run with 400bs hac settings? 

`-m  medaka model, (default: r1041_e82_400bps_sup_variant_v4.2.0).
        Choices: r103_fast_variant_g507 r103_hac_variant_g507 r103_prom_variant_g3210 r103_sup_variant_g507 r1041_e82_260bps_fast_variant_g632 r1041_e82_260bps_hac_variant_g632 r1041_e82_260bps_hac_variant_v4.1.0 r1041_e82_260bps_sup_variant_g632 r1041_e82_260bps_sup_variant_v4.1.0 r1041_e82_400bps_fast_variant_g615 r1041_e82_400bps_fast_variant_g632 r1041_e82_400bps_hac_variant_g615 r1041_e82_400bps_hac_variant_g632 r1041_e82_400bps_hac_variant_v4.1.0 r1041_e82_400bps_hac_variant_v4.2.0 r1041_e82_400bps_sup_variant_g615 r1041_e82_400bps_sup_variant_v4.1.0 r1041_e82_400bps_sup_variant_v4.2.0 r104_e81_fast_variant_g5015 r104_e81_hac_variant_g5015 r104_e81_sup_variant_g610 r941_e81_fast_variant_g514 r941_e81_hac_variant_g514 r941_e81_sup_variant_g514 r941_min_fast_variant_g507 r941_min_hac_variant_g507 r941_min_sup_variant_g507 r941_prom_fast_variant_g507 r941_prom_hac_variant_g507 r941_prom_sup_variant_g507 r941_prom_variant_g303 r941_prom_variant_g322 r941_prom_variant_g360 r941_sup_plant_variant_g61.`

**Comment by cjw85** [comment]
`r1041_e82_400bps_hac_variant_v4.1.0`

**Comment by cjw85** [comment]
The version 4.2 models are for 5kHz sampling rate announced recently at London Calling.

**Comment by nextgenusfs** [comment]
@cjw85 is it possible to put a table or something on the README of which guppy base calling models correspond to which medaka models.  If I'm honest, the difference in the naming schemes is annoying.  Effectively it requires me to hardcode a lookup in some of our automation code to map the guppy model file to the one to use for medaka.  Not sure on the easiest general solution for this, but at least if documented in an obvious way on the README where could be updated when a new release is pushed that would be helpful.  Ideally it would be nice to be able to pass the guppy model file to medaka and have it choose the appropriate model, ie `--guppy-model template_r10.4.1_e8.2_400bps_5khz_hac.jsn` which use the `r1041_e82_400bps_hac_v4.2.0` model. Or possibly re-use the `--model` option in to auto lookup the proper model if a guppy model is passed.

**Comment by yzhang-github-pub** [comment]
Totally agree @nextgenusfs. Medaka, guppy and other tools are excellent, and training the models takes a lot of effort. But the potential impact of the tools/models is greatly reduced if downstream cannot pick the right models due to the lack of or insufficient documentation.

**Comment by katefgit** [comment]
Hi again, 

I am coming back to this, as my guppy logs I cann't figure out if the 5khz or 4khz has been used (only showing this /opt/ont/guppy/data/dna_r10.4.1_e8.2_400bps_hac.cfg). Is the 5khz the default and could it be because in the lab we often run basecalling using MinKNOW and therefore can't have control of the specific guppy model. I guess that  selecting 
![image](https://github.com/nanoporetech/medaka/assets/74652982/f6ea6bca-e89d-4f9e-9edf-9d5abdbb9c5a) is the 5khz matching with the v4.2, since the is another option with 4khz 
<img width="242" alt="image" src="https://github.com/nanoporetech/medaka/assets/74652982/6d9192c1-d64e-4d3e-b469-606767a185c6">

**Comment by cjw85** [comment]
@katefgit your data is 5kHz.

**Comment by cjw85** [comment]
@nextgenusfs 

I agree this has become a complete mess, particularly as we are transitioning from Guppy to dorado. [This table](https://github.com/epi2me-labs/wf-bacterial-genomes/blob/master/data/medaka_models.tsv) may be of use, though its incomplete as it doesn't take account of the fact that some models were updated across Guppy versions (it is correct provided a "recent" version of Guppy is used, but don't ask me to quantify "recent"!).

The original naming of medaka models was intended to provide an interface logically equivalent to your `--guppy-model` idea. The issue is that Guppy models were not historically versioned separately to Guppy itself --- hence the somewhat obtuse guidance in the [README](https://github.com/nanoporetech/medaka#models).

Dorado introduced a cleaner notion of model version, which helps as there is a more direct correspondence between the dorado model names and medaka model names.

**Comment by cjw85** [comment]
Automatic model selection has been implemented in medaka v1.11.0, which should mostly alleviate these difficulties. See [this section](https://github.com/nanoporetech/medaka#models) of the README.
