### ISSUE TITLE
make install fails if -j is too big

### ISSUE THREAD

**Issue by grzadr** [nanoporetech/medaka#44]
During execution of ```make install``` if additional argument -j is added to make ( like ```make -j 4 install``` ) build fails, because of 
```
/usr/bin/ld: htslib-1.9/libhts.a(hfile_s3.o): in function `s3_sign':           
hfile_s3.c:(.text+0x306): undefined reference to `EVP_sha1'                       
/usr/bin/ld: hfile_s3.c:(.text+0x32a): undefined reference to `HMAC'                                
collect2: error: ld returned 1 exit status                               
make[1]: *** [Makefile:144: samtools] Error 1
```

Everything works when -j is no greater than 2.

**Comment by cjw85** [comment]
@grzadr 
Thank you for reporting this; we will have a more atomic Makefile in the next release.

**Comment by cjw85** [comment]
Parallel builds should now behave nicely.
