### ISSUE TITLE
model for Guppy 6.4.2 

### ISSUE THREAD

**Issue by ArtyomVodnev** [nanoporetech/medaka#442]
Hello, could you please advise with which model I should use medaka for polishing a long read sequenced genome which was sequenced on a MinION R10.4.1 flow cell at 400bps, basecalling was performed with Guppy 6.4.2 in super-accuracy mode ?  

Here are the models listed:

    e82_260bps_sup_v4.0.0
    r1041_e82_260bps_sup_variant_g632
    r1041_e82_400bps_fast_g615
    r1041_e82_400bps_fast_g632
    r1041_e82_400bps_fast_variant_g615
    r1041_e82_400bps_fast_variant_g632
    r1041_e82_400bps_hac_g615
    r1041_e82_400bps_hac_g632
    r1041_e82_400bps_hac_v4.0.0
    r1041_e82_400bps_hac_variant_g615
    r1041_e82_400bps_hac_variant_g632
    r1041_e82_400bps_sup_g615
    r1041_e82_400bps_sup_v4.0.0
    r1041_e82_400bps_sup_variant_g615
    r104_e81_fast_g5015
    r104_e81_fast_variant_g5015
    r104_e81_hac_g5015
    r104_e81_hac_variant_g5015
    r104_e81_sup_g5015
    r104_e81_sup_g610
    r104_e81_sup_variant_g610
    r10_min_high_g303
    r10_min_high_g340
    r941_e81_fast_g514
    r941_e81_fast_variant_g514
    r941_e81_hac_g514
    r941_e81_hac_variant_g514
    r941_e81_sup_g514
    r941_e81_sup_variant_g514
    r941_min_fast_g303
    r941_min_fast_g507
    r941_min_fast_snp_g507
    r941_min_fast_variant_g507
    r941_min_hac_g507
    r941_min_hac_snp_g507
    r941_min_hac_variant_g507
    r941_min_high_g303
    r941_min_high_g330
    r941_min_high_g340_rle
    r941_min_high_g344
    r941_min_high_g351
    r941_min_high_g360
    r941_min_sup_g507
    r941_min_sup_snp_g507
    r941_min_sup_variant_g507
    r941_prom_fast_g303
    r941_prom_fast_g507
    r941_prom_fast_snp_g507
    r941_prom_fast_variant_g507
    r941_prom_hac_g507
    r941_prom_hac_snp_g507

Thank you!

**Comment by ftostevin-ont** [comment]
The medaka model corresponding to that guppy version is `r1041_e82_400bps_sup_g615`. There was no change to the basecaller model between guppy 6.1.5 and 6.4.2.

**Comment by pecholleyn** [comment]
Hi, if I understand correctly these [release notes](https://community.nanoporetech.com/posts/guppy-6-5-7-release), the next version involving a change is version 6.5.7, and the model to use is `r1041_e8.2_400bps_sup_v4.2.0`. And that models `r1041_e8.2_[260_or_400]bps_[X]_v4.0.0` are not meant to be used for data basecalled with Guppy, right?

**Comment by ftostevin-ont** [comment]
Yes, guppy v6.5.7 updates the kit14 basecaller models. The v4.2.0 models are specifically for 5khz data. For 4khz data the latest model is v4.1.0.
The v4.0.0 models were for use with dorado and have not been included in guppy, from what I could see.
