### ISSUE TITLE
medaka_consensus Model for Guppy 6.4.6

### ISSUE THREAD

**Issue by FrostFlow13** [nanoporetech/medaka#448]
I'm currently trying to run medaka_consensus on ONT long-read data, and I'm running into some frustrations in trying to figure out which basecalling model to use. I see that there's a (seemingly outdated) guide under "_Models_" that gives instructions on how to figure out what you should use, but I also see that the newest versions have dropped the nice and clear names based on the Guppy models. Looking around in the issues, I see that this sort of thing has been asked before (by a couple of different users).

To give additional information on my long-read data: 

> Machine = PromethION 24
> Flow cell type = FLO-PRO114M (R10.4.1)
> Kit type = SQK-NBD114-24 (V14)
> Basecalling = High-accuracy model, 400 bps
> MinKNOW = 22.12.5
> Bream = 7.4.8
> Configuration = 5.4.7
> Guppy = 6.4.6
> MinKNOW Core = 5.4.3
> basecalling_config_filename: "dna_r10.4.1_e8.2_400bps_hac_prom.cfg"

I've also attached the .md and .json (.txt version) report files we were provided in-case those give any additional information needed that I didn't include.

**For my specifications, what consensus model should I be using:** `r1041_e82_400bps_hac_g632`, `r1041_e82_400bps_hac_v4.0.0`, or `r1041_e82_400bps_hac_v4.1.0`**?** Or one I didn't list?

I believe that a safe bet for me would be to use the `r1041_e82_400bps_hac_g632` option, as it fulfills the "Models" section's suggestion of, "_Where a version of Guppy has been used without an exactly corresponding medaka model, the medaka model with the highest version equal to or less than the guppy version should be selected._" However, if one of the newer models would be better/are improved over the g632 version and are still compatible with the pieces I'm using, I definitely want to go with one of those!

Additionally, I think it might be helpful to update the "_Models_" section to include some information on the new naming system for the models.

[report_PAO85317_20230615_1429_373a141b.md](https://github.com/nanoporetech/medaka/files/12162772/report_PAO85317_20230615_1429_373a141b.md)
[report_PAO85317_20230615_1429_373a141b.json.txt](https://github.com/nanoporetech/medaka/files/12162778/report_PAO85317_20230615_1429_373a141b.json.txt)

**Comment by ftostevin-ont** [comment]
Yes, `r1041_e82_400bps_hac_g632` is the correct model for that Guppy basecaller version.

The medaka and basecaller models are paired, and using a newer medaka model with an older basecaller will probably yield worse results.

**Comment by FrostFlow13** [comment]
Thank you - I appreciate the confirmation!
