### ISSUE TITLE
Cannot import pyabpoa, some features may not be available. medaka 1.9.0

### ISSUE THREAD

**Issue by nextgenusfs** [nanoporetech/medaka#451]
Just noticed this after updating to latest:

```
$ medaka --version
Cannot import pyabpoa, some features may not be available.
medaka 1.9.0
```
So it seems `pyabpoa` is missing from requirements.txt.

**Comment by cjw85** [comment]
The message is a warning. It is deliberate as pyabpoa is not yet available on PyPI for all architectures that medaka supports.

If you are running on x86 Linux you can install pyabpoa to avoid the message appearing.
