### ISSUE TITLE
How trustworthy is the quality score output of medaka smolecule using the --quality flag?

### ISSUE THREAD

**Issue by AmstlerStephan** [nanoporetech/medaka#453]
> As of v1.6.1 medaka stitch can now has a [--qualities](https://github.com/nanoporetech/medaka/blob/master/medaka/medaka.py#L505) option to output a fastq file.

I was wondering how the quality scores from the network are interpreted now and if I could use the obtained quality scores for downstream analysis.

**Comment by cjw85** [comment]
The quality scores are simply the log-transformed softmax output from the RNN. We've made little attempt to quantify how these scores match empirical residual error.
