### ISSUE TITLE
choosinge the correct medaka model

### ISSUE THREAD

**Issue by laura-bankers** [nanoporetech/medaka#454]
Is there documentation or guidance available for choosing the correct medaka model? We are currently using guppy version 6.4.6+ae70e8f and are updating to the new 10.4 chemistry and are wondering what the best model would be for SARS-CoV-2 Artic tiled amplicon WGS given these parameters.

**Comment by CFB2018** [comment]
I would also like to know how to choose the correct model. We used the guppy software version 567, and the previous chemistry type R9.4.1, to run a flongle-sequencing. If the models are chosen after {pore}_{device}_{caller variant}_{caller version}, neither of these two work; r941_flo_high_g657, r941_min_high_g657.

**Comment by cjw85** [comment]
[This table](https://github.com/epi2me-labs/wf-bacterial-genomes/blob/master/data/medaka_models.tsv) may be of use.

**Comment by asan-emirsaleh** [comment]
Hello! Could you please provide another link to the same data? The page returns 404 now.
