### ISSUE TITLE
Please push new releases to Conda

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/medaka#455]
Hello, 

Please push the latest Medaka version to Conda if still supported.

Thank you.

**Comment by hoelzer** [comment]
Yes, please! +1

**Comment by cjw85** [comment]
There is an outstanding pull request on bioconda to update medaka. It will need community help to resolve.

https://github.com/bioconda/bioconda-recipes/pull/41417

We recommended using the PyPI packages which are available in various manylinux flavours and architectures.
