### ISSUE TITLE
"Failed to run medaka consensus"

### ISSUE THREAD

**Issue by sxh1136** [nanoporetech/medaka#46]
Running nanopore draft assemblies from Flye, run through racon 4 times and medaka fails at the consensus stage. The basecalls were made by guppy version 2.3.5. Medaka was installed into its own environment in conda.

```
Checking program versions
Program    Version    Required   Pass
bgzip      1.9        1.9        True
minimap2   2.11       2.11       True
samtools   1.9        1.9        True
tabix      1.9        1.9        True
Aligning basecalls to draft
-P option is deprecated
Found minimap files.
[M::main::1.814*1.00] loaded/built the index for 5496 target sequence(s)
[M::mm_mapopt_update::2.293*1.00] mid_occ = 52
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 5496
[M::mm_idx_stat::2.685*1.00] distinct minimizers: 20489295 (72.38% are singletons); average occurrences: 1.722; average spacing: 5.361
[M::worker_pipeline::51.221*14.92] mapped 79682 sequences
[M::worker_pipeline::83.219*19.17] mapped 76831 sequences
[M::worker_pipeline::107.127*21.37] mapped 75735 sequences
[M::worker_pipeline::130.271*22.80] mapped 77551 sequences
[M::worker_pipeline::156.134*23.91] mapped 76292 sequences
[M::worker_pipeline::181.773*24.29] mapped 75865 sequences
[M::worker_pipeline::211.141*24.11] mapped 76293 sequences
[M::worker_pipeline::236.326*24.68] mapped 75231 sequences
[M::worker_pipeline::260.724*25.09] mapped 77703 sequences
[M::worker_pipeline::287.333*25.15] mapped 76443 sequences
[M::worker_pipeline::314.211*24.76] mapped 75857 sequences
[M::worker_pipeline::339.408*25.12] mapped 78103 sequences
[M::worker_pipeline::355.932*25.30] mapped 83441 sequences
[M::worker_pipeline::374.894*25.32] mapped 84073 sequences
[M::worker_pipeline::400.614*25.06] mapped 78833 sequences
[M::worker_pipeline::428.461*25.36] mapped 72657 sequences
[M::worker_pipeline::452.870*25.56] mapped 72243 sequences
[M::worker_pipeline::480.282*25.62] mapped 73771 sequences
[M::worker_pipeline::508.286*25.35] mapped 71908 sequences
[M::worker_pipeline::536.047*25.57] mapped 71866 sequences
[M::worker_pipeline::560.878*25.73] mapped 72110 sequences
[M::worker_pipeline::587.958*25.77] mapped 71773 sequences
[M::worker_pipeline::609.060*25.68] mapped 78327 sequences
[M::worker_pipeline::613.150*25.58] mapped 55049 sequences
[M::main] Version: 2.11-r797
[M::main] CMD: minimap2 -x map-ont --MD -t 32 -a /home/ubuntu/stan/nanopore/flye_assemblies/D3S/D3S.flye.assembly.racon4.fasta.mmi /home/ubuntu/stan/nanopore/raw_data/D3S/D3S_cat.fasta
[M::main] Real time: 613.456 sec; CPU: 15683.244 sec
[bam_sort_core] merging from 0 files and 32 in-memory blocks...
Running medaka consensus
Using TensorFlow backend.
/home/ubuntu/miniconda3/envs/medaka/bin/medaka_consensus: line 88:  3068 Floating point exception(core dumped) medaka consensus ${CALLS2DRAFT}.bam ${CONSENSUSPROBS} --model ${MODEL} --batch_size ${BATCH_SIZE} --threads ${THREADS}
Failed to run medaka consensus.
```

This is what's in the output file:
```
total 2128508
-rw-rw-r-- 1 ubuntu ubuntu 2178192425 Apr 25 14:30 calls_to_draft.bam
-rw-rw-r-- 1 ubuntu ubuntu    1392768 Apr 25 14:30 calls_to_draft.bam.bai
```

Anyone know where I'm going wrong?

**Comment by dominik-handler** [comment]
Hi,

I have the same problem but interestingly only on one of our cluster environments. I use the very same singularity container on both systems so medaka should be experiencing the very same environment on both systems. The biggest difference might be the CPU version, do you think this can be the cause of this? 


Working:
NAME="CentOS Linux"
VERSION="7 (Core)"
CPU=Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz

Not working:
NAME="CentOS Linux"
VERSION="7 (Core)"
CPU=Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GH

**Comment by cjw85** [comment]
Hi @sxh1136 and @dominik-handler 

Apologies for the lack of reply until now.

We have not been able to reproduce this error; I have a suspicion it may be how the conda package is built. Admittedly we do not use the conda builds too often, though I know other users (@wdecoster?) do.

You may wish to try building from source (check the [build-wheels.sh](https://github.com/nanoporetech/medaka/blob/master/build-wheels.sh#L9) script in the repository), or to use the [pypi package](https://pypi.org/project/medaka/) instead. The pypi package does not require compilation but unlike the conda package will require you to install `samtools`, `minimap2`, `tabix`, and `bgzip` yourself

It may be possible to install the pypi package into a conda environment, though I'm not sure if this will resolve your issue.

**Comment by sxh1136** [comment]
Hi @cjw85 

I was able to solve my issue by installing medaka in a conda environment with a virtualenv.

**Comment by wdecoster** [comment]
In my case, I also use a conda environment, on a CentOS7.
