### ISSUE TITLE
medaka_consensus outputs .fasta with option -q

### ISSUE THREAD

**Issue by pecholleyn** [nanoporetech/medaka#464]
An output ending with ".fastq" is expected when the option "-q" ("Output consensus with per-base quality scores (fastq)") is used.

https://github.com/nanoporetech/medaka/blob/a736c21f644316ee60b093c792729112b3408d65/scripts/medaka_consensus#L159C1-L159C1

**Comment by cjw85** [comment]
Hi @pecholleyn,

Thank you for reporting this. We will fix the behaviour in the next release.

**Comment by cjw85** [comment]
This is fixed in v1.11.0
