### ISSUE TITLE
tools resolve_model requires chardet

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/medaka#465]
After updating to the latest medaka and running `medaka tools resolve_model --auto_model consensus file.bam` I get a python error complaining `chardet` does not exist. I installed it with Conda and then the command worked.

**Comment by cjw85** [comment]
There have been no recent changes to medaka that would require chardet needing to be added to the dependency list. I cannot reproduce this error when creating a clean install in a fresh Python3.8 virtual environment. The package from bioconda is not supported by Oxford Nanopore Technologies.
