### ISSUE TITLE
medaka_consensus compatabile with guppy v3.0.3

### ISSUE THREAD

**Issue by damientully** [nanoporetech/medaka#47]
Hi,
Just wanted to check whether the models released as part of guppy v3.0.3 compatible with the medaka models specifically the r941_flip235 model. As of 3.0.3 all of the r9.4.1 models are now flip-flop models so are they the same as those in medaka. Reason I ask is that I noticed a very slight drop in accuracy (99.87 -> 99.85!) when re-basecalling the same data with v3.0.3. 

Thanks.
Damien

**Comment by cjw85** [comment]
Hi @damientully,

We are currently validating medaka models which are paired with the new guppy 3.0.3 models. These will appear in medaka v0.7.0. The existing `r941_flip235` is likely to be serviceable with the new basecalling models, though perhaps not optimal.

**Comment by damientully** [comment]
Great I look forward to the v0.70 release!
