### ISSUE TITLE
Should the sum of SR be equal to DP?

### ISSUE THREAD

**Issue by kevin-wamae** [nanoporetech/medaka#471]
**Describe the bug**
Should the sum of reads in SR be equal to DP?

```##INFO=<ID=DP,Number=1,Type=Integer,Description="Depth of reads at pos">```
```##INFO=<ID=SR,Number=.,Type=Integer,Description="Depth of spanning reads by strand which best align to each allele (ref fwd, ref rev, alt1 fwd, alt1 rev, etc.)">```

**Logging**
I generated vcf files using medaka variant and medaka_haploid_variant

```medaka variant genome.fa consensus.hdf output_1.vcf```
```medaka tools annotate --dpsp output_2.vcf genome.fa sample.bam```

```medaka_haploid_variant -s -m r1041_e82_400bps_sup_variant_v4.2.0 -r genome.fa -i test.fastq -o vcf_dir```

Here's one SNP where the sum of SR is more that DP:

```
Pf3D7_11_v3	1294378	. T G 31.398 PASS AR=197,89;DP=8058;DPS=4326,3732;DPSP=10939;SC=1239906,1291888,1285260,1339930;SR=15,103,5094,5441 GT:GQ 1:31
```

**Environment**
Installation method: Singularity image from https://depot.galaxyproject.org/singularity/medaka:1.11.1--py310h87e71ce_0
medaka version 1.11.1
No GPU

**Comment by cjw85** [comment]
See #466
