### ISSUE TITLE
Could not load symbol cublasGetSmCountTarget from libcublas.so.11.

### ISSUE THREAD

**Issue by aksti** [nanoporetech/medaka#472]
Hello,

While running Medaka (UBUNTU 18.04; Conda environment; Python 3.9.18; CUDA 11.2; cuBLAS 11.4), the following error occurred:

```
Could not load symbol cublasGetSmCountTarget from libcublas.so.11. Error: /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.11: undefined symbol: cublasGetSmCountTarget 
```

The pipeline runs despite the error, but are there any drawbacks? How can I fix this error?

**Comment by cjw85** [comment]
Hi @aksti,

I'm curious that you say you have CUDA 11.2 but cuBLAS 11.4. The version of tensorflow used by medaka is linked to CUDA 11.2.

**Comment by aksti** [comment]
Thanks for the answer. Here all versions installed automatically on my system.
{
   "cuda" : {
      "name" : "CUDA SDK",
      "version" : "11.2.2"
   },
   "cuda_cudart" : {
      "name" : "CUDA Runtime (cudart)",
      "version" : "11.2.152"
   },
   "cuda_cuobjdump" : {
      "name" : "cuobjdump",
      "version" : "11.2.152"
   },
   "cuda_cupti" : {
      "name" : "CUPTI",
      "version" : "11.2.152"
   },
   "cuda_cuxxfilt" : {
      "name" : "CUDA cu++ filt",
      "version" : "11.2.152"
   },
   "cuda_demo_suite" : {
      "name" : "CUDA Demo Suite",
      "version" : "11.2.152"
   },
   "cuda_gdb" : {
      "name" : "CUDA GDB",
      "version" : "11.2.152"
   },
   "cuda_memcheck" : {
      "name" : "CUDA Memcheck",
      "version" : "11.2.152"
   },
   "cuda_nsight" : {
      "name" : "Nsight Eclipse Plugins",
      "version" : "11.2.152"
   },
   "cuda_nvcc" : {
      "name" : "CUDA NVCC",
      "version" : "11.2.152"
   },
   "cuda_nvdisasm" : {
      "name" : "CUDA nvdisasm",
      "version" : "11.2.152"
   },
   "cuda_nvml_dev" : {
      "name" : "CUDA NVML Headers",
      "version" : "11.2.152"
   },
   "cuda_nvprof" : {
      "name" : "CUDA nvprof",
      "version" : "11.2.152"
   },
   "cuda_nvprune" : {
      "name" : "CUDA nvprune",
      "version" : "11.2.152"
   },
   "cuda_nvrtc" : {
      "name" : "CUDA NVRTC",
      "version" : "11.2.152"
   },
   "cuda_nvtx" : {
      "name" : "CUDA NVTX",
      "version" : "11.2.152"
   },
   "cuda_nvvp" : {
      "name" : "CUDA NVVP",
      "version" : "11.2.152"
   },
   "cuda_samples" : {
      "name" : "CUDA Samples",
      "version" : "11.2.152"
   },
   "cuda_sanitizer_api" : {
      "name" : "CUDA Compute Sanitizer API",
      "version" : "11.2.152"
   },
   "fabricmanager" : {
      "name" : "Fabric Manager",
      "version" : "460.32.03"
   },
   "libcublas" : {
      "name" : "CUDA cuBLAS",
      "version" : "11.4.1.1043"
   },
   "libcufft" : {
      "name" : "CUDA cuFFT",
      "version" : "10.4.1.152"
   },
   "libcurand" : {
      "name" : "CUDA cuRAND",
      "version" : "10.2.3.152"
   },
   "libcusolver" : {
      "name" : "CUDA cuSOLVER",
      "version" : "11.1.0.152"
   },
   "libcusparse" : {
      "name" : "CUDA cuSPARSE",
      "version" : "11.4.1.1152"
   },
   "libnpp" : {
      "name" : "CUDA NPP",
      "version" : "11.3.2.152"
   },
   "libnvjpeg" : {
      "name" : "CUDA nvJPEG",
      "version" : "11.4.0.152"
   },
   "nsight_compute" : {
      "name" : "Nsight Compute",
      "version" : "2020.3.1.4"
   },
   "nsight_systems" : {
      "name" : "Nsight Systems",
      "version" : "2020.4.3.7"
   },
   "nvidia_driver" : {
      "name" : "NVIDIA Linux Driver",
      "version" : "460.32.03"
   }
}


Regards,
Sascha

**Comment by cjw85** [comment]
You appear to have a rather eclectic mix of versions of CUDA libraries being displayed here. I suggest talking to your system administrator to understand this more.
