### ISSUE TITLE
biocontainers issue with 1.11.2 and above

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/medaka#479]
Hi,

not exactly sure if this is the right place to report this, but as far as I'm aware the biocontainer images (https://quay.io/repository/biocontainers/medaka?tab=tags) get built automatically.

Anyhow, all versions 1.11.2 and 1.11.3 containers crash with following error:

![image](https://github.com/nanoporetech/medaka/assets/4354282/0806aa64-bd3b-4212-9393-6972ba9313b6)

I was hoping to use the latest version, but the 'official' ONT container at https://hub.docker.com/r/ontresearch/medaka/tags is currently at 1.11.1 (also, the tagging there can certainly be improved).
Cheers,
Johannes

**Comment by cjw85** [comment]
The messy container tags stem from our continuous deployment system for Nextflow workflows (they're not really for human consumption). I'll take a look at creating a nicely named tag.

Oxford Nanopore Technologies has no affiliation or control over the biocontainers project.

**Comment by cjw85** [comment]
I'm just tagging a docker image for v1.11.3 now.

**Comment by JWDebler** [comment]
Thanks for that, not sure if intended, but the container that hast a proper tag is only available for linux/arm64:

![image](https://github.com/nanoporetech/medaka/assets/4354282/2e5321ed-ac74-4914-8b7f-7864bed37e68)

**Comment by cjw85** [comment]
Oh dear, you are correct. I manually retagged the `latest` image with `v1.11.3` on my MacBook forgetting that a) its and ARM device b) we have multiarch images.

**Comment by cjw85** [comment]
I've pushed a manifest with both images tagged as v1.11.3
