### ISSUE TITLE
medaka_variant hanging

### ISSUE THREAD

**Issue by wdecoster** [nanoporetech/medaka#48]
I am using `medaka_variant` for PromethION data of a human genome and notice that after the `medaka_consensus` step the program starts hanging. It has reached 100%, but hasn't moved to the next stage (calling medaka snp). Is this the same issue as https://github.com/nanoporetech/medaka/issues/42? Or should I just be more patient?
medaka consensus is now using one process, about 50GB of RAM (according to htop) and hasn't edited its hdf file `round_0_hap_mixed_probs.hdf` in the last 4 days.

**Comment by mwykes** [comment]
Yes, that sounds very much like #42. I would recommend upgrading to medaka v0.6.5. If you want to speed things up, you could try running on GPU, and parallelising over chromosomes, see [here](https://github.com/nanoporetech/medaka/issues/39#issuecomment-479472087) for details.

**Comment by wdecoster** [comment]
Thanks, I'll do that. Do you think the `round_0_hap_mixed_probs.hdf` is valid to restart from, or should I clean it up and entirely start over?

**Comment by cjw85** [comment]
Restarting with that existing file should be fine, on the assumption it was closed correctly etc. This is the output of the initial pass over, you should delete any files created after this file if you want to pick up the workflow after this point.

**Comment by wdecoster** [comment]
I don't know for sure if that assumption is valid, as I have to kill the running job. What I get when restarting is the following:

```
...
Not running medaka consensus, round_0_hap_mixed_probs.hdf exists.
======================================
Running medaka snp with threshold 0.04
======================================

[12:21:26 - DataIndex] Could not find samples in round_0_hap_mixed_probs.hdf
[12:21:26 - DataIndex] Loaded sample-index from 1/1 (100.00%) of feature files.
VCF written to path/round_0_hap_mixed_thresh_0.04_unphased.vcf.
Using existing output:  path/GRCh38.fa.fai.

=============================================
Running whatshap phase to phase vcf round_0_hap_mixed_thresh_0.04_unphased.vcf.
=============================================

This is WhatsHap 0.18 running under Python 3.6.7
Working on 1 samples from 1 family

== SUMMARY ==
Maximum memory usage: 0.239 GB
Time spent reading BAM/CRAM:                    0.0 s
Time spent parsing VCF:                         0.0 s
Time spent selecting reads:                     0.0 s
Time spent phasing:                             0.0 s
Time spent writing VCF:                         0.0 s
Time spent finding components:                  0.0 s
Time spent on rest:                             0.9 s
Total elapsed time:                             0.9 s
Phased VCF written to path/round_0_hap_mixed_thresh_0.04_phased.vcf.
Compressing round_0_hap_mixed_thresh_0.04_phased.vcf.
Compressed file written to path/round_0_hap_mixed_thresh_0.04_phased.vcf.gz.
Indexing round_0_hap_mixed_thresh_0.04_phased.vcf.gz.
Compressed file written to path/round_0_hap_mixed_thresh_0.04_phased.vcf.gz.tbi.

=============================================
Running whatshap tag using round_0_hap_mixed_thresh_0.04_phased.vcf.gz.
=============================================

Found 1 samples in VCF file
Samples in BAM file: 
Processing alignments on chromosome chr1
No variants given for chromosome chr1 in the input VCF.
```

It's now running whatshap. The vcf file called `round_0_hap_mixed_thresh_0.04_phased.vcf.gz` is empty though, so that worries me.

**Comment by cjw85** [comment]
I that case I would advise starting from scratch, perhaps testing first on a 1-10Mb region (`medaka_variant` has a `-R` option, or simply subset your `.bam`).

**Comment by oneillkza** [comment]
@wdecoster, very likely the same issue as #42 , since I'm using your NA19240 data. ;)
