### ISSUE TITLE
Medaka_consensus python command not found error message

### ISSUE THREAD

**Issue by LEGMCGILL** [nanoporetech/medaka#480]
Dear community I am here to ask some feedback about an error I am getting while attempting to run medaka_consensus command. 

I am trying to do self polishing of my nanopore data, however, I am encountering python: command not found error message, although python is installed, I have python3 and python3.8 apparently. I have tried a couple of options including moving the medaka_consensus to my path, I also tried moving python to my path.
Find the following picture with the error message that I am getting:
Some things I have tried with no changes is updating from medaka 1.11.2 to medaka 1.11.3

![image](https://github.com/nanoporetech/medaka/assets/147701622/1b30c1af-3ac9-48c2-a38e-789b1add9359)
All feedback will be highly appreciated.

Thanks,

Laura.

**Comment by cjw85** [comment]
Hi Laura,

As requested previously please reopen an issue using the  Bug Report template and provide all the requested information. Again it really helps us to help you to have the requested information.
