### ISSUE TITLE
Missing pyabpoa in Docker image

### ISSUE THREAD

**Issue by zhengxinchang** [nanoporetech/medaka#483]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> Please ensure that you are using the most recent version of medaka before filing
> a bug report. The most recent version can be found on the [release page](https://github.com/nanoporetech/medaka/releases).
> If you are not using the most recent release, and file a issue regardless the
> most likely response from our developers will be to ask you to first upgrade.
>
> Please ensure also to provide the information below, not doing so will likely
> result in a request for the information.

**Describe the bug**
A clear and concise description of what the bug is including the command that you have run.

**Logging**
Please attach any relevant logging messages. (Use \`\`\` before and after code blocks).

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: CentOS7
 - medaka version 1.11.3
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

I am writing to report a potential bug when running medaka tandem by using Docker image. 

I built the singularity image based on the Docker image and run the image as follows:

```
singularity exec -f -B /run:/run  --bind /stornext/:/stornext/ /softwares/medaka/medaka.sif    medaka tandem  --model res_medaka_tandem_r1041_e82_400bps_sup_v420.tar.gz  input.bam hg38_allchr_fixchrMT.fa ./adotto_TRregions_v1.2.bed.small   male test_out
```

Error returned from madaka
```
Traceback (most recent call last):
  File "/home/epi2melabs/conda/bin/medaka", line 8, in <module>
    sys.exit(main())
  File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 814, in main
    args.func(args)
  File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/tandem.py", line 804, in main
    raise RuntimeError(
RuntimeError: pyabpoa >= 1.4.1 is not installed. Refer to abpoa documentation at https://github.com/yangao07/abPOA for installation instructions.
```

I try to install the pyabpoa in the docker container and rebuild it. It seems works well. 

Thanks
Xinchang

**Comment by cjw85** [comment]
Hi @zhengxinchang,

Thank you for reporting this. The `medaka tandem` command is a little experimental, and relies on abpoa whereas the rest of medaka does not. this is why the import is optional. Unfortunately we cannot add pyapoa as a requirement to medaka in the natural way because the pyapoa package is itself broken (https://github.com/yangao07/abPOA/issues/41).

**Comment by cjw85** [comment]
It is not possible to run medaka tandem without pyabpoa: its inclusion as a requirement in medaka is solely for its use in medaka tandem.
