### ISSUE TITLE
Medaka error

### ISSUE THREAD

**Issue by setshabaTaukobong** [nanoporetech/medaka#487]
Hi there, I am trying to run medaka using a nextflow script but I keep running into the below issue. Could I please get some assistance on this. Thank you

Error:

ERROR ~ Error executing process > 'POLISHMED (1)'
 
Caused by:
  Process `POLISHMED (1)` terminated with an error exit status (1)
 
Command executed:
 
  medaka_consensus -t 4 -m r1041_e82_400bps_hac_v4.2.0 -i sample_id.trimmed.fastq -d Racon_polished.fasta -o medaka_polished
 
Command exit status:
  1
 
Command output:
  TF_CPP_MIN_LOG_LEVEL is set to '3'
  Checking program versions
  This is medaka 1.11.1
 
Command error:
  TF_CPP_MIN_LOG_LEVEL is set to '3'
  Checking program versions
  This is medaka 1.11.1
 
Work dir:
  /mnt/lustre/users/pswart/theodorae/work/9f/c1895afbf1c9783084723fbddab494
 
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
 
 -- Check '.nextflow.log' file for details

**Comment by cjw85** [comment]
I apologise for not responding sooner.

I cannot comment on what the error might be from these logs. You will need to inspect the Nextflow logs further to understand the cause.
