### ISSUE TITLE
1.6.0 release unavailable in pypi

### ISSUE THREAD

**Issue by lvreynoso** [nanoporetech/medaka#493]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> Please ensure that you are using the most recent version of medaka before filing
> a bug report. The most recent version can be found on the [release page](https://github.com/nanoporetech/medaka/releases).
> If you are not using the most recent release, and file a issue regardless the
> most likely response from our developers will be to ask you to first upgrade.
>
> Please ensure also to provide the information below, not doing so will likely
> result in a request for the information.

**Describe the bug**
Hello, I work on a project that builds a Docker image, based on ubuntu:20.04, and installs medaka 1.6.0 as part of the build. The most recent build of this image failed to install medaka. Looking at the PyPI page for medaka [release 1.6.0 is no longer available](https://pypi.org/project/medaka/#history), although previous and subsequent releases are available. Why was 1.6.0 in particular pulled from PyPI?

**Logging**
From the Docker build:
```
 > [15/19] RUN pip3 install medaka==1.6.0 --no-deps:
0.992 ERROR: Could not find a version that satisfies the requirement medaka==1.6.0 (from versions: 1.1.3, 1.2.6, 1.3.4, 1.4.4, 1.5.0, 1.6.1, 1.7.3, 1.8.2, 1.9.1, 1.10.0, 1.11.0, 1.11.1, 1.11.2, 1.11.3)
0.993 ERROR: No matching distribution found for medaka==1.6.0
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: pypi
 - OS: Ubuntu 20.04
 - medaka version 1.6.0
 - GPU model N/A
 - Nvidia driver version N/A
 - CUDA version N/A
 - cuDNN version N/A

**Additional context**

**Comment by cjw85** [comment]
Unfortunately the medaka project on PyPI has made so many releases over the years that we had hit the quota limit on the total storage of packages. We therefore removed various historical versions, leaving the last point release for each minor release in place.

**Comment by lvreynoso** [comment]
Got it. Thanks for the quick response!
