### ISSUE TITLE
I run medaka consensus in HPC, it only generated HDF5 data, how to generate consensus. fasta? 

### ISSUE THREAD

**Issue by JWang52md** [nanoporetech/medaka#495]
Hi, 
version: medaka 1.11.3
this is my script:
medaka consensus sorted_1A.bam medaka_1A --model 'dna_r10.4.1_e8.2_400bps_sup@v4.3.0:consensus' 
the output is only medaka_1A ( HDF5 format)
so, how can I get my consensus.fasta file?
Any suggestions will be truely appreciated.

**Comment by JWang52md** [comment]
btw: I install medaka in conda environment in HPC

**Comment by cjw85** [comment]
Reading the documentation is always a good place to start:
[Usage](https://github.com/nanoporetech/medaka?tab=readme-ov-file#usage)

**Comment by olawa** [comment]
It is a good start but clearly it did not help as the command used is from the documentation.  Try

medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t ${NPROC} -m r10.4.1_e8.2_400bps_sup@v4.3.0

FWIW, a fresh install on a HPC (I think with conda) gave me medaka 1.5. Switching from python 3.6 to 3.10 gave me the latest version, but with issues. Next try with 3.8 gave the newest version and even with functioning (single) GPU acceleration. I could not find any documentation on which python version to use.

**Comment by cjw85** [comment]
The OP ran `medaka consensus` not  `medaka_consensus` as in the basic usage instructions. (Yes, we know that's a little confusing, if medaka ever has a 2.0.0 version it will be changed).

Python 3.6 has been past it's end of life for over 2 years. The newer versions of medaka didn't exist when Python 3.6 was in its active lifespan. Hence there are no packages for newer versions of medaka for older versions of Python.

There are packages on PyPI for the latest version of medaka for Pythons 3.8-3.10 inclusive.

If you are having issues with Python 3.10 please open a new issue.

**Comment by nponts** [comment]
Hi,
I had the same problem so I thought I'd share what worked out for me.
I created a conda env with python 3.9 and then I installed medaka with conda install -c bioconda medaka
Miracle it worked!
Hope you'll get lucky ;)
Cheers!

**Comment by JWang52md** [comment]
Thank you guys!!! I have worked it out by installing python3.8
