### ISSUE TITLE
Python 3.12 compatibility for pip

### ISSUE THREAD

**Issue by mesti90** [nanoporetech/medaka#499]
It would be useful to be able to install using pip for python3.12

**Comment by cjw85** [comment]
The last time we revised which binary packages we build and push to PyPI, many of medaka's dependencies did not have Python 3.12 packages available. We will look at adding Python 3.11 and 3.12 wheel packages in a future release.

In the meantime, PyPI does have a source distribution from which medaka itself can be built (providing your system as the required compilation prerequisites installed). I don't know about the current state of the dependency packages on PyPI however.

**Comment by cjw85** [comment]
We are preparing a new release. However unfortunately some of medaka's dependencies are yet to be available for Python 3.12, so the new release will likely support only up to Python 3.11. We are chasing the maintainers of the other packages in order that they release new versions.
