### ISSUE TITLE
Pre-built model?

### ISSUE THREAD

**Issue by rrwick** [nanoporetech/medaka#5]
Enhancement request: I'm keen to give Medaka a try, but I was wondering if ONT could provide a pre-trained model to use? Perhaps a model trained on the same datasets ONT uses to train basecallers? Or maybe separate models based on organism type: bacterial, human, etc.

I saw the `medaka/test/data/test_model.hdf5` file and assumed that was just for running the tests. But let me know if it is appropriate to use that model more generally.

Ryan

**Comment by cjw85** [comment]
Hi @rrwick 

This indeed got missed in the latest release. We were mostly concerned with making the backend parts of the code more generic for experimentation. We're currently going through a process of evaluating various model architectures and will release a pre-trained model when we have one with which we are happy. (Currently we have simpler models which perform similar to nanopolish in limited test cases but want to check they perform well under a wider range of datasets).

**Comment by rrwick** [comment]
Thanks for letting me know - looking forward to it!

**Comment by Psy-Fer** [comment]
Sorry to bring up an old thread, but is there any news on releasing general human based models? I have a rather long list of samples I'd like to try this with.
Cheers.

**Comment by cjw85** [comment]
Hi @Psy-Fer,

Our current benchmarks for [small variant calling](https://nanoporetech.github.io/medaka/snp.html#v0-7-0-snp-and-indel-calling) are all obtained using the standard models distributed with medaka. Training models bespoke to human consensus and variant calling is an active area of research.

**Comment by Psy-Fer** [comment]
Ahh that gives a bit more background than the katuali explanations of training a model. (in the training section).

Cheers.
