### ISSUE TITLE
Medaka uses way too many threads

### ISSUE THREAD

**Issue by dominik-handler** [nanoporetech/medaka#50]
Hi,
Maybe related to #17 
I am running medaka from a Singularity container. I specified 10 threads for Medaka but it seems to just use most of the cores available on the node (28):
![image](https://user-images.githubusercontent.com/12491961/57221117-31d61200-6ffe-11e9-915d-23ba332b9008.png)

Dominik

**Comment by cjw85** [comment]
Hi @dominik-handler 
Since #17 there have been a few changes to the code, though that's not to say its unrelated. This is not an issue we have ever been able to replicate. Can you provide your singularity definition file, perhaps this will allow us to replicate and understand the problem.
