### ISSUE TITLE
batch size and GPU use

### ISSUE THREAD

**Issue by CorentinEscobar** [nanoporetech/medaka#500]
Hi,

I use medaka with a GPU but I have an error (see attached file). I tried to run medaka with an other pc without GPU (so with CPU) and it's function normally.
I want to know what this batch size consists of ?
What if it has an impact on my final output when I decrease the batch size to make it work ? 
Or else, is it possible to run medaka on the CPU (and not the GPU) ? The GPU is already fully used for basecalling.

Thanks for you help

Corentin

**Logging**
See attached file 
[sal25_batch_size_100.log](https://github.com/nanoporetech/medaka/files/14616340/sal25_batch_size_100.log)

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: Ubuntu 22.04.4 LTS
 - medaka version 1.8.0
 - GPU model : NVIDIA RTX A4500 
 - Nvidia driver version : 535.161.07
 - CUDA version : 12.2
 - cuDNN version : 9

**Comment by cjw85** [comment]
The error:
```
OOM when allocating tensor with shape[1032651776] and type uint8 on
```
suggests the GPU has run out of memory? Were you using the GPU for basecalling at the same time?

You can prevent medaka from using the GPU by exporting a CUDA environment variable before running medaka:
```
export CUDA_VISIBLE_DEVICES=""
```

Alternatively you can `pip install medaka-cpu` to install a version of medaka that has GPU usage disabled.

**Comment by CorentinEscobar** [comment]
Ok thank you !
I tested running medaka during basecalling but also alone.
But if I export the CUDA environment variable I won't be able to do basecalling (with GPU) at the same time ?

**Comment by cjw85** [comment]
The variable will only apply to processes running in the shell where it is set.

**Comment by CorentinEscobar** [comment]
it works ! Thanks a lot !
