### ISSUE TITLE
Medaka v1.11.3 ImportError - undefined symbol: libdeflate_free_compressor

### ISSUE THREAD

**Issue by nbel15** [nanoporetech/medaka#504]
Hi,
I tried installing the latest medaka version (1.11.3) from the source, everything went smoothly during the installation. However, I got the error below when I tried to use it. 

> Traceback (most recent call last):
>   File "medaka/venv/bin/medaka", line 5, in <module>
>     from medaka.medaka import main
>   File "medaka/venv/lib/python3.10/site-packages/medaka/medaka.py", line 7, in <module>
>     import medaka.common
>   File "medaka/venv/lib/python3.10/site-packages/medaka/common.py", line 17, in <module>
>     import libmedaka
> ImportError: medaka/venv/lib/python3.10/site-packages/libmedaka.abi3.so: undefined symbol: libdeflate_free_compressor

I tried with a conda environment, and the latest version I could get is "1.7.0", despite the specification of the latest version during the installation.
Could you please assist in sorting out this issue?

PS: Python 3.10, ubuntu 22.04

**Comment by cjw85** [comment]
Is there a particular reason you wish to compile medaka from source? The recommended installation method is through the binary wheels available on PyPI.

It seems you have managed to compile the code linked to `libdeflate` but don't have this present on your system. The [Makefile](https://github.com/nanoporetech/medaka/blob/master/Makefile#L43) only optionally links to `libdeflate` and notes what needs to be done to use it at runtime. Alternatively you may just wish to install `libdeflate` on your system with `apt`.
