### ISSUE TITLE
error of -d must be specified.

### ISSUE THREAD

**Issue by ramnageena11** [nanoporetech/medaka#508]
Hi I'm running medaka consensus for a metagenome assembly from nanopore reads. but it giving the error of "-d must be specified".
I have tried to run the command from the same folder where .fasta files was located but error is keep coming.

Pls suggest.

Usage/command:
medaka_consensus -i /media/majorram/Analysis_Data/singhrn/meta_assembly/raw_data/*.fastq -d /media/majorram/Analysis_Data/singhrn/meta_assembly/assembly_all/medaka_polis/all_assembly.fasta -o /media/majorram/Analysis_Data/singhrn/meta_assembly/assembly_all/medaka_polis/meda_poli_assembly -t 2 -m r941_min_sup_g507

medaka 1.6.1
------------

Assembly polishing via neural networks. Medaka is optimized
to work with the Flye assembler.

medaka_consensus [-h] -i <fastx> -d <fasta>

    -h  show this help text.
    -i  fastx input basecalls (required).
    -d  fasta input assembly (required).
    -o  output folder (default: medaka).
    -g  don't fill gaps in consensus with draft sequence.
    -m  medaka model, (default: r941_min_hac_g507).
        Choices: r103_fast_g507 r103_hac_g507 r103_min_high_g345 r103_min_high_g360 r103_prom_high_g360 r103_sup_g507 r1041_e82_400bps_fast_g615 r1041_e82_400bps_hac_g615 r1041_e82_400bps_sup_g615 r104_e81_fast_g5015 r104_e81_hac_g5015 r104_e81_sup_g5015 r104_e81_sup_g610 r10_min_high_g303 r10_min_high_g340 r941_e81_fast_g514 r941_e81_hac_g514 r941_e81_sup_g514 r941_min_fast_g303 r941_min_fast_g507 r941_min_hac_g507 r941_min_high_g303 r941_min_high_g330 r941_min_high_g340_rle r941_min_high_g344 r941_min_high_g351 r941_min_high_g360 r941_min_sup_g507 r941_prom_fast_g303 r941_prom_fast_g507 r941_prom_hac_g507 r941_prom_high_g303 r941_prom_high_g330 r941_prom_high_g344 r941_prom_high_g360 r941_prom_high_g4011 r941_prom_sup_g507 r941_sup_plant_g610
        Alternatively a .tar.gz/.hdf file from 'medaka train'.
    -f  Force overwrite of outputs (default will reuse existing outputs).
    -x  Force recreation of alignment index.
    -t  number of threads with which to create features (default: 1).
    -b  batchsize, controls memory use (default: 100).

-d must be specified.

Thanks
rgds
Ram

**Comment by cjw85** [comment]
I suspect the issue here is that you are attempting to pass more than one fastq file as input. You will need to concatenate your files first and provide a single file.

**Comment by ramnageena11** [comment]
Hi Chris,

Thanks for the reply. I did made a single file and it worked.

Rgds
Ram
