### ISSUE TITLE
Suggestions of threshold of minimum mapping quality and read quality score

### ISSUE THREAD

**Issue by hungweichen0327** [nanoporetech/medaka#510]
Hi,

Do you have any suggestions about the threshold of minimum mapping quality?
` -M  Minimum mapQ (default: None)`

About the read quality score, do you suggest filtering the raw ONT reads (e.g. Q>=10) for `medaka_consensus`?

**Comment by cjw85** [comment]
For read quality score, medaka is trained with "pass" reads from the sequencer. Deviating from this may provide sub-par results. Counter intuitively filtering to keep only the very highest quality data may not provide optimal results.

Mapping quality is as much to do with the similarity of reads to multiple locations in reference sequences than absolute  accuracy of reads. We don't typically find it useful to adjust this filtering.

**Comment by hungweichen0327** [comment]
I see. Many thanks for your kind suggestions!
