### ISSUE TITLE
Failed to run medaka consensus.

### ISSUE THREAD

**Issue by NHoang98** [nanoporetech/medaka#516]
**Describe the bug**
I'm trying to polish an assembly using consensus mode but it keeps failing to produce consensus file.

**Logging**
Command: 
medaka_consensus -o Documents/Gac/Genomic/5.polishing/1stmedaka -m r941_e81_sup_g514 -t 16 -f -d Documents/Gac/Genomic/5.polishing/racon/minimap.racon.consensus.fasta -i Documents/Gac/Genomic/3.filter/qscore7/all.fastq.gz

[13:57:14 - PWorker] Batches in cache: 8.
[13:57:14 - PWorker] 18.4% Done (4.3/23.1 Mbases) in 7621.4s
[13:57:14 - Sampler] Initializing sampler for consensus of region contig_15507:0-3433.
[13:57:14 - Feature] Processed contig_15507:0.0-3432.0 (median depth 2.0)
[13:57:14 - Sampler] Took 0.00s to make features.
[13:57:16 - Sampler] Initializing sampler for consensus of region contig_15508:0-9121.
[13:57:16 - Feature] Processed contig_15508:0.0-9120.0 (median depth 4.0)
[13:57:16 - Sampler] Took 0.01s to make features
/home/cmmr/anaconda3/bin/medaka_consensus: line 179: 1313347 Killed                  
medaka consensus "${CALLS2DRAFT}.bam" "${CONSENSUSPROBS}" --model "${MODEL}" --batch_size "${BATCH_SIZE}" --threads "${THREADS}" ${MAPQ_OPTS}
Failed to run medaka consensus.

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method frompypi (pip install)
 - OS: Ubuntu 20.04.6 LTS
 - medaka version 1.12.0
 - GPU model: Nvidia Geforce RTX 3080
 - Nvidia driver version: 520.61.05
 - CUDA version: 11.8

**Additional context**
The output files: call_to_draft.bam, call_to_draft.bam.bai, consensus_probs.hdf and consensus.fasta but fasta file has zero bytes.

**Comment by cjw85** [comment]
The error:
```
/home/cmmr/anaconda3/bin/medaka_consensus: line 179: 1313347 Killed
```
indicates the process was killed by the system not an error in the code per se.

I notice that your medaka appears to be installed within an conda environment. This is not something that is tested, even if the installation is performed with `pip`. You may wish to try creating a Python virtual environment and installing with pip inside that.

**Comment by NHoang98** [comment]
@cjw85 Thank you, I gave it a try and things seem smoothly (until now)! I'll update when the run is finished
