### ISSUE TITLE
r1041_e82_400bps_fast_v4.3.0

### ISSUE THREAD

**Issue by nicolo-tellini** [nanoporetech/medaka#518]
looking for the model `r1041_e82_400bps_fast_v4.3.0`, but I could not find it. 
In its absence, is it recommended running a model with different caller variant (like `r1041_e82_400bps_hac_v4.3.0`) ?

**Comment by cjw85** [comment]
We no longer provide consensus models for fast basecalling. You should basecall with the "hac" basecalling model before using medaka.

**Comment by nicolo-tellini** [comment]
should I go back to the service and ask to rerun the calling? is it possible ?

**Comment by cjw85** [comment]
If they have kept the requisite files from the sequencer they should be able to run the basecalling again.

Using the fast basecalling model is not something we typically recommend beyond basic QC activities

**Comment by nicolo-tellini** [comment]
thanks a lot this is really useful information!
