### ISSUE TITLE
medaka variant produces unsorted vcf, crashing whatshap

### ISSUE THREAD

**Issue by wdecoster** [nanoporetech/medaka#52]
I've noticed more than once now that medaka_variant produces an unsorted  vcf file, which will then downstream crash the whatshap phase step with the following error:

```
 jTraceback (most recent call last):
  File "/home/wdecoster/anaconda3/envs/medaka/bin/whatshap", line 12, in <module>
    sys.exit(main())
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/whatshap/phase.py", line 1114, in main
    run_whatshap(**vars(args))
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/whatshap/phase.py", line 663, in run_whatshap
    for variant_table in vcf_reader:
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/whatshap/vcf.py", line 329, in __iter__
    yield self._process_single_chromosome(chromosome, records)
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/whatshap/vcf.py", line 379, in _process_single_chromosome
    raise VcfNotSortedError('VCF not ordered: {}:{} appears before {}:{}'.format(chromosome, prev_position+1, chromosome, pos+1))
whatshap.vcf.VcfNotSortedError: VCF not ordered: chr4:155958777 appears before chr4:155957327
```

Cheers,
Wouter

**Comment by cjw85** [comment]
Hi @wdecoster,

Can you provide a minimal example (bam) that reproduces this? Our current pre-release may fix this; we've worked quite a bit on how chunks of data are handled. The pre-release is available on pypi: `pip install medaka==0.7.0a1`. If you want to test this, note that some command line options may have changed.

**Comment by wdecoster** [comment]
I encountered this issue for a 20x human genome coverage bam, but not for two larger bams. The bam is 80Gb, which is perhaps not a 'minimal' example. I'll have a look at the pre-release.

**Comment by cjw85** [comment]
Wouter can you confirm the v0.7.x releases resolve this issue for you?

**Comment by wdecoster** [comment]
I'm now on v0.7.0-alpha.1, and running in parallel in separate windows over the genome (I should maybe look into using the GPUs of our PromethION...).
I haven't encountered the error anymore, but I also haven't exactly reproduced what caused in the first place, so I cannot confirm conclusively that it is resolved.

**Comment by cjw85** [comment]
Thanks, I believe the issue is resolved: I have run successfully through a chrom1 dataset.

Using a GPU is definitely preferred if available; a V100 will perform the consensus steps at around 10Mb per minute.
