### ISSUE TITLE
error with building ont-parasail

### ISSUE THREAD

**Issue by myphan210** [nanoporetech/medaka#521]
My Mac is M3 max, Sonoma 14.5. I tried to install medaka from source but first installation failed as I had python 3.11.14 in my system. I downgraded python to python 3.10.8 and reran the "make install".
This time I ran into a different problem with building ont-parasail. Any advice would be much appreciated.

Installing medaka
. ./venv/bin/activate && LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib" pip install .
Processing /Users/myv.t.phan/Downloads/medaka
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi==1.15.0 (from medaka==1.12.1)
  Using cached cffi-1.15.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (1.2 kB)
Collecting edlib (from medaka==1.12.1)
  Using cached edlib-1.3.9.tar.gz (91 kB)
  Preparing metadata (setup.py) ... done
Collecting grpcio (from medaka==1.12.1)
  Using cached grpcio-1.65.4-cp310-cp310-macosx_12_0_universal2.whl.metadata (3.3 kB)
Collecting h5py~=3.10.0 (from medaka==1.12.1)
  Using cached h5py-3.10.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (2.5 kB)
Collecting intervaltree (from medaka==1.12.1)
  Using cached intervaltree-3.1.0.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorflow-macos~=2.10.0 (from medaka==1.12.1)
  Using cached tensorflow_macos-2.10.0-cp310-cp310-macosx_12_0_arm64.whl.metadata (3.0 kB)
Collecting numpy<2.0.0,>=1.21.0 (from medaka==1.12.1)
  Using cached numpy-1.26.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (61 kB)
Requirement already satisfied: mappy in ./venv/lib/python3.10/site-packages (from medaka==1.12.1) (2.24)
Collecting ont-fast5-api (from medaka==1.12.1)
  Using cached ont_fast5_api-4.1.3-py3-none-any.whl.metadata (13 kB)
INFO: pip is looking at multiple versions of medaka to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement ont-parasail (from medaka) (from versions: none)
ERROR: No matching distribution found for ont-parasail
make: *** [install] Error 1

**Comment by truong-phu-minh** [comment]
It seems there is no ont-parasail version available, you should rename "ont-parail" to "parasail" in the requirement.txt file. This can run well

**Comment by myphan210** [comment]
Thanks for the suggestion. I changed the "ont-parasail" to "parasail" but then I ran into a different problem with building parasail.

Building wheel for parasail (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      running bdist_wheel
      parasail/libparasail.dylib not found, attempti
...
          raise RuntimeError("autoreconf -fi failed")
      RuntimeError: autoreconf -fi failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for parasail
  Running setup.py clean for parasail
  Building wheel for progressbar33 (setup.py) ... done
  Created wheel for progressbar33: filename=progressbar33-2.4-py3-none-any.whl size=12143 sha256=bd370465756990e92ce7f4c9d3a51db8e55d0c3d84e49518d8f7bbadca2a014b
Successfully built medaka pyspoa edlib intervaltree progressbar33
Failed to build parasail
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (parasail)
make: *** [install] Error 1

**Comment by truong-phu-minh** [comment]
I think you should download the parasail package using git clone via this [link](https://github.com/jeffdaily/parasail). It has instruction on finding parasail folder, then you can manually paste in your site-packages in your env. Then you can run make install successfully

**Comment by myphan210** [comment]
Thanks a lot for the suggestion. I got it to work now.

**Comment by cjw85** [comment]
Can I invite you to try:

```
pip install medaka==2.0.0a2
```

This will install a prerelease version that should pull only prebuilt wheels for medaka and all its dependencies. It is available for Python 3.9-3.11 inclusive.
