### ISSUE TITLE
Illegal instruction on medaka_consensus

### ISSUE THREAD

**Issue by truong-phu-minh** [nanoporetech/medaka#523]
I install medaka via this [instruction](https://github.com/nanoporetech/medaka) and it seems installing successfully. But when I run medaka_consensus on this suggestion [command line](https://github.com/rrwick/Perfect-bacterial-genome-tutorial/wiki/Tutorial-%28easy%29), it returns illegal instructions. Here is my execute code and the error: 

medaka_consensus -i trycycler/cluster_001/4_reads.fastq -d trycycler/cluster_001/7_final_consensus.fasta -o trycycler/cluster_001/medaka -m r941_min_sup_g507

TF_CPP_MIN_LOG_LEVEL is set to '3'
Cannot import pyabpoa, some features may not be available.
Cannot import pyabpoa, some features may not be available.
Cannot import pyabpoa, some features may not be available.
Checking program versions
This is medaka 1.12.1
Cannot import pyabpoa, some features may not be available.
Program    Version    Required   Pass     
bcftools   1.14       1.11       True     
bgzip      1.14       1.11       True     
minimap2   2.17       2.11       True     
samtools   1.14       1.11       True     
tabix      1.14       1.11       True     
WARNING: Output trycycler/cluster_001/medaka already exists, may use old results.
Cannot import pyabpoa, some features may not be available.
[22:17:14 - MdlStrTF] Successfully removed temporary files from /var/folders/7h/h9g984v17lj3hjph_s63l11h0000gn/T/tmp4hyh6qqn.
Cannot import pyabpoa, some features may not be available.
[22:17:15 - MdlStrTF] Successfully removed temporary files from /var/folders/7h/h9g984v17lj3hjph_s63l11h0000gn/T/tmp43f5wggd.
Not aligning basecalls to draft, calls_to_draft.bam exists.
Running medaka consensus
Cannot import pyabpoa, some features may not be available.
User/medaka/venv/bin/medaka_consensus: line 183:   725 Illegal instruction: 4  medaka consensus "${CALLS2DRAFT}.bam" "${CONSENSUSPROBS}" --model "${MODEL}" --batch_size "${BATCH_SIZE}" --threads "${THREADS}" ${MAPQ_OPTS}
Failed to run medaka consensus.

 - Installation method [from github source]
 - OS: [MacOS Sonoma 14.1]
 - medaka version 1.12.1

**Comment by cjw85** [comment]
If you have installed medaka from source on your device it looks like you have cross-compiled the package for x86 on an ARM based MacBook. The binary you have ended up with is not compatible with your processor.

I imagine that you've managed this by configuring your shell or environment to believe it is running on an x86 processor. You will need to undo that in order to correctly compile the package for ARM.

**Comment by truong-phu-minh** [comment]
Thanks for your suggestion. It work for now.
