### ISSUE TITLE
Model for error-corrected reads coming from dorado-herro

### ISSUE THREAD

**Issue by nponts** [nanoporetech/medaka#527]
Hi,
Thank you for the tool !
I am wondering if any model can be applied to Herro-corrected reads coming from dorado correct? Or maybe, since they are error-corrected correction is not needed anymore? Feels like the latter to me, I just want to be sure :)
Best!

Nadia

**Comment by cjw85** [comment]
medaka models are trained against a particular basecaller and method of reference or draft assembly construction. Applying medaka to pre-corrected reads is not something I would advise (except in the specific case of APK data, which which there is an explicit model).
