### ISSUE TITLE
medaka on *.bam reads as input

### ISSUE THREAD

**Issue by gwl2** [nanoporetech/medaka#528]
**Describe the bug**
It's not really a bug, but a imprecise description:
it says:
"medaka can be run using its default settings through the medaka_consensus program. An assembly in .fasta format and basecalls in .fasta or .fastq formats are required. "
later its noted
"Recent basecaller versions annotate their output with their model version. In such cases medaka can inspect the files and attempt to select an appropriate model for itself. This typically works best in the case of BAM output from basecallers."
So does it mean we can run medaka on reads in the bam format as an input? A clearification in the readme would help here,.
Thanks for your efforts!

**Logging**
-

**Environment (if you do not have a GPU, write No GPU):**
-

**Additional context**

**Comment by cjw85** [comment]
The `medaka_consensus` program accepts reads only in fastq(.gz) format, and creates an intermediate BAM. The programs internal to medaka all use BAM.
