### ISSUE TITLE
installation issue [Hash mismatch]

### ISSUE THREAD

**Issue by cv-1993** [nanoporetech/medaka#531]
Hi medaka dev team,

I am trying to install medaka using python virtual environment.
Here is the command I used:
`python3.8 -m venv medaka`
`source ./medaka/bin/activate`
`pip install medaka`

However, I received an error message about the mismatched hashes as detailed below:

> Collecting medaka
  Using cached medaka-2.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.7 MB)
Collecting requests
  Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Collecting intervaltree
  Using cached intervaltree-3.1.0.tar.gz (32 kB)
Collecting h5py~=3.10.0
  Using cached h5py-3.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
Collecting wurlitzer
  Using cached wurlitzer-3.1.1-py3-none-any.whl (8.6 kB)
Collecting ont-parasail
  Using cached ont_parasail-1.3.4-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (15.8 MB)
Collecting tqdm
  Using cached tqdm-4.66.5-py3-none-any.whl (78 kB)
Collecting cffi
  Using cached cffi-1.17.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (446 kB)
Collecting torch~=2.3
  Using cached torch-2.4.1-cp38-cp38-manylinux1_x86_64.whl (797.1 MB)
Collecting pyspoa>=0.2.1
  Using cached pyspoa-0.2.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (990 kB)
Collecting edlib
  Using cached edlib-1.3.9.post1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (381 kB)
Collecting numpy<2.0.0,>=1.21.0
  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting ont-fast5-api
  Using cached ont_fast5_api-4.1.3-py3-none-any.whl (2.3 MB)
Collecting pysam>=0.16.0.1
  Using cached pysam-0.22.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.9 MB)
Collecting ont-mappy
  Using cached ont_mappy-2.28-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (756 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.10-py3-none-any.whl (70 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Collecting sortedcontainers<3.0,>=2.0
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting pycparser
  Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Requirement already satisfied: setuptools in ./medaka/lib/python3.8/site-packages (from ont-fast5-api->medaka) (44.0.0)
Collecting packaging
  Using cached packaging-24.1-py3-none-any.whl (53 kB)
Collecting progressbar33>=2.3.1
  Using cached progressbar33-2.4.tar.gz (10 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch~=2.3 from https://files.pythonhosted.org/packages/a9/71/45aac46b75742e08d2d6f9fc2b612223b5e36115b8b2ed673b23c21b5387/torch-2.4.1-cp38-cp38-manylinux1_x86_64.whl#sha256=c99e1db4bf0c5347107845d715b4aa1097e601bdc36343d758963055e9599d93 (from medaka):
        Expected sha256 c99e1db4bf0c5347107845d715b4aa1097e601bdc36343d758963055e9599d93
             Got        3a355562d41f8b9043d83eebc41fc5dfe1bfbb6f321bfd7630823d5cba1ec6b9

How should I do to solve this?
Thanks a lot.

**Comment by cjw85** [comment]
This seems like a failed download by the Python package manager and nothing to do with medaka itself.
