### ISSUE TITLE
Support for x86_64 on macOS for medaka v2

### ISSUE THREAD

**Issue by jmtsuji** [nanoporetech/medaka#533]
> Medaka is a Research Release.
>
> Research releases are provided as technology demonstrators to provide early
> access to features or stimulate Community development of tools. Support for
> this software will be minimal and is only provided directly by the developers.
> Feature requests, improvements, and discussions are welcome and can be
> implemented by forking and pull requests. However much as we would
> like to rectify every issue and piece of feedback users may have, the
> developers may have limited resource for support of this software. Research
> releases may be unstable and subject to rapid iteration by Oxford Nanopore
> Technologies.
>
> We provide no guarantees that feature requests will be implemented. They may
> be implemented if sufficient interest is generated or if the request aligns
> with research objectives.

**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Thanks so much for your recent release of medaka v2! It's great to see that the new install includes support for x86_64 and aarch64 linux along with arm64 macOS.

Unfortunately, I find that my research still commonly needs x86_64 (i.e., osx-64) versions of bioinformatics software for macOS. Although I am using Mac's with M-series processors (e.g., M1, M2, or M3, which are ARM-based), many non-medaka bioinformatics tools still only have x86_64 versions available. This often forces me to run bioinformatics pipelines in a x86_64 environment with tools translated into arm64 via Rosetta. Because no x86_64 version of medaka v2 is available, I cannot include it in these pipelines.

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

It would be great if a x86_64 version of medaka v2 could be made for macOS. It seems strange to ask for a x86_64 version of medaka to run on macOS now that M-series chips are used, but until more bioinformatics tools are arm64 compatible, I suspect that many bioinformatics users will appreciate having the x86_64 version available.

As an additional note, x86_64 versions of medaka v1 often had issues being translated by Rosetta, but it seems like this was due to tensorflow, which is no longer used by medaka v2. I've tested x86_64 PyTorch on macOS with a M2 chip, and it seems to translate via Rosetta. This suggests that a x86_64 version of medaka v2 for macOS might translate better via Rosetta than medaka v1 (although I can't be sure about this).

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

The alternative to having a x86_64 install of medaka v2 for macOS would be to use the arm64 version of medaka v2 in bioinformatics pipelines on macOS, as an exception to the other x86_64 tools used in the pipelines. This option is poorly compatible with bioinformatics workflow languages such as snakemake, requiring manual hacks to get tools of different architectures to run in the same workflow.

**Additional context**
> Add any other context or screenshots about the feature request here.

I completely understand if it is not feasible to address this request, but I thought I would put it out there in case other users also have interest in this feature. Thanks again for all your work on this helpful tool.

**Comment by cjw85** [comment]
Medaka 2 is based on pytorch for which there are no x86_64 packages. As such there is no intention to provide such a package for medaka.

Apple removed the remaining Intel SKUs from their lineup in June 2023, after laptops had transitioned between November 2020 and October 2021.

We've put a lot of [effort](https://labs.epi2me.io/inkling/) into getting various software working on ARM, and pushing the community to do the same. Endeavouring to create x86 packages for macOS feels like a retrograde step, the correct solution to be to push software developers and package maintainers to build ARM packages.

**Comment by jmtsuji** [comment]
@cjw85 Thanks very much for your quick reply and for the article link. That's great that you have been putting so much effort into getting bioinformatics tools up and running on ARM. I agree this is the right direction to go, although quite labour intensive at times. I will take a look at our pipeline and evaluate the feasibility of getting ARM support for all dependencies.
