### ISSUE TITLE
medaka smolecule: medaka: error: argument command: invalid choice: 'consensus' 

### ISSUE THREAD

**Issue by mariusmessemaker** [nanoporetech/medaka#534]
When I run: 
`medaka smolecule --model r1041_e82_400bps_hac_v4.2.0 --method spoa --depth 2 --length 50 --threads 80 medaka_test ./smolecule_clusters.fa`

I get the following error: 
`usage: medaka [-h] [--version] {compress_bam,features,train,inference,smolecule,tandem,consensus_from_features,fastrle,sequence,vcf,tools} ...
medaka: error: argument command: invalid choice: 'consensus' (choose from 'compress_bam', 'features', 'train', 'inference', 'smolecule', 'tandem', 'consensus_from_features', 'fastrle', 'sequence', 'vcf', 'tools')`

And also when I run a simpler command: 
`medaka smolecule ./medaka_test ./smolecule_clusters.fasta`

I get the error:
`usage: medaka [-h] [--version] {compress_bam,features,train,inference,smolecule,tandem,consensus_from_features,fastrle,sequence,vcf,tools} ...
medaka: error: argument command: invalid choice: 'consensus' (choose from 'compress_bam', 'features', 'train', 'inference', 'smolecule', 'tandem', 'consensus_from_features', 'fastrle', 'sequence', 'vcf', 'tools')`

The smolecule_clusters.fa has the following structure: 
`
>5_0
TTTCCAATTGACGTTACGCTTGGACTTTGGGGTGGACCATCCTCTAGACTGCCGGATCCGGCGCCAAGCCGCCATGCTGCTGCTCCTGCT
>5_1
TTTGGGCTTCGGATTCACGTTAAGATTTGGGGGTCCTTCAGCTGGTATACGGCGGGCTCGGGGTTCTGGATGTCAGGCTTGATGATCAGC
>5_2
TTTGGGCTTCGGATTCACGTTAAGATTTGGGGGTCCTTCAGCTGGTATACGGCGGGCTCGGGGTTCTGGATGTCAGGCTTGATGATCAGC`

From https://github.com/nanoporetech/pipeline-umi-amplicon/pull/35#issue-2533202303 I get the idea that this error is caused by the Medaka smolecule syntax being changed in newer Medaka versions. That is why I wonder how I can replicate my older medaka version smolecule command with the latest version of medaka, as I would like to run Medaka using the latest version? 

**Environment**
 - Installation method: conda
 - OS: Ubuntu 22.04.5 LTS
 - medaka version: 2.0.0
 - No GPU 

**Additional context**
I am trying to write an updated version of: https://github.com/nanoporetech/pipeline-umi-amplicon/blob/a95d5737a164e4b1fb6990cf4f225fbb5570247d/Snakefile

**Comment by cjw85** [comment]
Hi @mariusmessemaker,

This looks like a bug thats crept in when `medaka consensus` was renamed to `medaka inference` in v2.0.0. It should be easy to fix.

**Comment by mariusmessemaker** [comment]
That would be amazing if it is easy to fix! Thank you so much for your help!

**Comment by cjw85** [comment]
This should be fixed with: https://github.com/nanoporetech/medaka/releases/tag/v2.0.1

**Comment by mariusmessemaker** [comment]
Thanks! Are you planning to release 2.0.1 also on Conda soon?

**Comment by mariusmessemaker** [comment]
Unfortunately, the latest version of minimap2 (i.e., `minimap2=2.28`) cannot be installed in the same conda environment as `medaka=2.0.1` due to Medaka's requirement of `libzlib >=1.3.1`, while `minimap2=2.28` requires `libzlib <1.3.0a0`. Although I understand that this may not necessarily be an issue for the Medaka developers to address, I wonder if `medaka=2.0.1` truly depends on `libzlib >=1.3.1`. If not, could Medaka's libzlib dependency somehow be changed to `libzlib <1.3.0a0` (e.g., `medaka=1.11.3 is compatible with the `minimap2=2.28 version`)? I think many users would likely appreciate the ability to use the latest version of minimap2 in the same conda environment as Medaka, especially since minimap2 introduced important updates since `minimap2=2.24` – the last minimap2 version that I found to be compatible with `medaka=2.0.1`. 

Again, thank you for your help!

**Comment by cjw85** [comment]
IIRC the zlib >=1.3.1 dependency is transitive and comes from the spoa/pyspoa library. medaka 1.11.3 was compatible because I think it didn't specify pyspoa as a hard dependency as pyspoa wasn't available on all platforms. Pyspoa was made a hard requirement when it became available on all the platforms we wanted to support.

I can reinvestigate the reason why pyspoa requires the zlib that it does, but I recollect giving up previously with forcing it to build with other versions.
