### ISSUE TITLE
Directed here for support - medaka beginner having installation issues.

### ISSUE THREAD

**Issue by jtay9562** [nanoporetech/medaka#535]
Hi all,
I reached out to the Nanopore technical support team and was directed to create a ticket here (?). I'm a bit confused as there's only options to create a bug or feature report. Well anyways sorry in advance if I cause confusion.

I was able to get medaka installed on WSL ubuntu using Conda, but am having issues installing medaka the official way (python virtual environment). I think it's because I have to install the required binaries (samtools, minimap2, tabix, bgzip) and place them within PATH. This step goes way over my head. Who can I reach out to for assistance since the Nanopore technical support team was unable to? I appreciate all and any info, thank you!

**Comment by cjw85** [comment]
The easiest way to install these tools would be with the conda (or mamba) package managers. See the instructions in the README.

**Comment by jtay9562** [comment]
> The easiest way to install these tools would be with the conda (or mamba) package managers. See the instructions in the README.

Alright sounds like I'll be good with Conda then. I will proceed forward with that, thank you!
