### ISSUE TITLE
Stand-alone Sedaka consensus and stitch

### ISSUE THREAD

**Issue by christopher-vollmers** [nanoporetech/medaka#539]
Hi,

 I've been using medaka as part of our bc1 pipeline. I did a fresh install recently and now "medaka consensus" and "medaka stitch" are no longer available. They are still mentioned in the README though.

Did those options go away?

Best,
Chris

**Comment by iiSeymour** [comment]
Hey @christopher-vollmers

These where changed in the v2.0.0 release of Medaka. 

> - The medaka consensus command has been renamed to medaka inference to reflect
its function in running an arbitrary model and avoid confusion with medaka_consensus.
> - The medaka stitch command has been renamed to medaka sequence to reflect its
function in creating a consensus sequence.

See https://github.com/nanoporetech/medaka/releases/tag/v2.0.0

**Comment by christopher-vollmers** [comment]
Got it! Thank you. I will give it a try.

**Comment by christopher-vollmers** [comment]
Working as intended again. Will have to update bc1. Thank you for the tool and advice!
