### ISSUE TITLE
The difference between medaka inference and medaka_consensus in medaka version 2.0.1

### ISSUE THREAD

**Issue by hungweichen0327** [nanoporetech/medaka#542]
Dear community,

I would like to ask about the difference between medaka inference and medaka_consensus in medaka version 2.0.1.

Based on the manual below, the input read file of medaka inference is the bam file:
```
# align reads to assembly
mini_align -i basecalls.fasta -r assembly.fasta -P -m \
    -p calls_to_draft.bam -t <threads>
# run lots of jobs like this:
mkdir results
medaka inference calls_to_draft.bam results/contigs1-4.hdf \
    --region contig1 contig2 contig3 contig4
```

While in the medaka_consensus, the input read file of medaka inference is the fasta/fastq file:
```
NPROC=$(nproc)
BASECALLS=basecalls.fa
DRAFT=draft_assm/assm_final.fa
OUTDIR=medaka_consensus
medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t ${NPROC}
```

I was wondering, in addition to the input file format of the raw ONT reads, whether the final polished genome.fasta is the same or not.

Thank you for the help.

**Comment by cjw85** [comment]
`medaka_consensus` is a convenience bash script for running a workflow starting from a draft sequence and fastq files. It uses `medaka inference` internally in much the same way as the example in the README.
