### ISSUE TITLE
Username / password

### ISSUE THREAD

**Issue by vineeth-s** [nanoporetech/medaka#6]
Hi, 

I am trying to clone the repository, and I am being asked for a username and password 
My username and password lead to a "Authentication failed" response  

Cheers,
Vineeth

**Comment by cjw85** [comment]
Hi @vineeth-s,

Have you checked the URL that you are trying to clone? There is no access protection.

**Comment by vineeth-s** [comment]
Hi @cjw85,

gah! Autocomplete on the URL to nanoporetech.com. Works now. Thanks and apologies for the bother
