### ISSUE TITLE
Error during installation with pip (tensorflow==1.12.2 is not downloaded)

### ISSUE THREAD

**Issue by ilnamkang** [nanoporetech/medaka#61]
Hi,

I'm experiencing a difficulty during installation with pip.

My command is below.
$ sudo -H pip3 install --force-reinstall medaka

Below is the error message.
"Could not find any downloads that satisfy the requirement tensorflow==1.12.2 (from medaka)
Cleaning up...
No distributions at all found for tensorflow==1.12.2 (from medaka)
Storing debug log for failure in /root/.pip/pip.log"

How can I solve this problem?

I had no difficulty in installation with conda.

Thanks.

**Comment by cjw85** [comment]
Hi @ilnamkang,

Can you check the version of python you have on your system? The pypi tensorflow [release page](https://pypi.org/project/tensorflow/1.12.2/#files) lists the available 1.12.2 packages. Are  you by chance using python 3.7?

As an aside, we would not generally recommend installing medaka into the root environment.

**Comment by ilnamkang** [comment]
Hi,

Python 3.4.3 is installed on my system (Ubuntu 14.04).
I'm not sure, but I feel that this problems is caused by pip versions installed in my system.

Anyway, following your advice, I'm going to use conda.

Thanks.

**Comment by vinaykumar2491** [comment]
> Hi @ilnamkang,
> 
> Can you check the version of python you have on your system? The pypi tensorflow [release page](https://pypi.org/project/tensorflow/1.12.2/#files) lists the available 1.12.2 packages. Are you by chance using python 3.7?
> 
> As an aside, we would not generally recommend installing medaka into the root environment.

I am having the same issue. I am using Python 3.7.4 and trying to install Tensorflow==1.12.2
But, I am getting this error.
<img width="1440" alt="Screen Shot 2020-03-16 at 9 19 36 PM" src="https://user-images.githubusercontent.com/12234745/76812668-013d3800-67cc-11ea-9613-d0ef83bca448.png">

Please help.
Thank you!

**Comment by ajinkyajawale14** [comment]
having same error

**Comment by ilnamkang** [comment]
I've never tried again.

I'm just satisfied with conda installation.
