### ISSUE TITLE
Unable to call Medaka

### ISSUE THREAD

**Issue by emmannaemeka** [nanoporetech/medaka#62]
Hello,
I used Pip install Medaka to install Medaka. I tried to call it and I got the error below. Can you help?

source /home/emmanuel/tutorial-env/bin/medaka
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
-bash: from: command not found
-bash: /home/emmanuel/tutorial-env/bin/medaka: line 9: syntax error near unexpected token `('
-bash: /home/emmanuel/tutorial-env/bin/medaka: line 9: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])'

**Comment by cjw85** [comment]
Hi @emmannaemeka 

I think the command you want above is:

    source /home/emmanuel/tutorial-env/bin/activate

not 

    source /home/emmanuel/tutorial-env/bin/medaka
