### ISSUE TITLE
File write failed

### ISSUE THREAD

**Issue by ahcm** [nanoporetech/medaka#63]
medaka_consensus -i ../../fastq/SAMPLE-guppy-3.1.5-hac.porechop.fastq -d ../SAMPLE-guppy-3.1.5-hac.porechop.fastq-wtdbg2-xont-L2000-R-g2.4G.racon1.fasta -t 16 -m r941_min_high
Checking program versions
Program    Version    Required   Pass
bgzip      1.9        1.9        True
minimap2   2.17       2.11       True
samtools   1.9        1.9        True
tabix      1.9        1.9        True
Aligning basecalls to draft
-P option is deprecated
Found minimap files.
[M::main::23.332*0.86] loaded/built the index for 8808 target sequence(s)
[M::mm_mapopt_update::26.285*0.87] mid_occ = 710
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 8808
[M::mm_idx_stat::27.357*0.88] distinct minimizers: 97538053 (40.98% are singletons); average occurrences: 5.091; average spacing: 
5.327
[M::worker_pipeline::120.388*11.49] mapped 152347 sequences
[M::worker_pipeline::186.963*13.04] mapped 149546 sequences
[M::worker_pipeline::250.019*13.80] mapped 150442 sequences
[M::worker_pipeline::337.735*13.46] mapped 149846 sequences
[M::worker_pipeline::401.322*13.79] mapped 148507 sequences
[M::worker_pipeline::460.964*14.07] mapped 148659 sequences
[M::worker_pipeline::521.005*14.28] mapped 147547 sequences
[M::worker_pipeline::579.615*14.46] mapped 154226 sequences
[M::worker_pipeline::653.106*14.34] mapped 142303 sequences
[M::worker_pipeline::712.323*14.47] mapped 148234 sequences
[M::worker_pipeline::772.608*14.59] mapped 154063 sequences
[M::worker_pipeline::832.504*14.69] mapped 147845 sequences
[E::bgzf_flush] File write failed (wrong size)
samtools sort: failed to create temporary file "calls_to_draft.bam.tmp.0005.bam": Bad address
[E::hts_open_format] Failed to open file calls_to_draft.bam
samtools index: failed to open "calls_to_draft.bam": No such file or directory
Failed to run alignment of reads to draft.

**Comment by mwykes** [comment]
Thanks for your query. Could you try running the minimap2 alignments yourself rather than using medaka_consensus? medaka expects a bam filtered to primary alignments (samtools view -F 2308) and with the MD tag set (--MD option to minimap2). 

Once you have the bam, you can obtain the consensus sequence by runnng:


`medaka consensus <your bam> consensus_probs.hdf --model r941_min_high --threads 16`
`medaka stitch consensus_probs.hdf consensus.fasta`
