### ISSUE TITLE
missing bzip2 dependency in readme

### ISSUE THREAD

**Issue by kapsakcj** [nanoporetech/medaka#68]
I believe `bzip2` is required when installing Medaka from source on Ubuntu. I ran into errors with the uncompression of samtools while trying to install Medaka from source in an Ubuntu xenial docker image. Adding `apt-get install bzip2` fixed the issue.

**Comment by cjw85** [comment]
This is quite possibly true, thanks for the heads up.

**Comment by cjw85** [comment]
`bzip2` is now listed.
