### ISSUE TITLE
Add benchmark results for Racon x1 and eukaryote

### ISSUE THREAD

**Issue by mbhall88** [nanoporetech/medaka#69]
Hi team,

This is a suggestion following on from a [discussion on twitter](https://twitter.com/sergekoren/status/1158850929338310657?s=20).  

In the [current benchmarks](https://nanoporetech.github.io/medaka/benchmarks.html#comparison-of-medaka-and-nanopolish) the results for medaka and nanopolish are shown after 4 rounds of Racon. It would be great to also see the results from just one round too.  

In addition, also in the twitter thread, it was mentioned that maybe this amount of polishing could be more detrimental in something like the human genome, so it would be great to see the results of single vs. multiple Racon rounds for human data.  

I understand I am asking a lot here and don't expect results immediately. But I think this would be very insightful/helpful for everyone in the community using this great tool.

**Comment by cjw85** [comment]
We are looking to pull together some examples using both NA12878 and C. elegans. Possibly not covering all the points initially, mostly to provide a broader range of examples than the bacterial consensus results we have in the current benchmarks.

**Comment by cjw85** [comment]
We have added some quick C. elegans assemblies to the [benchmarks](https://nanoporetech.github.io/medaka/benchmarks.html) page. The numbers there will evolve with time as we develop the methodology.

We have not reported an extensive study of results with varying numbers of racon applications, the *E. coli* table depicts the difference between not using racon at all and using it once. The *C. elegans* results do not use racon at all.
