### ISSUE TITLE
Label encoding

### ISSUE THREAD

**Issue by vineeth-s** [nanoporetech/medaka#7]
Hi, 

I got medaka running, and successfully trained it on one of our datasets - I stopped the training at Epoch 108 as I saw acc not improving (it had reached 1.0000, and val_acc was at 0.9996) 

On trying to generate the consensus, I end up with this error: 

> Traceback (most recent call last):
  File "/home/ngs/medaka/venv/bin/medaka", line 11, in <module>
    load_entry_point('medaka==0.1.0', 'console_scripts', 'medaka')()
  File "/home/ngs/medaka/venv/lib/python3.5/site-packages/medaka-0.1.0-py3.5.egg/medaka/medaka.py", line 69, in main
    args.func(args)
  File "/home/ngs/medaka/venv/lib/python3.5/site-packages/medaka-0.1.0-py3.5.egg/medaka/inference.py", line 372, in predict
    model, encoding = load_model_hdf(args.model, args.encoding, need_encoding=True)
  File "/home/ngs/medaka/venv/lib/python3.5/site-packages/medaka-0.1.0-py3.5.egg/medaka/inference.py", line 127, in load_model_hdf
    raise KeyError("Could not find label encodings in the model, please provide an encoding json")
KeyError: 'Could not find label encodings in the model, please provide an encoding json'
Exception ignored in: <bound method BaseSession.\_\_del\_\_ of <tensorflow.python.client.session.Session object at 0x7f7d0b991c50>>
Traceback (most recent call last):
  File "/home/ngs/medaka/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 696, in \_\_del\_\_
TypeError: 'NoneType' object is not callable

Since I see that the alphabet considered is A,T,G,C,* and the draft reference I use has a N in it, could this be the problem ? 

Cheers and TIA,
Vineeth

**Comment by cjw85** [comment]
Hi @vineeth-s 

Thanks for your interest.

We haven't properly considered the case where a draft contains "N" but suspect the consensus inference should still work (though we will skip over regions containing "N" during training - the model will not learn to recall "N").

In your case I think the problem arises because you terminated the training early: when training ends we write some additional meta information required for the consensus program required for inference. You should however be able to rescue the situation by running the consensus with the additional option:

    --encoding <train_name>/<train_name>_label_encodings.json

For future reference, the training program does use early stopping: this is hard-coded to terminate the training when the validation loss has not improved for 20 epochs.

**Comment by vineeth-s** [comment]
Hi @cjw85 

So I did that, and now it manages to read the labels, but jumps out with another error : 

> [17:30:35 - root] Running network took 1.2875598339887802s for data of shape (1, 4639, 9)
[17:30:35 - root] Decoding took 0.001005782003630884s for 1 chunks.
Exception ignored in: <bound method BaseSession.\_\_del\_\_ of <tensorflow.python.client.session.Session object at 0x7ff24f7f1c88>>
Traceback (most recent call last):
  File "/home/ngs/medaka/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 696, in\_\_del\_\_
  File "/home/ngs/medaka/venv/lib/python3.5/site-packages/tensorflow/python/framework/c\_api\_util.py", line 30, in \_\_init\_\_
TypeError: 'NoneType' object is not callable


I think I am just going to let it run to completion instead of preempting it, and see what happens ?

**Comment by vineeth-s** [comment]
Hi @cjw85,

How easy or difficult would it be to make the number of epochs a parameter that can be provided on the command line ? 

Also, thanks for developing this and releasing it, if it works the way we see it working, it'd be a major boost to our work

**Comment by vineeth-s** [comment]
Hi @cjw85 

Just letting you know, when I let it run to the end of training, the consensus gets polished without any errors. 

Cheers, and thanks much

**Comment by cjw85** [comment]
That can be easily done. We plan to make a release with a pre-trained model soonish; these models are relatively simple so we're concerned about over-training. We'll see about adding more features to the command line interface.

I've occasionally seen the error you report above whilst running `keras`. In those instances it appeared harmless. Can you check if an output `.fasta` file has been produced?

**Comment by vineeth-s** [comment]
I am looking at the output with the chunks, and there is only one segment of that particular draft written out ... would i be correct in assuming that only sequences or segments of sequences which get polished get written out ? 

ps : apologies for the comment/question bombardment

**Comment by cjw85** [comment]
Yes, that is correct. This was simply a pragmatic choice to not over-complicate the code and keep the output transparent.

Happy to answer questions, it help us improve these tools. :)
