### ISSUE TITLE
Medaka for chromosome phasing of particular gene sequences

### ISSUE THREAD

**Issue by Michaela124** [nanoporetech/medaka#76]
Good morning, 

I’m interested in chromosome phasing of particular gene sequences and I think Medaka might be the best program to use, but before before I start using Medaka for my research I have a couple of questions I’m hoping you could answer.

I am interested in using Medaka to identify combinations of single nucleotide polymorphisms (SNPs) on each chromosomal copy within an individual and I would like to know how Medaka can accomplish this. 

-	Does Medaka create a single or two consensus sequences from the data? (Most individuals contain two different sequence variants of the gene).
-	Does Medaka create a consensus sequence based on individual nucleotide positions or based on entire sequence reads? 
-	Does the consensus sequence created by Medaka contain the SNP with the highest probability of being a real SNP independently of other SNPs present in the sequence, thus creating a consensus with a mix of SNPs, each selected based on its probability of being a real SNP? 
-	If the consensus sequence created by Medaka, is then provided to Whatshap, does Whatshap use that consensus sequence to phase two haplotypes or does it ignore the consensus and uses the reads directly?

**Comment by cjw85** [comment]
`medaka` can operate in one of two modes. The first and most common is to create a single consensus sequence from a set of reads. The second is more what you want for your application: we have a pipeline that will call and phase (diploid) SNPs and small indel variants, outputting a VCF file. It does this with the aid of Whashap, more details can be found here if you are interested: https://nanoporetech.github.io/medaka/snp.html

In the interest of open science you may also like to try https://github.com/HKU-BAL/Clair, created independently by academics studying variant calling with Oxford Nanopore Technologies' datasets.
