### ISSUE TITLE
Unable to find h5f files in latest update

### ISSUE THREAD

**Issue by david0rr** [nanoporetech/medaka#79]
Running the latest update, my `medaka_consensus` step fails when loading in the models, see below:

> Traceback (most recent call last):
>   File "gpu_test/medaka/venv/bin/medaka", line 11, in <module>
>     load_entry_point('medaka==0.9.0', 'console_scripts', 'medaka')()
>   File "gpu_test/medaka/venv/lib/python3.6/site-packages/medaka-0.9.0-py3.6-linux-x86_64.egg/medaka/medaka.py", line 431, in main
>     args.func(args)
>   File "gpu_test/medaka/venv/lib/python3.6/site-packages/medaka-0.9.0-py3.6-linux-x86_64.egg/medaka/prediction.py", line 100, in predict
>     with medaka.datastore.DataStore(args.model) as ds:
>   File "medaka/venv/lib/python3.6/site-packages/medaka-0.9.0-py3.6-linux-x86_64.egg/medaka/datastore.py", line 52, in __enter__
>     self.fh = h5py.File(self.filename, self.mode)
>   File "gpu_test/medaka/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
>     fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
>   File "gpu_test/medaka/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 78, in h5py.h5f.open
> OSError: Unable to open file (file signature not found)

Looking at the model files in `/gpu_test/medaka/medaka/data/` it seems these files are not dowloaded correctly. I believe it is something to do with these files now being stored on git-lfs. Although I manually downloaded the default model but this error still persisted. 

I tried using `git clone` as well as downloading the tar file from the releases tab but this makes no difference.

Running with v0.8.2 works correctly.

**Comment by cjw85** [comment]
You are correct that this is due to the models being store in git-lfs. To successfully clone the repository you will need to first install git-lfs following the instructions here: https://git-lfs.github.com/.

**Comment by david0rr** [comment]
Fixed! Thanks.
