### ISSUE TITLE
what is the main feature in medaka model?

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/medaka#81]
Hi:
  I am interested in this polish project. what is the main input feature of neural network? the observed base percentage on each pisition of alignment bam file is the feature?
 thanks!
neng

**Comment by cjw85** [comment]
Roughly speaking you are correct, the input feature is a vector of normalised counts for the set of symbols {gap, A, T, C, G} x {forward strand, reverse strand}.

**Comment by huangnengCSU** [comment]
@cjw85 
thanks a lot.
