### ISSUE TITLE
Samtools index command output redirection error

### ISSUE THREAD

**Issue by aineniamh** [nanoporetech/medaka#83]
** Samtools index command outputting into '-@'**
The function in scripts/medaka_variant to call samtools index is currently as follows:
```
        samtools index ${BAM} -@ ${THREADS} \
            || (echo "Failed to index bam ${BAM}." && exit 1)
```
As the samtools index user interface suggests, this command results in creation of a file named '-@', rather than the ${BAM}.bai index file that should be created. 

The samtools index UI as follows:
```
Usage: samtools index [-bc] [-m INT] <in.bam> [out.index]
Options:
  -b       Generate BAI-format index for BAM files [default]
  -c       Generate CSI-format index for BAM files
  -m INT   Set minimum interval size for CSI indices to 2^INT [14]
  -@ INT   Sets the number of threads [none]
```
The options, including   ##-@, should be placed before the <in.bam>. 

**Logging**
The output and exit error  that medaka consistently fails with is: 
```
== SUMMARY ==
Total alignments processed:                       334
Alignments that could be tagged:                  144
Alignments spanning multiple phase sets:            0
Tagged reads written to path/to/round_0_hap_mixed_thresh_0.04_phased.bam.
Running samtools index on round_0_hap_mixed_thresh_0.04_phased.bam.
Bam index in path/to/round_0_hap_mixed_thresh_0.04_phased.bam.bai.
Could not find file round_0_hap_mixed_thresh_0.04_phased.bam.bai, exiting.
```
**Environment (if you do not have a GPU, write No GPU):**
 - OS: MacOS Mojave 10.14.6 
 - No GPU

**FIX**
I've altered the samtools index command to be:
```
        samtools index -@ ${THREADS} ${BAM}  \
            || (echo "Failed to index bam ${BAM}." && exit 1)
```
and this fixes the problem on my machine. #82

**Comment by cjw85** [comment]
#82 Is merged, thanks @aineniamh.

**Comment by aineniamh** [comment]
No worries!
