### ISSUE TITLE
[Feature request] Is it possible for a --force flag to be included?

### ISSUE THREAD

**Issue by SRooke** [nanoporetech/medaka#85]
Hi there,

Wondering if there is room to include a flag for --force, overwriting intermediary files such as the medaka index files and whatever may be already present in the specified outdir?

Cheers,
Stefan

**Comment by cjw85** [comment]
Hi @SRooke,

I have added this to our internal issue list. In the meantime it would be useful to understand your usecase for us to better implement this feature. For example, is there a reason you would not want to simply remove medaka's output directory before rerunning?

**Comment by SRooke** [comment]
I did fall back to removing the existing medaka output file in some cases.

The problem that was a specific set-back was that in some cases an empty/broken .mmi file was produced for the racon-polished draft assembly. Again I did eventually write a step into my pipeline to delete this - however it took a long time to determine what was causing that subset of my assemblies to fail medaka polishing (~7% of our 200 sequenced isolates).

**Comment by cjw85** [comment]
@SRooke thanks for this information, the situation is a bit more subtle in this case, and something we may have overlooked as `medaka_consensus` is not itself responsible for generating the `.mmi` file.

**Comment by cjw85** [comment]
We've implemented this, it will be available in the next release within two weeks.

**Comment by cjw85** [comment]
We have just released v0.10.0 which adds the `-f` option to `medaka_consensus`.
