### ISSUE TITLE
AssertionError Failed to stitch consensus chunks

### ISSUE THREAD

**Issue by Siadjeu** [nanoporetech/medaka#89]
**Describe the bug**
Hi,
I have problem with the stitch function of the newest version of medaka v0.9.2 installed with conda.

**Logging**
[02:22:00 - Stitch] Processing tig00001220:0-.
[02:22:01 - Stitch] Processing tig00001224:0-.
[02:22:02 - Stitch] Processing tig00001233:0-.
Traceback (most recent call last):
File "/user/wupf2892/miniconda2/envs/medaka/bin/medaka", line 11, in
sys.exit(main())
File "/user/wupf2892/miniconda2/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 428, in main
args.func(args)
File "/user/wupf2892/miniconda2/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 116, in stitch
joined = stitch_from_probs(args.inputs, regions=args.regions)
File "/user/wupf2892/miniconda2/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 87, in stitch_from_probs
s1, s2)
File "/user/wupf2892/miniconda2/envs/medaka/lib/python3.6/site-packages/medaka/common.py", line 275, in overlap_indices
assert len(pos1_ovl) == len(pos2_ovl)
AssertionError
Failed to stitch consensus chunks.

**Environment (No GPU):**
 - OS: [e.g. Ubuntu 16.04]
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by cjw85** [comment]
Hi @Siadjeu,

I apologise that you have run in to issues. Would it be possible for you to share your data? We would need the `.bam` file in the medaka output directory, filtered to the reference sequence `tig00001233` if that makes it significantly smaller.

**Comment by Siadjeu** [comment]
Hi @cjw85 

thanks for your quick answer, ok no problem, just let me know how to share my data with you. My email is

**Comment by Siadjeu** [comment]
Hi @cjw85 

thanks for your quick answer, ok no problem, just let me know how to share my data with you. My email is : siadjeu2012@gmail.com

**Comment by cjw85** [comment]
You should shortly receive an email with instructions.

**Comment by Siadjeu** [comment]
ok thanks, I am searching how to extract the reference sequence  tig00001233  from the bam file using samtools but I will really appreciate your help if you can share with me how to do that.

**Comment by cjw85** [comment]
Something like:

`samtools view -h -b medaka/calls_to_draft.bam tig00001233 > filtered.bam`

should get you started.

**Comment by Siadjeu** [comment]
thanks, I will upload the .bam file as soon as possible.

**Comment by Siadjeu** [comment]
I am uploading the bam file is about 2.1Gb.

**Comment by Siadjeu** [comment]
Data is already uploaded

**Comment by cjw85** [comment]
Thank, yes I have it.

**Comment by cjw85** [comment]
@Siadjeu 

I have reproduced your issue, we will issue a fix in the next release within the next week or so.

**Comment by Siadjeu** [comment]
@cjw85 
Ok, thanks I am looking forward to have this next release!

**Comment by cjw85** [comment]
We have just released v0.10.0 which fixes this issue.
