### ISSUE TITLE
missing model files when building from source

### ISSUE THREAD

**Issue by robegan21** [nanoporetech/medaka#91]
Hello,
I need to build medaka from source or use a docker image as virtual envs and conda are not well supported on my compute systems.  I was able to build and use v0.7.1 this way but the latest versions do not include the model files, so attempts to use newer builds of medaka fail.  How can I obtain these model files when building from source?
Thanks

**Comment by cjw85** [comment]
The model files are stored in git LFS. To successfully clone the repository you will need to first install git-lfs following the instructions here: https://git-lfs.github.com/.

What system are you using? For many users it shouldn't be necessary to compile medaka from source, the wheel files on [PYPI](https://pypi.org/project/medaka/#files) will work on any linux. Using the `Makefile` in the repository simply has the convenience that it fetches and compiles third party binaries.

**Comment by cjw85** [comment]
Hi @robegan21, have you resolved your issue?

**Comment by robegan21** [comment]
Yes, with git-lfs I was able to download the model files.  I haven't been able to verify that medaka work yet as I'm still struggling to get a working tensor-flow environment.  I have an older server without AVX instructions, so the packaged binaries do not work and I've found that I need to rebuild everything.

**Comment by cjw85** [comment]
Hi Rob, I will therefore close this issue.
