### ISSUE TITLE
mini_align missing

### ISSUE THREAD

**Issue by reiverjohn** [nanoporetech/medaka#92]
Build fails b/c scripts/mini_align is missing.  I copied the mini_align version of 0.9.1 over to the 0.10.0/scripts directory to get the build to complete.

**Comment by cjw85** [comment]
Hi @reiverjohn,

How were you trying to setup `medaka`? The `mini_align` script is fetched from another repository when running `make install`.

**Comment by reiverjohn** [comment]
I copied it over from an install I had for version 0.9.

Sent from my iPhone

On Oct 11, 2019, at 12:17 PM, cjw85 <notifications@github.com> wrote:

﻿

Hi @reiverjohn<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_reiverjohn&d=DwMCaQ&c=nE__W8dFE-shTxStwXtp0A&r=qSSp7ubrmnsFIIKA0J_cqA&m=MjcogkqNxZHL_fJP-yzpLbVjmH8Es2r_BeOrP4YcOX8&s=-F3eDXSva1oV5na3KMEB2E7iqgbTWfMlvjBvey2SJCc&e=>,

How were you trying to setup medaka? The mini_align script is fetched from another repository when running make install.
