### ISSUE TITLE
Building gpu version from source on centOS cluster locally

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/medaka#95]
Hello,

So i've been trying to install a gpu version from scratch on our centOS cluster.

I tried a number of approaches, like using pip or setup.py but they all had issues.
pip tries to write to /tmp which needs sudo
setup.py uses the requirement files from the pypy, so doesn't switch out the tensorflow-gpu library.

When I do make install, it was failing to create a python 3 virtual environment with virtualenv.
Given python3 has it's own `-m venv` method, I just modified the Makefile like so

```
venv/bin/activate:
	#test -d venv || virtualenv venv --python=python3 --prompt "(medaka) "
	test -d venv || /home/jamfer/work/python363/bin/python3.6 -m venv --prompt "(medaka) " venv
```

Then everything seemed to work (although i had some file number limits, so had to start over in another dir, but that's issues on my end)

**Comment by cjw85** [comment]
Hi @Psy-fer,

I'm unsure from your description what your resultant issue is here. We have a description in the README of how to create an installation for GPU use (modify `requirements.txt` before running `make`). `virtualenv` is noted as being a prerequisite. `pip` has a `--user` option which removes the requirement to install as the root user.

**Comment by Psy-Fer** [comment]
Indeed, I missed it in the 
```
bzip2, gcc, zlib1g-dev, libbz2-dev, liblzma-dev, libffi-dev, libncurses5-dev,
libcurl4-gnutls-dev, libssl-dev, curl, make, cmake, wget, python3-all-dev,
python-virtualenv
```

My hack above got me around that problem anyway. along with the pypy venv too
