### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Tdanis** [nanoporetech/medaka#98]
Hello, I want to ask a naive question. So, is it better to use basecalls or trimmed data for medaka consensus command.??

Thank you for your help

**Comment by cjw85** [comment]
Medaka aligns reads to the given draft sequence, which in most cases will act like a form of trimming (the parts of the read which don't align will be discarded). Naturally using knowledge of the known adapter sequences will always be more powerful, but the additional compute resource required likely is not worthwhile.

Ryan Wick has examples of this in his [assembly accuracy](https://github.com/rrwick/August-2019-consensus-accuracy-update#assembly-accuracy) benchmarks.

**Comment by Tdanis** [comment]
Thank you for your answer.
